window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "atomic",
  title: "Atomic, Nuclear and Particle Physics",
  order: 6,
  greWeight: 0.10,
  prereqs: ["qm"],
  blurb: "Applies quantum mechanics to real atoms, nuclei, and particles — spectra, decay, and the recognition-level facts the exam expects about the subatomic world.",

  lessons: [
    // ---------------------------------------------------------------
    {
      id: "atomic-bohr",
      title: "The Bohr Model and Hydrogen's Spectral Lines",
      minutes: 12,
      discovery: "Quantizing angular momentum ($L=n\\hbar$) in an otherwise classical orbit model forces the atom's energy into discrete levels $E_n=-13.6\\text{ eV}/n^2$ — explaining both atomic stability and discrete spectral lines with one assumption.",
      sections: [
        { kind: "problem", md: `Hot hydrogen gas emits light only at specific, sharp wavelengths (656 nm, 486 nm, 434 nm, ... — the Balmer series), never a continuous rainbow. Also puzzling: an electron orbiting a proton like a tiny planet should, according to classical electromagnetism, continuously radiate energy (any accelerating charge radiates) and spiral into the nucleus in about $10^{-11}\\text{ s}$. Real hydrogen atoms are stable for the age of the universe. Why is the spectrum discrete, and why doesn't the atom collapse?` },
        { kind: "candidates", md: `**A. Classical planetary model.** Electron orbits the proton under Coulomb attraction, exactly like a planet under gravity — no restriction on orbit radius or energy.

**B. Empirical curve-fitting.** Balmer noticed the visible hydrogen lines fit $1/\\lambda = R(1/2^2 - 1/n^2)$ for integer $n>2$, with $R$ a fitted constant. Just use the formula.` },
        { kind: "failures", md: `**A fails twice over.** It predicts continuous radiation (any orbit radius allowed, and the radiated frequency should sweep continuously as the orbit decays) — contradicting sharp lines — and it predicts total collapse within nanoseconds, contradicting atomic stability. Classical mechanics plus classical E&M is simply inconsistent with a stable atom.

**B works for the pattern but explains nothing.** It has no mechanism: it can't predict $R$ from first principles, doesn't extend to the ultraviolet (Lyman) or infrared (Paschen) series without separately fitting new constants, and gives no reason why *these* transitions and not others should occur. A fit is not an explanation.` },
        { kind: "discovery", md: `Keep the classical orbit picture (Coulomb force = centripetal force) but add one non-classical postulate: the electron can only occupy orbits where its angular momentum is quantized, $L = n\\hbar$ for integer $n=1,2,3,\\dots$, and while in such an orbit it does *not* radiate ("stationary state"). A photon is emitted only when the electron jumps between two allowed orbits, with $E_{photon}=E_i - E_f$. This one restriction simultaneously kills the classical continuum of orbits (fixing the spiral-collapse problem) and predicts a discrete photon spectrum matching Balmer's formula exactly, with $R$ now *derived* rather than fitted.` },
        { kind: "formal", md: `Setting Coulomb force equal to centripetal force with $L=mvr=n\\hbar$ gives quantized radii $r_n = n^2 a_0$ (Bohr radius $a_0=0.529\\text{ Å}$) and quantized energies
$$E_n = -\\frac{13.6\\text{ eV}}{n^2}$$
Photon energy for a transition $n_i\\to n_f$ is $E_{photon}=13.6\\text{ eV}\\left(\\frac{1}{n_f^2}-\\frac{1}{n_i^2}\\right)$, equivalent to $1/\\lambda = R(1/n_f^2-1/n_i^2)$ with $R=1.097\\times10^7\\text{ m}^{-1}$ (Rydberg constant). Series are named by final state: Lyman ($n_f=1$, UV), Balmer ($n_f=2$, visible), Paschen ($n_f=3$, IR).` },
        { kind: "apply", md: `Balmer-$\\alpha$ line ($n_i=3\\to n_f=2$): $E_{photon}=13.6(1/4-1/9)=13.6\\times5/36\\approx1.89\\text{ eV}$, giving $\\lambda = hc/E = 1240\\text{ eV nm}/1.89\\text{ eV}\\approx656\\text{ nm}$ — matching the observed red hydrogen line exactly. Lyman-$\\alpha$ ($n=2\\to1$): $E=13.6(1-1/4)=10.2\\text{ eV}$, $\\lambda\\approx122\\text{ nm}$.` },
        { kind: "transfer", md: `The Bohr model is "wrong" in detail (real quantum mechanics replaces sharp orbits with probability clouds, and $L=n\\hbar$ turns out to be the wrong quantization rule for angular momentum — the correct one gives $L^2=l(l+1)\\hbar^2$), but the pattern it introduces — physical quantities restricted to discrete values, with transitions between them emitting or absorbing quanta — is the seed of all quantum mechanics, and the $E_n\\propto -1/n^2$ energy ladder survives unchanged in the full Schrödinger treatment of hydrogen. This is the correspondence principle at work: a simple, partly-wrong model can still get the energy spectrum right.` }
      ],
      checkpoints: [
        { q: "What does the Bohr postulate $L=n\\hbar$ prevent, that the purely classical orbital model could not?", options: ["Photon emission entirely", "Continuous radiation and orbital collapse into the nucleus", "The existence of the ground state", "Coulomb attraction between electron and proton"], answer: 1, explain: "Restricting orbits to discrete quantized values removes the continuum of orbits a classical electron could spiral through while radiating; 'stationary states' by postulate don't radiate at all." },
        { q: "Why couldn't Balmer's empirical fit alone explain the hydrogen spectrum?", options: ["It gave the wrong wavelengths", "It had no physical mechanism and couldn't predict $R$ or extend to other series from first principles", "It only worked for helium", "It predicted a continuous spectrum"], answer: 1, explain: "A fit reproduces a pattern but explains nothing about why that pattern occurs; the Bohr model derives $R$ from constants ($m_e, e, \\hbar$) and extends naturally to Lyman/Paschen." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-spectroscopy",
      title: "Term Symbols, Selection Rules, Fine Structure, and Zeeman Splitting",
      minutes: 13,
      discovery: "Photon emission is itself a quantum transition that must conserve angular momentum, so only transitions with $\\Delta l=\\pm1$ (and related rules) actually occur — a huge reduction from 'any energy-allowed transition.'",
      sections: [
        { kind: "problem", md: `Sodium vapor lamps glow with a famous yellow doublet (two very close lines, not one). If you simply list every pair of energy levels in sodium and assume any pair with $\\Delta E$ matching a photon energy can transition, you'd predict vastly more lines than are actually observed, and you'd have no explanation for why some levels split into close pairs at all. What actually restricts which transitions occur, and how do spectroscopists even label the states compactly enough to talk about this?` },
        { kind: "candidates", md: `**A. Energy conservation is the only requirement.** Any transition between two levels with the right $\\Delta E = hf$ should be observable, given enough atoms and enough time.

**B. There must be some additional rule — check whether angular momentum is involved, since the photon itself isn't just a bundle of energy.**` },
        { kind: "failures", md: `**A fails immediately against data.** Many energy-allowed transitions (e.g., hydrogen's $2s\\to1s$) are almost never observed as single-photon emission, while others dominate — a pure energy criterion can't distinguish them.

**B is on the right track, but needs a concrete rule.** A photon carries intrinsic spin angular momentum $1\\hbar$. For the atom to emit one, the *total* angular momentum of (atom + photon) must be conserved just like energy — so the atom's own angular momentum state has to change in a way that supplies exactly what the photon carries off. This constrains which $l$ (orbital angular momentum quantum number) an electron can jump between.` },
        { kind: "discovery", md: `Working through the angular-momentum bookkeeping for an electric-dipole transition (by far the dominant, fastest photon-emission process) gives strict selection rules: $\\Delta l = \\pm1$, $\\Delta m_l = 0,\\pm1$, and (including spin via spin-orbit coupling) $\\Delta J = 0,\\pm1$ but $J=0\\to J=0$ forbidden, with $\\Delta S=0$. A transition violating these is not literally impossible, but is enormously suppressed (it must proceed through a slower, higher-order process, if at all) — which is exactly why hydrogen's $2s\\to1s$ is famously "metastable."` },
        { kind: "formal", md: `**Term symbol notation:** $^{2S+1}L_J$, where $S$ is total spin, $L$ is total orbital angular momentum (coded S,P,D,F,... for $L=0,1,2,3,\\dots$, capital letters distinguishing multi-electron totals from single-electron $s,p,d,f$), and $J$ is total angular momentum $|L-S|\\le J\\le L+S$. **Fine structure:** spin-orbit coupling ($\\vec{L}\\cdot\\vec{S}$ interaction between the electron's spin and the magnetic field it sees from orbiting the nucleus) splits a single $L,S$ level into distinct $J$ sublevels with a small energy splitting (scaling roughly as $(Z\\alpha)^2$ times the level spacing, $\\alpha\\approx1/137$ the fine structure constant) — this is the origin of doublets like sodium's D lines. **Zeeman effect:** an external magnetic field further splits each level by $m_J$, $\\Delta E = g_J\\mu_B B\\, m_J$, with $\\mu_B$ the Bohr magneton — recognized on sight as "extra splitting proportional to applied $B$."` },
        { kind: "apply", md: `Sodium's yellow doublet is the transition $3p\\to3s$. The upper $3p$ level splits by spin-orbit coupling into $^2P_{3/2}$ and $^2P_{1/2}$ (same $L=1,S=1/2$, different $J$), each of which satisfies $\\Delta J=0,\\pm1$ (not $0\\to0$) when decaying to the single $3s$ level ($^2S_{1/2}$), giving two closely-spaced lines (589.0 nm and 589.6 nm) instead of one — fine structure made directly visible.` },
        { kind: "transfer", md: `"The emitted quantum must conserve the same conservation laws as everything else" is a pattern that reappears throughout atomic, nuclear, and particle physics: angular momentum selection rules here, and (later in this module) charge, baryon number, and lepton number selection rules for nuclear and particle reactions — always the same logic of tallying a conserved quantity on both sides and rejecting mismatches.` }
      ],
      checkpoints: [
        { q: "Why is the hydrogen $2s\\to1s$ transition strongly suppressed compared to $2p\\to1s$?", options: ["It releases less energy", "$\\Delta l=0$ for $2s\\to1s$, violating the electric-dipole selection rule $\\Delta l=\\pm1$", "The $2s$ state has zero energy", "Photons cannot be emitted from s states at all"], answer: 1, explain: "$2s$ has $l=0$ and $1s$ has $l=0$, so $\\Delta l=0$ — forbidden for single-photon electric-dipole emission, forcing a much slower alternate decay route." },
        { q: "In the term symbol $^2P_{3/2}$, the superscript 2 indicates:", options: ["$L=2$", "$J=2$", "$2S+1=2$, i.e. $S=1/2$", "Two electrons in the state"], answer: 2, explain: "The superscript is the spin multiplicity $2S+1$; here $2S+1=2 \\Rightarrow S=1/2$, consistent with a single unpaired electron." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-xray-compton",
      title: "X-Rays and the Compton Effect: Photons as Particles",
      minutes: 12,
      discovery: "An X-ray tube's continuous spectrum has a hard short-wavelength cutoff, independent of target material, because a single photon can carry away at most the electron's entire kinetic energy — direct evidence that light is quantized as discrete photons, confirmed again by Compton scattering.",
      sections: [
        { kind: "problem", md: `Fire fast electrons (accelerated through voltage $V$) into a metal target, and the emitted X-rays show a continuous background spectrum with a *sharp minimum wavelength* $\\lambda_{min}$ — no radiation at all below it — plus some sharp spikes at wavelengths that depend on the target element. What sets that hard cutoff, and does light really behave like discrete particles when it collides with things?` },
        { kind: "candidates", md: `**A. The cutoff is a property of the target material** (different elements, different atomic structure, different minimum wavelength).

**B. Classical electromagnetism: a decelerating (braking) electron radiates continuously across all frequencies as it decelerates** ("Bremsstrahlung," German for braking radiation) — so there should be no cutoff at all, just an ever-thinning tail toward $\\lambda=0$.` },
        { kind: "failures", md: `**A fails experimentally.** Changing the target element changes the characteristic spikes, but $\\lambda_{min}$ stays exactly the same for a fixed accelerating voltage $V$ — the cutoff clearly doesn't come from the target's atomic structure.

**B fails to predict any cutoff at all.** Classical radiation theory allows arbitrarily short wavelengths (arbitrarily high frequency) in principle; it gives no mechanism for a hard minimum, yet one is observed reliably, scaling as $\\lambda_{min}\\propto1/V$.` },
        { kind: "discovery", md: `The resolution requires taking Einstein's photon idea seriously: light of frequency $f$ comes in indivisible quanta of energy $hf$. An electron accelerated through voltage $V$ arrives at the target with kinetic energy $eV$ and (at most) that entire kinetic energy can go into producing a *single* photon in one deceleration event — you can't get a photon more energetic than the electron that made it. That sets a maximum photon energy $hf_{max}=eV$, hence a minimum wavelength, with no dependence on what the target is made of (it's purely a statement about the incoming electron's energy budget).` },
        { kind: "formal", md: `**Duane–Hunt law:** $\\lambda_{min} = \\dfrac{hc}{eV}$. Using $hc=1240\\text{ eV nm}$, this becomes a one-line calculation: $\\lambda_{min}(\\text{nm}) = 1240/V(\\text{volts, in eV units})$. The sharp spikes superimposed on the continuum are **characteristic X-rays**: an incoming electron knocks out a deeply-bound inner-shell electron, and an outer electron falls in to fill the vacancy, emitting a photon whose energy depends on the (screened) nuclear charge $Z$ the falling electron feels — **Moseley's law**, $\\sqrt{f}\\propto(Z-1)$, which historically let physicists order the elements by atomic number rather than atomic weight.` },
        { kind: "apply", md: `An X-ray tube runs at $V=40\\text{ kV}$: $\\lambda_{min}=1240\\text{ eV nm}/40{,}000\\text{ eV}=0.031\\text{ nm}=31\\text{ pm}$, independent of whether the target is copper or tungsten.` },
        { kind: "transfer", md: `The same "photon carries a definite quantum of energy and momentum" idea, applied to a photon *colliding* with a free (or nearly free) electron rather than being created from one, is the **Compton effect**: the scattered photon loses energy (wavelength increases) by an amount $\\Delta\\lambda = \\dfrac{h}{m_ec}(1-\\cos\\theta)$, where $h/m_ec=2.43\\text{ pm}$ is the electron's Compton wavelength. Both effects were historically decisive because neither can be explained by treating light as a classical wave — a photon must also carry momentum $p=h/\\lambda$, exactly as it does in the X-ray-cutoff argument above (energy budget) and in relativistic momentum conservation during the collision (Compton).` }
      ],
      checkpoints: [
        { q: "Why is the X-ray continuum's minimum wavelength independent of the target material?", options: ["All elements have identical atomic structure", "It's set by the incident electron's kinetic energy $eV$, not by target atomic properties", "X-rays cannot have a minimum wavelength", "The target only affects the maximum wavelength"], answer: 1, explain: "$\\lambda_{min}=hc/eV$ depends only on the accelerating voltage, since the hardest possible photon uses up the electron's entire kinetic energy in one event, regardless of what material absorbs the electron." },
        { q: "In Compton scattering, the photon's wavelength increases after scattering because:", options: ["The photon loses energy (and gains wavelength) by transferring momentum and energy to the electron it scatters from", "Photons always slow down in matter", "The electron absorbs the photon completely", "Wavelength always increases upon reflection"], answer: 0, explain: "Energy-momentum conservation in a photon-electron collision (treating the photon as a particle with $E=hf,\\,p=h/\\lambda$) forces the scattered photon to have lower energy, hence longer wavelength, by $\\Delta\\lambda=(h/m_ec)(1-\\cos\\theta)$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-lasers",
      title: "Lasers and Stimulated Emission",
      minutes: 11,
      discovery: "A photon can trigger an excited atom to emit an identical (same phase, direction, frequency) photon — and pumping a medium into population inversion makes this stimulated process outrun ordinary absorption, producing coherent, amplified light.",
      sections: [
        { kind: "problem", md: `An incandescent bulb or a fluorescent tube emits light in all directions, with random phases and a broad range of frequencies — completely incoherent. How could you instead build a light source that emits a narrow, directional, coherent (all photons in phase) beam?` },
        { kind: "candidates", md: `**A. Just excite a huge number of atoms and let them all radiate; more excited atoms should mean a brighter, still-useful beam.**

**B. Rely on ordinary absorption and re-emission processes at thermal equilibrium, just with a very bright pump source.**` },
        { kind: "failures", md: `**A fails on coherence.** Ordinary (spontaneous) emission from excited atoms happens at random times, in random directions, with uncorrelated phases — photons from different atoms don't add up into a coherent beam no matter how many atoms you excite; you just get a brighter incoherent glow.

**B fails on net amplification.** At thermal equilibrium, the Boltzmann distribution guarantees the lower (ground) state is always more populated than any higher excited state (for any positive temperature), so a photon passing through the medium is more likely to be absorbed (promoting a ground-state atom) than to trigger emission from an excited one. Net effect: the light is absorbed, not amplified — no thermal-equilibrium medium can amplify light.` },
        { kind: "discovery", md: `Einstein identified a third process besides absorption and spontaneous emission: an incoming photon of the right energy can *stimulate* an already-excited atom to emit a second photon that is a perfect copy — same frequency, phase, and direction as the one that triggered it. If a medium can somehow be forced into **population inversion** (more atoms in the excited state than the ground state — impossible at ordinary thermal equilibrium, but achievable with external pumping into a third or fourth energy level that then relaxes into the upper laser level), stimulated emission events outnumber absorption events, and an initial photon triggers a cascading, coherent, amplified beam: **L**ight **A**mplification by **S**timulated **E**mission of **R**adiation.` },
        { kind: "formal", md: `Einstein's rate equations (recognition level): spontaneous emission rate $=A_{21}N_2$; absorption rate $=B_{12}\\rho(\\nu)N_1$; stimulated emission rate $=B_{21}\\rho(\\nu)N_2$, where $\\rho(\\nu)$ is the radiation energy density and $N_1,N_2$ the populations. Detailed balance at thermal equilibrium forces $g_1B_{12}=g_2B_{21}$ and $A_{21}/B_{21}=8\\pi h\\nu^3/c^3$ — the same relation used to derive Planck's blackbody law. A laser requires $N_2>N_1$ (population inversion), which is only reachable via a non-equilibrium pumping scheme (typically a 3- or 4-level system, where the pump excites atoms to a short-lived high level that rapidly decays into the metastable upper laser level, avoiding a direct 2-level bottleneck).` },
        { kind: "apply", md: `A true 2-level system pumped by ordinary light can, at best, reach $N_1=N_2$ (saturation) — never inversion — because pumping and stimulated emission both scale with the same populations and cancel at equal occupancy; this is why practical lasers use 3- or 4-level schemes, routing atoms through an auxiliary level that population can pile up behind before it's "released" into the lasing transition.` },
        { kind: "transfer", md: `Stimulated emission is coherent amplification by exploiting a *non-equilibrium* population — the same detailed-balance bookkeeping (comparing $A,B$ coefficients) that Einstein used here is the same logic used to derive the blackbody spectrum by balancing absorption against spontaneous plus stimulated emission in a cavity, tying this lesson back to thermal radiation.` }
      ],
      checkpoints: [
        { q: "Why can't a two-level system at thermal equilibrium ever lase?", options: ["Spontaneous emission is too fast", "Boltzmann statistics guarantee the lower level is always more populated at any positive temperature, so absorption dominates over stimulated emission", "Photons cannot stimulate emission in principle", "Two-level atoms don't exist"], answer: 1, explain: "Population inversion ($N_2>N_1$) is required for net amplification, but thermal equilibrium at any $T>0$ always gives $N_1>N_2$ for a simple two-level system — inversion requires external pumping into a non-equilibrium configuration." },
        { q: "In stimulated emission, the emitted photon is:", options: ["Random in phase and direction relative to the triggering photon", "Identical in frequency, phase, and direction to the triggering photon", "Always higher in energy than the triggering photon", "Emitted only from ground-state atoms"], answer: 1, explain: "Stimulated emission produces a photon that is a coherent copy of the incident photon — the basis for laser amplification." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-binding-energy",
      title: "Nuclear Binding Energy: Why Fusion and Fission Both Release Energy",
      minutes: 13,
      discovery: "The binding energy per nucleon curve peaks near iron ($A\\approx56$); any process that moves nucleons closer to that peak — light nuclei fusing upward, heavy nuclei splitting downward — increases total binding energy and releases the difference, explaining fusion and fission with one rule.",
      sections: [
        { kind: "problem", md: `Fusing light nuclei (hydrogen into helium, powering the Sun) releases enormous energy. Splitting heavy nuclei (uranium fission, powering reactors) also releases enormous energy. These are opposite processes — one builds up nucleon number in a nucleus, the other tears it down. What single principle explains why energy comes out *either* way?` },
        { kind: "candidates", md: `**A. "Bigger nuclei are always more tightly bound, so building them up (fusion) releases energy, and only fusion should be exothermic."**

**B. "Binding energy per nucleon increases monotonically with mass number $A$, so heavier is always more stable."**` },
        { kind: "failures", md: `**A fails outright against fission.** Uranium fission conserves total nucleon number (a $A=235$ nucleus splits into two nuclei whose mass numbers still sum to about 235) — nothing is "built up" — yet it releases roughly 200 MeV per event, more energy per event than almost any fusion reaction. A rule that only allows fusion to release energy is contradicted by the existence of nuclear reactors.

**B fails against the measured binding-energy-per-nucleon curve.** If $B/A$ increased monotonically with $A$, uranium (very heavy) should have *higher* $B/A$ than iron (medium mass) — but measured data show the opposite: $B/A$ actually peaks around $A\\approx56$ (iron) at about 8.8 MeV/nucleon, then *decreases* slowly for heavier nuclei (uranium's $B/A\\approx7.6\\text{ MeV}$) due to growing Coulomb repulsion between all those protons.` },
        { kind: "discovery", md: `The binding energy per nucleon curve isn't monotonic — it rises steeply for light nuclei, peaks near iron, then declines slowly for heavy nuclei. Any nuclear rearrangement that moves nucleons *toward* that peak increases the total binding energy, and the increase is released as energy (via $E=\\Delta m\\,c^2$, since more tightly bound means lower rest mass for the same nucleons). Light nuclei are *below* the peak, so fusing them upward (toward iron) climbs the curve and releases energy. Heavy nuclei are *above* the peak (on the declining far side), so splitting them into fragments closer to iron *also* climbs the curve and *also* releases energy. Same rule, opposite directions on the same curve.` },
        { kind: "formal", md: `Binding energy $B = \\left[Zm_p + (A-Z)m_n - M_{nucleus}\\right]c^2$ (mass defect times $c^2$); the semi-empirical mass formula (recognition level) models $B(A,Z)$ with volume, surface, Coulomb, asymmetry, and pairing terms, reproducing the peak near $A\\approx56$ and the slow decline for heavy $A$ from Coulomb repulsion among many protons. Nuclear radius scales as $R = R_0 A^{1/3}$ with $R_0\\approx1.2\\text{ fm}$ — nuclear density is roughly constant across all nuclei, consistent with nucleons packed like an incompressible fluid.` },
        { kind: "apply", md: `Fission of U-235 releases about 200 MeV per event (roughly: $\\sim1\\text{ MeV}$ gain per nucleon $\\times\\sim235$ nucleons, moving from $B/A\\approx7.6\\text{ MeV}$ toward fragment nuclei with $B/A\\approx8.5\\text{ MeV}$ near the middle of the periodic table). D-T fusion ($^2\\text{H}+{}^3\\text{H}\\to{}^4\\text{He}+n$) releases 17.6 MeV per event — smaller in absolute terms (fewer nucleons involved) but far larger *per unit mass of fuel*, since light nuclei sit on the steep part of the curve.` },
        { kind: "transfer", md: `"Systems release energy moving toward a configuration of lower total energy (here, higher binding energy per particle)" is the same minimum-energy logic that governs chemical reactions (moving toward more stable bond configurations) and mechanical systems settling into potential wells — nuclear physics is just a case where the energy scale (MeV per nucleon) is about a million times the chemical scale (eV per bond).` }
      ],
      checkpoints: [
        { q: "Why do both nuclear fusion (light nuclei) and nuclear fission (heavy nuclei) release energy, despite being opposite processes?", options: ["Both always increase total nucleon number", "Binding energy per nucleon peaks near iron; both processes move nucleons toward that peak from opposite sides", "Energy release only depends on total mass number decreasing", "Fusion releases energy but fission actually absorbs it"], answer: 1, explain: "The non-monotonic binding-energy-per-nucleon curve peaks near $A\\approx56$; light nuclei climb it by fusing, heavy nuclei climb it by splitting — both increase total binding energy and release the difference." },
        { q: "Nuclear radius scaling as $R=R_0A^{1/3}$ implies:", options: ["Nuclear density decreases with $A$", "Nuclear density is roughly constant across nuclei (nucleons pack like an incompressible fluid)", "Heavier nuclei are less dense", "Nuclear volume is independent of $A$"], answer: 1, explain: "Since $R^3\\propto A$, volume $\\propto A$, so mass/volume (density) is roughly constant — a nucleus behaves like a liquid drop of nearly fixed density regardless of size." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-decay",
      title: "Radioactive Decay: The Exponential Law and Conservation Rules",
      minutes: 12,
      discovery: "Each nucleus decays with a constant, memoryless probability per unit time, and this individually-random process produces a precisely deterministic bulk law, $N(t)=N_0e^{-\\lambda t}$, once $N$ is astronomically large.",
      sections: [
        { kind: "problem", md: `A sample of a million identical radioactive nuclei decays unpredictably — you can never say *when* a specific nucleus will decay. Yet measure the bulk sample and you get an extremely precise, smooth exponential decrease, $N(t)=N_0e^{-\\lambda t}$, reproducible to high accuracy every time. How can something built entirely out of individually random events produce such a precise deterministic law?` },
        { kind: "candidates", md: `**A. Each nucleus has an internal "clock" or hidden aging process counting down to a fixed, predetermined lifetime** — like a biological organism nearing the end of its lifespan.

**B. Each nucleus has a constant probability per unit time of decaying, with no memory of how long it has already existed** — check whether this reproduces the smooth bulk law.` },
        { kind: "failures", md: `**A fails against direct measurement.** If nuclei aged toward a fixed lifetime, a batch of nuclei all created at the same time should decay in a tight burst around that lifetime, not spread out exponentially — and a 1000-year-old surviving nucleus should be "close to its limit" and decay soon. Neither is observed: surviving nuclei of any age show exactly the same decay probability per unit time as freshly-formed ones (radioactive decay is famously *memoryless*), directly contradicting an aging-clock model.

So B is the right starting assumption — the question is whether pure per-atom randomness, with no memory, can still add up to the smooth deterministic curve seen in bulk.` },
        { kind: "discovery", md: `It does, and for the same reason kinetic theory turns individually random molecular collisions into a smooth, steady pressure: with $N$ astronomically large ($\\sim10^{20}$ or more in a real sample), the *fraction* decaying in a short time interval is essentially deterministic even though *which* atoms decay is random. Each of the $N$ remaining nuclei independently has probability $\\lambda\\,dt$ of decaying in time $dt$, so on average $dN=-\\lambda N\\,dt$ — a smooth differential equation emerges from a swarm of memoryless coin-flips, precisely because the sample size is huge.` },
        { kind: "formal", md: `Integrating $dN/dt=-\\lambda N$ gives $N(t)=N_0e^{-\\lambda t}$. Define **half-life** $t_{1/2}=\\dfrac{\\ln2}{\\lambda}$ (time for half the sample to decay) and **mean lifetime** $\\tau=1/\\lambda$. **Activity** $\\mathcal{A}=\\lambda N$ (decays per second). Common decay modes and what they conserve: **$\\alpha$ decay** ($(Z,A)\\to(Z-2,A-4)+{}^4\\text{He}$) — conserves nucleon number and charge, occurs by quantum tunneling through the nuclear Coulomb barrier. **$\\beta^-$ decay** ($n\\to p+e^-+\\bar\\nu_e$) — a neutron converts to a proton; conserves charge, baryon number, and lepton number (the antineutrino was proposed by Pauli purely to save these conservation laws, since the electron alone carries a continuous range of energies, not a fixed value). **$\\beta^+$/electron capture** ($p\\to n+e^++\\nu_e$) — the reverse. **$\\gamma$ decay** — no change in $Z$ or $A$, just a de-excitation photon from an excited nuclear state.` },
        { kind: "apply", md: `I-131 has $t_{1/2}=8.02$ days. After 24.06 days (exactly 3 half-lives), the remaining fraction is $(1/2)^3=1/8=12.5\\%$. In general, $N/N_0=(1/2)^{t/t_{1/2}}=e^{-\\lambda t}$, both forms equivalent.` },
        { kind: "transfer", md: `The exact same "memoryless, constant per-unit-time probability leading to an exponential law" structure reappears as the **Poisson process** in counting statistics (the number of decays counted in a fixed window follows a Poisson distribution — the subject of a later lesson in this curriculum), and the same conservation-tally technique used to identify which decay modes are allowed (charge, baryon number, lepton number) generalizes directly to particle physics reactions.` }
      ],
      checkpoints: [
        { q: "Why does radioactive decay follow a precise exponential law despite each individual decay being unpredictable?", options: ["Each nucleus has an internal aging clock", "A constant, memoryless per-atom decay probability, averaged over an astronomically large $N$, produces a smooth deterministic bulk curve", "Nuclei communicate with each other to coordinate decay", "The exponential law is only an approximation that fails for real samples"], answer: 1, explain: "Memorylessness means every surviving atom has the same decay probability regardless of age; averaged over huge $N$, the law of large numbers turns this randomness into the smooth curve $N(t)=N_0e^{-\\lambda t}$." },
        { q: "In beta-minus decay ($n\\to p+e^-+\\bar\\nu_e$), the antineutrino is required to conserve:", options: ["Only charge", "Energy-momentum (fixed electron energy would result without it) and lepton number", "Only nucleon number", "Nothing; it's not actually required"], answer: 1, explain: "Without the antineutrino, energy-momentum conservation would force the electron to always emerge with one fixed energy, contradicting the observed continuous electron energy spectrum; the antineutrino also balances lepton number, since the electron alone has lepton number $+1$ with nothing on the left side to match it." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-standard-model",
      title: "The Standard Model: Recognizing What a Reaction Forbids",
      minutes: 12,
      discovery: "Checking energy and charge conservation alone isn't enough to tell whether a proposed particle reaction is allowed — you must separately tally baryon number and lepton number (and flavor, for strong/EM processes) on both sides.",
      sections: [
        { kind: "problem", md: `Given a proposed reaction like $p\\to e^++\\gamma$ (a proton decaying into a positron and a photon), how do you quickly tell whether it's forbidden, without doing any dynamics? It conserves charge ($+1\\to+1$) and can easily be arranged to conserve energy and momentum. Yet this reaction has never been observed, despite enormous experimental effort to detect it (proton decay searches) — protons appear to be extremely stable, if not perfectly so. What's missing from a check based only on energy, momentum, and charge?` },
        { kind: "candidates", md: `**A. Energy and momentum conservation are the only real requirements** — if a reaction can be arranged to conserve those, it should eventually occur.

**B. Charge conservation is the only *additional* constraint beyond energy-momentum.**` },
        { kind: "failures", md: `**A fails against the non-observation of proton decay.** $p\\to e^++\\gamma$ can easily satisfy energy-momentum conservation (choose the photon energy appropriately) and yet is never seen, with experiments ruling out a proton lifetime shorter than about $10^{34}$ years. Something beyond energy-momentum must be forbidding it.

**B also fails.** $p\\to e^++\\gamma$ *does* conserve charge ($+1=+1+0$) and is still forbidden — so charge conservation alone is insufficient too. Tallying the reaction shows the left side has one baryon (the proton) and the right side has zero baryons (a positron and photon are not baryons) — a mismatch in a quantity neither A nor B checked.` },
        { kind: "discovery", md: `Beyond energy-momentum and charge, two more additively-conserved quantum numbers must balance on both sides of any particle reaction: **baryon number** $B$ (protons/neutrons and other three-quark particles have $B=+1$, antibaryons $-1$, everything else $0$) and **lepton number** $L$ (electrons, muons, taus, and their neutrinos have $L=+1$, antiparticles $-1$, everything else $0$, with each flavor of lepton number — electron, muon, tau — separately conserved to high accuracy in the Standard Model). A reaction that gets energy, momentum, and charge all correct can still be absolutely forbidden if it violates one of these.` },
        { kind: "formal", md: `**Standard Model particle content (recognition level):** *Quarks* — up, down, charm, strange, top, bottom, each with an antiquark; charges $+2/3$ or $-1/3$ (in units of $e$); always confined into color-neutral combinations — baryons (3 quarks, e.g. proton $=uud$, neutron $=udd$) or mesons (quark-antiquark pairs, e.g. $\\pi^0$). *Leptons* — electron, muon, tau, and their neutrinos, each with its own conserved lepton-flavor number; charged leptons carry charge $-1$, neutrinos are neutral. *Gauge bosons* — photon (mediates EM), $W^\\pm$ and $Z^0$ (mediate the weak force), gluons (mediate the strong force, confining quarks). *Higgs boson* — gives mass to fundamental particles via the Higgs mechanism. **Screening method:** for any proposed reaction, tally charge, baryon number, and (flavor) lepton number on each side before worrying about dynamics; any mismatch makes the reaction forbidden regardless of how much energy is available.` },
        { kind: "apply", md: `Check $\\mu^-\\to e^-+\\gamma$: charge balances ($-1=-1$), energy can balance, but muon lepton number is $+1$ on the left and $0$ on the right, while electron lepton number is $0$ on the left and $+1$ on the right — both flavor lepton numbers mismatch, so this decay is forbidden in the Standard Model (and its absence, searched for extensively, is itself a precision test of lepton-flavor conservation). Compare $\\mu^-\\to e^-+\\bar\\nu_e+\\nu_\\mu$: muon lepton number $+1\\to0+0+1=+1$ ✓, electron lepton number $0\\to+1-1+0=0$ ✓ — allowed, and this is in fact the observed muon decay channel.` },
        { kind: "transfer", md: `This conservation-law screening technique is identical in spirit to the decay-mode bookkeeping from the previous lesson (checking charge and baryon/lepton number for $\\alpha$/$\\beta$/$\\gamma$ decay) — the same tally-and-compare method scales from single nuclear decays up to the full zoo of particle reactions, and is exactly the fast, calculator-free check the exam rewards.` }
      ],
      checkpoints: [
        { q: "Which conservation law, beyond charge and energy-momentum, forbids $p\\to e^++\\gamma$?", options: ["Baryon number (1 baryon on the left, 0 on the right)", "Spin", "Color charge", "Lepton number"], answer: 0, explain: "The proton has baryon number $+1$; neither the positron nor the photon is a baryon, so the right side has baryon number $0$ — a mismatch that forbids the decay regardless of energetics." },
        { q: "A proton's quark content is:", options: ["$udd$", "$uud$", "$uus$", "$ddd$"], answer: 1, explain: "The proton is $uud$ (charge $2/3+2/3-1/3=+1$); the neutron is $udd$ (charge $2/3-1/3-1/3=0$)." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "atomic-detectors",
      title: "Detectors, Units, and Fast Arithmetic (eV, barns, natural units)",
      minutes: 10,
      discovery: "Working entirely in eV/MeV/GeV with precomputed constants like $hc=1240\\text{ eV nm}$ turns most atomic/nuclear/particle problems into pure algebra, avoiding slow, error-prone SI unit conversions under exam time pressure.",
      sections: [
        { kind: "problem", md: `A GRE problem gives you a photon energy in keV and asks for its wavelength, with no calculator and about 100 seconds to answer. Converting everything to joules, using $h=6.63\\times10^{-34}\\text{ J s}$ and $c=3\\times10^8\\text{ m/s}$ explicitly, tracking powers of ten by hand, is slow and error-prone. Is there a faster, more reliable route?` },
        { kind: "candidates", md: `**A. Always convert every quantity fully to SI units (joules, meters, kilograms) before starting, then convert the final answer back.**

**B. Work entirely in "natural" atomic/nuclear units — eV, MeV, GeV for energy; keep a small set of precomputed conversion constants on hand instead of $h$, $c$, $e$ separately.**` },
        { kind: "failures", md: `**A is correct but far too slow.** Every problem becomes a fresh, multi-step unit conversion involving numbers like $6.63\\times10^{-34}$ and $1.6\\times10^{-19}$, multiplied and divided by hand — high risk of a power-of-ten slip under time pressure, for no physics benefit (the SI value is rarely what's asked for anyway; energies in eV or wavelengths in nm are the usual answer format).

**B needs a specific toolkit to actually be fast** — which constants, and does it really work for typical problems? Check: essentially every atomic/nuclear/particle GRE question only ever needs energies (eV-scale to GeV-scale), momenta (eV$/c$), masses (eV$/c^2$), and lengths (fm to nm) — never a bare joule or kilogram — so a small set of precombined constants suffices.` },
        { kind: "discovery", md: `Keeping just a few numbers memorized — $hc = 1240\\text{ eV nm}$ (or equivalently $1.24\\text{ keV nm}$, useful across the whole visible-to-X-ray range), $\\hbar c \\approx 197\\text{ MeV fm}$ (useful at nuclear scales), $m_ec^2 = 0.511\\text{ MeV}$, $1\\text{ u}=931.5\\text{ MeV}/c^2$ — turns almost every atomic/nuclear/particle problem into one-line algebra with no explicit joules or kilograms anywhere, because $E$, $p$, and $m$ are all quoted and manipulated in the same natural energy units throughout.` },
        { kind: "formal", md: `Key conversions: $1\\text{ eV}=1.6\\times10^{-19}\\text{ J}$; a **barn** ($1\\text{ b}=10^{-28}\\text{ m}^2=100\\text{ fm}^2$) is the standard nuclear/particle cross-section unit (roughly the geometric size of a heavy nucleus). Common detector types, recognized by what they measure: **Geiger–Müller counter** — simple ionization counting, registers a "click" per particle but gives no energy information. **Scintillation detector** — a particle deposits energy as light flashes (proportional to energy) read out by a photomultiplier tube, giving good energy resolution and fast timing. **Cloud/bubble chamber** — visualizes actual particle tracks; a magnetic field curves the tracks, and the curvature radius gives momentum while the curvature *direction* gives the sign of the charge. **Semiconductor (solid-state) detector** — a particle creates electron-hole pairs proportional to deposited energy, giving excellent energy resolution.` },
        { kind: "apply", md: `Positron-electron annihilation produces two 511 keV photons (each carrying the electron/positron rest energy $m_ec^2=0.511\\text{ MeV}$). Their wavelength: $\\lambda = hc/E = 1240\\text{ eV nm}/511{,}000\\text{ eV} = 2.43\\times10^{-3}\\text{ nm} = 2.43\\text{ pm}$ — one line, no explicit SI units at all (and notably equal to the electron's Compton wavelength from an earlier lesson, since both quantities are built from the same $m_ec^2$).` },
        { kind: "transfer", md: `The general exam strategy — precompute and memorize the handful of constant *combinations* that actually show up (here $hc$, $\\hbar c$, $m_ec^2$), rather than the raw SI constants — is the same trick worth applying everywhere on the exam: $k_B$ combined with room-temperature $T$ ($kT\\approx0.025\\text{ eV}$ at 300 K, useful throughout thermal and solid-state physics) is another standing example.` }
      ],
      checkpoints: [
        { q: "Using $hc=1240\\text{ eV nm}$, the wavelength of a 2.0 eV photon (visible red light) is closest to:", options: ["62 nm", "310 nm", "620 nm", "1240 nm"], answer: 2, explain: "$\\lambda=hc/E=1240/2.0=620\\text{ nm}$, in the visible red range as expected." },
        { q: "A detector that visualizes curved particle tracks in a magnetic field, from which momentum and charge sign can be read off directly, is a:", options: ["Geiger–Müller counter", "Cloud or bubble chamber", "Photomultiplier tube alone", "Lock-in amplifier"], answer: 1, explain: "Cloud/bubble chambers show actual particle trajectories; curvature radius in an applied $B$ field gives momentum ($p=qBr$) and the direction of curvature gives the sign of the charge." }
      ]
    }
  ],

  drills: [
    // atomic-bohr
    { id: "atomic-bohr-d1", lesson: "atomic-bohr", type: "numeric", prompt: "Find the wavelength (in nm) of the Lyman-$\\alpha$ line ($n=2\\to n=1$) in hydrogen.", answer: 121.6, tolerance: 0.02, unit: "nm", hint: "$E=13.6(1-1/4)\\text{ eV}$, then $\\lambda=1240/E$.", solution: "$E=13.6\\times0.75=10.2\\text{ eV}$; $\\lambda=1240/10.2\\approx121.6\\text{ nm}$.", difficulty: 1, tags: ["atomic", "bohr-model"] },
    { id: "atomic-bohr-d2", lesson: "atomic-bohr", type: "mc", prompt: "The Bohr model's key non-classical postulate is:", options: ["Electrons have negative charge", "Angular momentum is quantized as $L=n\\hbar$, and states satisfying this don't radiate", "The proton is much heavier than the electron", "Coulomb's law applies to atoms"], answer: 1, hint: "What single rule fixes both stability and discreteness?", solution: "Restricting orbits to $L=n\\hbar$ and declaring such orbits non-radiating (\"stationary states\") is the sole added assumption beyond classical mechanics.", difficulty: 1, tags: ["atomic", "bohr-model"] },
    { id: "atomic-bohr-d3", lesson: "atomic-bohr", type: "numeric", prompt: "Find the ionization energy (in eV) of a hydrogen-like ion with $Z=3$ (doubly-ionized lithium) in its ground state. ($E_n=-13.6Z^2/n^2\\text{ eV}$)", answer: 122.4, tolerance: 0.02, unit: "eV", hint: "$E_1=-13.6Z^2$ eV; ionization energy is $-E_1$.", solution: "$E_1=-13.6\\times9=-122.4\\text{ eV}$; ionization energy is $122.4\\text{ eV}$.", difficulty: 2, tags: ["atomic", "bohr-model"] },
    { id: "atomic-bohr-d4", lesson: "atomic-bohr", type: "mc", prompt: "As $n\\to\\infty$ in the Bohr model, the energy levels:", options: ["Diverge to $-\\infty$", "Approach $0$ from below, becoming continuous (ionization limit)", "Approach $+13.6$ eV", "Remain equally spaced"], answer: 1, hint: "$E_n=-13.6/n^2$.", solution: "$E_n=-13.6/n^2\\to0^-$ as $n\\to\\infty$, and the spacing between levels shrinks to zero — the discrete spectrum merges into a continuum at the ionization threshold.", difficulty: 2, tags: ["atomic", "bohr-model"] },
    { id: "atomic-bohr-d5", lesson: "atomic-bohr", type: "mc", prompt: "The Balmer series corresponds to transitions ending at:", options: ["$n_f=1$", "$n_f=2$", "$n_f=3$", "Any $n_f$"], answer: 1, hint: "Balmer lines are in the visible range.", solution: "Balmer series: $n_f=2$ (visible light); Lyman is $n_f=1$ (UV); Paschen is $n_f=3$ (IR).", difficulty: 1, tags: ["atomic", "bohr-model"] },
    // atomic-spectroscopy
    { id: "atomic-spectroscopy-d1", lesson: "atomic-spectroscopy", type: "mc", prompt: "The electric-dipole selection rule for orbital angular momentum in a single-photon transition is:", options: ["$\\Delta l=0$", "$\\Delta l=\\pm1$", "$\\Delta l=\\pm2$", "$\\Delta l$ can be anything"], answer: 1, hint: "The photon carries away one unit of angular momentum.", solution: "$\\Delta l=\\pm1$ is required to conserve angular momentum between the atom and the emitted photon (spin-1).", difficulty: 1, tags: ["atomic", "selection-rules"] },
    { id: "atomic-spectroscopy-d2", lesson: "atomic-spectroscopy", type: "mc", prompt: "In the term symbol $^3D_2$, the value of total spin $S$ is:", options: ["0", "1/2", "1", "2"], answer: 2, hint: "Superscript is $2S+1$.", solution: "$2S+1=3\\Rightarrow S=1$.", difficulty: 1, tags: ["atomic", "term-symbols"] },
    { id: "atomic-spectroscopy-d3", lesson: "atomic-spectroscopy", type: "mc", prompt: "Fine structure splitting in an atom's spectral lines arises physically from:", options: ["The nucleus vibrating", "Spin-orbit coupling between an electron's spin and the magnetic field from its own orbital motion", "Doppler broadening", "The finite lifetime of excited states"], answer: 1, hint: "It's an $\\vec L\\cdot\\vec S$ interaction.", solution: "Spin-orbit coupling splits a given $L,S$ level into distinct $J$ sublevels, producing closely-spaced doublets/multiplets like sodium's D lines.", difficulty: 1, tags: ["atomic", "fine-structure"] },
    { id: "atomic-spectroscopy-d4", lesson: "atomic-spectroscopy", type: "mc", prompt: "The Zeeman effect refers to:", options: ["Splitting of spectral lines in an external magnetic field", "Splitting of spectral lines from spin-orbit coupling alone", "Doppler shift of spectral lines", "The photoelectric threshold"], answer: 0, hint: "It requires an externally applied field.", solution: "Zeeman splitting is the additional splitting of energy levels (by $m_J$) in the presence of an external magnetic field, distinct from fine structure (which requires no external field).", difficulty: 1, tags: ["atomic", "zeeman"] },
    { id: "atomic-spectroscopy-d5", lesson: "atomic-spectroscopy", type: "mc", prompt: "A transition from a $J=0$ state to another $J=0$ state via single-photon electric-dipole emission is:", options: ["Always allowed", "Forbidden, since the photon cannot carry away zero net angular momentum", "Allowed only for $l=0$ states", "Allowed only in hydrogen"], answer: 1, hint: "Recall the exception to $\\Delta J=0,\\pm1$.", solution: "$J=0\\to J=0$ is explicitly forbidden for a single photon, since the photon must carry away at least one unit of angular momentum.", difficulty: 2, tags: ["atomic", "selection-rules"] },
    // atomic-xray-compton
    { id: "atomic-xray-compton-d1", lesson: "atomic-xray-compton", type: "numeric", prompt: "An X-ray tube operates at 60 kV. Find the minimum wavelength (in pm) of the emitted X-rays.", answer: 20.7, tolerance: 0.02, unit: "pm", hint: "$\\lambda_{min}=1240/V$ nm, with $V$ in volts.", solution: "$\\lambda_{min}=1240/60{,}000\\text{ nm}=0.0207\\text{ nm}=20.7\\text{ pm}$.", difficulty: 1, tags: ["atomic", "x-ray"] },
    { id: "atomic-xray-compton-d2", lesson: "atomic-xray-compton", type: "mc", prompt: "Why is the X-ray continuum's minimum wavelength independent of the target element?", options: ["Because all elements absorb X-rays equally", "Because it's set by the incident electron's kinetic energy $eV$, an energy budget with no dependence on the target's atomic structure", "Because the electron never actually loses energy to the target", "It is not independent of the target"], answer: 1, hint: "Recall the Duane–Hunt argument.", solution: "A single photon can carry at most the electron's full kinetic energy $eV$, regardless of what material stops the electron.", difficulty: 1, tags: ["atomic", "x-ray"] },
    { id: "atomic-xray-compton-d3", lesson: "atomic-xray-compton", type: "numeric", prompt: "A photon Compton-scatters off a free electron at $\\theta=180°$ (backscatter). Find $\\Delta\\lambda$ in pm. ($h/m_ec=2.43\\text{ pm}$)", answer: 4.86, tolerance: 0.02, unit: "pm", hint: "$\\Delta\\lambda=(h/m_ec)(1-\\cos\\theta)$; at $180°$, $1-\\cos\\theta=2$.", solution: "$\\Delta\\lambda=2.43\\times(1-(-1))=2.43\\times2=4.86\\text{ pm}$.", difficulty: 2, tags: ["atomic", "compton"] },
    { id: "atomic-xray-compton-d4", lesson: "atomic-xray-compton", type: "mc", prompt: "Moseley's law states that the frequency of characteristic X-ray lines satisfies:", options: ["$f\\propto Z$", "$\\sqrt{f}\\propto(Z-1)$", "$f\\propto1/Z^2$", "$f$ is independent of $Z$"], answer: 1, hint: "It's how elements were ordered by atomic number historically.", solution: "$\\sqrt{f}\\propto(Z-1)$, reflecting a hydrogen-like transition in a screened nuclear charge $Z-1$.", difficulty: 2, tags: ["atomic", "x-ray"] },
    { id: "atomic-xray-compton-d5", lesson: "atomic-xray-compton", type: "mc", prompt: "The Compton effect was historically important because it demonstrated:", options: ["That light is purely a wave", "That photons carry momentum $p=h/\\lambda$ and behave as particles in collisions", "That electrons have no mass", "That X-rays cannot scatter"], answer: 1, hint: "Momentum conservation in a photon-electron collision.", solution: "Treating the photon as a particle with definite momentum $h/\\lambda$, and applying relativistic energy-momentum conservation to the collision, correctly predicts the observed wavelength shift — evidence a wave picture alone cannot explain.", difficulty: 1, tags: ["atomic", "compton"] },
    // atomic-lasers
    { id: "atomic-lasers-d1", lesson: "atomic-lasers", type: "mc", prompt: "Population inversion means:", options: ["More atoms in an excited state than in a lower state", "All atoms in the ground state", "Equal populations in all states", "The atom's spin is inverted"], answer: 0, hint: "It's a non-equilibrium condition.", solution: "Population inversion ($N_2>N_1$) is required for stimulated emission to outpace absorption, enabling net light amplification.", difficulty: 1, tags: ["atomic", "lasers"] },
    { id: "atomic-lasers-d2", lesson: "atomic-lasers", type: "mc", prompt: "Why can't a simple two-level system at thermal equilibrium ever achieve population inversion?", options: ["Photons cannot be absorbed by two-level atoms", "Boltzmann statistics guarantee the lower level is more populated for any $T>0$", "Two-level systems cannot absorb light", "Population inversion requires exactly zero temperature"], answer: 1, hint: "Recall the failure of candidate B in the lesson.", solution: "At thermal equilibrium, $N_2/N_1=e^{-\\Delta E/kT}<1$ for any positive $T$, so $N_1>N_2$ always; a non-equilibrium pumping scheme is required to invert this.", difficulty: 2, tags: ["atomic", "lasers"] },
    { id: "atomic-lasers-d3", lesson: "atomic-lasers", type: "mc", prompt: "Compared to spontaneous emission, light produced by stimulated emission is distinguished by:", options: ["Higher photon energy", "Coherence — identical phase, frequency, and direction to the stimulating photon", "Being emitted only from the ground state", "Always being at a shorter wavelength"], answer: 1, hint: "This is the property that makes laser light coherent.", solution: "Stimulated emission produces a photon that is a coherent copy of the triggering photon, unlike the random phase/direction of spontaneous emission.", difficulty: 1, tags: ["atomic", "lasers"] },
    { id: "atomic-lasers-d4", lesson: "atomic-lasers", type: "mc", prompt: "Real lasers typically use 3- or 4-level pumping schemes rather than a direct 2-level scheme because:", options: ["3- and 4-level atoms don't exist", "A pure 2-level system can at best reach equal populations (saturation), never true inversion, under optical pumping", "4-level schemes require no external energy input", "2-level schemes lase more efficiently"], answer: 1, hint: "Think about what happens to pump and stimulated-emission rates as $N_1\\to N_2$.", solution: "In a 2-level system, pumping and stimulated emission both scale with the populations and the system saturates at $N_1=N_2$ rather than inverting; routing through an auxiliary level avoids this bottleneck.", difficulty: 2, tags: ["atomic", "lasers"] },
    { id: "atomic-lasers-d5", lesson: "atomic-lasers", type: "mc", prompt: "The relation $A_{21}/B_{21}=8\\pi h\\nu^3/c^3$ between Einstein coefficients is derived by requiring:", options: ["Consistency with Planck's blackbody spectrum at thermal equilibrium", "Momentum conservation in a single scattering event", "That spontaneous emission never occurs", "That stimulated emission always dominates"], answer: 0, hint: "Detailed balance between absorption, spontaneous, and stimulated emission in a cavity at temperature $T$.", solution: "Balancing all three processes against a blackbody radiation field reproduces Planck's law only if $A_{21}/B_{21}=8\\pi h\\nu^3/c^3$.", difficulty: 3, tags: ["atomic", "lasers"] },
    // atomic-binding-energy
    { id: "atomic-binding-energy-d1", lesson: "atomic-binding-energy", type: "mc", prompt: "The binding energy per nucleon curve as a function of mass number $A$:", options: ["Increases monotonically with $A$", "Decreases monotonically with $A$", "Peaks near $A\\approx56$ (iron) and declines slowly for larger $A$", "Is constant for all $A$"], answer: 2, hint: "Neither fusion-only nor fission-only intuition survives.", solution: "$B/A$ rises steeply for light nuclei, peaks near iron ($\\approx8.8\\text{ MeV}$/nucleon), then slowly declines for heavy nuclei due to growing Coulomb repulsion.", difficulty: 1, tags: ["atomic", "binding-energy"] },
    { id: "atomic-binding-energy-d2", lesson: "atomic-binding-energy", type: "numeric", prompt: "Nuclear radius scales as $R=R_0A^{1/3}$ with $R_0=1.2\\text{ fm}$. Find the radius (in fm) of a nucleus with $A=125$.", answer: 6.0, tolerance: 0.02, unit: "fm", hint: "$125^{1/3}=5$.", solution: "$R=1.2\\times125^{1/3}=1.2\\times5=6.0\\text{ fm}$.", difficulty: 1, tags: ["atomic", "nuclear-size"] },
    { id: "atomic-binding-energy-d3", lesson: "atomic-binding-energy", type: "mc", prompt: "Uranium fission releases energy even though total nucleon number is conserved (splitting into two lighter nuclei), because:", options: ["Nucleon number is not actually conserved in fission", "The fragment nuclei have higher binding energy per nucleon than uranium (closer to the peak of the curve)", "Fission always violates energy conservation", "Neutrons carry away all the released energy as kinetic energy alone, unrelated to binding energy"], answer: 1, hint: "Where does uranium sit on the $B/A$ curve relative to the fragments?", solution: "Uranium ($B/A\\approx7.6\\text{ MeV}$) splits into fragments nearer the middle of the periodic table with higher $B/A$ (closer to iron's peak), releasing the binding-energy difference.", difficulty: 2, tags: ["atomic", "binding-energy"] },
    { id: "atomic-binding-energy-d4", lesson: "atomic-binding-energy", type: "numeric", prompt: "D-T fusion ($^2\\text{H}+{}^3\\text{H}\\to{}^4\\text{He}+n$) releases 17.6 MeV per reaction. Estimate the energy released (in MeV) per nucleon involved (5 nucleons total).", answer: 3.52, tolerance: 0.02, unit: "MeV/nucleon", hint: "Divide total energy by total nucleon count.", solution: "$17.6/5=3.52\\text{ MeV per nucleon}$ — far higher per unit mass than fission's roughly $200/235\\approx0.85\\text{ MeV per nucleon}$, which is why fusion fuel is so energy-dense.", difficulty: 2, tags: ["atomic", "binding-energy"] },
    { id: "atomic-binding-energy-d5", lesson: "atomic-binding-energy", type: "mc", prompt: "Nuclear density is approximately constant across all nuclei. This follows from:", options: ["$R\\propto A$", "$R\\propto A^{1/3}$, so volume $\\propto A$ and density $\\propto$ mass/volume is roughly $A$-independent", "Binding energy per nucleon being constant", "The strong force having infinite range"], answer: 1, hint: "Volume scales as $R^3$.", solution: "Since $R\\propto A^{1/3}$, volume $V\\propto R^3\\propto A$, so mass (also $\\propto A$) divided by volume gives a density independent of $A$ — nuclei behave like an incompressible liquid drop.", difficulty: 2, tags: ["atomic", "nuclear-size"] },
    // atomic-decay
    { id: "atomic-decay-d1", lesson: "atomic-decay", type: "numeric", prompt: "A radioactive sample has half-life 10 days. What fraction of the original sample remains after 40 days?", answer: 0.0625, tolerance: 0.02, unit: "(fraction)", hint: "40 days = 4 half-lives.", solution: "$(1/2)^4=1/16=0.0625$.", difficulty: 1, tags: ["atomic", "decay-law"] },
    { id: "atomic-decay-d2", lesson: "atomic-decay", type: "mc", prompt: "Radioactive decay is described as 'memoryless' because:", options: ["Nuclei decay in a fixed order", "A surviving nucleus has the same decay probability per unit time regardless of how long it has already existed", "Older samples decay faster", "The decay constant $\\lambda$ increases with time"], answer: 1, hint: "This distinguishes it from an aging process.", solution: "The per-atom decay probability per unit time, $\\lambda$, is constant and independent of the nucleus's age — no 'wear and tear' accumulates.", difficulty: 1, tags: ["atomic", "decay-law"] },
    { id: "atomic-decay-d3", lesson: "atomic-decay", type: "numeric", prompt: "A sample has decay constant $\\lambda=0.0231\\text{ day}^{-1}$. Find its half-life in days.", answer: 30.0, tolerance: 0.02, unit: "days", hint: "$t_{1/2}=\\ln2/\\lambda$.", solution: "$t_{1/2}=0.693/0.0231\\approx30.0\\text{ days}$.", difficulty: 1, tags: ["atomic", "decay-law"] },
    { id: "atomic-decay-d4", lesson: "atomic-decay", type: "mc", prompt: "In alpha decay, $(Z,A)\\to(Z-2,A-4)+{}^4\\text{He}$, the nucleus loses two protons and two neutrons. This process is possible even though the alpha particle doesn't have enough energy to classically surmount the Coulomb barrier, because of:", options: ["Beta decay assisting it", "Quantum mechanical tunneling", "Conservation of angular momentum alone", "Gamma ray absorption"], answer: 1, hint: "This is a genuinely quantum effect.", solution: "The alpha particle tunnels through the classically forbidden Coulomb barrier region, with a probability that depends sensitively on barrier height and width.", difficulty: 2, tags: ["atomic", "decay-modes"] },
    { id: "atomic-decay-d5", lesson: "atomic-decay", type: "mc", prompt: "Which quantity is NOT conserved in beta-minus decay ($n\\to p+e^-+\\bar\\nu_e$) considered alone (i.e., ignoring the parent/daughter nucleus's binding energy)?", options: ["Charge", "Baryon number", "Lepton number", "None of these — all are conserved"], answer: 3, hint: "Tally each side: charge $0\\to+1-1+0$; baryon number $1\\to1+0+0$; lepton number $0\\to0+1-1$.", solution: "All three are conserved: charge $0=1-1$, baryon number $1=1$, lepton number $0=1-1$ — this is exactly why the antineutrino, with lepton number $-1$, is required in the reaction.", difficulty: 2, tags: ["atomic", "decay-modes"] },
    // atomic-standard-model
    { id: "atomic-standard-model-d1", lesson: "atomic-standard-model", type: "mc", prompt: "Which particle mediates the electromagnetic force?", options: ["Gluon", "Photon", "$W^\\pm$ boson", "Higgs boson"], answer: 1, hint: "Recall the four force carriers.", solution: "The photon mediates EM; gluons mediate the strong force; $W^\\pm,Z^0$ mediate the weak force.", difficulty: 1, tags: ["atomic", "standard-model"] },
    { id: "atomic-standard-model-d2", lesson: "atomic-standard-model", type: "mc", prompt: "A neutron's quark content is:", options: ["$uud$", "$udd$", "$uus$", "$ddd$"], answer: 1, hint: "Charge must be zero.", solution: "$udd$ has charge $2/3-1/3-1/3=0$, matching the neutron.", difficulty: 1, tags: ["atomic", "standard-model"] },
    { id: "atomic-standard-model-d3", lesson: "atomic-standard-model", type: "mc", prompt: "Which reaction is forbidden by baryon number conservation?", options: ["$n\\to p+e^-+\\bar\\nu_e$", "$p+p\\to p+n+e^++\\nu_e$", "$p\\to\\pi^++\\gamma$", "$\\pi^0\\to\\gamma+\\gamma$"], answer: 2, hint: "Count baryons on each side of each reaction.", solution: "$p\\to\\pi^++\\gamma$ has baryon number $1$ on the left and $0$ on the right (a pion is a meson, not a baryon) — forbidden.", difficulty: 2, tags: ["atomic", "standard-model"] },
    { id: "atomic-standard-model-d4", lesson: "atomic-standard-model", type: "mc", prompt: "Quarks are never observed as free, isolated particles because:", options: ["They have zero mass", "Of color confinement — the strong force keeps them bound into color-neutral hadrons", "They decay too quickly to detect", "They have no electric charge"], answer: 1, hint: "This is a defining feature of the strong force.", solution: "The strong force confines quarks into color-neutral combinations (baryons, mesons); isolated free quarks are not observed.", difficulty: 1, tags: ["atomic", "standard-model"] },
    { id: "atomic-standard-model-d5", lesson: "atomic-standard-model", type: "mc", prompt: "$\\mu^-\\to e^-+\\bar\\nu_e+\\nu_\\mu$ is the observed muon decay because:", options: ["It violates charge conservation but is allowed anyway", "Both muon and electron lepton numbers balance on each side", "It conserves baryon number, which is the only relevant rule", "Muons are baryons"], answer: 1, hint: "Tally muon-flavor and electron-flavor lepton number separately.", solution: "With $e^-$ carrying electron lepton number $+1$ and $\\bar\\nu_e$ carrying $-1$, electron-flavor totals balance: $0\\to(+1)+(-1)+0=0$. With $\\nu_\\mu$ carrying muon lepton number $+1$, muon-flavor totals also balance: $+1\\to0+0+(+1)=+1$. Both flavors balance, unlike the forbidden $\\mu^-\\to e^-+\\gamma$.", difficulty: 3, tags: ["atomic", "standard-model"] },
    // atomic-detectors
    { id: "atomic-detectors-d1", lesson: "atomic-detectors", type: "numeric", prompt: "Using $hc=1240\\text{ eV nm}$, find the energy (in eV) of a photon with wavelength 400 nm.", answer: 3.1, tolerance: 0.02, unit: "eV", hint: "$E=hc/\\lambda$.", solution: "$E=1240/400=3.1\\text{ eV}$.", difficulty: 1, tags: ["atomic", "units"] },
    { id: "atomic-detectors-d2", lesson: "atomic-detectors", type: "mc", prompt: "One barn equals:", options: ["$10^{-15}\\text{ m}^2$", "$10^{-28}\\text{ m}^2$", "$10^{-10}\\text{ m}^2$", "$10^{-34}\\text{ m}^2$"], answer: 1, hint: "It's a nuclear-scale cross-sectional area.", solution: "$1\\text{ b}=10^{-28}\\text{ m}^2=100\\text{ fm}^2$, roughly the geometric cross section of a heavy nucleus.", difficulty: 1, tags: ["atomic", "units"] },
    { id: "atomic-detectors-d3", lesson: "atomic-detectors", type: "mc", prompt: "A Geiger–Müller counter differs from a scintillation detector in that it:", options: ["Cannot count particles at all", "Registers a count per particle but provides no information about the particle's energy", "Only works for photons", "Provides better energy resolution"], answer: 1, hint: "Think about what information each detector type gives.", solution: "A Geiger–Müller tube gives a simple ionization-triggered count with no energy information, unlike a scintillator (light output proportional to deposited energy) or solid-state detector.", difficulty: 1, tags: ["atomic", "detectors"] },
    { id: "atomic-detectors-d4", lesson: "atomic-detectors", type: "numeric", prompt: "Using $\\hbar c\\approx197\\text{ MeV fm}$, estimate the momentum $p$ (in MeV/$c$) of a particle with de Broglie wavelength $\\lambda=2\\pi\\times1\\text{ fm}$ (i.e., reduced wavelength $\\bar\\lambda=1\\text{ fm}$).", answer: 197, tolerance: 0.02, unit: "MeV/c", hint: "$p=\\hbar/\\bar\\lambda$, so $pc=\\hbar c/\\bar\\lambda$.", solution: "$pc=\\hbar c/\\bar\\lambda=197\\text{ MeV fm}/1\\text{ fm}=197\\text{ MeV}$, so $p=197\\text{ MeV}/c$.", difficulty: 2, tags: ["atomic", "units"] },
    { id: "atomic-detectors-d5", lesson: "atomic-detectors", type: "mc", prompt: "In a bubble chamber placed in a magnetic field, a particle track curving more tightly (smaller radius) than another of the same charge indicates:", options: ["Lower momentum", "Higher momentum", "Higher charge only, momentum is irrelevant", "Nothing about momentum, only mass"], answer: 0, hint: "$p=qBr$.", solution: "Since $p=qBr$, a smaller radius of curvature at fixed $B$ and $q$ means lower momentum.", difficulty: 2, tags: ["atomic", "detectors"] }
  ],

  test: [
    { id: "atomic-t1", prompt: "A hydrogen atom in the $n=4$ state drops to $n=2$. The wavelength of the emitted photon is closest to:", options: ["97 nm", "122 nm", "486 nm", "656 nm", "1876 nm"], answer: 2, solution: "$E=13.6(1/4-1/16)=13.6\\times3/16\\approx2.55\\text{ eV}$; $\\lambda=1240/2.55\\approx486\\text{ nm}$ (this is the Balmer-$\\beta$ line).", difficulty: 1, tags: ["atomic", "bohr-model"], lesson: "atomic-bohr" },
    { id: "atomic-t2", prompt: "The ionization energy of a hydrogen-like ion (single electron) with atomic number $Z=2$ (He$^+$) is:", options: ["3.4 eV", "13.6 eV", "27.2 eV", "54.4 eV", "108.8 eV"], answer: 3, solution: "$E_1=-13.6Z^2=-13.6\\times4=-54.4\\text{ eV}$; ionization energy is $54.4\\text{ eV}$.", difficulty: 1, tags: ["atomic", "bohr-model"], lesson: "atomic-bohr" },
    { id: "atomic-t3", prompt: "Which of the following best explains why the classical planetary model of the atom fails?", options: ["Electrons have no charge", "An accelerating (orbiting) charge should radiate continuously and spiral into the nucleus, contradicting atomic stability", "The proton attracts the electron too weakly", "Classical mechanics forbids circular orbits", "The electron's mass is too small to orbit stably"], answer: 1, solution: "Classical E&M requires any accelerating charge to radiate energy, which would cause continuous orbital decay in about $10^{-11}$ s — contradicted by observed atomic stability.", difficulty: 1, tags: ["atomic", "bohr-model"], lesson: "atomic-bohr" },
    { id: "atomic-t4", prompt: "The transition $2p\\to1s$ in hydrogen is electric-dipole allowed, while $2s\\to1s$ is strongly suppressed, because:", options: ["$2s\\to1s$ releases no energy", "$\\Delta l=1$ for $2p\\to1s$ but $\\Delta l=0$ for $2s\\to1s$, violating the dipole selection rule", "$2s$ electrons cannot exist", "The photon has no angular momentum in either case", "$2p$ and $2s$ have different energies in hydrogen"], answer: 1, solution: "Electric dipole transitions require $\\Delta l=\\pm1$; $2p$ ($l=1$) to $1s$ ($l=0$) satisfies this, but $2s$ ($l=0$) to $1s$ ($l=0$) does not.", difficulty: 2, tags: ["atomic", "selection-rules"], lesson: "atomic-spectroscopy" },
    { id: "atomic-t5", prompt: "Sodium's yellow D-line doublet arises because:", options: ["Sodium has two isotopes", "Spin-orbit coupling splits the upper $3p$ level into $^2P_{3/2}$ and $^2P_{1/2}$ sublevels, both of which can decay to $3s$", "The transition violates the Pauli exclusion principle", "Two different elements are present in the lamp", "The Zeeman effect always produces exactly two lines"], answer: 1, solution: "Fine-structure (spin-orbit) splitting of the $3p$ level into two close $J$ sublevels produces two closely-spaced emission lines from the single $3p\\to3s$ transition.", difficulty: 2, tags: ["atomic", "fine-structure"], lesson: "atomic-spectroscopy" },
    { id: "atomic-t6", prompt: "A $^1S_0$ state cannot decay by a single-photon electric-dipole transition to another $J=0$ state because:", options: ["The photon has zero angular momentum, so this is always allowed", "A single photon must carry away at least one unit of angular momentum, making $J=0\\to J=0$ forbidden", "$S=0$ states cannot emit photons", "Energy conservation forbids it", "$J=0$ states have no defined parity"], answer: 1, solution: "The photon is spin-1, so it cannot be emitted while total angular momentum stays exactly zero on both sides — the $J=0\\to0$ selection rule exclusion.", difficulty: 3, tags: ["atomic", "selection-rules"], lesson: "atomic-spectroscopy" },
    { id: "atomic-t7", prompt: "An X-ray tube's short-wavelength cutoff shifts to a shorter wavelength when:", options: ["The target element is changed to a heavier one", "The accelerating voltage is increased", "The tube current (number of electrons per second) is increased", "The tube is cooled", "The target is replaced with a lighter element"], answer: 1, solution: "$\\lambda_{min}=hc/eV$ depends only on accelerating voltage $V$; increasing $V$ decreases $\\lambda_{min}$. Target element and current don't affect it.", difficulty: 1, tags: ["atomic", "x-ray"], lesson: "atomic-xray-compton" },
    { id: "atomic-t8", prompt: "In Compton scattering, a photon scattered at $\\theta=90°$ from a free electron has its wavelength increased by (using $h/m_ec=2.43\\text{ pm}$):", options: ["0 pm", "1.2 pm", "2.4 pm", "4.9 pm", "9.7 pm"], answer: 2, solution: "$\\Delta\\lambda=(h/m_ec)(1-\\cos90°)=2.43\\times(1-0)=2.43\\text{ pm}$.", difficulty: 2, tags: ["atomic", "compton"], lesson: "atomic-xray-compton" },
    { id: "atomic-t9", prompt: "Which statement about lasers is correct?", options: ["Population inversion can be reached at thermal equilibrium given enough time", "Stimulated emission produces photons identical in phase, frequency, and direction to the triggering photon", "Spontaneous emission alone is sufficient to produce a coherent beam given enough excited atoms", "A two-level system pumped optically will readily reach population inversion", "Lasers require no external energy input once started"], answer: 1, solution: "Coherent amplification specifically requires stimulated emission, which copies the triggering photon's phase, frequency, and direction; the other statements are all false for the reasons discussed in the lesson.", difficulty: 2, tags: ["atomic", "lasers"], lesson: "atomic-lasers" },
    { id: "atomic-t10", prompt: "Why do practical lasers use 3- or 4-level pumping schemes rather than a direct 2-level scheme?", options: ["2-level atoms cannot absorb light", "A 2-level system under optical pumping saturates at equal populations rather than inverting", "3- and 4-level schemes require no energy input", "Population inversion is unnecessary in a 2-level system", "2-level atoms have no spontaneous emission"], answer: 1, solution: "In a strict 2-level system, pumping and stimulated emission rates both scale with the level populations and the system saturates at $N_1=N_2$, never truly inverting; routing through an auxiliary level avoids this.", difficulty: 3, tags: ["atomic", "lasers"], lesson: "atomic-lasers" },
    { id: "atomic-t11", prompt: "Both nuclear fusion of light nuclei and nuclear fission of heavy nuclei release energy because:", options: ["Both processes always increase total nucleon number", "Both move the nucleons involved toward the peak of the binding-energy-per-nucleon curve near iron", "Fusion releases energy but fission's energy release is a common misconception", "Binding energy per nucleon increases monotonically with mass number", "Both processes convert all nucleon mass entirely into energy"], answer: 1, solution: "The $B/A$ curve peaks near $A\\approx56$; light nuclei climb it via fusion, heavy nuclei climb it via fission — both increase total binding energy.", difficulty: 1, tags: ["atomic", "binding-energy"], lesson: "atomic-binding-energy" },
    { id: "atomic-t12", prompt: "Using $R=R_0A^{1/3}$ with $R_0=1.2\\text{ fm}$, the radius of a nucleus with $A=216$ is closest to:", options: ["1.8 fm", "3.6 fm", "6.0 fm", "7.2 fm", "12.0 fm"], answer: 3, solution: "$216^{1/3}=6$, so $R=1.2\\times6=7.2\\text{ fm}$.", difficulty: 1, tags: ["atomic", "nuclear-size"], lesson: "atomic-binding-energy" },
    { id: "atomic-t13", prompt: "A sample of radioactive isotope has $N_0$ nuclei at $t=0$. After a time equal to 5 half-lives, the number of remaining nuclei is:", options: ["$N_0/5$", "$N_0/10$", "$N_0/16$", "$N_0/32$", "$N_0/64$"], answer: 3, solution: "$(1/2)^5=1/32$.", difficulty: 1, tags: ["atomic", "decay-law"], lesson: "atomic-decay" },
    { id: "atomic-t14", prompt: "Why is the observed continuous energy spectrum of electrons in beta decay strong evidence for the neutrino?", options: ["It shows energy is not conserved in beta decay", "A two-body decay ($n\\to p+e^-$ alone) would force the electron to have one fixed energy, contradicted by the observed continuous spectrum, unless a third undetected particle shares the energy", "It shows the neutron has zero rest mass", "It proves lepton number is not conserved", "It shows the proton is unstable"], answer: 1, solution: "Two-body kinematics fixes the electron's energy uniquely; a continuous spectrum requires a third particle (the antineutrino) sharing the released energy in a three-body decay.", difficulty: 2, tags: ["atomic", "decay-modes"], lesson: "atomic-decay" },
    { id: "atomic-t15", prompt: "Which of the following reactions is forbidden by a conservation law?", options: ["$n\\to p+e^-+\\bar\\nu_e$", "$\\mu^-\\to e^-+\\gamma$", "$\\pi^0\\to\\gamma+\\gamma$", "$p+e^-\\to n+\\nu_e$", "$\\mu^-\\to e^-+\\bar\\nu_e+\\nu_\\mu$"], answer: 1, solution: "$\\mu^-\\to e^-+\\gamma$ conserves charge and energy but violates conservation of muon-flavor and electron-flavor lepton number separately — never observed.", difficulty: 2, tags: ["atomic", "standard-model"], lesson: "atomic-standard-model" },
    { id: "atomic-t16", prompt: "Which particle is a baryon?", options: ["Photon", "Electron", "Proton", "Muon neutrino", "Positron"], answer: 2, solution: "The proton ($uud$) is a three-quark baryon; the others are all leptons or a gauge boson, with baryon number 0.", difficulty: 1, tags: ["atomic", "standard-model"], lesson: "atomic-standard-model" },
    { id: "atomic-t17", prompt: "Using $hc=1240\\text{ eV nm}$, an X-ray photon of wavelength 0.10 nm has energy closest to:", options: ["1.2 keV", "6.2 keV", "12.4 keV", "24.8 keV", "124 keV"], answer: 2, solution: "$E=1240\\text{ eV nm}/0.10\\text{ nm}=12{,}400\\text{ eV}=12.4\\text{ keV}$.", difficulty: 1, tags: ["atomic", "units"], lesson: "atomic-detectors" },
    { id: "atomic-t18", prompt: "A particle detector must distinguish two closely-spaced gamma-ray energies with high precision. The best choice from the following is:", options: ["A Geiger–Müller counter", "A semiconductor (solid-state) detector, since electron-hole pair count is closely proportional to deposited energy with low statistical spread", "A simple photographic plate", "A cloud chamber alone", "A scintillation detector, which always outperforms solid-state detectors"], answer: 1, solution: "Solid-state detectors give the best energy resolution among common detector types, since they produce large numbers of electron-hole pairs per unit energy deposited, minimizing relative statistical spread.", difficulty: 2, tags: ["atomic", "detectors"], lesson: "atomic-detectors" }
  ]
});
