window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "foundations",
  title: "Foundations: Math and Habits for the Exam",
  order: 0,
  greWeight: 0,
  prereqs: [],
  blurb: "The calculus, vectors, and estimation reflexes every other module assumes you already have.",
  lessons: [
    {
      id: "foundations-derivative",
      title: "Rate of Change: From Average to Instantaneous",
      minutes: 15,
      discovery: "Shrinking the time interval in an average-rate calculation makes the ratio converge to a single number: the instantaneous rate.",
      sections: [
        { kind: "problem", md: `A car's trip computer gives you total distance and total time, so you can compute average speed. But the speedometer shows a number *right now*, while the car is speeding up on a ramp. That number is not "distance so far over time so far" — so what is it, and how would you compute it from a table of (time, position) readings alone?` },
        { kind: "candidates", md: `1. Use average speed for the whole trip: $\\bar v = \\Delta x/\\Delta t$ over the full drive.
2. Use the position one second ago and now: $v \\approx (x(t) - x(t-1\\,\\text{s}))/(1\\,\\text{s})$.
3. Do the same thing as (2), but with a much smaller gap, like $0.01\\,\\text{s}$.` },
        { kind: "failures", md: `Candidate 1 fails immediately: a trip with a red light and a highway sprint can average to "40 mph" the whole way, even though the car was never actually going 40. It tells you nothing about *this instant*.
Candidate 2 is closer, but on a car that's accelerating, the answer depends on which gap you pick — 1 s gives a different number than 0.1 s gives a different number than 0.01 s. If the "true" instantaneous speed is a single number, which gap is the right one?` },
        { kind: "discovery", md: `Try candidate 2 with shrinking gaps on $x(t) = t^2$ (meters) near $t=3\\,\\text{s}$: with $\\Delta t = 1$, $(x(4)-x(3))/1 = 7$; with $\\Delta t = 0.1$, the ratio is $6.1$; with $\\Delta t = 0.01$, it's $6.01$. The numbers aren't wandering — they're homing in on $6$. The instantaneous rate isn't one more choice of gap size; it's *the limit the ratio approaches as the gap shrinks to zero*. That limit exists even though "divide by zero" doesn't.` },
        { kind: "formal", md: `This limit is the **derivative**: $$\\frac{dx}{dt} = \\lim_{\\Delta t \\to 0} \\frac{x(t+\\Delta t)-x(t)}{\\Delta t}.$$ Geometrically it's the slope of the line tangent to the $x$-vs-$t$ curve at that point. Notation you'll see interchangeably: $\\dot x$, $x'(t)$, $\\frac{dx}{dt}$, $f'(x)$. Key building-block rule, provable from the limit: $\\frac{d}{dt}t^n = nt^{n-1}$.` },
        { kind: "apply", md: `For $x(t) = t^2$, the rule gives $\\frac{dx}{dt} = 2t$. At $t=3$: $2(3) = 6$ — exactly what the shrinking gaps converged to. Velocity is the derivative of position; acceleration is the derivative of velocity: $a = dv/dt$.` },
        { kind: "transfer", md: `Any "how fast is X changing right now" question is a derivative: current is the rate of charge flow, reaction rate is the rate concentration changes, power is the rate energy is delivered. Whenever the exam gives you a quantity as a function of something else and asks for a rate, this is the tool.` }
      ],
      checkpoints: [
        { q: "For $x(t) = t^3$ (meters, seconds), using the power rule, the instantaneous velocity at $t = 2\\,\\text{s}$ is closest to:", options: ["$8\\,\\text{m/s}$", "$12\\,\\text{m/s}$", "$6\\,\\text{m/s}$", "$4\\,\\text{m/s}$"], answer: 1, explain: "$dx/dt = 3t^2$, so at $t=2$: $3(4)=12\\,\\text{m/s}$." },
        { q: "An \"average velocity over 1 second\" estimate is closest to the true instantaneous velocity when:", options: ["velocity is changing rapidly during that second", "velocity is roughly constant during that second", "the object is momentarily at rest", "the time interval is exactly 1 second, regardless of motion"], answer: 1, explain: "The limiting process only matters when the rate is changing; if it's constant, any interval gives the same (correct) answer." }
      ]
    },
    {
      id: "foundations-integral",
      title: "Accumulation: From Sum of Slices to the Integral",
      minutes: 15,
      discovery: "Total accumulated change is the limit of summed thin slices — the integral is a sum, not a mysterious inverse operation.",
      sections: [
        { kind: "problem", md: `You have a velocity-vs-time graph for a rocket where speed keeps changing — no single "speed times time" works. How far did the rocket travel? You only know $v(t)$, not $x(t)$.` },
        { kind: "candidates", md: `1. Multiply the average of the starting and ending velocity by total time.
2. Chop the trip into a few big time chunks, treat velocity as constant in each chunk, and add up (chunk velocity) $\\times$ (chunk duration).
3. Do the same as (2), but with many, many thinner chunks.` },
        { kind: "failures", md: `Candidate 1 only works if $v(t)$ happens to be a straight line — for a rocket that surges and throttles back, "average of endpoints" can be wildly wrong.
Candidate 2 is a real improvement (this is a Riemann sum), but with only a few fat chunks, each chunk's constant-velocity assumption is a bad approximation whenever $v(t)$ curves noticeably within a chunk — you either overshoot or undershoot depending on whether velocity was rising or falling in that chunk.` },
        { kind: "discovery", md: `As the chunks get thinner, the constant-velocity assumption gets better in each one (over a tiny sliver of time, velocity barely changes), and the sum of (velocity)$\\times$(tiny duration) converges to a fixed number — the true distance. Each thin slice contributes a sliver of area under the $v$-$t$ curve, so total distance is the *area under the velocity curve*.` },
        { kind: "formal", md: `This limiting sum is the **definite integral**: $$x = \\int_{t_1}^{t_2} v(t)\\,dt = \\lim_{\\Delta t \\to 0} \\sum_i v(t_i)\\,\\Delta t.$$ It is exactly the reverse bookkeeping of the derivative: if $F'(t) = f(t)$, then $\\int_{t_1}^{t_2} f(t)\\,dt = F(t_2)-F(t_1)$ (the Fundamental Theorem of Calculus). Key building block: $\\int t^n\\,dt = \\frac{t^{n+1}}{n+1} + C$ (for $n \\ne -1$).` },
        { kind: "apply", md: `If $v(t) = 2t$ (m/s), distance from $t=0$ to $t=3\\,\\text{s}$ is $\\int_0^3 2t\\,dt = [t^2]_0^3 = 9\\,\\text{m}$ — matching the area of the triangle under the line $v=2t$, base 3, height 6, area $\\tfrac12(3)(6)=9$.` },
        { kind: "transfer", md: `Whenever the exam gives a rate and asks for a total — work from a varying force, charge from a varying current, impulse from a varying force over time — that total is an integral, i.e. "area under the rate curve." When the curve is a simple shape (triangle, rectangle), skip the calculus and just compute the area.` }
      ],
      checkpoints: [
        { q: "A force varies as $F(x) = 3x$ (N, meters). The work done moving from $x=0$ to $x=4\\,\\text{m}$ equals the area under $F(x)$, which is:", options: ["$12\\,\\text{J}$", "$24\\,\\text{J}$", "$48\\,\\text{J}$", "$6\\,\\text{J}$"], answer: 1, explain: "Triangle area: $\\tfrac12(4)(12) = 24\\,\\text{J}$; matches $\\int_0^4 3x\\,dx = [\\tfrac32x^2]_0^4 = 24$." },
        { q: "Why does shrinking the width of Riemann-sum chunks improve the approximation of area under a curved (non-straight) function?", options: ["Thinner chunks always sum to a smaller total", "Over a thinner chunk the function is closer to constant, so the rectangle better matches the true curve", "Calculus requires an even number of chunks", "It doesn't — chunk width has no effect on accuracy"], answer: 1, explain: "The rectangle approximation's error comes from the function changing within the chunk; a thinner chunk means less change, less error." }
      ]
    },
    {
      id: "foundations-chain-product",
      title: "Chain and Product Rule: Differentiating Things Built From Other Things",
      minutes: 12,
      discovery: "A rate of change of a composite quantity is the product of the rates of each layer it's built from.",
      sections: [
        { kind: "problem", md: `A pond's radius grows at a known rate, $dr/dt = 0.5\\,\\text{m/s}$. You need $dA/dt$, how fast the *area* $A=\\pi r^2$ is growing, but you only directly know how $A$ depends on $r$, and how $r$ depends on $t$ — not how $A$ depends on $t$.` },
        { kind: "candidates", md: `1. Just plug $r(t)$ into $A=\\pi r^2$ to get $A(t)$ explicitly, then differentiate that.
2. Multiply the two known rates together directly: $\\frac{dA}{dr}\\cdot\\frac{dr}{dt}$, treating the derivative like a fraction that "cancels."
3. Since $A$ depends on $r$ which depends on $t$, ignore the intermediate step and just differentiate $A$ with respect to $t$ using the power rule directly on $t^2$.` },
        { kind: "failures", md: `Candidate 1 always works but is often impractical: on the real exam you frequently *don't* have an explicit formula for $r(t)$ — you're just told numeric rates at one instant. You need a method that works without ever writing $A(t)$ out.
Candidate 3 is a category error: $A = \\pi r^2$ is a function of $r$, not of $t$; there's no "$t^2$" to apply the power rule to unless you already know $r(t)=t$, which isn't given.` },
        { kind: "discovery", md: `Candidate 2's "cancellation" isn't just a mnemonic trick — it's exactly what the limit definition gives you: $\\frac{\\Delta A}{\\Delta t} = \\frac{\\Delta A}{\\Delta r}\\cdot\\frac{\\Delta r}{\\Delta t}$ is an algebraic identity for any nonzero $\\Delta r$, and it survives the limit $\\Delta t \\to 0$ (which also forces $\\Delta r \\to 0$ if $r(t)$ is smooth). So multiplying the two known rates is legitimate, not a coincidence.` },
        { kind: "formal", md: `This is the **chain rule**: $$\\frac{d}{dt}f(g(t)) = f'(g(t))\\cdot g'(t).$$ A companion rule for *products* of two functions of the same variable, $h(t)=f(t)g(t)$, follows from a similar limit argument: $$\\frac{d}{dt}\\big[f(t)g(t)\\big] = f'(t)g(t) + f(t)g'(t)$$ (each factor gets differentiated in turn, the other left alone).` },
        { kind: "apply", md: `$\\frac{dA}{dr} = 2\\pi r$. At the instant $r = 4\\,\\text{m}$: $\\frac{dA}{dt} = 2\\pi(4)(0.5) = 4\\pi \\approx 12.6\\,\\text{m}^2/\\text{s}$ — obtained without ever writing $A(t)$ explicitly.` },
        { kind: "transfer", md: `Chain rule is how you handle $\\sin(\\omega t)$, $e^{-t/\\tau}$, or any "rate depends on a rate" setup — it's everywhere in oscillations and decay. Product rule is how you differentiate momentum $p=mv$ when *both* mass and velocity change (rockets losing fuel), or power $P=IV$ when both current and voltage vary.` }
      ],
      checkpoints: [
        { q: "If $f(t) = \\sin(3t)$, then $f'(t)$ is:", options: ["$\\cos(3t)$", "$3\\cos(3t)$", "$-3\\cos(3t)$", "$\\sin(3)\\cos(t)$"], answer: 1, explain: "Chain rule: derivative of $\\sin(u)$ is $\\cos(u)$, times $du/dt = 3$." },
        { q: "A rocket has $p(t) = m(t)v(t)$ with both mass and velocity changing. $dp/dt$ equals:", options: ["$\\frac{dm}{dt}\\frac{dv}{dt}$", "$m\\frac{dv}{dt} + v\\frac{dm}{dt}$", "$m\\frac{dv}{dt}$ only, mass changes don't matter", "$v\\frac{dm}{dt}$ only, velocity changes don't matter"], answer: 1, explain: "Product rule: both terms are needed since both factors vary with time." }
      ]
    },
    {
      id: "foundations-vectors",
      title: "Vectors: Dot and Cross Products as Answers to Different Questions",
      minutes: 15,
      discovery: "Dot product extracts \"how much overlap/alignment\"; cross product extracts \"how much perpendicularity, with a handedness.\" Two different questions need two different multiplications.",
      sections: [
        { kind: "problem", md: `You drag a crate with force $\\vec F$ at an angle to the direction it actually moves, $\\vec d$. How much *work* did you do (a single number, the energy transferred)? Separately: a wrench applies force $\\vec F$ at the end of a handle $\\vec r$ from the pivot — how much *twisting effect* (a directional quantity, with an axis and a handedness) results? Ordinary multiplication only works for numbers, not arrows with direction.` },
        { kind: "candidates", md: `1. Multiply the magnitudes: $|\\vec F||\\vec d|$, ignore the angle between them.
2. Multiply magnitudes, but scale by how *aligned* the vectors are: $|\\vec F||\\vec d|\\cos\\theta$.
3. Multiply magnitudes, but scale by how *perpendicular* the vectors are: $|\\vec F||\\vec d|\\sin\\theta$, and additionally record an axis and sense of rotation.` },
        { kind: "failures", md: `Candidate 1 fails a basic sanity check: pushing a crate sideways to its motion does zero work (you exert force, but the crate doesn't move any further in your push direction), yet candidate 1 would report a nonzero answer regardless of angle.
For the wrench problem, candidate 2 (the "aligned" version) gives *zero* twisting effect when force is exactly perpendicular to the handle — which is exactly when a wrench is most effective. That's backwards.` },
        { kind: "discovery", md: `Work needs the *aligned* component of force — only the part of $\\vec F$ that points along $\\vec d$ does anything, which is $|\\vec F|\\cos\\theta$ resolved along $\\vec d$: candidate 2 for work. Torque needs the opposite: only the part of $\\vec F$ *perpendicular* to the handle produces a twist, and the twist has a definite rotation axis (found by curling fingers from $\\vec r$ to $\\vec F$) — candidate 3 for torque. The two everyday questions ("how much overlap" vs "how much perpendicular turning effect, and about what axis") demand two structurally different products.` },
        { kind: "formal", md: `**Dot product** (scalar result): $$\\vec A\\cdot\\vec B = |\\vec A||\\vec B|\\cos\\theta = A_xB_x+A_yB_y+A_zB_z.$$ **Cross product** (vector result, magnitude $|\\vec A||\\vec B|\\sin\\theta$, direction by the right-hand rule, perpendicular to both): $$\\vec A\\times\\vec B = (A_yB_z-A_zB_y,\\ A_zB_x-A_xB_z,\\ A_xB_y-A_yB_x).$$ Note $\\vec A\\times\\vec B = -\\vec B\\times\\vec A$ (order matters); $\\vec A\\cdot\\vec B = \\vec B\\cdot\\vec A$ (order doesn't).` },
        { kind: "apply", md: `Work: $W = \\vec F\\cdot\\vec d$. If $|\\vec F|=10\\,\\text{N}$, $|\\vec d|=3\\,\\text{m}$, $\\theta=60°$: $W = 10(3)(0.5)=15\\,\\text{J}$. Torque: $\\vec\\tau = \\vec r\\times\\vec F$. If $|\\vec r|=0.2\\,\\text{m}$, $|\\vec F|=50\\,\\text{N}$ perpendicular ($\\theta=90°$): $|\\vec\\tau| = 0.2(50)(1) = 10\\,\\text{N}\\cdot\\text{m}$.` },
        { kind: "transfer", md: `Dot products show up wherever "effective component along a direction" matters: power $P=\\vec F\\cdot\\vec v$, flux $\\Phi = \\vec E\\cdot\\vec A$. Cross products show up wherever rotation, magnetism, or angular momentum appears: $\\vec L = \\vec r\\times\\vec p$, magnetic force $\\vec F = q\\vec v\\times\\vec B$. On the exam, seeing "$\\cos$" in a formula signals a dot product in disguise; seeing "$\\sin$" with a stated rotation axis signals a cross product.` }
      ],
      checkpoints: [
        { q: "Two vectors are perpendicular. Their dot product is:", options: ["Maximum possible", "Zero", "Equal to the product of magnitudes", "Undefined"], answer: 1, explain: "$\\cos(90°)=0$." },
        { q: "A force is applied exactly along the handle of a wrench (parallel to $\\vec r$, $\\theta=0$). The torque magnitude is:", options: ["Maximum possible", "Zero", "Half of maximum", "Depends on force magnitude only"], answer: 1, explain: "$\\sin(0°)=0$ — force along the handle produces no twist." }
      ]
    },
    {
      id: "foundations-taylor",
      title: "Taylor Series: Replacing a Hard Function With a Good-Enough Polynomial",
      minutes: 18,
      discovery: "Near any point, a smooth function is well-approximated by a polynomial built from its derivatives there — and for small displacements, the first surviving term usually dominates everything else.",
      sections: [
        { kind: "problem", md: `A pendulum's restoring force involves $\\sin\\theta$. Newton's law with $\\sin\\theta$ in it has no clean, exam-friendly solution — the exact motion isn't even a simple sinusoid. But for a pendulum swinging through a *small* angle, the exam expects you to instantly replace $\\sin\\theta$ with something simple. What justifies that swap, and what exactly should replace it?` },
        { kind: "candidates", md: `1. Just set $\\sin\\theta \\approx 0$ for small $\\theta$ and drop it entirely.
2. Replace $\\sin\\theta$ with $\\theta$ itself (in radians).
3. Replace $\\sin\\theta$ with $\\theta - \\theta^3/6$ (keep an extra term for accuracy).` },
        { kind: "failures", md: `Candidate 1 destroys the physics: if the restoring force is zero, there's no restoring force at all, and the pendulum wouldn't oscillate — contradicts reality.
Candidate 3 isn't wrong, but for the GRE's typical "small angle" regime it's overkill: at $\\theta=0.1\\,\\text{rad}$, $\\theta^3/6 \\approx 0.00017$, over 500× smaller than $\\theta$ itself — carrying it adds complexity without changing which answer choice you'd pick.` },
        { kind: "discovery", md: `Plot $\\sin\\theta$ against $\\theta$ near $\\theta=0$: the curve and the straight line $y=\\theta$ are visually indistinguishable for small $\\theta$, because $\\sin\\theta$'s value, *and its slope*, both match $\\theta$'s at the origin ($\\sin 0 = 0$, $\\frac{d}{d\\theta}\\sin\\theta|_0 = \\cos 0 = 1$). Matching a function's value and successive derivatives at a point, term by term, is exactly how you build the best polynomial approximation near that point — and the very next term ($-\\theta^3/6$) is the size of the *error* you're accepting, which for small $\\theta$ is negligible compared to $\\theta$ itself.` },
        { kind: "formal", md: `The **Taylor series** of $f$ about $x=0$ (Maclaurin series): $$f(x) = f(0) + f'(0)x + \\frac{f''(0)}{2!}x^2 + \\frac{f'''(0)}{3!}x^3 + \\cdots$$ Memorize for the exam: $$\\sin x \\approx x - \\frac{x^3}{6}, \\quad \\cos x \\approx 1-\\frac{x^2}{2}, \\quad e^x \\approx 1+x+\\frac{x^2}{2}, \\quad (1+x)^n \\approx 1+nx \\ (\\text{for } |x|\\ll 1).$$ "Small $x$" means keep only the first nonzero term unless the leading terms cancel (then go to the next order).` },
        { kind: "apply", md: `Small-angle pendulum: $\\sin\\theta\\approx\\theta$ turns $ml\\ddot\\theta = -mg\\sin\\theta$ into the linear equation $\\ddot\\theta = -(g/l)\\theta$ — solvable by inspection (next lesson). Numeric check: $\\sqrt{1.02} = (1+0.02)^{1/2} \\approx 1+\\tfrac12(0.02) = 1.01$ (true value $1.00995$) — a mental-math shortcut worth 10+ seconds on the real exam.` },
        { kind: "transfer", md: `Whenever the exam says "for small $x$," "to leading order," or gives you a suspiciously messy expression evaluated near a limiting case, Taylor-expand and keep the first surviving term. This is the single most exam-relevant math skill: relativistic energy $\\approx \\tfrac12mv^2$ for $v\\ll c$, binomial approximations for error propagation, small-oscillation limits of any potential.` }
      ],
      checkpoints: [
        { q: "For small $x$, $\\frac{1}{1-x}$ is approximately:", options: ["$1-x$", "$1+x$", "$1-x^2$", "$x$"], answer: 1, explain: "$(1-x)^{-1} \\approx 1+(-1)(-x) = 1+x$, using $(1+u)^n\\approx1+nu$ with $u=-x,\\,n=-1$." },
        { q: "A formula reduces to $\\frac{(1+\\epsilon)^2 - 1}{\\epsilon}$ for small $\\epsilon \\ne 0$. Its limiting value as $\\epsilon\\to 0$ is:", options: ["$0$", "$1$", "$2$", "Undefined"], answer: 2, explain: "$(1+\\epsilon)^2\\approx 1+2\\epsilon$, so numerator $\\approx 2\\epsilon$, and the ratio $\\to 2$." }
      ]
    },
    {
      id: "foundations-complex",
      title: "Complex Numbers and $e^{i\\theta}$: One Object Instead of Two",
      minutes: 15,
      discovery: "Encoding a 2D rotating quantity as a single complex number turns coupled sine/cosine bookkeeping into ordinary exponent algebra.",
      sections: [
        { kind: "problem", md: `An AC circuit has a voltage $V\\cos(\\omega t)$ driving a resistor and capacitor together. Tracking the resulting current means juggling a $\\cos(\\omega t)$ term, a $\\sin(\\omega t)$ term (from the capacitor's phase-shifted response), sum-to-product trig identities, and phase angles — all just to add two oscillating signals with different phases. It's correct but miserable.` },
        { kind: "candidates", md: `1. Grind through it with trig identities: sum-of-angle formulas, converting everything to a single $A\\cos(\\omega t + \\phi)$ using $R\\cos\\phi$, $R\\sin\\phi$ bookkeeping.
2. Represent each oscillating quantity as a point $(\\cos\\theta, \\sin\\theta)$ in a 2D plane and add the points as vectors.
3. Represent each oscillating quantity as a single complex number $\\cos\\theta + i\\sin\\theta$ and use ordinary algebra on it.` },
        { kind: "failures", md: `Candidate 1 works but the identities pile up fast — every added phase-shifted signal means another round of expansion; error-prone and slow, exactly wrong for a timed exam.
Candidate 2 (vector addition) correctly *adds* phased signals, but stalls the moment you need to *multiply* by something that itself rotates (like an impedance) — there's no natural "multiply two arrows" operation that matches what the physics needs.` },
        { kind: "discovery", md: `Candidate 3's complex number $z=\\cos\\theta+i\\sin\\theta$ has magnitude $1$ and angle $\\theta$, same information as the vector. But complex numbers, unlike plane vectors, come with a built-in, well-defined multiplication — and remarkably, multiplying two such numbers *adds their angles* (verify: $(\\cos\\alpha+i\\sin\\alpha)(\\cos\\beta+i\\sin\\beta) = \\cos(\\alpha+\\beta)+i\\sin(\\alpha+\\beta)$ by expanding and using angle-sum identities once, then never again). That "angles add under multiplication" behavior is exactly what exponents do ($x^a x^b = x^{a+b}$) — suggesting $\\cos\\theta+i\\sin\\theta$ secretly *is* an exponential.` },
        { kind: "formal", md: `**Euler's formula**: $$e^{i\\theta} = \\cos\\theta + i\\sin\\theta.$$ A rotating physical quantity $A\\cos(\\omega t+\\phi)$ is represented as the real part of $Ae^{i(\\omega t+\\phi)} = Ae^{i\\phi}e^{i\\omega t}$; the constant complex number $Ae^{i\\phi}$ (a "phasor") carries the amplitude and phase, and multiplying phasors together (for impedances, transfer functions) is now just exponent addition. Recover physical values at the end by taking the real part.` },
        { kind: "apply", md: `Adding $\\cos(\\omega t)$ and $\\cos(\\omega t + 90°)$: as phasors, $1 + i$ (since $e^{i\\cdot 90°}=i$), magnitude $\\sqrt2$, angle $45°$ — so the sum is $\\sqrt2\\cos(\\omega t+45°)$, read off with no trig identities needed.` },
        { kind: "transfer", md: `This trick underlies AC circuit analysis (impedance as complex resistance), quantum mechanics (wavefunctions are inherently complex), and any driven-oscillator problem (next module). Recognize the pattern: two things oscillating at the same frequency with different phases → encode as complex numbers, do algebra, take the real part at the end.` }
      ],
      checkpoints: [
        { q: "$e^{i\\pi}$ equals:", options: ["$1$", "$-1$", "$i$", "$0$"], answer: 1, explain: "$\\cos\\pi + i\\sin\\pi = -1 + 0 = -1$." },
        { q: "Multiplying two phasors $Ae^{i\\alpha}$ and $Be^{i\\beta}$ gives a result whose angle is:", options: ["$\\alpha\\beta$", "$\\alpha+\\beta$", "$\\alpha-\\beta$", "$\\alpha/\\beta$"], answer: 1, explain: "Exponents add: $e^{i\\alpha}e^{i\\beta}=e^{i(\\alpha+\\beta)}$." }
      ]
    },
    {
      id: "foundations-odes",
      title: "Solving ODEs by Guessing: Exponentials and Sinusoids as the Right Shapes",
      minutes: 15,
      discovery: "Equations relating a function to its own derivatives are solved by guessing a functional shape that reproduces itself under differentiation, then fitting the guess's parameters.",
      sections: [
        { kind: "problem", md: `Two physics equations recur constantly: radioactive decay, $\\frac{dN}{dt} = -\\lambda N$ (the rate of loss is proportional to what's left), and the small-angle pendulum from two lessons ago, $\\ddot\\theta = -\\omega^2\\theta$ (the acceleration is proportional to *minus* the displacement). Neither is solved by direct integration — $N$ and its own derivative are tangled together in the same equation. How do you find $N(t)$ or $\\theta(t)$?` },
        { kind: "candidates", md: `1. Try a polynomial guess, like $N(t) = a + bt + ct^2$, and see if it can satisfy the equation.
2. Try guessing that the function looks like itself under differentiation: $N(t) = Ce^{kt}$ for some constant $k$ to be determined.
3. For the pendulum, try a straight-line guess $\\theta(t) = At$.` },
        { kind: "failures", md: `Candidate 1: differentiating a polynomial *lowers* its degree ($ct^2 \\to 2ct$), so $\\frac{dN}{dt}=-\\lambda N$ would require a degree-1 polynomial to equal a degree-2 one times $-\\lambda$ — impossible unless everything is zero. Polynomials don't reproduce their own shape under differentiation.
Candidate 3 for the pendulum: $\\ddot\\theta = 0$ for a straight line, but the equation demands $\\ddot\\theta=-\\omega^2 At \\ne 0$ — fails immediately unless $A=0$ (no motion), which isn't the physical pendulum.` },
        { kind: "discovery", md: `$e^{kt}$ is special: $\\frac{d}{dt}e^{kt} = ke^{kt}$ — differentiating just multiplies by a constant, the *shape* is unchanged. Try $N=Ce^{kt}$ in $\\dot N = -\\lambda N$: $Cke^{kt} = -\\lambda Ce^{kt}$, so $k=-\\lambda$ works for *any* $C$ — the guess succeeds by turning a differential equation into an algebra problem for $k$. For the pendulum's *second*-derivative equation, try $\\theta = Ce^{kt}$: $Ck^2e^{kt} = -\\omega^2Ce^{kt}$ gives $k^2=-\\omega^2$, i.e. $k=\\pm i\\omega$ — complex, but by the previous lesson $e^{i\\omega t}=\\cos\\omega t + i\\sin\\omega t$, so real solutions are $\\sin(\\omega t)$ and $\\cos(\\omega t)$.` },
        { kind: "formal", md: `For a **linear ODE** with constant coefficients, guess $x=Ce^{kt}$ (the "characteristic equation" method). $\\dot x = kx \\Rightarrow x(t)=x_0e^{kt}$ (exponential growth/decay). $\\ddot x = -\\omega^2 x \\Rightarrow x(t) = A\\cos(\\omega t) + B\\sin(\\omega t)$, or equivalently $A\\cos(\\omega t + \\phi)$, with constants fixed by initial position and velocity. $\\ddot x = +\\omega^2 x$ (note the sign) gives real exponentials $x=Ae^{\\omega t}+Be^{-\\omega t}$ — runaway growth/decay, not oscillation.` },
        { kind: "apply", md: `Decay: $N(t) = N_0e^{-\\lambda t}$; half-life is where $e^{-\\lambda t}=1/2$, i.e. $t_{1/2}=\\ln2/\\lambda$. Pendulum: $\\theta(t) = \\theta_0\\cos(\\omega t)$ with $\\omega=\\sqrt{g/l}$, released from rest at $\\theta_0$.` },
        { kind: "transfer", md: `This single pattern-match — "does the equation have $\\dot x \\propto x$ (exponential) or $\\ddot x \\propto -x$ (oscillation)?" — solves RC circuit charging, radioactive chains, simple harmonic motion, and (with a sign flip) unstable equilibria, without ever grinding through integration by hand. Recognizing the *sign* in front of the proportionality is the whole game: minus gives oscillation or decay, plus gives runaway growth.` }
      ],
      checkpoints: [
        { q: "An equation $\\dot x = 3x$ has general solution:", options: ["$x=A\\sin(3t)$", "$x=Ae^{3t}$", "$x=Ae^{-3t}$", "$x=A+3t$"], answer: 1, explain: "$k=3$ (positive) gives growing exponential, not oscillation." },
        { q: "An equation $\\ddot x = -9x$ has angular frequency $\\omega$ equal to:", options: ["$9$", "$3$", "$81$", "$-3$"], answer: 1, explain: "Matching $\\ddot x=-\\omega^2 x$ gives $\\omega^2=9$, so $\\omega=3$." }
      ]
    },
    {
      id: "foundations-matrices",
      title: "Matrices and Eigenvalues: Directions a Transformation Leaves Alone",
      minutes: 15,
      discovery: "Most vectors get both stretched and rotated by a linear transformation, but a special few directions only get stretched — those are the eigenvectors, and the stretch factor is the eigenvalue.",
      sections: [
        { kind: "problem", md: `Two masses connected by springs (a coupled oscillator) can, in general, jiggle in a complicated combination of motions. But physically you know there must be some special starting configurations where *both* masses oscillate at the exact same single frequency, moving in a fixed pattern relative to each other (the two textbook "normal modes": both masses in phase, or exactly out of phase). How do you find those special configurations directly, instead of guessing and checking?` },
        { kind: "candidates", md: `1. Simulate many different starting configurations numerically and see which ones look periodic.
2. Write the coupled equations as a matrix acting on a state vector, and look for input vectors that come back out *scaled by a number but not rotated in direction*.
3. Assume any two starting configurations happen to work and just call them "modes."` },
        { kind: "failures", md: `Candidate 1 is not wrong in principle but is exam-impossible and doesn't generalize — you need a method that always finds the special directions, not a search.
Candidate 3 begs the question: not every configuration is a normal mode (most starting configurations produce messy, beating motion with two frequencies mixed together) — you need a criterion for *which* configurations qualify.` },
        { kind: "discovery", md: `Write the coupled spring equations as $\\ddot{\\vec x} = -M\\vec x$ for some matrix $M$ (built from masses and spring constants) and state vector $\\vec x$ (the two displacements). A normal mode is a special $\\vec x$-direction where the matrix's action is just "multiply by a number" — $M\\vec x = \\mu \\vec x$ — because that's exactly the condition under which the ODE from the previous lesson decouples into a single $\\ddot x_\\parallel = -\\mu x_\\parallel$ along that direction, giving one clean frequency $\\omega=\\sqrt\\mu$. Directions where the matrix instead rotates the vector into a *different* direction don't decouple — they mix frequencies, which is the messy behavior you're trying to avoid.` },
        { kind: "formal", md: `A vector $\\vec v \\ne 0$ satisfying $$M\\vec v = \\mu \\vec v$$ is an **eigenvector** of $M$, with **eigenvalue** $\\mu$. Found by solving $\\det(M-\\mu I) = 0$ (the "characteristic equation") for $\\mu$, then back-substituting for $\\vec v$. For an $n\\times n$ matrix there are up to $n$ eigenvalue/eigenvector pairs.` },
        { kind: "apply", md: `Two equal masses $m$, springs of constant $k$ to walls and $k$ between them: $M = \\frac{k}{m}\\begin{pmatrix}2&-1\\\\-1&2\\end{pmatrix}$. Eigenvalues $\\mu=k/m$ (eigenvector $(1,1)$: both masses move together, weak restoring force from the middle spring, low frequency) and $\\mu=3k/m$ (eigenvector $(1,-1)$: masses move oppositely, middle spring fully engaged, higher frequency).` },
        { kind: "transfer", md: `Eigenvalues/eigenvectors are the general tool for "what are the natural, non-mixing modes of this coupled system": normal modes of vibration, principal axes of the moment-of-inertia tensor (rotation module), stationary states in quantum mechanics (energy eigenvalues of the Hamiltonian). Recognize: whenever a system is described by a matrix acting on a state, and you want directions/states that evolve without changing character, you want eigenvectors.` }
      ],
      checkpoints: [
        { q: "If $M\\vec v = 5\\vec v$ for some nonzero $\\vec v$, then $\\vec v$ is:", options: ["An eigenvector with eigenvalue 5", "A normal mode with frequency 5", "Not physically meaningful", "Only valid if $M$ is diagonal"], answer: 0, explain: "That's exactly the eigenvector/eigenvalue definition." },
        { q: "In the two-mass coupled spring example, the higher-frequency mode corresponds to the masses moving:", options: ["In phase, same displacement", "In antiphase, opposite displacement", "One mass stationary", "Randomly, no fixed pattern"], answer: 1, explain: "The antiphase mode engages the middle spring fully, giving the larger eigenvalue $3k/m$." }
      ]
    },
    {
      id: "foundations-dimensional-analysis",
      title: "Dimensional Analysis and Fermi Estimation as Exam Weapons",
      minutes: 15,
      discovery: "Units alone often pin down a formula's structure up to a dimensionless constant — and that's frequently enough to eliminate 4 of 5 answer choices without doing the physics.",
      sections: [
        { kind: "problem", md: `On the real exam you have about 1.7 minutes per question and no calculator. A question asks for the period of a pendulum, and you've forgotten (or never memorized) the exact formula — but you remember it must depend on length $l$, gravity $g$, and possibly mass $m$. Five answer choices are given, all different combinations of $l$, $g$, $m$. Can you find the right one without recalling or re-deriving the physics?` },
        { kind: "candidates", md: `1. Try to re-derive the pendulum equation from scratch under time pressure.
2. Guess based on which formula "looks most familiar."
3. Write down every quantity's units, and demand the combination on the right side produce units of time — algebra on the exponents, no physics needed.` },
        { kind: "failures", md: `Candidate 1 is correct in principle (and you did it in the ODE lesson) but costs 3-4 minutes — too slow when 20 more questions are waiting.
Candidate 2 has no principled stopping point: "familiar-looking" is not a filter, it's a guess, and GRE distractors are deliberately built to look familiar.` },
        { kind: "discovery", md: `Assign units: $[l] = \\text{m}$, $[g] = \\text{m/s}^2$, $[m] = \\text{kg}$, and the answer (period) must be $\\text{s}$. Try $T \\propto l^a g^b m^c$: units give $\\text{m}^{a+b}\\,\\text{s}^{-2b}\\,\\text{kg}^c = \\text{s}^1$. Matching powers: seconds force $-2b=1 \\Rightarrow b=-1/2$; kilograms force $c=0$ (mass *cannot* appear — no combination of kg with the other units cancels it, so any answer choice containing $m$ is automatically wrong); meters force $a+b=0 \\Rightarrow a=1/2$. Units alone give $T \\propto \\sqrt{l/g}$, eliminating every choice with the wrong mass-dependence or the wrong power of $l$ and $g$ — often leaving only one or two candidates, in under 30 seconds.` },
        { kind: "formal", md: `**Dimensional analysis**: every valid physics equation must be dimensionally consistent (both sides carry identical units); solving for the exponents that make a proposed combination match the target units is a fast, physics-free way to constrain a formula's structure, up to an unknown dimensionless constant (like the $2\\pi$ in $T=2\\pi\\sqrt{l/g}$, which dimensional analysis alone cannot find). **Fermi estimation**: for "order of magnitude" questions, break an unknown quantity into a product of roughly-known factors, round each to the nearest power of 10 (or a memorable round number), and multiply — errors partially cancel because some factors are rounded up and some down.` },
        { kind: "apply", md: `Fermi example: estimate the number of atoms in a person ($\\sim$70 kg, mostly water, $\\sim18\\,\\text{g/mol}$, $6\\times10^{23}$/mol): $70{,}000\\,\\text{g} / 18\\,\\text{g/mol} \\approx 4000\\,\\text{mol}$, times $6\\times10^{23} \\approx 2\\times10^{27}$ atoms — the real answer is this order of magnitude, which is all a Fermi question ever asks for.` },
        { kind: "transfer", md: `Use dimensional analysis first on *every* "which formula" question before trying to recall or derive — it's the highest-value 20 seconds on the exam. Use Fermi estimation whenever exact computation is infeasible without a calculator but the answer choices are spread by factors of 10 or more.` }
      ],
      checkpoints: [
        { q: "A quantity has units of energy $[E]=\\text{kg m}^2\\text{s}^{-2}$. Which combination of mass $m$ (kg), speed $v$ (m/s) has these units?", options: ["$mv$", "$mv^2$", "$m^2v$", "$mv^3$"], answer: 1, explain: "$[mv^2] = \\text{kg}\\cdot(\\text{m/s})^2 = \\text{kg m}^2\\text{s}^{-2}$, matches." },
        { q: "Dimensional analysis alone can determine:", options: ["The exact numerical prefactor (like $2\\pi$ or $1/2$) in a formula", "The powers of each variable, up to an unknown dimensionless constant", "Whether a formula is physically true", "The sign of a formula's result"], answer: 1, explain: "Dimensionless constants are, by definition, invisible to a units-only argument." }
      ]
    },
    {
      id: "foundations-si-units",
      title: "SI Units and the Constants You Must Know by Heart",
      minutes: 12,
      discovery: "A small fixed set of constants and their approximate values, memorized once, replaces looking anything up — because the real exam gives you nothing.",
      sections: [
        { kind: "problem", md: `A question gives you a photon wavelength and asks for its energy in eV. No calculator, no reference sheet, no internet — the exam hands you the problem and nothing else. If you don't already have $h$, $c$, and the eV-to-joule conversion in your head, the question is unsolvable in the time available, regardless of how well you understand photons.` },
        { kind: "candidates", md: `1. Rely on remembering the *shape* of formulas and hope the numbers "work out" approximately.
2. Memorize every constant to 4+ significant figures, exactly as printed in a textbook.
3. Memorize a short list of constants to 1-2 significant figures plus their power of ten, and memorize the small set of unit conversions that recur.` },
        { kind: "failures", md: `Candidate 1 fails on any question that asks for an actual number (not just a scaling) — "approximately right shape" gives you nothing to bubble in on a 5-option numeric-answer question.
Candidate 2 wastes study time: the exam's answer choices are typically spread widely enough (often by factors of 2 or more, or different powers of ten) that 4-sig-fig precision on constants is never the bottleneck — the bottleneck is *having the right order of magnitude at all*, fast.` },
        { kind: "discovery", md: `What actually distinguishes the 5 answer choices on a typical numeric question is order of magnitude and simple factors (2, $\\pi$, $\\sqrt2$) — not the 4th significant figure of $c$. So the efficient memorization target is: 2 significant figures and the correct power of ten, for a short, fixed list, practiced until instant.` },
        { kind: "formal", md: `Memorize (2 sig figs + power of ten):
$c = 3.0\\times10^8\\,\\text{m/s}$; $g = 9.8\\,\\text{m/s}^2$ ($\\approx10$ for quick estimates); $G = 6.7\\times10^{-11}\\,\\text{N m}^2/\\text{kg}^2$; $h = 6.6\\times10^{-34}\\,\\text{J s}$ (or $\\hbar = 1.05\\times10^{-34}\\,\\text{J s}$); $e = 1.6\\times10^{-19}\\,\\text{C}$; $k_B = 1.4\\times10^{-23}\\,\\text{J/K}$; $m_e = 9.1\\times10^{-31}\\,\\text{kg}$; $\\epsilon_0 = 8.9\\times10^{-12}\\,\\text{C}^2/(\\text{N m}^2)$; $N_A = 6.0\\times10^{23}\\,\\text{mol}^{-1}$; $1\\,\\text{eV} = 1.6\\times10^{-19}\\,\\text{J}$; $hc \\approx 1240\\,\\text{eV}\\cdot\\text{nm}$ (a derived shortcut worth memorizing directly — it turns photon-energy questions into one division).` },
        { kind: "apply", md: `Photon of wavelength $500\\,\\text{nm}$: $E = hc/\\lambda \\approx 1240\\,\\text{eV}\\cdot\\text{nm} / 500\\,\\text{nm} \\approx 2.5\\,\\text{eV}$ — one line, no lookup, using the derived shortcut instead of separately recalling $h$ and $c$ and multiplying.` },
        { kind: "transfer", md: `Build a small set of *derived* shortcuts like $hc\\approx1240\\,\\text{eV}\\cdot\\text{nm}$ on top of the base constants — these collapse a two-constant, two-step calculation into a single division and are worth the extra minute of memorization now for every future photon-energy question.` }
      ],
      checkpoints: [
        { q: "The order of magnitude of the elementary charge $e$ is:", options: ["$10^{-19}\\,\\text{C}$", "$10^{-23}\\,\\text{C}$", "$10^{-34}\\,\\text{C}$", "$10^{-11}\\,\\text{C}$"], answer: 0, explain: "$e \\approx 1.6\\times10^{-19}\\,\\text{C}$." },
        { q: "Using $hc\\approx1240\\,\\text{eV}\\cdot\\text{nm}$, a photon of wavelength $620\\,\\text{nm}$ has energy closest to:", options: ["$0.5\\,\\text{eV}$", "$2\\,\\text{eV}$", "$20\\,\\text{eV}$", "$620\\,\\text{eV}$"], answer: 1, explain: "$1240/620 = 2\\,\\text{eV}$." }
      ]
    }
  ],
  drills: [
    { id: "foundations-derivative-d1", lesson: "foundations-derivative", type: "mc", prompt: "For $x(t) = 4t^2 - 3t$, the velocity $dx/dt$ is:", options: ["$8t-3$", "$4t-3$", "$8t$", "$8t^2-3$"], answer: 0, hint: "Differentiate term by term using the power rule.", solution: "$\\frac{d}{dt}(4t^2) = 8t$, $\\frac{d}{dt}(-3t) = -3$. Sum: $8t-3$.", difficulty: 1, tags: ["derivative"] },
    { id: "foundations-derivative-d2", lesson: "foundations-derivative", type: "numeric", prompt: "For $x(t) = t^2 - 2t$ (m, s), find the instantaneous velocity at $t=3\\,\\text{s}$, in m/s.", answer: 4, tolerance: 0.03, unit: "m/s", hint: "$dx/dt = 2t - 2$.", solution: "$v(t) = 2t-2$; at $t=3$: $v=6-2=4\\,\\text{m/s}$.", difficulty: 1, tags: ["derivative"] },
    { id: "foundations-derivative-d3", lesson: "foundations-derivative", type: "mc", prompt: "Differentiate $x(t)=5t^3$.", options: ["$5t^2$", "$15t^2$", "$15t^3$", "$5t^3$"], answer: 1, hint: "Power rule: bring down the exponent, then reduce it by 1.", solution: "$\\frac{d}{dt}5t^3 = 5\\cdot3\\cdot t^2 = 15t^2$. Forgetting to multiply by the exponent 3 gives the wrong $5t^2$ distractor.", difficulty: 1, tags: ["derivative"] },
    { id: "foundations-integral-d1", lesson: "foundations-integral", type: "mc", prompt: "$\\int_0^2 3t^2\\,dt$ equals:", options: ["$6$", "$8$", "$12$", "$4$"], answer: 1, hint: "Antiderivative of $3t^2$ is $t^3$.", solution: "$[t^3]_0^2 = 8-0=8$.", difficulty: 1, tags: ["integral"] },
    { id: "foundations-integral-d2", lesson: "foundations-integral", type: "numeric", prompt: "Velocity is $v(t) = 6t$ (m/s). Find the distance traveled from $t=0$ to $t=4\\,\\text{s}$, in meters.", answer: 48, tolerance: 0.03, unit: "m", hint: "This is the area of a triangle under $v(t)$, or integrate directly.", solution: "$\\int_0^4 6t\\,dt = [3t^2]_0^4 = 48\\,\\text{m}$; matches triangle area $\\tfrac12(4)(24)=48$.", difficulty: 1, tags: ["integral"] },
    { id: "foundations-integral-d3", lesson: "foundations-integral", type: "mc", prompt: "A common error integrating $\\int t^2\\,dt$ is forgetting to divide by the new exponent. The correct antiderivative (plus C) is:", options: ["$t^3+C$", "$\\tfrac13t^3+C$", "$3t^3+C$", "$2t+C$"], answer: 1, hint: "$\\int t^n dt = t^{n+1}/(n+1)$.", solution: "$\\int t^2 dt = t^3/3 + C$. Forgetting the $1/3$ factor gives the common wrong answer $t^3+C$.", difficulty: 1, tags: ["integral"] },
    { id: "foundations-chain-product-d1", lesson: "foundations-chain-product", type: "mc", prompt: "If $f(t) = (2t+1)^3$, then $f'(t)$ is:", options: ["$3(2t+1)^2$", "$6(2t+1)^2$", "$(2t+1)^2$", "$6t(2t+1)^2$"], answer: 1, hint: "Chain rule: derivative of outer function times derivative of inner.", solution: "$f'(t) = 3(2t+1)^2 \\cdot 2 = 6(2t+1)^2$. Forgetting the inner derivative (factor of 2) is the common mistake giving $3(2t+1)^2$.", difficulty: 2, tags: ["chain-rule"] },
    { id: "foundations-chain-product-d2", lesson: "foundations-chain-product", type: "mc", prompt: "For $h(t) = t^2\\sin(t)$, $h'(t)$ is:", options: ["$2t\\cos(t)$", "$2t\\sin(t) + t^2\\cos(t)$", "$t^2\\cos(t)$", "$2t\\sin(t) - t^2\\cos(t)$"], answer: 1, hint: "Product rule: derivative of first times second, plus first times derivative of second.", solution: "$\\frac{d}{dt}(t^2)\\sin t + t^2\\frac{d}{dt}\\sin t = 2t\\sin t + t^2\\cos t$.", difficulty: 2, tags: ["product-rule"] },
    { id: "foundations-chain-product-d3", lesson: "foundations-chain-product", type: "numeric", prompt: "A rocket has $m(t) = 1000 - 5t$ (kg) and $v(t) = 2t$ (m/s). Using the product rule, find $dp/dt$ (the rate of change of momentum) at $t=10\\,\\text{s}$, in $\\text{kg}\\cdot\\text{m/s}^2$.", answer: 1800, tolerance: 0.03, unit: "kg m/s^2", hint: "$p=mv$; use the product rule.", solution: "$\\dot p = \\dot m v + m\\dot v = (-5)(20) + (950)(2) = -100+1900=1800\\,\\text{kg}\\cdot\\text{m/s}^2$ (note: for this open, mass-losing system, $dp/dt$ is not simply the net external force).", difficulty: 2, tags: ["product-rule"] },
    { id: "foundations-vectors-d1", lesson: "foundations-vectors", type: "numeric", prompt: "$\\vec A = (3,4,0)$, $\\vec B=(0,0,5)$. Find $\\vec A\\cdot\\vec B$.", answer: 0, tolerance: 0.03, hint: "Multiply matching components and sum.", solution: "$3(0)+4(0)+0(5)=0$ — the vectors are perpendicular (one lies entirely in the $xy$-plane, the other along $z$).", difficulty: 1, tags: ["dot-product"] },
    { id: "foundations-vectors-d2", lesson: "foundations-vectors", type: "numeric", prompt: "Force $\\vec F$ has magnitude $20\\,\\text{N}$ at $30°$ to displacement $\\vec d$ of magnitude $5\\,\\text{m}$. Find the work done $W=\\vec F\\cdot\\vec d$, in J.", answer: 86.6, tolerance: 0.03, unit: "J", hint: "$W=|F||d|\\cos\\theta$.", solution: "$W = 20(5)\\cos30° = 100(0.866) = 86.6\\,\\text{J}$.", difficulty: 1, tags: ["dot-product"] },
    { id: "foundations-vectors-d3", lesson: "foundations-vectors", type: "mc", prompt: "$\\vec A\\times\\vec B$ for $\\vec A=(1,0,0)$, $\\vec B=(0,1,0)$ is:", options: ["$(0,0,1)$", "$(1,1,0)$", "$(0,0,-1)$", "$(0,0,0)$"], answer: 0, hint: "Use the right-hand rule or the determinant formula.", solution: "$\\hat x\\times\\hat y=\\hat z=(0,0,1)$.", difficulty: 1, tags: ["cross-product"] },
    { id: "foundations-vectors-d4", lesson: "foundations-vectors", type: "numeric", prompt: "A wrench applies $40\\,\\text{N}$ perpendicular to a $0.25\\,\\text{m}$ handle. Find the torque magnitude, in $\\text{N}\\cdot\\text{m}$.", answer: 10, tolerance: 0.03, unit: "N m", hint: "$\\tau = rF\\sin\\theta$, $\\theta=90°$.", solution: "$\\tau = 0.25(40)(1) = 10\\,\\text{N}\\cdot\\text{m}$.", difficulty: 1, tags: ["cross-product", "torque"] },
    { id: "foundations-taylor-d1", lesson: "foundations-taylor", type: "mc", prompt: "For small $x$, $\\cos(x)$ is approximately:", options: ["$1-x$", "$1-x^2/2$", "$x-x^3/6$", "$1+x^2/2$"], answer: 1, hint: "Recall the Maclaurin series for cosine.", solution: "$\\cos x \\approx 1 - x^2/2$; note $\\cos$ is even, so no linear term.", difficulty: 1, tags: ["taylor-series"] },
    { id: "foundations-taylor-d2", lesson: "foundations-taylor", type: "numeric", prompt: "Estimate $\\sqrt{0.99}$ using a first-order Taylor expansion of $(1+x)^{1/2}$.", answer: 0.995, tolerance: 0.001, hint: "$(1+x)^n\\approx1+nx$ with $x=-0.01$, $n=1/2$.", solution: "$1+\\tfrac12(-0.01)=0.995$ (true value $0.99499$).", difficulty: 1, tags: ["taylor-series"] },
    { id: "foundations-taylor-d3", lesson: "foundations-taylor", type: "mc", prompt: "A pendulum problem keeps $\\sin\\theta\\approx\\theta$ but a student instead sets $\\sin\\theta\\approx 0$. What goes wrong physically?", options: ["Nothing, both are valid small-angle approximations", "The restoring force vanishes, predicting no oscillation at all", "The period becomes infinite but oscillation still occurs", "The amplitude is overestimated"], answer: 1, hint: "Think about what drives the pendulum back toward equilibrium.", solution: "Dropping the leading term entirely removes the restoring force from the equation of motion, which is qualitatively wrong — the object wouldn't oscillate.", difficulty: 2, tags: ["taylor-series"] },
    { id: "foundations-taylor-d4", lesson: "foundations-taylor", type: "numeric", prompt: "For small $\\epsilon$, evaluate $\\lim_{\\epsilon\\to0}\\frac{e^{2\\epsilon}-1}{\\epsilon}$.", answer: 2, tolerance: 0.03, hint: "Expand $e^{2\\epsilon}\\approx1+2\\epsilon$.", solution: "$e^{2\\epsilon}-1\\approx2\\epsilon$, so the ratio $\\to2$.", difficulty: 2, tags: ["taylor-series"] },
    { id: "foundations-complex-d1", lesson: "foundations-complex", type: "mc", prompt: "$e^{i\\pi/2}$ equals:", options: ["$1$", "$-1$", "$i$", "$-i$"], answer: 2, hint: "Use Euler's formula with $\\theta=\\pi/2$.", solution: "$\\cos(\\pi/2)+i\\sin(\\pi/2) = 0+i(1) = i$.", difficulty: 1, tags: ["complex-numbers"] },
    { id: "foundations-complex-d2", lesson: "foundations-complex", type: "numeric", prompt: "Find $|3+4i|$ (the magnitude of the complex number).", answer: 5, tolerance: 0.03, hint: "Magnitude is $\\sqrt{\\text{Re}^2+\\text{Im}^2}$.", solution: "$\\sqrt{3^2+4^2}=\\sqrt{25}=5$.", difficulty: 1, tags: ["complex-numbers"] },
    { id: "foundations-complex-d3", lesson: "foundations-complex", type: "mc", prompt: "Two phasors $2e^{i0}$ and $2e^{i\\pi}$ added together give:", options: ["$4$", "$0$", "$2i$", "$4i$"], answer: 1, hint: "$e^{i\\pi}=-1$.", solution: "$2(1) + 2(-1) = 0$ — the two signals are exactly out of phase and cancel.", difficulty: 2, tags: ["complex-numbers"] },
    { id: "foundations-odes-d1", lesson: "foundations-odes", type: "mc", prompt: "$\\dot N = -\\lambda N$ has solution:", options: ["$N=N_0\\cos(\\lambda t)$", "$N=N_0e^{-\\lambda t}$", "$N=N_0e^{\\lambda t}$", "$N=N_0-\\lambda t$"], answer: 1, hint: "Guess $N=Ce^{kt}$ and solve for $k$.", solution: "Substituting gives $k=-\\lambda$, so $N=N_0e^{-\\lambda t}$.", difficulty: 1, tags: ["odes"] },
    { id: "foundations-odes-d2", lesson: "foundations-odes", type: "numeric", prompt: "A radioactive sample has $\\lambda = 0.1\\,\\text{s}^{-1}$. Find the half-life, in seconds (use $\\ln2\\approx0.693$).", answer: 6.93, tolerance: 0.03, unit: "s", hint: "$t_{1/2}=\\ln2/\\lambda$.", solution: "$0.693/0.1 = 6.93\\,\\text{s}$.", difficulty: 1, tags: ["odes"] },
    { id: "foundations-odes-d3", lesson: "foundations-odes", type: "mc", prompt: "$\\ddot x = 4x$ (note the positive sign) has general solution involving:", options: ["Sines and cosines, oscillation", "Real exponentials, growth/decay, no oscillation", "A single linear function of $t$", "No real solution exists"], answer: 1, hint: "Guess $x=Ce^{kt}$; what sign does $k^2$ need?", solution: "$k^2=4\\Rightarrow k=\\pm2$, both real — solutions are $Ae^{2t}+Be^{-2t}$, not oscillatory.", difficulty: 2, tags: ["odes"] },
    { id: "foundations-odes-d4", lesson: "foundations-odes", type: "numeric", prompt: "A pendulum has $\\omega=\\sqrt{g/l}$ with $l=2.5\\,\\text{m}$, $g\\approx10\\,\\text{m/s}^2$. Find $\\omega$, in rad/s.", answer: 2, tolerance: 0.03, unit: "rad/s", hint: "$\\omega=\\sqrt{g/l}$.", solution: "$\\sqrt{10/2.5}=\\sqrt4=2\\,\\text{rad/s}$.", difficulty: 1, tags: ["odes"] },
    { id: "foundations-matrices-d1", lesson: "foundations-matrices", type: "mc", prompt: "For $M=\\begin{pmatrix}2&0\\\\0&5\\end{pmatrix}$, the eigenvalues are:", options: ["$2$ and $5$", "$0$ and $7$", "$10$ only", "$\\sqrt2$ and $\\sqrt5$"], answer: 0, hint: "For a diagonal matrix, eigenvalues are the diagonal entries.", solution: "Diagonal matrices have their diagonal entries as eigenvalues, with eigenvectors along the axes.", difficulty: 1, tags: ["eigenvalues"] },
    { id: "foundations-matrices-d2", lesson: "foundations-matrices", type: "mc", prompt: "In the two-mass coupled spring system, the eigenvector $(1,1)$ corresponds to:", options: ["Masses moving oppositely, high frequency", "Masses moving together, low frequency", "One mass stationary", "No physical motion"], answer: 1, hint: "The middle spring barely stretches if both masses move the same way.", solution: "Both masses moving identically means the middle spring's length doesn't change, giving a weaker effective restoring force and lower frequency.", difficulty: 2, tags: ["eigenvalues"] },
    { id: "foundations-matrices-d3", lesson: "foundations-matrices", type: "numeric", prompt: "For $M\\vec v = \\mu\\vec v$ with $\\mu=3k/m$ found in a coupled-spring system with $k=6\\,\\text{N/m}$, $m=2\\,\\text{kg}$, find the mode's angular frequency $\\omega=\\sqrt\\mu$, in rad/s.", answer: 3, tolerance: 0.03, unit: "rad/s", hint: "$\\mu = 3(6)/2 = 9$.", solution: "$\\mu=9\\,\\text{s}^{-2}$, so $\\omega=3\\,\\text{rad/s}$.", difficulty: 2, tags: ["eigenvalues"] },
    { id: "foundations-dimensional-analysis-d1", lesson: "foundations-dimensional-analysis", type: "mc", prompt: "Which combination of speed $v$ and radius $r$ has units of acceleration?", options: ["$v/r$", "$v^2/r$", "$vr$", "$v^2r$"], answer: 1, hint: "Units of acceleration: $\\text{m/s}^2$.", solution: "$[v^2/r] = (\\text{m/s})^2/\\text{m} = \\text{m/s}^2$ — this is centripetal acceleration.", difficulty: 1, tags: ["dimensional-analysis"] },
    { id: "foundations-dimensional-analysis-d2", lesson: "foundations-dimensional-analysis", type: "numeric", prompt: "Fermi-estimate the number of seconds in a year, to 1 significant figure times a power of ten (answer in seconds, e.g. enter 30000000 for $3\\times10^7$).", answer: 30000000, tolerance: 0.2, hint: "$\\approx 365\\times24\\times3600$.", solution: "$365\\times86400\\approx3.15\\times10^7\\,\\text{s}$, i.e. about $3\\times10^7\\,\\text{s}$ — a number worth memorizing directly.", difficulty: 1, tags: ["fermi-estimation"] },
    { id: "foundations-dimensional-analysis-d3", lesson: "foundations-dimensional-analysis", type: "mc", prompt: "An answer choice for orbital period $T$ includes a factor of mass $m$ of the orbiting (small) body. Dimensional analysis on $T(G, M, r)$ (central mass $M$, orbital radius $r$) shows:", options: ["$m$ must appear to the first power", "$m$ cannot appear at all — it's dimensionally impossible to include it and still match seconds", "$m$ must appear as $m^2$", "Dimensional analysis can't say anything about $m$"], answer: 1, hint: "Try to include $m$ in the combination and see if any exponent choice can cancel its kg units.", solution: "With only $G, M, r$ (no other mass-bearing quantity) available to cancel kg from $m$, no combination restores pure seconds — this matches the real physics, where orbital period is independent of the small body's mass (Kepler's third law).", difficulty: 2, tags: ["dimensional-analysis"] },
    { id: "foundations-si-units-d1", lesson: "foundations-si-units", type: "numeric", prompt: "Using $c=3.0\\times10^8\\,\\text{m/s}$, find how long light takes to cross a $6\\,\\text{m}$ room, in nanoseconds.", answer: 20, tolerance: 0.03, unit: "ns", hint: "$t=d/c$.", solution: "$t = 6/(3.0\\times10^8) = 2\\times10^{-8}\\,\\text{s} = 20\\,\\text{ns}$.", difficulty: 1, tags: ["constants"] },
    { id: "foundations-si-units-d2", lesson: "foundations-si-units", type: "mc", prompt: "The order of magnitude of the speed of light is:", options: ["$10^6\\,\\text{m/s}$", "$10^8\\,\\text{m/s}$", "$10^{10}\\,\\text{m/s}$", "$10^{12}\\,\\text{m/s}$"], answer: 1, hint: "$c=3.0\\times10^8\\,\\text{m/s}$.", solution: "$c\\approx3\\times10^8\\,\\text{m/s}$.", difficulty: 1, tags: ["constants"] },
    { id: "foundations-si-units-d3", lesson: "foundations-si-units", type: "numeric", prompt: "Convert $2\\,\\text{eV}$ to joules, expressing your answer as a multiple of $10^{-19}\\,\\text{J}$ (e.g. enter 3.2 for $3.2\\times10^{-19}\\,\\text{J}$).", answer: 3.2, tolerance: 0.03, hint: "$1\\,\\text{eV}=1.6\\times10^{-19}\\,\\text{J}$.", solution: "$2\\times1.6\\times10^{-19} = 3.2\\times10^{-19}\\,\\text{J}$.", difficulty: 1, tags: ["constants"] }
  ],
  test: [
    { id: "foundations-t1", prompt: "A quantity $x(t)$ is measured at $t=2.000\\,\\text{s}$ and $t=2.001\\,\\text{s}$; the values differ by $0.006\\,\\text{m}$. The ratio $(0.006\\,\\text{m})/(0.001\\,\\text{s}) = 6\\,\\text{m/s}$ best approximates:", options: ["The average velocity over the whole trip", "The instantaneous velocity at $t\\approx2.0\\,\\text{s}$", "The acceleration at $t=2.0\\,\\text{s}$", "The total distance traveled", "The position at $t=0$"], answer: 1, solution: "A very small $\\Delta t$ around a point approximates the derivative (instantaneous velocity) there, by the definition of the limit.", difficulty: 1, tags: ["derivative"], lesson: "foundations-derivative" },
    { id: "foundations-t2", prompt: "A force varies as $F(x) = kx$ for $0\\le x \\le d$ (a spring). Without integrating, the work done is best found by recognizing this as:", options: ["A rectangle of height $kd$ and width $d$", "A triangle of base $d$ and height $kd$, area $\\tfrac12kd^2$", "A circle of radius $d$", "Impossible to find without calculus", "Equal to $kd$ regardless of the shape"], answer: 1, solution: "$\\int_0^d kx\\,dx$ is exactly the area of a triangle with base $d$ and height $kd$: $\\tfrac12kd^2$. Recognizing geometric shapes under simple linear force laws saves time over symbolic integration.", difficulty: 1, tags: ["integral"], lesson: "foundations-integral" },
    { id: "foundations-t3", prompt: "If $y = \\sin(x^2)$, then $dy/dx$ is:", options: ["$\\cos(x^2)$", "$2x\\cos(x^2)$", "$2x\\sin(x^2)$", "$x^2\\cos(x^2)$", "$\\cos(2x)$"], answer: 1, solution: "Chain rule: derivative of $\\sin(u)$ is $\\cos(u)$ times $du/dx = 2x$, giving $2x\\cos(x^2)$.", difficulty: 1, tags: ["chain-rule"], lesson: "foundations-chain-product" },
    { id: "foundations-t4", prompt: "Vectors $\\vec A$ and $\\vec B$ have equal magnitude and $\\vec A\\cdot\\vec B = 0$. The angle between them, and what this implies about $|\\vec A\\times\\vec B|$, are:", options: ["$0°$; cross product is zero", "$90°$; cross product is maximal, equal to $|A||B|$", "$180°$; cross product is zero", "$45°$; cross product is $|A||B|/\\sqrt2$", "Cannot be determined"], answer: 1, solution: "Zero dot product means $\\cos\\theta=0$, so $\\theta=90°$; at $90°$, $\\sin\\theta=1$, so the cross product magnitude is maximal, $|A||B|$.", difficulty: 2, tags: ["vectors"], lesson: "foundations-vectors" },
    { id: "foundations-t5", prompt: "For small $\\theta$ (radians), the fractional error in approximating $\\sin\\theta$ by $\\theta$ is approximately:", options: ["$\\theta$", "$\\theta^2/6$", "$\\theta^3$", "Independent of $\\theta$", "$1/\\theta$"], answer: 1, solution: "$\\sin\\theta = \\theta - \\theta^3/6 + \\cdots$, so the absolute error is $\\approx\\theta^3/6$ and the fractional error (error/$\\theta$) is $\\approx\\theta^2/6$.", difficulty: 3, tags: ["taylor-series"], lesson: "foundations-taylor" },
    { id: "foundations-t6", prompt: "A quantity is written as $5e^{i\\pi/3}$. Its real part (the physically observed value at that phase) is:", options: ["$5$", "$2.5$", "$5\\sqrt3/2$", "$0$", "$-5$"], answer: 1, solution: "$\\text{Re}(5e^{i\\pi/3}) = 5\\cos(60°) = 5(0.5) = 2.5$.", difficulty: 2, tags: ["complex-numbers"], lesson: "foundations-complex" },
    { id: "foundations-t7", prompt: "An equation of motion is $\\ddot x + 4x = 0$. The angular frequency and period of oscillation are:", options: ["$\\omega=4$, $T=\\pi/2$", "$\\omega=2$, $T=\\pi$", "$\\omega=2$, $T=2\\pi$", "$\\omega=4$, $T=2\\pi$", "$\\omega=\\sqrt2$, $T=\\pi\\sqrt2$"], answer: 1, solution: "Matching $\\ddot x=-\\omega^2x$ gives $\\omega^2=4\\Rightarrow\\omega=2$; period $T=2\\pi/\\omega=\\pi$.", difficulty: 2, tags: ["odes"], lesson: "foundations-odes" },
    { id: "foundations-t8", prompt: "A symmetric matrix representing a coupled two-body system has eigenvalues $\\mu_1=2$ and $\\mu_2=8$ (units $\\text{s}^{-2}$). The ratio of the two normal-mode frequencies $\\omega_2/\\omega_1$ is:", options: ["$4$", "$2$", "$\\sqrt2$", "$8$", "$16$"], answer: 1, solution: "$\\omega=\\sqrt\\mu$, so $\\omega_2/\\omega_1 = \\sqrt{8/2}=\\sqrt4=2$.", difficulty: 2, tags: ["eigenvalues"], lesson: "foundations-matrices" },
    { id: "foundations-t9", prompt: "A quantity $Q$ has units of $\\text{kg}\\cdot\\text{m}^2/\\text{s}$ (angular momentum). Which combination reproduces these units, given mass $m$ (kg), speed $v$ (m/s), and length $r$ (m)?", options: ["$mvr$", "$mv/r$", "$mv^2r$", "$mv^2/r$", "$m v r^2$"], answer: 0, solution: "$[mvr] = \\text{kg}\\cdot(\\text{m/s})\\cdot\\text{m} = \\text{kg m}^2/\\text{s}$, matches. This is exactly the angular momentum of a point mass, $L=mvr$ for motion perpendicular to $r$.", difficulty: 1, tags: ["dimensional-analysis"], lesson: "foundations-dimensional-analysis" },
    { id: "foundations-t10", prompt: "Order-of-magnitude estimate: roughly how many molecules of air are in a typical classroom (volume $\\sim200\\,\\text{m}^3$), given $\\sim2.5\\times10^{25}\\,\\text{molecules/m}^3$ at room conditions?", options: ["$10^{22}$", "$10^{25}$", "$5\\times10^{27}$", "$10^{30}$", "$2.5\\times10^{23}$"], answer: 2, solution: "$200 \\times 2.5\\times10^{25} = 5\\times10^{27}$ molecules.", difficulty: 2, tags: ["fermi-estimation"], lesson: "foundations-dimensional-analysis" },
    { id: "foundations-t11", prompt: "Using $G=6.7\\times10^{-11}\\,\\text{N m}^2/\\text{kg}^2$, the gravitational force between two $70\\,\\text{kg}$ people standing $1\\,\\text{m}$ apart is closest to:", options: ["$10^{-3}\\,\\text{N}$", "$10^{-5}\\,\\text{N}$", "$10^{-7}\\,\\text{N}$", "$10^{-9}\\,\\text{N}$", "$10^{-11}\\,\\text{N}$"], answer: 2, solution: "$F = G m_1m_2/r^2 = 6.7\\times10^{-11}(70)(70)/1 \\approx 3.3\\times10^{-7}\\,\\text{N}$, order of magnitude $10^{-7}\\,\\text{N}$ — vanishingly small, which is why gravity between everyday objects is never noticed.", difficulty: 1, tags: ["constants", "fermi-estimation"], lesson: "foundations-si-units" },
    { id: "foundations-t12", prompt: "A pendulum of length $l$ and mass $m$ swings under gravity $g$. Using only dimensional analysis (the period $T$ must have units of seconds), which formula for $T$ survives?", options: ["$2\\pi\\sqrt{l/g}$", "$2\\pi\\sqrt{g/l}$", "$2\\pi\\sqrt{lm/g}$", "$2\\pi l/g$", "$2\\pi\\sqrt{l/g^2}$"], answer: 0, solution: "Check each formula's units. $2\\pi\\sqrt{l/g}$: $\\sqrt{\\text{m}/(\\text{m/s}^2)}=\\sqrt{\\text{s}^2}=\\text{s}$ — correct. $2\\pi\\sqrt{g/l}$: $\\text{s}^{-1}$ — wrong. $2\\pi\\sqrt{lm/g}$: carries a leftover $\\sqrt{\\text{kg}}$ — wrong. $2\\pi l/g$: $\\text{s}^2$ — wrong power. $2\\pi\\sqrt{l/g^2}$: $\\text{s}^2\\,\\text{m}^{-1/2}$ — wrong. Only $2\\pi\\sqrt{l/g}$ survives.", difficulty: 2, tags: ["dimensional-analysis"], lesson: "foundations-dimensional-analysis" },
    { id: "foundations-t13", prompt: "$\\int_1^3 \\frac{1}{x}\\,dx$ is closest to (using $\\ln3\\approx1.10$):", options: ["$0.37$", "$1.10$", "$2.0$", "$3.0$", "$0.5$"], answer: 1, solution: "$\\int\\frac1x dx = \\ln x$; $[\\ln x]_1^3 = \\ln3-\\ln1=\\ln3\\approx1.10$.", difficulty: 2, tags: ["integral"], lesson: "foundations-integral" }
  ]
});
