window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "qm",
  title: "Quantum Mechanics",
  order: 5,
  greWeight: 0.12,
  prereqs: ["mechanics", "em", "waves-optics"],
  blurb: "Rebuilds mechanics from the ground up once energy, and angular momentum, turn out to come in discrete packets.",

  lessons: [
    // ---------------------------------------------------------------
    {
      id: "qm-photoelectric",
      title: "The Failures That Forced Quanta",
      minutes: 14,
      discovery: "Light delivers energy in discrete packets, hf, not continuously — this alone explains three things the wave picture of light cannot.",
      sections: [
        { kind: "problem", md: `Shine light on a clean metal surface and electrons pop out (the photoelectric effect). Measure the maximum kinetic energy of the ejected electrons as you vary the light's intensity and frequency. Three results resist explanation: (1) below a sharp threshold frequency $f_0$, *no* electrons are ejected, no matter how intense the light; (2) above threshold, the maximum electron kinetic energy depends only on frequency, not on intensity at all; (3) emission is instantaneous — even extremely dim light above threshold ejects electrons with no measurable delay.` },
        { kind: "candidates", md: `**A. Light is a continuous electromagnetic wave** (the well-established, successful picture from Maxwell's equations, which correctly explains diffraction and interference). A wave delivers energy continuously, at a rate set by its intensity.

**B. Maybe the electron needs to slowly absorb wave energy over time until it accumulates enough to escape** — a patch to A that tries to account for the threshold.` },
        { kind: "failures", md: `**A fails on all three points.** A more intense wave delivers more power, so a wave picture predicts *more energetic* ejected electrons at higher intensity — not observed; energy is delivered continuously, so there should be no sharp frequency threshold, just a slower accumulation at low frequency — not observed; and for a dim wave spread over a macroscopic area, classical estimates for how long it would take a single atom's worth of area to accumulate enough energy to eject an electron predict delays of seconds to minutes — but emission is instantaneous.

**B fails too, on the same delay problem.** If electrons accumulate energy slowly from a continuous wave, dim light should show a measurable time lag before the first electrons appear, growing longer as intensity drops. No such delay is ever observed, at any intensity above threshold — ejection is immediate or not at all.` },
        { kind: "discovery", md: `The three anomalies all disappear at once under one assumption: light delivers its energy in discrete, indivisible packets of size $E=hf$ (Planck's constant $h=6.626\\times10^{-34}\\text{ J s}$), not as a continuous stream. A single electron absorbs *one* packet at a time. If $hf$ exceeds the metal's work function $\\phi$ (the minimum energy needed to escape), the electron is ejected immediately with the leftover energy as kinetic energy — instant, because absorption of one packet is instant, not a slow accumulation. If $hf<\\phi$, no single packet carries enough energy, and *no amount of low-energy packets adds up* for one electron (each electron absorbs at most one packet) — hence the sharp threshold, independent of intensity. More intense light means *more packets per second*, giving more ejected electrons, but each electron still only gets one packet's worth of energy — hence no dependence of maximum KE on intensity.` },
        { kind: "formal", md: `**Photon:** light of frequency $f$ is quantized into packets of energy $E=hf$. **Einstein's photoelectric equation:**
$$KE_{max} = hf - \\phi$$
where $\\phi$ is the metal's work function and $f_0=\\phi/h$ is the threshold frequency below which no ejection occurs regardless of intensity.` },
        { kind: "apply", md: `A metal with work function $\\phi=2.00\\text{ eV}$ is illuminated with light of frequency $f=1.00\\times10^{15}\\text{ Hz}$. Photon energy: $hf = (6.626\\times10^{-34})(1.00\\times10^{15}) = 6.63\\times10^{-19}\\text{ J} = 4.14\\text{ eV}$. Maximum ejected electron kinetic energy: $KE_{max} = 4.14 - 2.00 = 2.14\\text{ eV}$.` },
        { kind: "transfer", md: `The same "classical continuum prediction fails, quantization fixes it" pattern independently shows up in blackbody radiation (previous module), in Compton scattering (photons transferring momentum $p=h/\\lambda$ like particles when bouncing off electrons), and in the classical instability of the atom (an orbiting electron should radiate continuously and spiral into the nucleus in about $10^{-11}\\text{ s}$, yet atoms are stable) — quantization of light's energy here is the opening move; the next lesson asks whether matter shows the mirror-image behavior.` }
      ],
      checkpoints: [
        { q: "In the photoelectric effect, increasing the light's intensity (at fixed frequency above threshold) increases:", options: ["The maximum kinetic energy of ejected electrons", "The number of ejected electrons per second", "The threshold frequency", "The work function of the metal"], answer: 1, explain: "Each electron absorbs one photon of energy $hf$, so max KE is fixed by frequency alone; more intensity means more photons per second, hence more ejected electrons, not more energetic ones." },
        { q: "Below the threshold frequency, no photoelectrons are emitted no matter how intense the light, because:", options: ["Low-frequency photons are absorbed by the air", "Each electron can only absorb one photon, and a single photon below threshold never carries enough energy", "The metal reflects all low-frequency light", "Intensity has no physical meaning below threshold"], answer: 1, explain: "Since electrons don't accumulate energy from multiple photons, a photon energy below the work function can never eject an electron, regardless of how many such photons arrive." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-de-broglie",
      title: "De Broglie and Matter Waves",
      minutes: 12,
      discovery: "If light (a wave) behaves like particles, matter (particles) should behave like waves — and it does, with wavelength $\\lambda=h/p$.",
      sections: [
        { kind: "problem", md: `Light, long understood as a wave, turns out to also behave like a stream of particle-like quanta (photons, previous lesson). Fire a beam of electrons — long understood as particles, with definite mass and charge — at a crystal, and measure the angular distribution of scattered electrons. The result: a diffraction pattern, with sharp maxima and minima at angles that precisely satisfy the same Bragg condition used for X-ray diffraction off the same crystal. Why would a stream of particles diffract?` },
        { kind: "candidates", md: `**A. Electrons are ordinary point particles; the pattern is some artifact of the crystal's structure or surface defects, not true wave diffraction.**

**B. Electrons are actually waves, full stop — no particle nature at all.**` },
        { kind: "failures", md: `**A fails quantitatively.** The diffraction angles shift in exact, precise agreement with Bragg's law $n\\lambda=2d\\sin\\theta$ as the electron's kinetic energy (hence speed) is varied — the pattern tracks a wavelength that changes with electron momentum in exactly the way a wave theory predicts, far too precise and reproducible across many electron energies and crystal spacings to be a random defect artifact.

**B fails against the detector.** However spread the diffraction pattern looks in aggregate, each individual electron is still detected as one discrete, localized click at one point on the screen — never as a smeared-out continuous deposit of "electron stuff." Electrons also carry definite, quantized charge and mass measurable in bulk. A pure wave with no particle character can't explain this discreteness of detection.` },
        { kind: "discovery", md: `Both particle and wave character survive, together: matter has an associated wavelength, and it interferes/diffracts *like a wave* in how its arrival probability is distributed in space, while still being detected *like a particle* — as a discrete, localized event. The relation between the associated wavelength and the particle's momentum is the same one already found for photons ($p=h/\\lambda$), now applied universally to any particle with mass.` },
        { kind: "formal", md: `**De Broglie relation:**
$$\\lambda = \\frac{h}{p}$$
For a nonrelativistic particle of mass $m$ and speed $v$, $p=mv$, so $\\lambda = h/(mv)$.` },
        { kind: "apply", md: `Electron ($m=9.11\\times10^{-31}\\text{ kg}$) accelerated from rest through a $100\\text{ V}$ potential difference: $KE=eV=(1.6\\times10^{-19})(100)=1.6\\times10^{-17}\\text{ J}$, so $p=\\sqrt{2mKE}=\\sqrt{2(9.11\\times10^{-31})(1.6\\times10^{-17})}\\approx5.40\\times10^{-24}\\text{ kg m/s}$, giving
$$\\lambda = \\frac{6.626\\times10^{-34}}{5.40\\times10^{-24}} \\approx 1.23\\times10^{-10}\\text{ m} = 0.123\\text{ nm}$$
— comparable to atomic spacings, which is exactly why electrons diffract off crystals. A thrown baseball ($m\\sim0.15\\text{ kg}$, $v\\sim20\\text{ m/s}$) has $\\lambda\\sim10^{-34}\\text{ m}$ — unmeasurably, absurdly small, which is why macroscopic objects never show observable wave behavior.` },
        { kind: "transfer", md: `Wave-particle duality is universal, not a special property of light: any object with momentum has an associated wavelength, though it's only physically relevant when $\\lambda$ is comparable to the length scales of the system (crystal spacing for electrons, never for baseballs). This sets up the next question directly: if matter has a wavelength, what wave equation does it obey, and what is actually "waving"?` }
      ],
      checkpoints: [
        { q: "The Davisson–Germer electron diffraction experiment provides direct evidence that:", options: ["Electrons have negative charge", "Electrons behave as waves with a momentum-dependent wavelength", "Crystals are always defective", "X-rays are made of electrons"], answer: 1, explain: "The diffraction angles match Bragg's law with $\\lambda=h/p$, showing wave-like interference governed by the electron's momentum." },
        { q: "Why is quantum wave behavior never observed for everyday macroscopic objects like baseballs?", options: ["Macroscopic objects have no momentum", "Their de Broglie wavelength is astronomically smaller than any relevant length scale", "Planck's constant is zero for large objects", "Wave-particle duality only applies to charged particles"], answer: 1, explain: "$\\lambda=h/p$ becomes vanishingly small for objects with everyday mass and speed, far below any scale where diffraction could be observed." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-wavefunction",
      title: "The Wavefunction and the Born Rule",
      minutes: 13,
      discovery: "The wavefunction is a complex probability amplitude — complex so it can interfere, squared so probabilities stay non-negative.",
      sections: [
        { kind: "problem", md: `Fire electrons one at a time — slowly enough that only one is ever in flight — through a double slit, and record where each one lands on a screen. Individually, each electron makes one sharp, localized dot; there's no sign of "spreading out" for any single electron. But after accumulating thousands of individual dots, the pattern that builds up is a wave interference pattern, with dark fringes where *no* electrons ever land, even though either slit alone (blocking the other) would deposit electrons there. What quantity "waves," if each individual detection event is a single, localized particle?` },
        { kind: "candidates", md: `**A. The wavefunction $\\psi$ directly is the probability of finding the particle at each point.**

**B. $\\psi$ is a real-valued physical displacement, like a sound wave's pressure or a water wave's height.**` },
        { kind: "failures", md: `**A fails at the dark fringes.** Probabilities are non-negative real numbers; adding two non-negative numbers (the probability from slit 1, the probability from slit 2) can never produce zero unless each is already zero. But the dark fringes are located exactly where each slit *individually* (tested by blocking the other) would deposit electrons with nonzero probability — genuine cancellation is required, and plain non-negative probabilities cannot cancel.

**B fails for two reasons.** A real physical displacement, spread out over space, offers no natural account of why a measurement always collapses it to one discrete localized detection rather than registering some fraction of "electron" everywhere the wave has amplitude. It also can't carry the *phase* information needed to produce the correct interference pattern (constructive here, destructive there) purely from an amplitude that is either positive or negative — the equation that will turn out to govern this wave (next lesson) forces $\\psi$ to be complex, which a real-valued displacement wave cannot be.` },
        { kind: "discovery", md: `Let $\\psi$ be complex-valued. Complex numbers can be added with their phases (real and imaginary parts each add), producing genuine cancellation — two nonzero complex amplitudes can sum to exactly zero at a point where their phases are opposite, exactly what's needed for a dark fringe. But complex numbers themselves aren't directly observable as a "probability" (which must be a non-negative real number summing to 1). The reconciliation: the physically measurable probability is the *squared magnitude* $|\\psi|^2$, computed only *after* summing amplitudes from all indistinguishable paths (both slits). This gives interference in $|\\psi_1+\\psi_2|^2$ (which includes a cross term that can be positive or negative) while every individual measurement still yields one discrete, localized outcome, drawn probabilistically according to $|\\psi|^2$.` },
        { kind: "formal", md: `**Born rule:** the probability of finding a particle in $[x,x+dx]$ is $P(x)\\,dx = |\\psi(x)|^2\\,dx$, with normalization $\\int_{-\\infty}^{\\infty}|\\psi(x)|^2\\,dx=1$. $\\psi$ itself is a complex probability *amplitude*; only $|\\psi|^2$ is directly a probability density.` },
        { kind: "apply", md: `Two-slit amplitude: $\\psi = \\psi_1+\\psi_2$, so
$$P = |\\psi_1+\\psi_2|^2 = |\\psi_1|^2+|\\psi_2|^2+2\\,\\text{Re}(\\psi_1^*\\psi_2)$$
The cross term $2\\,\\text{Re}(\\psi_1^*\\psi_2)$ is the interference term — absent if you (incorrectly) added the individual *probabilities* $|\\psi_1|^2+|\\psi_2|^2$ instead of the amplitudes, which is exactly what happens experimentally if you make a measurement that reveals which slit each electron went through: the interference pattern vanishes.` },
        { kind: "transfer", md: `"Sum the amplitudes for all indistinguishable ways an outcome can occur, then square to get the probability" is the general rule underlying every QM interference phenomenon, not just double-slit — it reappears in quantum computing (interfering computational-basis amplitudes) and in the path-integral formulation of quantum mechanics.` }
      ],
      checkpoints: [
        { q: "Dark fringes in electron double-slit interference occur because:", options: ["Electrons are destroyed at those points", "The probability amplitudes from the two slits are complex and cancel there", "Probabilities from the two slits simply add to less than 1", "No electrons are emitted toward those angles"], answer: 1, explain: "Genuine cancellation requires complex amplitudes with opposite phase, which is impossible for non-negative probabilities alone." },
        { q: "The physically measurable probability density associated with a wavefunction $\\psi$ is:", options: ["$\\psi$", "$\\text{Re}(\\psi)$", "$|\\psi|^2$", "$d\\psi/dx$"], answer: 2, explain: "Born rule: $P(x) = |\\psi(x)|^2$, always non-negative and normalizable to 1." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-schrodinger",
      title: "The Schrödinger Equation",
      minutes: 14,
      discovery: "Matching a wave equation to the nonrelativistic energy relation $E=p^2/2m$ forces the equation to be complex and first-order in time.",
      sections: [
        { kind: "problem", md: `The wavefunction needs an equation of motion — something that determines how $\\psi(x,t)$ evolves, the way $F=ma$ determines how a classical trajectory evolves. Whatever equation governs $\\psi$ needs to reproduce the de Broglie relation $\\lambda=h/p$ for a free particle's plane-wave-like behavior, and needs to correctly encode the nonrelativistic kinetic-energy relation $E=p^2/2m$ for a massive particle (unlike light, where $E=pc$).` },
        { kind: "candidates", md: `**A. Borrow the classical wave equation** used for sound and light: $\\dfrac{\\partial^2\\psi}{\\partial x^2} = \\dfrac{1}{v^2}\\dfrac{\\partial^2\\psi}{\\partial t^2}$.

**B. Build the equation directly by correspondence: use the plane-wave relations $\\partial/\\partial t \\leftrightarrow -i\\omega = -iE/\\hbar$ and $\\partial/\\partial x \\leftrightarrow ik = ip/\\hbar$ to translate the energy relation $E=p^2/2m+V$ into an operator equation acting on $\\psi$.**` },
        { kind: "failures", md: `**A fails a direct test.** Plug a plane wave $\\psi=e^{i(kx-\\omega t)}$ into the classical wave equation: it requires $\\omega^2=v^2k^2$, i.e. $\\omega\\propto k$ (a *linear* dispersion relation, $E\\propto p$) — correct for light, but wrong for a massive nonrelativistic particle, which needs $E\\propto p^2$ (kinetic energy $p^2/2m$). The classical wave equation, second-order in time and built for waves with $E\\propto p$, simply cannot reproduce the right energy-momentum relation for matter.

**B needs checking, not rejecting.** Translating $E=p^2/2m+V$ using $E\\to i\\hbar\\partial/\\partial t$ and $p\\to-i\\hbar\\partial/\\partial x$ gives an equation with an explicit factor of $i$ — meaning $\\psi$ *must* be complex for the equation to make sense (consistent with the previous lesson's discovery, not a separate assumption) and the equation is first-order, not second-order, in time.` },
        { kind: "discovery", md: `Candidate B, worked through, produces an equation that (a) is inherently complex, matching the Born-rule requirement that $\\psi$ carry phase information, and (b) reproduces $E=p^2/2m$ exactly for a free-particle plane wave (checked directly below) — succeeding at both places A failed.` },
        { kind: "formal", md: `**Time-dependent Schrödinger equation:**
$$i\\hbar\\frac{\\partial\\psi}{\\partial t} = -\\frac{\\hbar^2}{2m}\\frac{\\partial^2\\psi}{\\partial x^2} + V(x)\\psi$$
For a potential $V$ that doesn't depend on time, separable solutions $\\psi(x,t)=\\phi(x)e^{-iEt/\\hbar}$ exist, where $\\phi(x)$ solves the **time-independent Schrödinger equation**:
$$-\\frac{\\hbar^2}{2m}\\frac{d^2\\phi}{dx^2} + V(x)\\phi = E\\phi$$
This is an eigenvalue equation: only certain values of $E$ (paired with well-behaved $\\phi$) are typically allowed once boundary conditions are imposed — the source of energy quantization explored in the next lessons.` },
        { kind: "apply", md: `Free particle ($V=0$): try $\\phi(x)=e^{ikx}$. Then $-\\dfrac{\\hbar^2}{2m}(ik)^2 e^{ikx} = \\dfrac{\\hbar^2k^2}{2m}e^{ikx} = E\\,e^{ikx}$, giving $E=\\hbar^2k^2/2m = p^2/2m$ (using $p=\\hbar k$) — exactly the correct nonrelativistic energy-momentum relation, confirming the equation was built correctly.` },
        { kind: "transfer", md: `The correspondence trick used here — replace $E$ and $p$ with operators acting on $\\psi$ — is the master template for building every other quantum-mechanical operator (angular momentum, etc.) and for quantizing any classical system: write the classical energy expression, then substitute operators for $E$ and $p$.` }
      ],
      checkpoints: [
        { q: "The Schrödinger equation must be complex (not real-valued) because:", options: ["Complex numbers are easier to compute with", "The correspondence $E\\to i\\hbar\\partial/\\partial t$ introduces an explicit factor of $i$, and $\\psi$ must carry phase for interference", "Energy is always a complex quantity", "It was an arbitrary historical choice with no physical necessity"], answer: 1, explain: "The equation's structure forces complex $\\psi$, consistent with the Born-rule requirement that $\\psi$ support interference via phase, not just amplitude." },
        { q: "For a free particle plane-wave solution of the Schrödinger equation, the energy $E$ satisfies:", options: ["$E=pc$", "$E=\\hbar\\omega$ with $\\omega\\propto k$ linearly, like light", "$E=\\hbar^2k^2/2m = p^2/2m$", "$E$ is undefined for a free particle"], answer: 2, explain: "Substituting a plane wave into the time-independent Schrödinger equation with $V=0$ reproduces the correct nonrelativistic kinetic energy relation." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-infinite-well",
      title: "The Infinite Square Well",
      minutes: 13,
      discovery: "Boundary conditions on the wavefunction force energy to come in a discrete ladder — and forbid a state of exactly zero energy.",
      sections: [
        { kind: "problem", md: `Trap a particle in a 1D box of width $L$ with perfectly rigid, impenetrable walls at $x=0$ and $x=L$ (the wavefunction must vanish there, since the particle can never be found outside). Classically, the particle could have any energy, including zero (sitting perfectly still anywhere in the box). What does the time-independent Schrödinger equation, with $V=0$ inside and boundary conditions $\\phi(0)=\\phi(L)=0$, actually allow?` },
        { kind: "candidates", md: `**A. Any energy is allowed, just as classically — a continuum of solutions with different wavelengths, all fitting inside the box somehow.**

**B. Only the lowest-energy solution exists — a single ground state, nothing above it.**` },
        { kind: "failures", md: `**A fails the boundary conditions directly.** The general solution to $-\\dfrac{\\hbar^2}{2m}\\phi''=E\\phi$ inside the well is $\\phi(x)=A\\sin(kx)+B\\cos(kx)$ with $k=\\sqrt{2mE}/\\hbar$. The condition $\\phi(0)=0$ forces $B=0$. The condition $\\phi(L)=0$ then forces $\\sin(kL)=0$, which holds *only* for $kL=n\\pi$ with $n$ a positive integer — not for arbitrary $k$. Most values of $E$ simply have no solution satisfying both boundary conditions at once.

**B fails because it stops too early.** $\\sin(kL)=0$ at $kL=\\pi$ is just one solution among infinitely many: $kL=\\pi,2\\pi,3\\pi,\\dots$ all work. There's a full discrete ladder, not a single state.` },
        { kind: "discovery", md: `The boundary conditions force $k_n=n\\pi/L$ for $n=1,2,3,\\dots$ — a discrete, evenly-spaced-in-$n$ (though not evenly-spaced-in-energy) ladder of allowed states, each with $E_n\\propto n^2$. Critically, $n=0$ is *not* allowed: $n=0$ would give $\\phi(x)\\equiv0$ everywhere, meaning no particle at all, which isn't a physical state. The lowest allowed energy, $E_1$, is strictly positive — a direct, inescapable consequence of confining a wave to a finite region and requiring it to vanish at both ends. Classically-forbidden "sitting still with zero energy" is quantum-mechanically impossible.` },
        { kind: "formal", md: `**Infinite square well energies and states:**
$$E_n = \\frac{n^2\\pi^2\\hbar^2}{2mL^2} = \\frac{n^2h^2}{8mL^2}, \\qquad \\phi_n(x) = \\sqrt{\\frac{2}{L}}\\sin\\!\\left(\\frac{n\\pi x}{L}\\right), \\qquad n=1,2,3,\\dots$$
$E_1$ is called the **zero-point energy** — the minimum possible energy of a confined quantum particle, always strictly greater than zero.` },
        { kind: "apply", md: `Electron confined to a $L=1.00\\text{ nm}$ box:
$$E_1 = \\frac{(6.626\\times10^{-34})^2}{8(9.11\\times10^{-31})(1.00\\times10^{-9})^2} \\approx 6.02\\times10^{-20}\\text{ J} \\approx 0.376\\text{ eV}$$
$E_2 = 4E_1 \\approx 1.50\\text{ eV}$, $E_3=9E_1\\approx3.39\\text{ eV}$ — energies scale as $n^2$, so spacing between successive levels *grows* with $n$.` },
        { kind: "transfer", md: `"Confinement plus wave nature forces discrete energies, and forbids zero energy" is the prototype pattern for every bound-state problem in quantum mechanics — the finite well, the harmonic oscillator, and the hydrogen atom (upcoming lessons) all reproduce some version of this same boundary-condition-driven quantization and zero-point energy.` }
      ],
      checkpoints: [
        { q: "In the infinite square well, the allowed energies are quantized because:", options: ["The Schrödinger equation is inherently discrete", "Only wavenumbers $k_n=n\\pi/L$ satisfy the boundary conditions $\\phi(0)=\\phi(L)=0$", "Energy is always quantized in classical mechanics too", "The particle's mass is quantized"], answer: 1, explain: "The general solution $A\\sin kx$ must vanish at both walls, which restricts $k$ to a discrete set $n\\pi/L$." },
        { q: "The lowest possible energy of a particle in an infinite square well is:", options: ["Exactly zero", "Strictly positive (the zero-point energy)", "Negative", "Undefined without knowing the particle's speed"], answer: 1, explain: "$n=0$ would require $\\phi\\equiv0$ (no particle), so the true ground state is $n=1$, with $E_1>0$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-tunneling",
      title: "Finite Wells, Barriers, and Tunneling",
      minutes: 13,
      discovery: "In a classically forbidden region the wavefunction decays but doesn't vanish, giving a real, nonzero probability of finding the particle where classical mechanics says it's absolutely impossible.",
      sections: [
        { kind: "problem", md: `A particle with total energy $E$ approaches a barrier of height $V_0>E$ and finite width $L$. Classically, this is a dead end: kinetic energy $E-V_0$ would have to be negative inside the barrier, which is impossible, so the particle simply bounces back with 100% certainty every time. Yet alpha decay is routinely observed: alpha particles escape nuclei even though their measured kinetic energies are well *below* the height of the electrostatic-plus-nuclear potential barrier confining them, by the classical accounting. How does anything ever get through?` },
        { kind: "candidates", md: `**A. Since $E<V_0$ makes kinetic energy negative (impossible) inside the barrier, $\\phi$ must be exactly zero there — just like outside the walls of the infinite well.**

**B. The particle "borrows" enough energy to briefly exceed $V_0$ while crossing, then returns it — a literal, if temporary, violation of energy conservation.**` },
        { kind: "failures", md: `**A fails the actual equation.** Inside the barrier, the time-independent Schrödinger equation becomes $-\\dfrac{\\hbar^2}{2m}\\phi'' = (E-V_0)\\phi$ with $E-V_0<0$, i.e. $\\phi'' = +\\kappa^2\\phi$ with $\\kappa=\\sqrt{2m(V_0-E)}/\\hbar$ real. The general solution is $\\phi = Ce^{-\\kappa x}+De^{\\kappa x}$ — real *exponentials*, not zero. Forcing $\\phi\\equiv0$ inside the barrier is inconsistent with requiring $\\phi$ and $\\phi'$ to be continuous at the boundary unless the entire wavefunction (including outside the barrier) is also forced to zero — an unphysical, over-constrained requirement not actually demanded by the boundary matching.

**B fails because nothing in the calculation requires it.** $E$ is a fixed constant throughout — it's the eigenvalue of a stationary state, not something that fluctuates in time during a single measurement. The exponentially decaying solution inside the barrier isn't an oscillating wave with some effective energy above $V_0$; it's a non-oscillating decay with the *same* fixed $E$ used everywhere. No energy non-conservation is needed or invoked.` },
        { kind: "discovery", md: `The correct solution — a decaying-but-nonzero exponential inside the barrier — means $|\\phi|^2$ is small but not zero throughout the classically forbidden region. If the barrier has finite width $L$, the decaying wavefunction reaches the far side with some small but nonzero amplitude, which then matches onto an oscillating (propagating) wave beyond the barrier. There is a real, calculable, nonzero probability that a particle incident on the barrier is transmitted through it — **tunneling** — with no energy violation anywhere.` },
        { kind: "formal", md: `For a rectangular barrier of height $V_0$ and width $L$ with $E<V_0$, the transmission probability (for $\\kappa L\\gg1$) is approximately
$$T \\sim e^{-2\\kappa L}, \\qquad \\kappa = \\frac{\\sqrt{2m(V_0-E)}}{\\hbar}$$
— exponentially sensitive to both the barrier width $L$ and the "depth" $V_0-E$ below the top of the barrier. A finite (as opposed to infinite) well similarly has bound-state wavefunctions that don't abruptly vanish at the well's edges but instead decay exponentially into the classically forbidden region outside.` },
        { kind: "apply", md: `Tunneling explains alpha decay (the alpha particle tunnels through the nuclear Coulomb barrier, with decay rate set by the exponential sensitivity of $T$ to barrier width and height — explaining why half-lives for different isotopes span more than 20 orders of magnitude for only modest changes in barrier parameters) and the scanning tunneling microscope (tunneling current between tip and surface falls off exponentially with the gap $L$, giving sub-angstrom height sensitivity).` },
        { kind: "transfer", md: `Any classically forbidden region of *finite* extent is quantum-mechanically "leaky" — the infinite well's rigid, absolute exclusion was a special (infinite-barrier) limiting case, not the generic behavior. This exponential leakage through finite barriers reappears throughout solid-state physics (tunnel diodes, tunnel junctions) and nuclear physics (fission, fusion in stars at energies below the classical Coulomb barrier).` }
      ],
      checkpoints: [
        { q: "Inside a classically forbidden barrier region ($E<V_0$), the wavefunction:", options: ["Is exactly zero", "Oscillates with a real wavenumber", "Decays exponentially but remains nonzero", "Becomes purely imaginary and unphysical"], answer: 2, explain: "The Schrödinger equation gives real exponential solutions ($\\phi''=+\\kappa^2\\phi$) in this region, decaying but not vanishing." },
        { q: "The tunneling transmission probability through a barrier depends most sensitively on:", options: ["The particle's charge", "The barrier width $L$, appearing in an exponent", "The particle's spin", "The color of the barrier material"], answer: 1, explain: "$T\\sim e^{-2\\kappa L}$: transmission falls off exponentially with barrier width, making tunneling extraordinarily sensitive to $L$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-harmonic-oscillator",
      title: "The Quantum Harmonic Oscillator",
      minutes: 14,
      discovery: "The harmonic oscillator's energy ladder is evenly spaced, $E_n=\\hbar\\omega(n+\\tfrac12)$ — including a zero-point energy that persists even in the ground state.",
      sections: [
        { kind: "problem", md: `Any smooth potential, Taylor-expanded around a minimum, looks like $V(x)\\approx V_0+\\tfrac12 kx^2$ near that minimum — a bond vibrating, an atom in a crystal lattice, almost any confined system close to equilibrium. What energies does the time-independent Schrödinger equation allow for this potential, $V(x)=\\tfrac12 m\\omega^2x^2$?` },
        { kind: "candidates", md: `**A. Solve it the same way as the infinite well and expect the same $n^2$ energy scaling, since both are "particle confined by boundary conditions."**

**B. Guess, following early (pre-Schrödinger) quantum theory, that energies are simply integer multiples of a basic quantum: $E_n=n\\hbar\\omega$.**` },
        { kind: "failures", md: `**A fails structurally.** The harmonic potential has no hard walls — $\\phi$ must instead decay smoothly to zero as $x\\to\\pm\\infty$ through a smoothly varying, not abruptly truncated, potential. Matching an oscillatory solution near $x=0$ onto exponentially decaying tails far away is a fundamentally different boundary-value problem from matching to hard walls; there's no reason to expect the same $n^2$ scaling, and solving it directly (via a series solution multiplying a Gaussian by Hermite polynomials) confirms the spacing is linear in $n$, not quadratic.

**B is close, but a direct check catches the gap.** The full solution (via a series expansion, or equivalently via raising/lowering operators) gives energies $E_n=\\hbar\\omega(n+\\tfrac12)$ for $n=0,1,2,\\dots$ — the guess $E_n=n\\hbar\\omega$ is missing the $+\\tfrac12$ entirely, and (relatedly) the ground state is $n=0$ with energy $\\tfrac12\\hbar\\omega$, not zero as the naive guess $E_0=0$ would suggest.` },
        { kind: "discovery", md: `A cleaner route than a brute-force series solution: define raising and lowering (ladder) operators $\\hat a = \\sqrt{\\tfrac{m\\omega}{2\\hbar}}\\left(\\hat x + \\tfrac{i\\hat p}{m\\omega}\\right)$ and $\\hat a^\\dagger$ (its complex conjugate-transpose), satisfying $[\\hat a,\\hat a^\\dagger]=1$. The Hamiltonian rewrites exactly as $\\hat H=\\hbar\\omega(\\hat a^\\dagger\\hat a+\\tfrac12)$, whose eigenvalues follow algebraically: $\\hat a^\\dagger\\hat a$ has non-negative-integer eigenvalues $n=0,1,2,\\dots$ (it cannot go below the $n=0$ state, since $\\hat a$ annihilates it), giving the exact energy ladder $E_n=\\hbar\\omega(n+\\tfrac12)$ — equally spaced by $\\hbar\\omega$, with an irreducible $\\tfrac12\\hbar\\omega$ zero-point energy that survives even in the $n=0$ ground state.` },
        { kind: "formal", md: `**Quantum harmonic oscillator energies:**
$$E_n = \\hbar\\omega\\left(n+\\frac12\\right), \\qquad n=0,1,2,\\dots$$
Equally spaced levels (spacing $\\hbar\\omega$, independent of $n$) — a distinctive fingerprint distinguishing this system from the infinite well's $n^2$-spaced levels. The ground state wavefunction is a Gaussian, $\\phi_0(x)\\propto e^{-m\\omega x^2/2\\hbar}$.` },
        { kind: "apply", md: `A vibrating diatomic molecule with $\\omega=4.0\\times10^{14}\\text{ rad/s}$: zero-point energy
$$E_0 = \\frac12\\hbar\\omega = \\frac12(1.055\\times10^{-34})(4.0\\times10^{14}) \\approx 2.11\\times10^{-20}\\text{ J} \\approx 0.132\\text{ eV}$$
This energy is present even at absolute zero temperature — the bond never truly stops vibrating, a direct, measurable consequence of the zero-point energy first seen (in a different form) for the infinite well.` },
        { kind: "transfer", md: `The evenly-spaced ladder $E_n=\\hbar\\omega(n+\\tfrac12)$, built from raising/lowering operators, is reused wholesale in quantum field theory, where each electromagnetic field mode behaves exactly like an independent harmonic oscillator, and "$n$" becomes the number of photons in that mode — quantized light itself, in a sense, is a harmonic oscillator ladder.` }
      ],
      checkpoints: [
        { q: "The energy levels of a quantum harmonic oscillator are:", options: ["Unevenly spaced, growing as $n^2$", "Evenly spaced by $\\hbar\\omega$, including a nonzero ground-state energy", "All degenerate at one energy", "Continuous, not discrete"], answer: 1, explain: "$E_n=\\hbar\\omega(n+\\tfrac12)$: consecutive levels differ by exactly $\\hbar\\omega$, and even $n=0$ has energy $\\tfrac12\\hbar\\omega>0$." },
        { q: "The harmonic oscillator's zero-point energy $\\tfrac12\\hbar\\omega$ means:", options: ["The oscillator is always in an excited state", "Even in its lowest-energy state, the system retains nonzero energy and never truly comes to rest", "The energy is a mathematical artifact with no physical consequence", "Zero-point energy only applies to charged particles"], answer: 1, explain: "It's a real, measurable minimum energy — analogous to (and for the same underlying reason as) the infinite well's inability to reach exactly $E=0$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-uncertainty",
      title: "Operators, Eigenvalues, and the Uncertainty Principle",
      minutes: 14,
      discovery: "Position and momentum operators don't commute — and that single algebraic fact is the entire origin of the uncertainty principle.",
      sections: [
        { kind: "problem", md: `A wavefunction $\\psi(x)$ is generally spread out over a range of $x$ — it doesn't have one definite position. How do we extract "the momentum" of a particle described by such a spread-out $\\psi$? And separately: is it possible, even in principle with a perfect instrument, to know both the position and momentum of a particle simultaneously to unlimited precision, the way classical mechanics always assumes?` },
        { kind: "candidates", md: `**A. Compute momentum the classical way, $p=mv$, by tracking how the "shape" of $\\psi$ moves through space over time, treating it like a fluid with one well-defined local velocity everywhere.**

**B. Assume, as classical mechanics does, that position and momentum are both simultaneously exactly knowable in principle — any apparent uncertainty is just a limitation of present-day measurement technology, fixable with cleverer instruments.**` },
        { kind: "failures", md: `**A fails because $\\psi$ generally has no single "local velocity."** A wavefunction can be built from a superposition of many different momentum components all occupying the same region of space at once; there's no classical trajectory or single flow velocity to point to. "Momentum" instead has to be extracted as an operator acting on $\\psi$, following the correspondence rule from the Schrödinger-equation lesson: $\\hat p = -i\\hbar\\,\\partial/\\partial x$.

**B fails on a purely algebraic ground, not a measurement-technology one.** Compute the commutator of the position and momentum operators: $[\\hat x,\\hat p]\\psi = \\hat x(-i\\hbar\\psi') - (-i\\hbar)(x\\psi)' = i\\hbar\\psi \\ne 0$. Because $\\hat x$ and $\\hat p$ do not commute, they cannot in general share a common set of eigenstates — there is no state in which both position and momentum are simultaneously exact eigenvalues. This isn't a statement about instrument precision; it's built into the operator structure of the theory itself.` },
        { kind: "discovery", md: `Physical observables correspond to Hermitian operators; measuring an observable can only yield one of that operator's eigenvalues (if $\\hat A\\psi=a\\psi$, a measurement of $A$ on state $\\psi$ certainly returns $a$; more generally the expansion of $\\psi$ in eigenstates of $\\hat A$ gives the probability of each possible outcome, generalizing the Born rule). Since $[\\hat x,\\hat p]=i\\hbar\\ne0$, no state has both position and momentum exactly defined — and this fundamental spread is quantifiable directly from the commutator's size.` },
        { kind: "formal", md: `**General uncertainty relation:** for any two Hermitian operators, $\\Delta A\\,\\Delta B \\ge \\tfrac12|\\langle[\\hat A,\\hat B]\\rangle|$. Applied to position and momentum, $[\\hat x,\\hat p]=i\\hbar$, giving the **Heisenberg uncertainty principle**:
$$\\Delta x\\,\\Delta p \\ge \\frac{\\hbar}{2}$$` },
        { kind: "apply", md: `An electron confined to $\\Delta x = 1.00\\times10^{-10}\\text{ m}$ (roughly atomic scale): minimum momentum spread
$$\\Delta p \\ge \\frac{\\hbar}{2\\Delta x} = \\frac{1.055\\times10^{-34}}{2(1.00\\times10^{-10})} \\approx 5.28\\times10^{-25}\\text{ kg m/s}$$
corresponding to a minimum velocity spread $\\Delta v = \\Delta p/m \\approx 5.8\\times10^{5}\\text{ m/s}$ — a large, physically significant spread purely from confinement, with nothing to do with measurement clumsiness.` },
        { kind: "transfer", md: `The same commutator-driven logic reappears for angular momentum components in the next lesson ($[\\hat L_x,\\hat L_y]=i\\hbar\\hat L_z\\ne0$, so no state has all three components simultaneously definite) and for energy and time ($\\Delta E\\,\\Delta t \\gtrsim \\hbar$, governing natural linewidths of unstable states). Non-commutativity of operators is the single mathematical source behind essentially every "cannot simultaneously know both" statement in quantum mechanics.` }
      ],
      checkpoints: [
        { q: "The Heisenberg uncertainty principle $\\Delta x\\Delta p\\ge\\hbar/2$ arises fundamentally because:", options: ["Measurement instruments are not yet precise enough", "The position and momentum operators do not commute", "Position and momentum are unrelated classical quantities", "Planck's constant is an experimental artifact"], answer: 1, explain: "$[\\hat x,\\hat p]=i\\hbar\\neq0$ is an algebraic fact about the operators, not a statement about measurement technology." },
        { q: "If a particle is confined to a smaller region (smaller $\\Delta x$), the minimum possible momentum uncertainty $\\Delta p$:", options: ["Decreases", "Stays the same", "Increases", "Becomes exactly zero"], answer: 2, explain: "$\\Delta p \\ge \\hbar/(2\\Delta x)$: tighter confinement in position forces a larger minimum spread in momentum." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-spin",
      title: "Angular Momentum and Spin",
      minutes: 14,
      discovery: "Electrons carry an intrinsic angular momentum with no classical analog — spin-$\\tfrac12$ — required to explain a two-way split that orbital motion alone cannot produce.",
      sections: [
        { kind: "problem", md: `Send a beam of silver atoms through an inhomogeneous magnetic field (the Stern–Gerlach experiment). Classically, if the atoms' magnetic moments point in random continuous directions, the beam should smear into a continuous vertical band on the detector screen, reflecting a continuum of deflection angles. The observed result: the beam splits into exactly *two* discrete spots, symmetric about the center, with nothing in between.` },
        { kind: "candidates", md: `**A. This is ordinary orbital angular momentum quantization — the two spots are simply the two lowest allowed orbital states.**

**B. Some leftover classical magnetic moment from the atom's nucleus happens to only take two values.**` },
        { kind: "failures", md: `**A fails on the actual quantum numbers involved.** Orbital angular momentum quantization gives $2l+1$ possible orientations for a given orbital quantum number $l$ (details formalized below) — always an *odd* number for any integer $l\\ge0$, never exactly 2. Worse, silver's outer (valence) electron is in an $l=0$ state in the ground-state configuration used in the experiment — zero orbital angular momentum, which by itself predicts *one* undeflected spot, not two.

**B fails on both scale and independence.** The magnitude of the observed splitting matches the electron's own magnetic moment (the Bohr magneton), not a value appropriate to a much heavier, much-less-magnetic nucleus. The same two-valued splitting is observed even for beams of bare electrons, entirely decoupled from any specific nuclear structure — ruling out a nucleus-specific explanation.` },
        { kind: "discovery", md: `The electron must carry an *intrinsic* angular momentum, entirely separate from orbital motion, with a fixed quantum number $s=\\tfrac12$ for every electron (unlike orbital $l$, which varies state to state). A quantum number $s=\\tfrac12$ gives exactly $2s+1=2$ possible orientations along any measurement axis — precisely reproducing the two Stern–Gerlach spots. This is **spin**: a genuine angular-momentum-like quantum degree of freedom with no classical picture of literally spinning matter behind it (treating the electron as a tiny spinning charged sphere gives wildly wrong, even superluminal, surface speeds).` },
        { kind: "formal", md: `**General angular momentum quantization** (covering both orbital $l$ and spin $s$): the squared magnitude has eigenvalues $\\hbar^2j(j+1)$, and the projection along any chosen axis (conventionally $z$) has eigenvalues $m\\hbar$ with $m=-j,-j+1,\\dots,j$ ($2j+1$ values). Orbital angular momentum: $l=0,1,2,\\dots$ (integer only). Spin: half-integer values allowed; the electron has $s=\\tfrac12$ fixed, always, giving $m_s=\\pm\\tfrac12$.` },
        { kind: "apply", md: `Electron spin magnitude: $|\\vec S| = \\hbar\\sqrt{s(s+1)} = \\hbar\\sqrt{\\tfrac34} = \\dfrac{\\sqrt3}{2}\\hbar \\approx 0.866\\,\\hbar$. Its two possible $z$-projections: $S_z = \\pm\\tfrac12\\hbar$ — these are the two Stern–Gerlach outcomes.` },
        { kind: "transfer", md: `The same $j(j+1)$-magnitude, $(2j+1)$-projection counting structure governs the addition of orbital and spin angular momentum (spin-orbit coupling) and nuclear spin — it's reused directly in the next lesson to organize hydrogen's full set of quantum numbers.` }
      ],
      checkpoints: [
        { q: "The Stern–Gerlach experiment on ground-state silver atoms (valence electron $l=0$) produces two spots because:", options: ["Orbital angular momentum gives exactly two orientations for $l=0$", "The electron carries an intrinsic spin angular momentum, $s=\\tfrac12$, independent of orbital motion", "Silver nuclei have two isotopes", "The magnetic field itself is quantized"], answer: 1, explain: "$l=0$ alone predicts one undeflected spot; the observed two-way split requires spin-$\\tfrac12$, an intrinsic degree of freedom with $2s+1=2$ orientations." },
        { q: "For any angular momentum with quantum number $j$, the number of possible $z$-axis projection values is:", options: ["$j$", "$j+1$", "$2j$", "$2j+1$"], answer: 3, explain: "$m=-j,-j+1,\\dots,+j$ in integer steps gives $2j+1$ values." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "qm-hydrogen",
      title: "The Hydrogen Atom: Quantum Numbers and Degeneracy",
      minutes: 16,
      discovery: "Solving the full 3D Coulomb problem naturally produces three quantum numbers, with orbital angular momentum capped by the principal quantum number — fixing what the Bohr model got wrong.",
      sections: [
        { kind: "problem", md: `The Bohr model postulated quantized circular orbits by fiat and got hydrogen's energy levels ($E_n=-13.6\\text{ eV}/n^2$) numerically right, but couldn't say *why* those particular orbits were special, couldn't describe the true 3D shape of an electron's probability distribution, and specifically predicted the ground state has orbital angular momentum $L=\\hbar$ — contradicted by experiment (ground-state hydrogen shows no orbital-angular-momentum-related magnetic structure, consistent instead with $L=0$). What does actually solving the Schrödinger equation for an electron in a Coulomb potential $V(r)=-e^2/4\\pi\\varepsilon_0 r$ predict?` },
        { kind: "candidates", md: `**A. Solve the 3D problem the same way as the 1D infinite well, expecting one quantum number $n$ to label every state completely, just as Bohr assumed.**

**B. Since the Coulomb potential is central (depends only on $r$, not direction) but genuinely three-dimensional, maybe the orbital angular momentum quantum number $l$ (from the previous lesson) can independently take any value, unconstrained by $n$.**` },
        { kind: "failures", md: `**A fails because the problem is genuinely three-dimensional.** Separating the 3D Schrödinger equation in spherical coordinates ($r,\\theta,\\phi$) produces *three* separate equations — one per coordinate — each contributing its own quantum number: a radial equation (giving $n$), a polar-angle equation (giving $l$), and an azimuthal equation (giving $m_l$, from the previous lesson's general angular momentum quantization). A single number $n$ cannot distinguish states that share the same energy but differ in angular shape — that distinction requires $l$ and $m_l$ as well.

**B fails once the radial equation is actually solved.** Requiring the radial wavefunction to stay normalizable (not blow up as $r\\to\\infty$, and behave sensibly as $r\\to0$) imposes a constraint linking $l$ to $n$: solutions only exist for $l=0,1,\\dots,n-1$ — $l$ is capped by $n$, not free to take any value independent of it. This is precisely why the true hydrogen ground state ($n=1$) is forced to have $l=0$ (hence $L=0$), resolving the exact discrepancy with the Bohr model noted above.` },
        { kind: "discovery", md: `The full 3D Coulomb problem separates cleanly into radial and angular parts. The radial equation, with the normalizability constraint, reproduces $E_n=-13.6\\text{ eV}/n^2$ (matching Bohr's formula, but now *derived* from boundary conditions on a genuine 3D wavefunction, not postulated) and additionally forces $l=0,1,\\dots,n-1$. The angular part reproduces the general angular-momentum quantization from the previous lesson, giving $m_l=-l,\\dots,l$. For fixed $n$, summing $2l+1$ states over all allowed $l=0,\\dots,n-1$ gives $n^2$ distinct spatial states sharing exactly the same energy — a large **degeneracy** entirely absent from the 1D infinite well, arising because the Coulomb potential's energy formula happens not to depend on $l$ at all.` },
        { kind: "formal", md: `**Hydrogen quantum numbers:** principal $n=1,2,3,\\dots$ (sets energy), orbital $l=0,1,\\dots,n-1$ (sets orbital angular momentum magnitude, $\\hbar\\sqrt{l(l+1)}$), magnetic $m_l=-l,\\dots,l$ (sets $z$-projection). Energy depends on $n$ alone: $E_n=-13.6\\text{ eV}/n^2$. Spatial degeneracy per $n$: $\\sum_{l=0}^{n-1}(2l+1)=n^2$; including the electron's two spin states ($m_s=\\pm\\tfrac12$), total degeneracy is $2n^2$.

*Recognition level.* When a small extra term $\\hat H'$ perturbs this exactly-solvable system (an external field, a relativistic correction), **first-order perturbation theory** gives the energy shift without re-solving the full equation:
$$E^{(1)} = \\langle\\psi_0|\\hat H'|\\psi_0\\rangle$$
the expectation value of the perturbation in the *unperturbed* state. Separately, because electrons are identical fermions, the **Pauli exclusion principle** forbids any two electrons in an atom from sharing the same full set $(n,l,m_l,m_s)$ — this is why electrons fill up successive shells (rather than all collapsing into $n=1,l=0$) and underlies the entire structure of the periodic table.` },
        { kind: "apply", md: `Spatial+spin degeneracy of the $n=3$ shell: $2n^2 = 2(9) = 18$ states. Energy of the photon emitted in an $n=2\\to n=1$ transition: $E_2=-13.6/4=-3.4\\text{ eV}$, $E_1=-13.6\\text{ eV}$, so $\\Delta E = 13.6-3.4 = 10.2\\text{ eV}$ (the Lyman-$\\alpha$ line), corresponding to $\\lambda = hc/\\Delta E \\approx (1240\\text{ eV nm})/10.2\\text{ eV} \\approx 121.6\\text{ nm}$ — matching the well-known Lyman-alpha wavelength.` },
        { kind: "transfer", md: `The pattern "central potential $\\to$ separable 3D equation $\\to$ quantum numbers emerging from boundary conditions in each coordinate, with later ones capped by earlier ones" reappears in any central-potential problem (finite spherical wells, simple models of quark confinement). Perturbation theory and the Pauli exclusion principle are the two tools that extend this one exactly-solvable atom to the rest of atomic, molecular, and condensed-matter physics — multi-electron atoms, chemical bonding, and band structure all build outward from exactly this foundation.` }
      ],
      checkpoints: [
        { q: "In the hydrogen atom, the orbital quantum number $l$ for a given principal quantum number $n$ is restricted to:", options: ["Any non-negative integer, independent of $n$", "$l=0,1,\\dots,n-1$", "$l=n$ only", "$l=-n,\\dots,n$"], answer: 1, explain: "Normalizability of the radial wavefunction caps $l$ at $n-1$; this is exactly why the $n=1$ ground state must have $l=0$." },
        { q: "The total degeneracy (including spin) of the hydrogen $n=2$ shell is:", options: ["2", "4", "8", "16"], answer: 2, explain: "Spatial degeneracy is $n^2=4$; including two spin states per spatial state gives $2n^2=8$." }
      ]
    }
  ],

  drills: [
    // qm-photoelectric
    { id: "qm-photoelectric-d1", lesson: "qm-photoelectric", type: "mc", prompt: "In the photoelectric effect, the maximum kinetic energy of ejected electrons depends on:", options: ["Light intensity only", "Light frequency only", "Both frequency and intensity equally", "Neither; it is always the same"], answer: 1, hint: "Each electron absorbs one photon.", solution: "$KE_{max}=hf-\\phi$ depends on frequency $f$ and the work function $\\phi$, not on intensity.", difficulty: 1, tags: ["qm", "photoelectric"] },
    { id: "qm-photoelectric-d2", lesson: "qm-photoelectric", type: "numeric", prompt: "A metal has work function $\\phi=2.30\\text{ eV}$. Find the threshold frequency $f_0$ in units of $10^{14}\\text{ Hz}$. ($h=6.626\\times10^{-34}\\text{ J s}$, $1\\text{ eV}=1.6\\times10^{-19}\\text{ J}$)", answer: 5.55, tolerance: 0.03, unit: "$\\times10^{14}$ Hz", hint: "$f_0=\\phi/h$.", solution: "$\\phi = 2.30\\times1.6\\times10^{-19}=3.68\\times10^{-19}\\text{ J}$; $f_0 = 3.68\\times10^{-19}/6.626\\times10^{-34} \\approx 5.55\\times10^{14}\\text{ Hz}$.", difficulty: 2, tags: ["qm", "photoelectric"] },
    { id: "qm-photoelectric-d3", lesson: "qm-photoelectric", type: "mc", prompt: "Below the threshold frequency, increasing light intensity:", options: ["Eventually ejects electrons if intensity is high enough", "Never ejects electrons, no matter how intense", "Increases the ejected electrons' kinetic energy", "Decreases the work function"], answer: 1, hint: "Each electron absorbs only one photon.", solution: "Since electrons don't accumulate energy across multiple photons, no intensity of below-threshold light ejects electrons.", difficulty: 1, tags: ["qm", "photoelectric"] },
    { id: "qm-photoelectric-d4", lesson: "qm-photoelectric", type: "mc", prompt: "The instantaneous nature of photoelectric emission (no measurable time delay, even for dim light) is best explained by:", options: ["Electrons are massless", "Energy arrives in discrete packets, absorbed one at a time by single electrons, not accumulated slowly", "The metal surface is perfectly reflective", "Light travels instantaneously"], answer: 1, hint: "Contrast with the classical wave-accumulation picture.", solution: "A single photon's energy is absorbed all at once; there's no accumulation process to cause a delay.", difficulty: 1, tags: ["qm", "photoelectric"] },
    { id: "qm-photoelectric-d5", lesson: "qm-photoelectric", type: "numeric", prompt: "Light of wavelength $400\\text{ nm}$ strikes a metal with work function $1.80\\text{ eV}$. Find the maximum kinetic energy of ejected electrons, in eV. ($hc\\approx1240\\text{ eV nm}$)", answer: 1.30, tolerance: 0.03, unit: "eV", hint: "$hf = hc/\\lambda$.", solution: "$hf = 1240/400 = 3.10\\text{ eV}$; $KE_{max}=3.10-1.80=1.30\\text{ eV}$.", difficulty: 2, tags: ["qm", "photoelectric"] },

    // qm-de-broglie
    { id: "qm-de-broglie-d1", lesson: "qm-de-broglie", type: "mc", prompt: "The de Broglie wavelength of a particle is given by:", options: ["$\\lambda=hp$", "$\\lambda=h/p$", "$\\lambda=p/h$", "$\\lambda=h^2/p$"], answer: 1, hint: "Same relation as for photons, $p=h/\\lambda$.", solution: "$\\lambda=h/p$, universal for any massive particle with momentum $p$.", difficulty: 1, tags: ["qm", "de-broglie"] },
    { id: "qm-de-broglie-d2", lesson: "qm-de-broglie", type: "numeric", prompt: "Find the de Broglie wavelength (in pm) of an electron ($m=9.11\\times10^{-31}\\text{ kg}$) moving at $2.00\\times10^6\\text{ m/s}$.", answer: 364, tolerance: 0.03, unit: "pm", hint: "$\\lambda=h/(mv)$.", solution: "$p=mv=(9.11\\times10^{-31})(2.00\\times10^6)=1.822\\times10^{-24}\\text{ kg m/s}$; $\\lambda=6.626\\times10^{-34}/1.822\\times10^{-24}\\approx3.64\\times10^{-10}\\text{ m}=364\\text{ pm}$.", difficulty: 2, tags: ["qm", "de-broglie"] },
    { id: "qm-de-broglie-d3", lesson: "qm-de-broglie", type: "mc", prompt: "Electron diffraction off a crystal (Davisson–Germer) is direct evidence for:", options: ["The particle nature of light", "The wave nature of matter", "The quantization of charge", "The existence of antimatter"], answer: 1, hint: "Diffraction is a wave phenomenon.", solution: "The observed diffraction pattern, matching Bragg's law with $\\lambda=h/p$, demonstrates electrons behave as waves.", difficulty: 1, tags: ["qm", "de-broglie"] },
    { id: "qm-de-broglie-d4", lesson: "qm-de-broglie", type: "mc", prompt: "Doubling a particle's momentum changes its de Broglie wavelength by a factor of:", options: ["2", "1/2", "4", "$\\sqrt2$"], answer: 1, hint: "$\\lambda\\propto1/p$.", solution: "$\\lambda=h/p$, so doubling $p$ halves $\\lambda$.", difficulty: 1, tags: ["qm", "de-broglie"] },
    { id: "qm-de-broglie-d5", lesson: "qm-de-broglie", type: "mc", prompt: "Macroscopic objects (like thrown balls) don't show observable diffraction because:", options: ["They have zero momentum", "Their de Broglie wavelength is far smaller than any relevant physical length scale", "Wave-particle duality only applies to charged particles", "Diffraction requires the object to be transparent"], answer: 1, hint: "$\\lambda=h/p$ with large $p$.", solution: "Large mass and speed give enormous $p$, hence a vanishingly small $\\lambda\\sim10^{-34}\\text{ m}$ — far too small to produce observable diffraction.", difficulty: 2, tags: ["qm", "de-broglie"] },

    // qm-wavefunction
    { id: "qm-wavefunction-d1", lesson: "qm-wavefunction", type: "mc", prompt: "The Born rule states that the probability density of finding a particle at position $x$ is:", options: ["$\\psi(x)$", "$\\psi(x)^*$", "$|\\psi(x)|^2$", "$\\int\\psi\\,dx$"], answer: 2, hint: "Squared magnitude of the complex amplitude.", solution: "$P(x)=|\\psi(x)|^2$, always non-negative and normalizable.", difficulty: 1, tags: ["qm", "wavefunction"] },
    { id: "qm-wavefunction-d2", lesson: "qm-wavefunction", type: "mc", prompt: "Interference (constructive and destructive) in the double-slit experiment requires that $\\psi$ be:", options: ["Real and non-negative", "Complex-valued, so amplitudes can carry phase and cancel", "Always positive", "Independent of position"], answer: 1, hint: "Non-negative probabilities alone cannot cancel.", solution: "Complex amplitudes can have opposite phase and cancel exactly, producing dark fringes; non-negative probabilities cannot.", difficulty: 2, tags: ["qm", "wavefunction"] },
    { id: "qm-wavefunction-d3", lesson: "qm-wavefunction", type: "mc", prompt: "If measurements are made that reveal which slit each electron passed through, the double-slit interference pattern:", options: ["Becomes sharper", "Disappears, leaving the sum of the two single-slit patterns", "Is unaffected", "Shifts to a new location"], answer: 1, hint: "Which-path information destroys the cross term.", solution: "Determining the path removes the interference cross term; probabilities simply add as $|\\psi_1|^2+|\\psi_2|^2$.", difficulty: 2, tags: ["qm", "wavefunction"] },
    { id: "qm-wavefunction-d4", lesson: "qm-wavefunction", type: "numeric", prompt: "A normalized wavefunction has $\\psi(x_0)=0.3+0.4i$ at some point $x_0$. Find $|\\psi(x_0)|^2$.", answer: 0.25, tolerance: 0.02, unit: "(probability density)", hint: "$|\\psi|^2=\\text{Re}(\\psi)^2+\\text{Im}(\\psi)^2$.", solution: "$|\\psi|^2 = 0.3^2+0.4^2 = 0.09+0.16 = 0.25$.", difficulty: 2, tags: ["qm", "wavefunction"] },
    { id: "qm-wavefunction-d5", lesson: "qm-wavefunction", type: "mc", prompt: "Individual electrons detected one at a time in a double-slit experiment:", options: ["Each arrive spread out over the whole screen", "Each arrive as one discrete, localized dot", "Never arrive individually, only in bulk", "Show interference individually, before any pattern builds up"], answer: 1, hint: "Particle-like detection, wave-like statistics.", solution: "Each detection event is discrete and localized; only the accumulated statistics over many electrons shows the interference pattern.", difficulty: 1, tags: ["qm", "wavefunction"] },

    // qm-schrodinger
    { id: "qm-schrodinger-d1", lesson: "qm-schrodinger", type: "mc", prompt: "The time-independent Schrödinger equation is an example of:", options: ["A first-order ODE with no boundary conditions", "An eigenvalue equation for the energy operator (Hamiltonian)", "A purely classical wave equation", "An equation with no solutions in bound systems"], answer: 1, hint: "$\\hat H\\phi=E\\phi$.", solution: "It has the form $\\hat H\\phi=E\\phi$, an eigenvalue equation whose allowed $E$ values (eigenvalues) are often discrete once boundary conditions are imposed.", difficulty: 1, tags: ["qm", "schrodinger-equation"] },
    { id: "qm-schrodinger-d2", lesson: "qm-schrodinger", type: "mc", prompt: "The correspondence used to build the Schrödinger equation replaces momentum $p$ with the operator:", options: ["$-i\\hbar\\,\\partial/\\partial x$", "$i\\hbar\\,\\partial/\\partial t$", "$\\hbar^2\\partial^2/\\partial x^2$", "$m\\,\\partial/\\partial t$"], answer: 0, hint: "Matches plane wave $e^{ikx}$ behavior.", solution: "$\\hat p = -i\\hbar\\,\\partial/\\partial x$, so that acting on $e^{ikx}$ returns $\\hbar k = p$.", difficulty: 2, tags: ["qm", "schrodinger-equation"] },
    { id: "qm-schrodinger-d3", lesson: "qm-schrodinger", type: "mc", prompt: "A classical (real) wave equation fails to describe matter waves because it predicts:", options: ["$E\\propto p^2$, matching nonrelativistic kinetic energy", "$E\\propto p$ (linear dispersion), not the correct $E=p^2/2m$", "No wave behavior at all", "Infinite energy for any wavelength"], answer: 1, hint: "Plug a plane wave into the classical wave equation.", solution: "The classical wave equation gives $\\omega\\propto k$ (like light), whereas a nonrelativistic massive particle needs $E=p^2/2m$, i.e. $\\omega\\propto k^2$.", difficulty: 2, tags: ["qm", "schrodinger-equation"] },
    { id: "qm-schrodinger-d4", lesson: "qm-schrodinger", type: "mc", prompt: "For time-independent potentials, separable solutions of the Schrödinger equation take the form $\\psi(x,t)=\\phi(x)e^{-iEt/\\hbar}$. The probability density $|\\psi(x,t)|^2$ for such a state is:", options: ["Oscillating in time with frequency $E/\\hbar$", "Constant in time (a 'stationary state')", "Always zero", "Growing exponentially in time"], answer: 1, hint: "$|e^{-iEt/\\hbar}|=1$.", solution: "$|\\psi|^2=|\\phi(x)|^2|e^{-iEt/\\hbar}|^2=|\\phi(x)|^2$, time-independent — hence the name 'stationary state.'", difficulty: 2, tags: ["qm", "schrodinger-equation"] },
    { id: "qm-schrodinger-d5", lesson: "qm-schrodinger", type: "numeric", prompt: "A free particle plane wave has wavenumber $k=2.0\\times10^{10}\\text{ m}^{-1}$. Find its energy in eV for an electron ($m=9.11\\times10^{-31}\\text{ kg}$, $\\hbar=1.055\\times10^{-34}\\text{ J s}$).", answer: 15.27, tolerance: 0.03, unit: "eV", hint: "$E=\\hbar^2k^2/2m$.", solution: "$E = (1.055\\times10^{-34})^2(2.0\\times10^{10})^2 / (2\\times9.11\\times10^{-31}) \\approx 2.44\\times10^{-18}\\text{ J} \\approx 15.27\\text{ eV}$.", difficulty: 3, tags: ["qm", "schrodinger-equation"] },

    // qm-infinite-well
    { id: "qm-infinite-well-d1", lesson: "qm-infinite-well", type: "mc", prompt: "In the infinite square well, the allowed wavenumbers satisfy:", options: ["$k_n = n\\pi/L$, $n=1,2,3,\\dots$", "$k_n$ can be any real number", "$k_n = n\\pi/2L$, $n=0,1,2,\\dots$", "$k_n = 2n\\pi/L$, $n=1,2,3,\\dots$"], answer: 0, hint: "From $\\sin(kL)=0$ with $\\phi(0)=0$ already imposed.", solution: "Boundary conditions force $\\sin(k_nL)=0$ with $k_n>0$, giving $k_n=n\\pi/L$ for positive integers $n$.", difficulty: 1, tags: ["qm", "infinite-well"] },
    { id: "qm-infinite-well-d2", lesson: "qm-infinite-well", type: "numeric", prompt: "An electron is confined to a 1D infinite well of width $L=0.50\\text{ nm}$. Find the ground-state energy $E_1$ in eV.", answer: 1.505, tolerance: 0.03, unit: "eV", hint: "$E_1=h^2/(8mL^2)$; scales as $1/L^2$.", solution: "$E_1 = h^2/(8mL^2) = (6.626\\times10^{-34})^2/(8\\times9.11\\times10^{-31}\\times(0.5\\times10^{-9})^2) \\approx 2.41\\times10^{-19}\\text{ J} \\approx 1.505\\text{ eV}$.", difficulty: 2, tags: ["qm", "infinite-well"] },
    { id: "qm-infinite-well-d3", lesson: "qm-infinite-well", type: "mc", prompt: "For an infinite square well, doubling the well width $L$ changes the ground-state energy by a factor of:", options: ["2", "1/2", "4", "1/4"], answer: 3, hint: "$E_1\\propto1/L^2$.", solution: "$E_1\\propto1/L^2$, so doubling $L$ multiplies $E_1$ by $1/4$.", difficulty: 1, tags: ["qm", "infinite-well"] },
    { id: "qm-infinite-well-d4", lesson: "qm-infinite-well", type: "mc", prompt: "In the infinite square well, the energy of the $n=3$ state relative to $E_1$ is:", options: ["$3E_1$", "$6E_1$", "$9E_1$", "$27E_1$"], answer: 2, hint: "$E_n\\propto n^2$.", solution: "$E_n = n^2E_1$, so $E_3=9E_1$.", difficulty: 1, tags: ["qm", "infinite-well"] },
    { id: "qm-infinite-well-d5", lesson: "qm-infinite-well", type: "mc", prompt: "The fact that $n=0$ is not an allowed state in the infinite square well reflects:", options: ["A mathematical convention with no physical meaning", "The impossibility of a normalizable wavefunction identically equal to zero representing a physical particle", "That $n=0$ would require negative energy", "Momentum conservation"], answer: 1, hint: "$n=0$ gives $\\phi\\equiv0$.", solution: "$n=0$ gives $\\phi(x)\\equiv0$ everywhere, which isn't a normalizable physical state — hence a strictly positive zero-point energy for $n=1$.", difficulty: 2, tags: ["qm", "infinite-well"] },

    // qm-tunneling
    { id: "qm-tunneling-d1", lesson: "qm-tunneling", type: "mc", prompt: "Inside a barrier where $E<V_0$, the time-independent Schrödinger equation admits solutions that are:", options: ["Oscillatory with real wavenumber", "Exactly zero everywhere", "Real exponentials (growing and decaying)", "Purely imaginary"], answer: 2, hint: "$\\phi''=+\\kappa^2\\phi$ with $\\kappa$ real.", solution: "The equation becomes $\\phi''=+\\kappa^2\\phi$, giving real exponential solutions $e^{\\pm\\kappa x}$, not oscillations.", difficulty: 1, tags: ["qm", "tunneling"] },
    { id: "qm-tunneling-d2", lesson: "qm-tunneling", type: "mc", prompt: "Quantum tunneling through a barrier does NOT require:", options: ["A barrier of finite width", "Violating energy conservation during the crossing", "A nonzero transmission probability $T$", "Matching the wavefunction and its derivative at the boundaries"], answer: 1, hint: "$E$ is fixed throughout, no borrowing needed.", solution: "Energy $E$ is a fixed eigenvalue throughout; the decaying exponential solution requires no violation of energy conservation.", difficulty: 2, tags: ["qm", "tunneling"] },
    { id: "qm-tunneling-d3", lesson: "qm-tunneling", type: "numeric", prompt: "A barrier gives $\\kappa L=5.0$. Estimate the order of magnitude of the transmission probability $T\\sim e^{-2\\kappa L}$ (report as $-\\log_{10}T$, i.e. how many powers of ten below 1).", answer: 4.3, tolerance: 0.05, unit: "(decades)", hint: "$T=e^{-10}$; convert to base 10.", solution: "$T=e^{-10}\\approx4.5\\times10^{-5}$, so $-\\log_{10}T\\approx4.34$.", difficulty: 3, tags: ["qm", "tunneling"] },
    { id: "qm-tunneling-d4", lesson: "qm-tunneling", type: "mc", prompt: "Alpha decay of atomic nuclei is best explained by:", options: ["The alpha particle having enough classical energy to escape", "Quantum tunneling through the nuclear potential barrier", "Thermal evaporation of nucleons", "The infinite square well model"], answer: 1, hint: "Alpha particle energies are measured below the classical barrier height.", solution: "Alpha particles tunnel through the confining Coulomb-plus-nuclear barrier even though their kinetic energy is classically insufficient to surmount it.", difficulty: 1, tags: ["qm", "tunneling"] },
    { id: "qm-tunneling-d5", lesson: "qm-tunneling", type: "mc", prompt: "The scanning tunneling microscope achieves sub-angstrom height sensitivity because the tunneling current:", options: ["Is independent of tip-sample distance", "Depends linearly on tip-sample distance", "Falls off exponentially with tip-sample distance", "Only exists at exactly zero distance"], answer: 2, hint: "$T\\sim e^{-2\\kappa L}$.", solution: "Exponential dependence on gap width $L$ makes the tunneling current extraordinarily sensitive to tiny changes in height.", difficulty: 2, tags: ["qm", "tunneling"] },

    // qm-harmonic-oscillator
    { id: "qm-harmonic-oscillator-d1", lesson: "qm-harmonic-oscillator", type: "mc", prompt: "The energy levels of a quantum harmonic oscillator are given by:", options: ["$E_n = n\\hbar\\omega$", "$E_n = \\hbar\\omega(n+\\tfrac12)$", "$E_n = n^2\\hbar\\omega$", "$E_n = \\hbar\\omega/n$"], answer: 1, hint: "Includes zero-point energy.", solution: "$E_n=\\hbar\\omega(n+\\tfrac12)$, $n=0,1,2,\\dots$ — evenly spaced with a nonzero ground state.", difficulty: 1, tags: ["qm", "harmonic-oscillator"] },
    { id: "qm-harmonic-oscillator-d2", lesson: "qm-harmonic-oscillator", type: "numeric", prompt: "Find the zero-point energy (in eV) of an oscillator with $\\omega=3.0\\times10^{14}\\text{ rad/s}$. ($\\hbar=1.055\\times10^{-34}\\text{ J s}$)", answer: 0.0988, tolerance: 0.03, unit: "eV", hint: "$E_0=\\tfrac12\\hbar\\omega$.", solution: "$E_0 = 0.5(1.055\\times10^{-34})(3.0\\times10^{14}) = 1.58\\times10^{-20}\\text{ J} \\approx 0.0988\\text{ eV}$.", difficulty: 2, tags: ["qm", "harmonic-oscillator"] },
    { id: "qm-harmonic-oscillator-d3", lesson: "qm-harmonic-oscillator", type: "mc", prompt: "The spacing between adjacent energy levels of a quantum harmonic oscillator:", options: ["Increases with $n$", "Decreases with $n$", "Is constant, equal to $\\hbar\\omega$", "Is zero for large $n$"], answer: 2, hint: "$E_{n+1}-E_n = \\hbar\\omega(n+3/2)-\\hbar\\omega(n+1/2)$.", solution: "$E_{n+1}-E_n = \\hbar\\omega$ for all $n$ — a constant, equal spacing, unlike the infinite well.", difficulty: 1, tags: ["qm", "harmonic-oscillator"] },
    { id: "qm-harmonic-oscillator-d4", lesson: "qm-harmonic-oscillator", type: "mc", prompt: "The raising and lowering operators $\\hat a^\\dagger,\\hat a$ satisfy the commutation relation:", options: ["$[\\hat a,\\hat a^\\dagger]=0$", "$[\\hat a,\\hat a^\\dagger]=1$", "$[\\hat a,\\hat a^\\dagger]=i\\hbar$", "$[\\hat a,\\hat a^\\dagger]=-1$"], answer: 1, hint: "This is what makes $\\hat a^\\dagger\\hat a$ have integer eigenvalues.", solution: "$[\\hat a,\\hat a^\\dagger]=1$; combined with $\\hat H=\\hbar\\omega(\\hat a^\\dagger\\hat a+\\tfrac12)$ this gives the integer-spaced spectrum.", difficulty: 2, tags: ["qm", "harmonic-oscillator"] },
    { id: "qm-harmonic-oscillator-d5", lesson: "qm-harmonic-oscillator", type: "mc", prompt: "The ground-state wavefunction of the quantum harmonic oscillator has the shape of:", options: ["A square pulse", "A Gaussian", "A pure sine wave", "A delta function"], answer: 1, hint: "$\\phi_0(x)\\propto e^{-m\\omega x^2/2\\hbar}$.", solution: "$\\phi_0(x)\\propto e^{-m\\omega x^2/2\\hbar}$, a Gaussian centered at the potential minimum.", difficulty: 1, tags: ["qm", "harmonic-oscillator"] },

    // qm-uncertainty
    { id: "qm-uncertainty-d1", lesson: "qm-uncertainty", type: "mc", prompt: "The Heisenberg uncertainty principle for position and momentum is:", options: ["$\\Delta x\\Delta p \\ge \\hbar$", "$\\Delta x\\Delta p \\ge \\hbar/2$", "$\\Delta x + \\Delta p \\ge \\hbar$", "$\\Delta x \\Delta p = 0$"], answer: 1, hint: "From the general bound with $[\\hat x,\\hat p]=i\\hbar$.", solution: "$\\Delta x\\,\\Delta p \\ge \\hbar/2$, derived from $\\Delta A\\Delta B\\ge\\tfrac12|\\langle[\\hat A,\\hat B]\\rangle|$ with $[\\hat x,\\hat p]=i\\hbar$.", difficulty: 1, tags: ["qm", "uncertainty"] },
    { id: "qm-uncertainty-d2", lesson: "qm-uncertainty", type: "numeric", prompt: "A proton ($m=1.67\\times10^{-27}\\text{ kg}$) is confined to a nucleus of diameter $\\Delta x = 5.0\\times10^{-15}\\text{ m}$. Estimate the minimum uncertainty in its speed, in m/s.", answer: 6.3e6, tolerance: 0.05, unit: "m/s", hint: "$\\Delta v \\ge \\hbar/(2m\\Delta x)$.", solution: "$\\Delta p \\ge \\hbar/(2\\Delta x) = 1.055\\times10^{-34}/(2\\times5.0\\times10^{-15}) \\approx 1.055\\times10^{-20}\\text{ kg m/s}$; $\\Delta v = \\Delta p/m \\approx 6.3\\times10^6\\text{ m/s}$.", difficulty: 3, tags: ["qm", "uncertainty"] },
    { id: "qm-uncertainty-d3", lesson: "qm-uncertainty", type: "mc", prompt: "The commutator $[\\hat x,\\hat p]$ equals:", options: ["0", "$i\\hbar$", "$\\hbar$", "$-i\\hbar^2$"], answer: 1, hint: "Compute $\\hat x\\hat p\\psi - \\hat p\\hat x\\psi$.", solution: "$[\\hat x,\\hat p]=i\\hbar$, the fundamental commutation relation underlying the uncertainty principle.", difficulty: 2, tags: ["qm", "uncertainty"] },
    { id: "qm-uncertainty-d4", lesson: "qm-uncertainty", type: "mc", prompt: "If two operators commute (their commutator is zero), the corresponding observables:", options: ["Can never be measured", "Can, in principle, be simultaneously known exactly", "Are always equal to each other", "Must both be zero"], answer: 1, hint: "Commuting operators share simultaneous eigenstates.", solution: "Commuting Hermitian operators possess a common set of eigenstates, in which both observables have simultaneously definite values.", difficulty: 2, tags: ["qm", "uncertainty"] },
    { id: "qm-uncertainty-d5", lesson: "qm-uncertainty", type: "mc", prompt: "The energy-time uncertainty relation $\\Delta E\\Delta t\\gtrsim\\hbar$ is most directly responsible for:", options: ["The quantization of charge", "The natural linewidth (energy spread) of short-lived excited states", "The Pauli exclusion principle", "The Born rule"], answer: 1, hint: "Short lifetime, broad energy spread.", solution: "States with short lifetimes ($\\Delta t$ small) necessarily have a larger energy uncertainty $\\Delta E$, observed as spectral line broadening.", difficulty: 2, tags: ["qm", "uncertainty"] },

    // qm-spin
    { id: "qm-spin-d1", lesson: "qm-spin", type: "mc", prompt: "The Stern–Gerlach experiment on silver atoms (valence electron $l=0$) shows two spots because:", options: ["Orbital angular momentum gives two states for $l=0$", "The electron has intrinsic spin $s=\\tfrac12$, giving $2s+1=2$ orientations", "Silver has two stable isotopes with different masses", "The magnetic field has two poles"], answer: 1, hint: "$l=0$ alone predicts one spot.", solution: "Spin-$\\tfrac12$ gives exactly two $z$-projections, $m_s=\\pm\\tfrac12$, matching the observed two-way split.", difficulty: 1, tags: ["qm", "spin"] },
    { id: "qm-spin-d2", lesson: "qm-spin", type: "numeric", prompt: "Find the magnitude of the electron's spin angular momentum, $|\\vec S|=\\hbar\\sqrt{s(s+1)}$, in units of $\\hbar$ (i.e. report $\\sqrt{s(s+1)}$ for $s=1/2$).", answer: 0.866, tolerance: 0.02, unit: "$\\hbar$", hint: "$\\sqrt{(1/2)(3/2)}$.", solution: "$\\sqrt{\\tfrac12\\cdot\\tfrac32} = \\sqrt{3/4} = \\dfrac{\\sqrt3}{2} \\approx 0.866$.", difficulty: 2, tags: ["qm", "spin"] },
    { id: "qm-spin-d3", lesson: "qm-spin", type: "mc", prompt: "For orbital angular momentum quantum number $l=2$, the number of possible $m_l$ values is:", options: ["2", "3", "4", "5"], answer: 3, hint: "$2l+1$.", solution: "$m_l=-2,-1,0,1,2$: five values, i.e. $2l+1=5$.", difficulty: 1, tags: ["qm", "spin"] },
    { id: "qm-spin-d4", lesson: "qm-spin", type: "mc", prompt: "Unlike orbital angular momentum, electron spin quantum number $s$:", options: ["Can be any non-negative integer, varying by state", "Is fixed at $\\tfrac12$ for every electron", "Is always zero", "Depends on the electron's kinetic energy"], answer: 1, hint: "Spin is an intrinsic, fixed property.", solution: "Every electron has $s=\\tfrac12$, always — it's an intrinsic property, unlike orbital $l$ which varies with the state.", difficulty: 1, tags: ["qm", "spin"] },
    { id: "qm-spin-d5", lesson: "qm-spin", type: "mc", prompt: "Modeling the electron as a literal tiny spinning charged sphere to explain its magnetic moment fails because:", options: ["Electrons have no charge", "It would require surface speeds exceeding the speed of light", "Spin has no measurable magnetic effect", "It correctly predicts the observed magnetic moment"], answer: 1, hint: "A classical picture breaks down quantitatively.", solution: "Matching the observed magnetic moment to a classical spinning charged sphere of the electron's known size requires superluminal surface speeds — spin has no literal classical picture.", difficulty: 2, tags: ["qm", "spin"] },

    // qm-hydrogen
    { id: "qm-hydrogen-d1", lesson: "qm-hydrogen", type: "mc", prompt: "For the hydrogen atom, the orbital quantum number $l$ for principal quantum number $n=4$ can take values:", options: ["0 only", "0, 1", "0, 1, 2, 3", "1, 2, 3, 4"], answer: 2, hint: "$l=0,\\dots,n-1$.", solution: "$l=0,1,2,3$ for $n=4$ (i.e. $l=0,\\dots,n-1$).", difficulty: 1, tags: ["qm", "hydrogen"] },
    { id: "qm-hydrogen-d2", lesson: "qm-hydrogen", type: "numeric", prompt: "Find the energy (in eV) of the hydrogen $n=4$ level. ($E_n=-13.6\\text{ eV}/n^2$)", answer: -0.85, tolerance: 0.03, unit: "eV", hint: "$-13.6/16$.", solution: "$E_4 = -13.6/16 = -0.85\\text{ eV}$.", difficulty: 1, tags: ["qm", "hydrogen"] },
    { id: "qm-hydrogen-d3", lesson: "qm-hydrogen", type: "mc", prompt: "The full spatial+spin degeneracy of the hydrogen $n=3$ shell is:", options: ["3", "9", "18", "36"], answer: 2, hint: "$2n^2$.", solution: "$2n^2 = 2(9) = 18$.", difficulty: 2, tags: ["qm", "hydrogen"] },
    { id: "qm-hydrogen-d4", lesson: "qm-hydrogen", type: "numeric", prompt: "Find the wavelength (in nm) of the photon emitted in a hydrogen $n=3\\to n=1$ transition. ($hc\\approx1240\\text{ eV nm}$)", answer: 102.6, tolerance: 0.03, unit: "nm", hint: "$\\Delta E = 13.6(1-1/9)$.", solution: "$E_3=-13.6/9=-1.51\\text{ eV}$, $E_1=-13.6\\text{ eV}$; $\\Delta E=12.09\\text{ eV}$; $\\lambda=1240/12.09\\approx102.6\\text{ nm}$.", difficulty: 3, tags: ["qm", "hydrogen"] },
    { id: "qm-hydrogen-d5", lesson: "qm-hydrogen", type: "mc", prompt: "First-order perturbation theory gives the energy shift of a state due to a small perturbation $\\hat H'$ as:", options: ["$\\langle\\psi_0|\\hat H'|\\psi_0\\rangle$", "$\\hat H'$ itself", "The unperturbed energy $E_0$", "Zero, always"], answer: 0, hint: "Expectation value in the unperturbed state.", solution: "$E^{(1)}=\\langle\\psi_0|\\hat H'|\\psi_0\\rangle$, the expectation value of the perturbation in the unperturbed eigenstate.", difficulty: 2, tags: ["qm", "hydrogen", "perturbation-theory"] },
    { id: "qm-hydrogen-d6", lesson: "qm-hydrogen", type: "mc", prompt: "The Pauli exclusion principle states that:", options: ["No two bosons can occupy the same state", "No two electrons in an atom can share the same full set of quantum numbers $(n,l,m_l,m_s)$", "Electrons cannot exist in $s$-orbitals", "All electrons must have the same spin"], answer: 1, hint: "Applies to identical fermions.", solution: "Identical fermions (like electrons) cannot share an identical full set of quantum numbers — this forces electron shells to fill up sequentially.", difficulty: 1, tags: ["qm", "hydrogen", "pauli"] }
  ],

  test: [
    { id: "qm-t1", prompt: "A metal's work function is $\\phi=4.20\\text{ eV}$. Light of frequency $f=1.20\\times10^{15}\\text{ Hz}$ strikes it. The maximum kinetic energy of ejected electrons is closest to: ($h=6.626\\times10^{-34}\\text{ J s}$, $1\\text{ eV}=1.6\\times10^{-19}\\text{ J}$)", options: ["0.76 eV", "1.2 eV", "2.0 eV", "3.0 eV", "4.2 eV"], answer: 0, solution: "$hf = 6.626\\times10^{-34}\\times1.2\\times10^{15}=7.95\\times10^{-19}\\text{ J}=4.97\\text{ eV}$; $KE_{max}=4.97-4.20\\approx0.76\\text{ eV}$.", difficulty: 1, tags: ["qm", "photoelectric"], lesson: "qm-photoelectric" },
    { id: "qm-t2", prompt: "Which observation is NOT explained by the classical (continuous) wave theory of light in the photoelectric effect?", options: ["Light can be reflected and refracted", "The existence of a sharp threshold frequency, independent of intensity", "Light carries momentum", "Light exhibits diffraction", "Light travels at finite speed"], answer: 1, solution: "The sharp threshold frequency (with no dependence on intensity) cannot be explained by continuous energy delivery; it requires photon quantization.", difficulty: 1, tags: ["qm", "photoelectric"], lesson: "qm-photoelectric" },
    { id: "qm-t3", prompt: "Estimate the de Broglie wavelength of a proton ($m=1.67\\times10^{-27}\\text{ kg}$) moving at $1.0\\times10^5\\text{ m/s}$.", options: ["$4.0\\times10^{-15}\\text{ m}$", "$4.0\\times10^{-12}\\text{ m}$", "$4.0\\times10^{-9}\\text{ m}$", "$4.0\\times10^{-6}\\text{ m}$", "$4.0\\times10^{-3}\\text{ m}$"], answer: 1, solution: "$p=mv=1.67\\times10^{-22}\\text{ kg m/s}$; $\\lambda=h/p=6.626\\times10^{-34}/1.67\\times10^{-22}\\approx4.0\\times10^{-12}\\text{ m}$.", difficulty: 1, tags: ["qm", "de-broglie"], lesson: "qm-de-broglie" },
    { id: "qm-t4", prompt: "Which statement about the wavefunction $\\psi$ is correct?", options: ["$\\psi$ itself is always a measurable probability", "$|\\psi|^2$ is a probability density, and $\\psi$ can be complex to allow interference", "$\\psi$ must always be real and positive", "$\\psi$ has no physical role beyond bookkeeping", "$\\psi$ is only defined for free particles"], answer: 1, solution: "Born rule: $P=|\\psi|^2$; $\\psi$ is generally complex, which is required for genuine interference (cancellation).", difficulty: 2, tags: ["qm", "wavefunction"], lesson: "qm-wavefunction" },
    { id: "qm-t5", prompt: "In a double-slit experiment with electrons, measuring which slit each electron passes through causes the interference pattern to disappear because:", options: ["The measurement destroys the electrons", "The probabilities now add directly ($|\\psi_1|^2+|\\psi_2|^2$) instead of the amplitudes interfering before squaring", "Electrons become classical particles permanently", "The slits physically close", "The electron beam intensity drops to zero"], answer: 1, solution: "Which-path information removes the coherent superposition of amplitudes, eliminating the interference cross term.", difficulty: 2, tags: ["qm", "wavefunction"], lesson: "qm-wavefunction" },
    { id: "qm-t6", prompt: "The Schrödinger equation for a free particle is built by requiring that a plane-wave solution reproduce which energy-momentum relation?", options: ["$E=pc$", "$E=mc^2$", "$E=p^2/2m$", "$E=\\hbar\\omega^2$", "$E=hf^2$"], answer: 2, solution: "The nonrelativistic kinetic energy relation $E=p^2/2m$ is exactly what the free-particle Schrödinger equation reproduces for a plane wave.", difficulty: 2, tags: ["qm", "schrodinger-equation"], lesson: "qm-schrodinger" },
    { id: "qm-t7", prompt: "Why must the Schrödinger equation be first-order in time, unlike the classical wave equation (second-order in time)?", options: ["To conserve momentum", "Because the correspondence $E\\to i\\hbar\\partial/\\partial t$ applied once to the linear-in-$E$ energy relation gives a first-time-derivative equation", "Because $\\psi$ must be real-valued", "There is no requirement; both orders work equally well", "Because position and momentum must commute"], answer: 1, solution: "Energy appears linearly (to the first power) in $E=p^2/2m+V$, so the corresponding operator equation is first-order in the time derivative.", difficulty: 3, tags: ["qm", "schrodinger-equation"], lesson: "qm-schrodinger" },
    { id: "qm-t8", prompt: "An electron is confined to an infinite square well of width $L$. If $L$ is halved, the ground-state energy:", options: ["Halves", "Doubles", "Quadruples", "Is quartered", "Stays the same"], answer: 2, solution: "$E_1\\propto1/L^2$; halving $L$ quadruples $E_1$.", difficulty: 1, tags: ["qm", "infinite-well"], lesson: "qm-infinite-well" },
    { id: "qm-t9", prompt: "For a particle in an infinite square well, the energy difference between the $n=2$ and $n=1$ levels, compared to the difference between $n=3$ and $n=2$, is:", options: ["Equal", "Smaller", "Larger", "Zero", "Cannot be determined"], answer: 1, solution: "$E_2-E_1=3E_1$ while $E_3-E_2=5E_1$ (since $E_n=n^2E_1$): spacing grows with $n$, so the $n=2\\to1$ gap is smaller than the $n=3\\to2$ gap.", difficulty: 3, tags: ["qm", "infinite-well"], lesson: "qm-infinite-well" },
    { id: "qm-t10", prompt: "A particle tunnels through a barrier of width $L$ with $E<V_0$. If the barrier width is doubled (all else fixed), the transmission probability $T\\sim e^{-2\\kappa L}$:", options: ["Doubles", "Is unaffected", "Is squared (drops dramatically)", "Increases by a factor of $\\sqrt2$", "Becomes exactly zero"], answer: 2, solution: "$T(2L) = e^{-2\\kappa(2L)} = \\left(e^{-2\\kappa L}\\right)^2 = T(L)^2$ — since $T(L)<1$, squaring it makes it dramatically smaller.", difficulty: 2, tags: ["qm", "tunneling"], lesson: "qm-tunneling" },
    { id: "qm-t11", prompt: "Which phenomenon is best explained by quantum tunneling rather than classical mechanics?", options: ["Rainbow formation", "Alpha decay of nuclei with energy below the classical barrier height", "Blackbody radiation spectrum", "The photoelectric effect threshold", "The Doppler shift of starlight"], answer: 1, solution: "Alpha particles escape nuclei despite having kinetic energy below the classical barrier, a direct signature of tunneling.", difficulty: 1, tags: ["qm", "tunneling"], lesson: "qm-tunneling" },
    { id: "qm-t12", prompt: "The energy levels of a quantum harmonic oscillator with classical frequency $\\omega$ are spaced by:", options: ["$\\hbar\\omega/2$", "$\\hbar\\omega$", "$2\\hbar\\omega$", "$\\hbar\\omega^2$", "Spacing that grows with $n$"], answer: 1, solution: "$E_{n+1}-E_n = \\hbar\\omega$, constant for all $n$.", difficulty: 2, tags: ["qm", "harmonic-oscillator"], lesson: "qm-harmonic-oscillator" },
    { id: "qm-t13", prompt: "A diatomic molecule modeled as a harmonic oscillator has zero-point energy $0.10\\text{ eV}$. Its classical vibration frequency $\\omega$ is closest to: ($\\hbar=1.055\\times10^{-34}\\text{ J s}$, $1\\text{ eV}=1.6\\times10^{-19}\\text{ J}$)", options: ["$1.5\\times10^{13}\\text{ rad/s}$", "$3.0\\times10^{14}\\text{ rad/s}$", "$1.5\\times10^{15}\\text{ rad/s}$", "$3.0\\times10^{15}\\text{ rad/s}$", "$1.5\\times10^{17}\\text{ rad/s}$"], answer: 1, solution: "$E_0=\\tfrac12\\hbar\\omega \\Rightarrow \\omega=2E_0/\\hbar = 2(0.10\\times1.6\\times10^{-19})/1.055\\times10^{-34}\\approx3.03\\times10^{14}\\text{ rad/s}$.", difficulty: 2, tags: ["qm", "harmonic-oscillator"], lesson: "qm-harmonic-oscillator" },
    { id: "qm-t14", prompt: "A particle's position is measured with uncertainty $\\Delta x=2.0\\times10^{-10}\\text{ m}$. The minimum possible uncertainty in its momentum is closest to:", options: ["$2.6\\times10^{-29}\\text{ kg m/s}$", "$2.6\\times10^{-25}\\text{ kg m/s}$", "$5.3\\times10^{-25}\\text{ kg m/s}$", "$1.1\\times10^{-24}\\text{ kg m/s}$", "$5.3\\times10^{-20}\\text{ kg m/s}$"], answer: 1, solution: "$\\Delta p \\ge \\hbar/(2\\Delta x) = 1.055\\times10^{-34}/(4.0\\times10^{-10}) \\approx 2.6\\times10^{-25}\\text{ kg m/s}$.", difficulty: 2, tags: ["qm", "uncertainty"], lesson: "qm-uncertainty" },
    { id: "qm-t15", prompt: "The Heisenberg uncertainty principle $\\Delta x\\Delta p\\ge\\hbar/2$ follows directly from:", options: ["The Pauli exclusion principle", "The non-vanishing commutator $[\\hat x,\\hat p]=i\\hbar$", "Energy conservation", "The normalization condition on $\\psi$", "The Born rule alone"], answer: 1, solution: "The general bound $\\Delta A\\Delta B\\ge\\tfrac12|\\langle[\\hat A,\\hat B]\\rangle|$ applied to $[\\hat x,\\hat p]=i\\hbar$ gives $\\Delta x\\Delta p\\ge\\hbar/2$.", difficulty: 1, tags: ["qm", "uncertainty"], lesson: "qm-uncertainty" },
    { id: "qm-t16", prompt: "The Stern–Gerlach experiment demonstrated the need for electron spin because:", options: ["Orbital angular momentum alone predicts a continuous smear, and observing any discreteness is unexpected", "For an $l=0$ valence electron, orbital angular momentum predicts one spot, but two are observed", "The experiment measured electron charge, not angular momentum", "Silver atoms have no magnetic moment classically", "The magnetic field was too weak to deflect the atoms"], answer: 1, solution: "With $l=0$ (zero orbital angular momentum), only spin's two-valued $m_s=\\pm\\tfrac12$ can account for the observed two-spot splitting.", difficulty: 3, tags: ["qm", "spin"], lesson: "qm-spin" },
    { id: "qm-t17", prompt: "The magnitude of the orbital angular momentum for a state with $l=3$ is:", options: ["$3\\hbar$", "$\\sqrt{3}\\hbar$", "$\\sqrt{6}\\hbar$", "$\\sqrt{12}\\hbar$", "$9\\hbar$"], answer: 3, solution: "$|\\vec L|=\\hbar\\sqrt{l(l+1)}=\\hbar\\sqrt{3\\cdot4}=\\hbar\\sqrt{12}$.", difficulty: 2, tags: ["qm", "spin"], lesson: "qm-spin" },
    { id: "qm-t18", prompt: "Which correctly lists the allowed values of $m_l$ for a state with $l=1$?", options: ["$0$", "$-1, 0, 1$", "$-1, 1$", "$0, 1$", "$-2,-1,0,1,2$"], answer: 1, solution: "$m_l = -l,\\dots,l$ in integer steps, so for $l=1$: $-1,0,1$.", difficulty: 1, tags: ["qm", "spin"], lesson: "qm-spin" },
    { id: "qm-t19", prompt: "Which of the following pairs of hydrogen quantum numbers is NOT allowed?", options: ["$n=2, l=1, m_l=0$", "$n=3, l=2, m_l=-2$", "$n=1, l=0, m_l=0$", "$n=2, l=2, m_l=1$", "$n=4, l=3, m_l=3$"], answer: 3, solution: "$l$ must satisfy $l\\le n-1$; for $n=2$, the maximum allowed $l$ is 1, so $l=2$ is forbidden.", difficulty: 2, tags: ["qm", "hydrogen"], lesson: "qm-hydrogen" },
    { id: "qm-t20", prompt: "The energy of the hydrogen atom's $n$-th level depends on:", options: ["$n$ and $l$ both", "$n$ only", "$l$ only", "$m_l$ only", "$n$, $l$, and $m_l$ equally"], answer: 1, solution: "In the non-relativistic hydrogen Schrödinger solution, $E_n=-13.6\\text{ eV}/n^2$ depends only on $n$, producing the large $n^2$-fold degeneracy in $l$ and $m_l$.", difficulty: 2, tags: ["qm", "hydrogen"], lesson: "qm-hydrogen" },
    { id: "qm-t21", prompt: "A perturbation $\\hat H'$ is added to the hydrogen Hamiltonian. To first order, the energy shift of the ground state is computed as:", options: ["The largest eigenvalue of $\\hat H'$", "$\\langle\\psi_0|\\hat H'|\\psi_0\\rangle$, using the unperturbed ground state", "Always zero for any perturbation", "$\\hat H'$ evaluated at $r=0$", "The full re-solved eigenvalue of $\\hat H+\\hat H'$"], answer: 1, solution: "First-order perturbation theory: $E^{(1)}=\\langle\\psi_0|\\hat H'|\\psi_0\\rangle$, the expectation value of the perturbing term in the unperturbed eigenstate.", difficulty: 3, tags: ["qm", "hydrogen", "perturbation-theory"], lesson: "qm-hydrogen" },
    { id: "qm-t22", prompt: "The Pauli exclusion principle is the reason that:", options: ["All electrons in an atom occupy the $n=1$ shell", "Electrons fill successive shells rather than collapsing into the lowest energy state", "Protons and neutrons have the same mass", "Photons can occupy the same state in unlimited numbers", "Electrons have no intrinsic spin"], answer: 1, solution: "Because no two electrons can share the full set $(n,l,m_l,m_s)$, electrons must fill successive shells, building up the periodic table's structure.", difficulty: 2, tags: ["qm", "hydrogen", "pauli"], lesson: "qm-hydrogen" }
  ]
});
