window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "relativity",
  title: "Special Relativity",
  order: 7,
  greWeight: 0.06,
  prereqs: ["mechanics", "em"],
  blurb: "Rebuilds space and time from the one experimental fact Newton's mechanics can't absorb: the speed of light is the same for every observer.",

  lessons: [
    // ---------------------------------------------------------------
    {
      id: "relativity-invariant-c",
      title: "The Problem Maxwell Created",
      minutes: 11,
      discovery: "Every attempt to preserve ordinary (Galilean) velocity addition for light fails experimentally, so the speed of light must instead be postulated the same in every inertial frame — the more 'obvious' assumption (Galilean kinematics) has to give way, not Maxwell's equations.",
      sections: [
        { kind: "problem", md: `Maxwell's equations predict electromagnetic waves traveling at a fixed speed $c=1/\\sqrt{\\mu_0\\epsilon_0}$, with no reference to any observer's velocity anywhere in the equations. But ordinary (Galilean) mechanics says velocities simply add: a ball thrown at speed $u$ from a truck moving at $v$ has speed $u+v$ to a stationary observer. Applied to light, this says a light beam should appear to travel at $c+v$ to someone moving toward the source, and $c-v$ moving away. Which is right, and how would you check?` },
        { kind: "candidates", md: `**A. Light travels through a medium (the "luminiferous ether") at rest in some absolute frame, with speed $c$ fixed only relative to that ether — ordinary Galilean addition holds relative to the ether, just as sound's speed is fixed relative to still air.**

**B. Light is like a stream of bullets fired from its source: its speed depends on the source's velocity, $c'=c+v_{source}$ (an "emission theory").**` },
        { kind: "failures", md: `**A predicts a detectable "ether wind."** As Earth orbits the Sun, it should move through the stationary ether at up to $30\\text{ km/s}$, so light should measurably travel faster or slower depending on direction relative to Earth's motion. The Michelson–Morley experiment (1887) looked for exactly this effect with an interferometer sensitive to tiny speed differences — and found nothing, to high precision, in every direction and every season. No ether wind exists.

**B predicts effects never seen in binary star systems.** If light's speed depended on the emitting source's velocity, light emitted by a star approaching us (moving fast in its orbit) would catch up with light emitted earlier when it was receding, garbling or duplicating the star's observed light curve (the "de Sitter" test). No such distortion is observed in any binary system, no matter how eccentric or fast the orbit — light from a moving source always arrives at speed $c$.` },
        { kind: "discovery", md: `Both attempts try to preserve ordinary Galilean velocity addition by attaching light's fixed speed to *something* (an ether frame, or the source) — and both are ruled out experimentally. The only option left is the radical one: $c$ really is the same in every inertial frame, period, with no medium and no dependence on the source's motion. Einstein elevated this directly to a postulate, alongside the principle of relativity (the laws of physics take the same form in every inertial frame — nothing new, just extended to include Maxwell's equations, not only mechanics).` },
        { kind: "formal", md: `**Postulates of special relativity:** (1) The laws of physics are the same in all inertial reference frames. (2) The speed of light in vacuum, $c$, is the same in all inertial reference frames, independent of the motion of the source or observer. Postulate 2 is the one that breaks Galilean kinematics — if $c$ is truly frame-independent, ordinary $x'=x-vt,\\ t'=t$ transformations (which would make $c$ frame-dependent) cannot be exactly correct and must be replaced (worked out in the next lesson).` },
        { kind: "apply", md: `Applied directly to the original problem: chase a light beam at speed $v$ close to $c$. Galilean addition would say you should see a beam moving at only $c-v$, approaching zero as $v\\to c$ — meaning you'd expect to eventually see a nearly "frozen," non-propagating electromagnetic wave (a static field pattern). But Maxwell's equations have no solution describing a static field oscillating in space with no propagation — such a field configuration isn't even physically consistent with Maxwell's equations at rest. The two postulates avoid this contradiction entirely: no matter how fast you chase it, light still recedes from you at exactly $c$.` },
        { kind: "transfer", md: `This is a recurring pattern in physics: when two well-tested frameworks conflict (here, Galilean kinematics vs. Maxwell's equations), the resolution sometimes requires abandoning the framework that *feels* more fundamental or intuitive (everyday kinematics) rather than the newer, more mathematically constrained one (field theory). The same move — trusting a precise, constraining theory over intuitive kinematics — recurs when quantum mechanics forces abandonment of classical trajectories.` }
      ],
      checkpoints: [
        { q: "What did the null result of the Michelson–Morley experiment rule out?", options: ["The existence of light itself", "A stationary ether medium against which Earth's motion could be detected via a directional variation in light's speed", "Maxwell's equations", "The existence of electromagnetic waves"], answer: 1, explain: "No variation in light's speed with direction or season was detected, ruling out a detectable ether wind and hence an absolute rest frame for light's propagation." },
        { q: "Einstein's second postulate of special relativity states that:", options: ["Energy is always conserved", "The speed of light in vacuum is the same in every inertial frame, independent of source or observer motion", "All motion is relative to the ether", "Light behaves only as a particle"], answer: 1, explain: "This is the postulate that directly replaces both the ether-based and emission-theory attempts to explain light's constant measured speed." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "relativity-time-length",
      title: "Time Dilation and Length Contraction from the Light Clock",
      minutes: 12,
      discovery: "If $c$ is truly the same for every inertial observer, a moving clock must genuinely tick slower ($\\Delta t=\\gamma\\Delta\\tau$) and a moving ruler must genuinely measure shorter ($L=L_0/\\gamma$) — not illusions of observation, but consequences of the light-clock geometry.",
      sections: [
        { kind: "problem", md: `Build a simple clock: a photon bounces vertically between two mirrors separated by distance $L$, ticking once per round trip. Mount this "light clock" on a spaceship moving at speed $v$ relative to the ground. Since $c$ is the same for every observer (the previous lesson's postulate), does the ground observer measure the same tick rate as an astronaut riding with the clock?` },
        { kind: "candidates", md: `**A. Tick rate is unaffected by motion** — the light clock's period only involves $L$ and $c$, quantities that don't reference $v$ at all, so both observers should agree on the ticking rate.

**B. The clock only *appears* to run slow from the ground due to the extra time it takes light signals to reach a receding/approaching observer — an observational illusion, not a real effect on the clock itself.**` },
        { kind: "failures", md: `**A fails once you draw the geometry.** From the ground frame, the spaceship (and its mirrors) also moves sideways during each photon bounce, so the photon traces a longer, diagonal zigzag path rather than a simple vertical up-down path. Since $c$ must still be exactly $c$ for the ground observer (postulate 2, not $c+v$ or anything else), covering that longer diagonal path at the same speed $c$ necessarily takes more time — the tick period cannot be the same for both observers.

**B fails against a clean experimental test.** Subtracting out ordinary light-travel-time delay (the effect any signal has when its source is moving away, present even in pre-relativistic physics) still leaves a genuine residual effect: atmospheric muons, created by cosmic rays high in the atmosphere and moving toward the ground at nearly $c$, are measured reaching the ground in far greater numbers than their intrinsic (rest-frame) lifetime should allow if it applied unchanged in the lab frame — a real, physical effect on the decaying particle's clock, not an artifact of when the light carrying the information arrives.` },
        { kind: "discovery", md: `Time dilation is a genuine geometric consequence of a fixed light speed: the ground observer sees the photon travel a longer diagonal distance per tick than the ship observer sees (a simple vertical bounce), and since both must agree the photon moves at exactly $c$, the ground observer necessarily measures more elapsed time per tick. By symmetry (apply the identical argument to a light clock oriented *along* the direction of motion instead), lengths measured along the direction of relative motion must correspondingly contract.` },
        { kind: "formal", md: `Let $\\tau$ be the tick period measured in the clock's own rest frame ("proper time"), and $L$ the mirror separation. In the ship frame, $\\tau = 2L/c$. In the ground frame, using the Pythagorean theorem on the diagonal photon path (base $\\tfrac12v\\Delta t$, height $L$, hypotenuse $\\tfrac12c\\Delta t$):
$$\\Delta t = \\gamma\\tau, \\qquad \\gamma \\equiv \\frac{1}{\\sqrt{1-v^2/c^2}} \\ge 1$$
The identical light-clock argument, run for a clock oriented along the direction of motion, gives **length contraction**: a rod with rest-frame ("proper") length $L_0$ has length $L=L_0/\\gamma$ as measured by an observer relative to whom it moves at speed $v$. Both effects vanish as $v\\to0$ ($\\gamma\\to1$) and blow up as $v\\to c$ ($\\gamma\\to\\infty$).` },
        { kind: "apply", md: `A muon has proper lifetime $\\tau_0=2.2\\ \\mu\\text{s}$. Moving at $v=0.995c$, $\\gamma = 1/\\sqrt{1-0.995^2}\\approx10.0$. In the lab (ground) frame its lifetime is dilated to $\\Delta t=\\gamma\\tau_0\\approx22\\ \\mu\\text{s}$, during which it travels $v\\Delta t\\approx0.995c\\times22\\ \\mu\\text{s}\\approx6.6\\text{ km}$ — enough to cross the atmosphere and be detected at sea level in the observed numbers, versus only about $660\\text{ m}$ predicted using the (wrong) unmodified proper lifetime.` },
        { kind: "transfer", md: `Proper time $\\tau$ (elapsed time in an object's own rest frame) is an *invariant* — every observer agrees on it, even though they disagree on the ordinary elapsed time $\\Delta t$ they each measure. This "the quantity measured in the object's own frame is the one everyone can agree on" theme reappears immediately in the next lesson as the invariant spacetime interval, and again with proper length and rest mass.` }
      ],
      checkpoints: [
        { q: "Why does a moving light clock tick slower as measured by a stationary observer?", options: ["Light actually slows down when the clock moves", "The stationary observer sees the photon trace a longer diagonal path, and since $c$ is fixed, a longer path means more elapsed time per tick", "The clock's mirrors physically move closer together", "It's purely an artifact of signal travel time, not a real effect"], answer: 1, explain: "The photon's path length increases (diagonal vs. vertical) in the frame where the clock is moving, and since the speed is fixed at $c$ in every frame, that longer path takes measurably more time." },
        { q: "The muon lifetime experiment is significant because it shows:", options: ["Muons decay faster when moving", "Time dilation is a real physical effect on decay processes, not merely an observational illusion from signal delay", "Muons violate relativity", "Time dilation only applies to light clocks specifically"], answer: 1, explain: "The observed survival rate of fast muons through the atmosphere matches the dilated lifetime, confirming a genuine physical effect on the decaying particle's internal clock." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "relativity-lorentz",
      title: "The Lorentz Transformation and Relativity of Simultaneity",
      minutes: 12,
      discovery: "Only a transformation that mixes space and time together, $x'=\\gamma(x-vt),\\ t'=\\gamma(t-vx/c^2)$, keeps a light pulse moving at $c$ in both frames — and because $t'$ depends on $x$, events simultaneous in one frame generally are not simultaneous in another.",
      sections: [
        { kind: "problem", md: `Time dilation and length contraction tell you how single durations and lengths transform, but a full theory needs a coordinate transformation relating an event's $(x,t)$ in one frame to $(x',t')$ in another — replacing the Galilean $x'=x-vt,\\ t'=t$ — consistent with $c$ being the same in both frames for *any* light pulse, not just the specific light-clock geometry already analyzed.` },
        { kind: "candidates", md: `**A. Patch only the time equation:** keep $x'=x-vt$ (unchanged) but scale time by $\\gamma$: $t'=t/\\gamma$.

**B. Allow both $x'$ and $t'$ to mix $x$ and $t$ together:** try $x'=\\gamma(x-vt)$, $t'=\\gamma(t-vx/c^2)$, and test it directly against a light pulse.` },
        { kind: "failures", md: `**A fails a direct light-pulse check.** Consider a light pulse emitted from the common origin at $t=0$: in the unprimed frame, $x=ct$. Plugging in candidate A: $x'=ct-vt=(c-v)t$ and $t'=t/\\gamma$, giving $x'/t' = (c-v)\\gamma \\ne c$ in general — the transformed pulse does *not* move at $c$ in the primed frame, directly violating the postulate this transformation was supposed to satisfy.

**B must be checked the same way before being trusted.** Substitute $x=ct$: $x'=\\gamma(ct-vt)=\\gamma t(c-v)$ and $t'=\\gamma(t-vct/c^2)=\\gamma t(1-v/c)$. Then $x'/t' = \\dfrac{\\gamma t(c-v)}{\\gamma t(1-v/c)} = \\dfrac{c-v}{1-v/c} = c$ — it works. (The same check for a pulse moving in the $-x$ direction, $x=-ct$, also gives $x'/t'=-c$, confirming the transformation is consistent both ways.)` },
        { kind: "discovery", md: `Only the mixed transformation preserves $c$ as invariant for every light pulse, and it must therefore be the correct replacement for the Galilean transformation. Crucially, $t'$ depends on $x$, not just $t$ — meaning two events at different positions $x$ that share the same time $t$ in one frame (simultaneous there) generally have *different* $t'$ in another frame. Simultaneity is not absolute; it depends on the observer's frame of motion.` },
        { kind: "formal", md: `**Lorentz transformation** (motion along $x$ at relative speed $v$):
$$x' = \\gamma(x-vt), \\qquad y'=y,\\ z'=z, \\qquad t' = \\gamma\\left(t - \\frac{vx}{c^2}\\right)$$
with inverse obtained by swapping primes and flipping the sign of $v$. Taking $v\\ll c$ recovers $\\gamma\\to1$ and the Galilean transformation as the low-speed limit — special relativity doesn't discard Newtonian kinematics, it generalizes it.` },
        { kind: "apply", md: `**Classic thought experiment:** lightning strikes both ends of a moving train simultaneously *in the ground frame* (same $t$, different $x$). A passenger at the train's midpoint, per the ground frame's simultaneity, should see both flashes arrive at once — but computing $t'$ for each strike event using the Lorentz transformation shows the two strikes have *different* $t'$ in the train's own frame: the strike toward which the train moves has smaller $t'$ (happens "first" for the passenger), so the passenger reports one strike happening before the other, even though the ground observer insists they were simultaneous. Both observers are correct in their own frame — simultaneity is frame-dependent, not a universal fact.` },
        { kind: "transfer", md: `The key structural change from Galilean to Lorentz transformations is that time is no longer a universal parameter shared by all observers — it's mixed with space just as thoroughly as $x,y,z$ mix with each other under an ordinary rotation. This is the first hint (fully developed two lessons later) that space and time are better treated as a single four-dimensional entity, spacetime, rather than separate 3D space plus a universal clock.` }
      ],
      checkpoints: [
        { q: "Why does the naive patch $x'=x-vt,\\ t'=t/\\gamma$ fail as a relativistic transformation?", options: ["It doesn't reduce to the Galilean transformation at low speed", "A light pulse $x=ct$ transformed this way does not come out moving at speed $c$ in the primed frame", "It doesn't involve $\\gamma$ at all", "It predicts no time dilation"], answer: 1, explain: "Direct substitution shows $x'/t'=(c-v)\\gamma\\ne c$ under this patch — it violates the very postulate (invariant $c$) it needs to satisfy." },
        { q: "Two events are simultaneous in the ground frame but occur at different positions. In a frame moving relative to the ground, these two events:", options: ["Are always still simultaneous", "Are generally not simultaneous, because $t'$ depends on both $t$ and $x$ in the Lorentz transformation", "Cannot both be observed", "Only one of them actually occurred"], answer: 1, explain: "Since $t'=\\gamma(t-vx/c^2)$, equal $t$ with different $x$ generally gives different $t'$ — this is the relativity of simultaneity." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "relativity-velocity-interval",
      title: "Velocity Addition and the Invariant Interval",
      minutes: 12,
      discovery: "Differentiating the Lorentz transformation gives a velocity-addition formula, $u'=(u-v)/(1-uv/c^2)$, that never lets combined speeds reach or exceed $c$ — and the same transformation leaves one particular combination of $\\Delta x,\\Delta t$, the spacetime interval, invariant for every observer.",
      sections: [
        { kind: "problem", md: `Given the Lorentz transformation, what replaces ordinary velocity addition? If two spaceships each move toward each other at $0.9c$ relative to a common observer, Galilean addition would say their relative closing speed is $1.8c$ — but nothing is supposed to exceed $c$ in relativity. What actually happens?` },
        { kind: "candidates", md: `**A. Keep ordinary Galilean addition, $u'=u-v$**, applied straightforwardly to relative velocities.

**B. Guess an ad hoc "capped" formula** that saturates as speeds approach $c$, patched in by hand to avoid superluminal results, without deriving it from the Lorentz transformation.` },
        { kind: "failures", md: `**A fails outright.** Two objects each moving at $0.9c$ toward a common observer, from opposite directions, would have relative closing speed $0.9c+0.9c=1.8c$ under Galilean addition — directly exceeding $c$, which the postulates forbid for any physical signal or object.

**B fails as untrustworthy.** An arbitrary saturating formula might avoid the obvious problem for this one example, but with no derivation from the actual transformation, there's no guarantee it gives correct results for other velocity combinations, other angles, or matches any other relativistic prediction (like time dilation) self-consistently. It needs to be derived, not patched.` },
        { kind: "discovery", md: `Differentiating the Lorentz transformation directly (rather than guessing) produces the correct relativistic velocity-addition rule. Checking it against extreme cases confirms it never allows combined speeds to reach or exceed $c$ for any physical $u,v<c$ — the "speed limit" emerges automatically from the transformation itself, with no separate patch required.` },
        { kind: "formal", md: `**Velocity addition:** if an object moves at speed $u'$ in a frame $S'$, and $S'$ moves at speed $v$ relative to $S$ (both along the same line), the object's speed in $S$ is
$$u = \\frac{u'+v}{1+u'v/c^2}$$
As $u',v\\to c$, $u\\to c$ (never past it); for $u',v\\ll c$, this reduces to ordinary addition $u\\approx u'+v$. **Invariant interval:** although observers disagree on $\\Delta x$ and $\\Delta t$ separately, direct substitution of the Lorentz transformation shows every inertial observer agrees on the combination
$$\\Delta s^2 \\equiv c^2\\Delta t^2 - \\Delta x^2 - \\Delta y^2 - \\Delta z^2$$
This is the relativistic generalization of "distance" — the one geometric quantity that plays the role invariant length plays under ordinary rotations.` },
        { kind: "apply", md: `A rocket moves at $0.8c$ relative to the ground and fires a probe forward at $0.5c$ relative to the rocket. The probe's speed relative to the ground: $u=\\dfrac{0.5c+0.8c}{1+(0.5)(0.8)} = \\dfrac{1.3c}{1.4} \\approx 0.929c$ — less than $c$, unlike the naive Galilean sum of $1.3c$.` },
        { kind: "transfer", md: `Finding the quantity left unchanged by a transformation is a general strategy for identifying what's physically real versus what's merely a choice of coordinates — dot products are invariant under ordinary spatial rotations for exactly the same reason the spacetime interval is invariant under Lorentz "rotations" mixing space and time. This sets up the four-vector formalism (recognized at the end of this module) where $\\Delta s^2$ is literally the squared "length" of a four-vector separation.` }
      ],
      checkpoints: [
        { q: "Two particles each move at $0.6c$ toward a common observer from opposite directions. What is the speed of one particle as measured in the other particle's own rest frame?", options: ["$1.2c$", "$0.6c$", "$0.75c$", "$0.882c$"], answer: 3, explain: "Converting into the other particle's rest frame requires the relativistic velocity-addition formula: $u=(0.6c+0.6c)/(1+0.6\\times0.6)=1.2c/1.36\\approx0.882c$ — never reaching or exceeding $c$, unlike the naive Galilean sum of $1.2c$." },
        { q: "What quantity remains the same for every inertial observer, even though $\\Delta x$ and $\\Delta t$ individually differ between frames?", options: ["$\\Delta x$ alone", "$\\Delta t$ alone", "The spacetime interval $\\Delta s^2 = c^2\\Delta t^2-\\Delta x^2$", "The velocity of the object being observed"], answer: 2, explain: "Direct substitution of the Lorentz transformation shows $\\Delta s^2$ is invariant, even though $\\Delta x$ and $\\Delta t$ separately are not." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "relativity-momentum-energy",
      title: "Relativistic Momentum and Energy",
      minutes: 13,
      discovery: "Ordinary momentum $p=mv$ isn't conserved across different inertial frames once velocities transform relativistically, but $p=\\gamma mv$ is — and this same $\\gamma$ factor applied to energy produces $E=\\gamma mc^2$, whose $v=0$ limit is the famous $E=mc^2$.",
      sections: [
        { kind: "problem", md: `Classical momentum, $p=mv$, and kinetic energy, $\\tfrac12mv^2$, worked perfectly well for centuries. But conservation laws are only useful if they hold in *every* inertial frame — and velocities no longer add the simple (Galilean) way. Does momentum conservation, computed with the old formula $p=mv$, still hold once you switch to a boosted frame using the relativistic velocity-addition rule?` },
        { kind: "candidates", md: `**A. Keep $p=mv$ unchanged, and just use the relativistic velocity-addition formula whenever transforming velocities between frames.**

**B. The definition of momentum itself needs to change — try $p=\\gamma mv$ instead, and check whether conservation now survives a frame change.**` },
        { kind: "failures", md: `**A fails a direct check.** Take a simple elastic collision where total $mv$ is conserved in one frame using ordinary $p=mv$. Transform each particle's velocity into a different (boosted) frame using the correct relativistic velocity-addition rule, then recompute $\\sum mv$ in that new frame: it no longer balances. A quantity that's conserved in one frame but not another after a legitimate change of frame isn't a good conservation law — real conservation laws should hold in every inertial frame.

So B needs to actually be tested, not just guessed — but working through the same collision with $p=\\gamma mv$ (deferred to a full derivation beyond this lesson's scope) does restore frame-independent conservation, so it survives where A failed.` },
        { kind: "discovery", md: `Relativistic momentum $p=\\gamma mv$ (not $mv$) is exactly the definition that keeps momentum conservation valid in every inertial frame, consistent with the relativistic velocity-addition rule. Since $\\gamma\\to1$ for $v\\ll c$, this smoothly reduces to the familiar $p\\approx mv$ at everyday speeds — nothing about low-speed physics changes.` },
        { kind: "formal", md: `**Relativistic momentum:** $p=\\gamma m v$. **Relativistic total energy:** $E=\\gamma mc^2$, of which the $v=0$ piece is the **rest energy** $E_0=mc^2$. Combining the definitions of $E$ and $p$ algebraically (eliminating $v$ and $\\gamma$) gives the energy-momentum relation
$$E^2 = (pc)^2 + (mc^2)^2$$
**Kinetic energy** is defined as the energy *beyond* rest energy: $KE = E - mc^2 = (\\gamma-1)mc^2$. Taylor-expanding $\\gamma=(1-v^2/c^2)^{-1/2}\\approx1+\\tfrac12v^2/c^2$ for $v\\ll c$ recovers the familiar $KE\\approx\\tfrac12mv^2$ as the low-speed limit.` },
        { kind: "apply", md: `An electron ($mc^2=0.511\\text{ MeV}$) is accelerated to kinetic energy $KE=1\\text{ MeV}$. Total energy $E=mc^2+KE=1.511\\text{ MeV}$, so $\\gamma=E/mc^2\\approx2.96$. Its momentum follows from $E^2=(pc)^2+(mc^2)^2$: $(pc)^2=E^2-(mc^2)^2=1.511^2-0.511^2\\approx2.02\\text{ MeV}^2$, so $pc\\approx1.42\\text{ MeV}$, i.e. $p\\approx1.42\\text{ MeV}/c$.` },
        { kind: "transfer", md: `$E=mc^2$ isn't a separate, mysterious statement that "mass turns into energy" — it's simply the $v=0$, $p=0$ special case of the general relation $E^2=(pc)^2+(mc^2)^2$, which already describes everyday kinetic energy at low $v$ and *also* correctly describes strictly massless particles: setting $m=0$ gives $E=pc$ exactly, the relation used for the photon throughout the atomic/nuclear module (X-ray cutoff, Compton scattering) — a single formula spanning both massive particles at rest and massless particles that can never be at rest.` }
      ],
      checkpoints: [
        { q: "Why does relativistic momentum have to be redefined as $p=\\gamma mv$ rather than $p=mv$?", options: ["To make momentum units consistent with energy units", "Because ordinary $p=mv$, combined with the relativistic velocity-addition rule, fails to conserve momentum consistently across different inertial frames", "Because $mv$ is always zero at relativistic speeds", "Purely as a notational convention with no physical necessity"], answer: 1, explain: "A conservation law should hold in every frame; using $p=mv$ together with relativistic velocity addition breaks that, while $p=\\gamma mv$ restores frame-independent conservation." },
        { q: "The formula $E=mc^2$ is best understood as:", options: ["A completely separate law unrelated to momentum", "The special case $p=0$ of the general relation $E^2=(pc)^2+(mc^2)^2$", "Valid only for photons", "An approximation only valid at low speed"], answer: 1, explain: "Setting $p=0$ (object at rest) in $E^2=(pc)^2+(mc^2)^2$ immediately gives $E=mc^2$ — the rest-energy special case of the fully general relation." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "relativity-doppler-fourvector",
      title: "Relativistic Doppler Shift and Four-Vectors",
      minutes: 11,
      discovery: "The classical (sound) Doppler formula secretly assumes a medium and gives different answers depending on whether the 'source' or 'observer' is said to be moving — but light has no medium, so relativity demands a single formula depending only on relative velocity, obtained by combining the classical light-travel-time effect with genuine time dilation.",
      sections: [
        { kind: "problem", md: `Sound's Doppler formula treats a moving source and a moving observer differently, because both are defined relative to the medium (air) that sound travels through. Light has no medium (a lesson-1 result). What replaces the Doppler formula for light, and does the classical asymmetry between "source moving" and "observer moving" survive?` },
        { kind: "candidates", md: `**A. Reuse the classical (sound-style) Doppler formula, just substituting $c$ for the medium's wave speed.**

**B. Derive the shift purely from the relative velocity between source and observer, combining ordinary light-travel-time geometry with genuine time dilation of the moving clock.**` },
        { kind: "failures", md: `**A fails on a symmetry the postulates require.** The classical formula gives different numerical answers depending on whether it's the source or the observer that's said to be "moving" (through the medium) — but relativity's first postulate forbids any physical distinction between "source moving, observer at rest" and "observer moving, source at rest," since there's no preferred rest frame to break the symmetry. A formula built assuming a medium at rest can't respect this.

**B must still be checked for internal consistency** — does a purely relative-velocity-based derivation actually reduce to something sensible at low speed, and does it correctly predict a shift even in the case with *no* line-of-sight approach or recession at all (motion exactly perpendicular)?` },
        { kind: "discovery", md: `Deriving the shift entirely from relative velocity (no preferred medium) does work self-consistently, and predicts something with no classical (sound) analog at all: even when a source moves exactly perpendicular to the line of sight at closest approach — no classical light-travel-time effect in that instant — light is still redshifted, purely from time dilation of the moving source's internal "clock" (its oscillation frequency). This **transverse Doppler effect** is a distinctively relativistic confirmation of time dilation itself, with nothing analogous in classical wave Doppler shifts.` },
        { kind: "formal", md: `**Longitudinal relativistic Doppler** (source receding directly along the line of sight at relative speed $v=\\beta c$):
$$f_{obs} = f_{source}\\sqrt{\\frac{1-\\beta}{1+\\beta}}$$
(approaching: swap the sign of $\\beta$). **Transverse Doppler** (perpendicular motion at closest approach): $f_{obs}=f_{source}/\\gamma$ — a pure redshift from time dilation alone. **Four-vectors (recognition level):** group $(ct,x,y,z)$ into a single four-vector that transforms under the Lorentz transformation exactly as $(E/c,p_x,p_y,p_z)$ does; the Minkowski "dot product" of any four-vector with itself (generalizing $\\Delta s^2$ from the previous lesson) is frame-invariant, e.g. $E^2-(pc)^2=(mc^2)^2$ is exactly this invariant for the energy-momentum four-vector.` },
        { kind: "apply", md: `A galaxy recedes directly along the line of sight at $\\beta=0.2$. The observed-to-emitted frequency ratio is $\\sqrt{(1-0.2)/(1+0.2)}=\\sqrt{0.8/1.2}=\\sqrt{2/3}\\approx0.816$ — light is redshifted to about $81.6\\%$ of its emitted frequency (equivalently, wavelength stretched by a factor $1/0.816\\approx1.225$).` },
        { kind: "transfer", md: `The four-vector idea is the same "find the frame-invariant combination" theme threaded through this entire module (proper time, the spacetime interval, and now the energy-momentum relation are all examples). It's worth explicitly distinguishing this *relativistic Doppler shift* (motion through space, at fixed spatial distance rules) from the *cosmological redshift* used for very distant galaxies (Hubble's law, covered later in this curriculum), which arises instead from the expansion of space itself — a different physical mechanism that happens to produce a formally similar-looking redshift.` }
      ],
      checkpoints: [
        { q: "Why can't the classical (sound-wave) Doppler formula be directly reused for light?", options: ["Light travels slower than sound", "The classical formula distinguishes 'source moving' from 'observer moving' relative to a medium, but light has no medium and no such distinction is physically meaningful", "Sound has no Doppler effect", "Light frequency never changes"], answer: 1, explain: "Relativity forbids any physical asymmetry between the source and observer's relative motion, since there's no preferred medium/frame — the classical formula's source/observer distinction has no counterpart for light." },
        { q: "The transverse Doppler effect is significant because it:", options: ["Has a direct classical (sound) analog", "Arises purely from time dilation, with no classical light-travel-time contribution, since there is no line-of-sight approach or recession at closest approach", "Only occurs for sound waves", "Predicts no frequency shift at all"], answer: 1, explain: "At the instant of closest approach (motion exactly perpendicular to line of sight), the only remaining effect is genuine time dilation of the source's own clock — a purely relativistic redshift with no classical counterpart." }
      ]
    }
  ],

  drills: [
    // relativity-invariant-c
    { id: "relativity-invariant-c-d1", lesson: "relativity-invariant-c", type: "mc", prompt: "The Michelson–Morley experiment's null result was significant because it:", options: ["Confirmed the existence of the ether", "Found no variation in light's speed with direction, ruling out a detectable ether wind", "Proved Maxwell's equations wrong", "Measured the speed of sound"], answer: 1, hint: "It looked for an effect and didn't find it.", solution: "No directional or seasonal variation in light's measured speed was ever found, ruling out an ether-based explanation for light's constant speed.", difficulty: 1, tags: ["relativity", "postulates"] },
    { id: "relativity-invariant-c-d2", lesson: "relativity-invariant-c", type: "mc", prompt: "An 'emission theory' of light, where speed depends on the source's velocity, is ruled out by:", options: ["The photoelectric effect", "Observations of binary star systems showing no light-curve distortion regardless of orbital speed", "The existence of radio waves", "Compton scattering"], answer: 1, hint: "Think of the de Sitter binary star test.", solution: "If light's speed depended on source velocity, light from different points in a binary star's fast orbit would arrive out of sequence, garbling the light curve — never observed.", difficulty: 2, tags: ["relativity", "postulates"] },
    { id: "relativity-invariant-c-d3", lesson: "relativity-invariant-c", type: "mc", prompt: "Special relativity's two postulates are:", options: ["Energy conservation and momentum conservation", "The laws of physics are the same in every inertial frame, and $c$ is the same in every inertial frame", "Space is absolute and time is relative", "Mass and energy are always equal"], answer: 1, hint: "One extends the principle of relativity; the other concerns $c$ specifically.", solution: "These are exactly Einstein's two postulates: relativity of physical law, and the frame-independence of $c$.", difficulty: 1, tags: ["relativity", "postulates"] },
    { id: "relativity-invariant-c-d4", lesson: "relativity-invariant-c", type: "mc", prompt: "Galilean velocity addition fails for light because:", options: ["It would make $c$ depend on the observer's velocity, contradicting the observed frame-independence of $c$", "Light has no velocity", "Galilean addition only applies to sound", "It predicts $c=0$"], answer: 0, hint: "What would chasing a light beam at high speed predict under Galilean addition?", solution: "Galilean addition would predict a different measured speed of light for observers in relative motion, directly contradicting the experimentally established constancy of $c$.", difficulty: 1, tags: ["relativity", "postulates"] },
    { id: "relativity-invariant-c-d5", lesson: "relativity-invariant-c", type: "mc", prompt: "In resolving the conflict between Maxwell's equations and Galilean kinematics, Einstein's approach was to:", options: ["Modify Maxwell's equations to include a velocity-dependent $c$", "Keep Maxwell's equations and the constancy of $c$, and instead modify the kinematic (space-time) transformation between frames", "Reject the principle of relativity", "Conclude that light doesn't actually propagate"], answer: 1, hint: "Which framework was more precisely tested and mathematically constrained?", solution: "Rather than modifying the well-tested field equations, Einstein modified the underlying kinematics (the Lorentz transformation replaces the Galilean one), preserving invariant $c$.", difficulty: 2, tags: ["relativity", "postulates"] },
    // relativity-time-length
    { id: "relativity-time-length-d1", lesson: "relativity-time-length", type: "numeric", prompt: "Find $\\gamma$ for a particle moving at $v=0.6c$.", answer: 1.25, tolerance: 0.02, unit: "(dimensionless)", hint: "$\\gamma=1/\\sqrt{1-v^2/c^2}$.", solution: "$\\gamma=1/\\sqrt{1-0.36}=1/\\sqrt{0.64}=1/0.8=1.25$.", difficulty: 1, tags: ["relativity", "time-dilation"] },
    { id: "relativity-time-length-d2", lesson: "relativity-time-length", type: "numeric", prompt: "A spaceship has proper length 100 m and travels at $v=0.6c$. Find its length as measured by a stationary observer, in meters.", answer: 80, tolerance: 0.02, unit: "m", hint: "$L=L_0/\\gamma$, with $\\gamma=1.25$ at $v=0.6c$.", solution: "$L=100/1.25=80\\text{ m}$.", difficulty: 1, tags: ["relativity", "length-contraction"] },
    { id: "relativity-time-length-d3", lesson: "relativity-time-length", type: "mc", prompt: "Time dilation and length contraction both derive from:", options: ["The assumption that light slows down near massive objects", "The requirement that $c$ be measured the same in every inertial frame, applied to a light-clock geometry", "Newton's third law", "The conservation of angular momentum"], answer: 1, hint: "Both use the same light-clock argument.", solution: "Both effects follow from requiring a photon to move at exactly $c$ in every frame, applied to light clocks oriented perpendicular and parallel to the motion respectively.", difficulty: 1, tags: ["relativity", "time-dilation"] },
    { id: "relativity-time-length-d4", lesson: "relativity-time-length", type: "numeric", prompt: "A particle with proper lifetime $2.0\\ \\mu\\text{s}$ moves at $v=0.8c$ ($\\gamma=5/3$). Find its lifetime as measured in the lab frame, in $\\mu\\text{s}$.", answer: 3.33, tolerance: 0.02, unit: "$\\mu$s", hint: "$\\Delta t = \\gamma\\tau_0$.", solution: "$\\Delta t = (5/3)\\times2.0\\approx3.33\\ \\mu\\text{s}$.", difficulty: 2, tags: ["relativity", "time-dilation"] },
    { id: "relativity-time-length-d5", lesson: "relativity-time-length", type: "mc", prompt: "The atmospheric muon experiment provides direct evidence for time dilation because:", options: ["Muons are only created at ground level", "Far more muons reach the ground than their rest-frame lifetime alone would allow, matching the lifetime dilated by $\\gamma$", "Muons travel slower than light", "It shows the speed of light varies"], answer: 1, hint: "Compare naive range (using $\\tau_0$) to dilated range (using $\\gamma\\tau_0$).", solution: "The measured survival rate matches a dilated lifetime $\\gamma\\tau_0$, not the much shorter proper lifetime $\\tau_0$ — direct confirmation of a real physical effect.", difficulty: 2, tags: ["relativity", "time-dilation"] },
    // relativity-lorentz
    { id: "relativity-lorentz-d1", lesson: "relativity-lorentz", type: "mc", prompt: "The Lorentz transformation reduces to the Galilean transformation in the limit:", options: ["$v\\to c$", "$v\\ll c$ (so $\\gamma\\to1$)", "$x\\to0$", "$t\\to0$"], answer: 1, hint: "Consider low speeds.", solution: "As $v\\ll c$, $\\gamma\\to1$ and $vx/c^2\\to0$, recovering $x'\\approx x-vt,\\ t'\\approx t$.", difficulty: 1, tags: ["relativity", "lorentz-transformation"] },
    { id: "relativity-lorentz-d2", lesson: "relativity-lorentz", type: "mc", prompt: "In the Lorentz transformation $t'=\\gamma(t-vx/c^2)$, the term $vx/c^2$ is directly responsible for:", options: ["Length contraction", "The relativity of simultaneity (equal $t$, different $x$ give different $t'$)", "Time running backward", "The speed of light changing"], answer: 1, hint: "What happens to two same-$t$, different-$x$ events?", solution: "Because $t'$ depends on $x$ through this term, events simultaneous in one frame (same $t$) generally are not simultaneous in another (different $t'$).", difficulty: 2, tags: ["relativity", "simultaneity"] },
    { id: "relativity-lorentz-d3", lesson: "relativity-lorentz", type: "mc", prompt: "Testing a proposed spacetime transformation against a light pulse $x=ct$ and requiring $x'=ct'$ in the new frame is a way of:", options: ["Checking energy conservation", "Verifying the transformation is consistent with the postulate that $c$ is frame-independent", "Measuring the transformation's length contraction factor", "Confirming Newton's second law"], answer: 1, hint: "This is exactly how the correct Lorentz transformation was singled out in the lesson.", solution: "Substituting a light pulse's worldline and checking that it still moves at $c$ in the new frame is the direct test of consistency with the second postulate.", difficulty: 2, tags: ["relativity", "lorentz-transformation"] },
    { id: "relativity-lorentz-d4", lesson: "relativity-lorentz", type: "mc", prompt: "In the train-lightning thought experiment (two strikes simultaneous in the ground frame), a passenger at the train's midpoint, moving toward one strike location:", answer: 2, options: ["Also observes both flashes simultaneously", "Observes the strike behind the train first", "Observes the strike ahead (in the direction of motion) as occurring first, due to relativity of simultaneity", "Cannot observe either flash"], hint: "Which strike has the smaller $t'$?", solution: "Computing $t'$ for each event using the Lorentz transformation shows the forward strike has a smaller $t'$ in the train frame — the passenger judges it to have occurred first, even though both are simultaneous in the ground frame.", difficulty: 2, tags: ["relativity", "simultaneity"] },
    { id: "relativity-lorentz-d5", lesson: "relativity-lorentz", type: "mc", prompt: "Relativity of simultaneity means that:", options: ["Simultaneity is meaningless in all frames", "Whether two spatially separated events are simultaneous depends on the observer's inertial frame", "Clocks physically break when in relative motion", "Only events at the same location can ever be simultaneous"], answer: 1, hint: "It's frame-dependent, not universally false or true.", solution: "Two spatially separated events judged simultaneous in one inertial frame are generally judged non-simultaneous (with a definite order that can even differ) in another frame moving relative to the first.", difficulty: 1, tags: ["relativity", "simultaneity"] },
    // relativity-velocity-interval
    { id: "relativity-velocity-interval-d1", lesson: "relativity-velocity-interval", type: "numeric", prompt: "A spaceship moves at $0.5c$ relative to the ground and fires a probe forward at $0.5c$ relative to the ship. Find the probe's speed relative to the ground, as a multiple of $c$.", answer: 0.8, tolerance: 0.02, unit: "$c$", hint: "$u=(u'+v)/(1+u'v/c^2)$.", solution: "$u=(0.5+0.5)/(1+0.25)=1.0/1.25=0.8c$.", difficulty: 2, tags: ["relativity", "velocity-addition"] },
    { id: "relativity-velocity-interval-d2", lesson: "relativity-velocity-interval", type: "mc", prompt: "The relativistic velocity-addition formula guarantees that:", options: ["Combined velocities can reach exactly $2c$", "No combination of two sub-light speeds can ever reach or exceed $c$", "Velocities always simply add as in Galilean mechanics", "Only light can reach $c$ exactly, from any addition"], answer: 1, hint: "Check the limiting case $u',v\\to c$.", solution: "As $u',v\\to c$, $u=(u'+v)/(1+u'v/c^2)\\to2c/2=c$ exactly — never exceeding $c$ for any valid sub-light inputs.", difficulty: 2, tags: ["relativity", "velocity-addition"] },
    { id: "relativity-velocity-interval-d3", lesson: "relativity-velocity-interval", type: "mc", prompt: "The invariant spacetime interval is defined as:", options: ["$\\Delta x^2+c^2\\Delta t^2$", "$c^2\\Delta t^2-\\Delta x^2-\\Delta y^2-\\Delta z^2$", "$\\Delta x/\\Delta t$", "$\\gamma\\Delta t$"], answer: 1, hint: "It mixes a time term with a negative spatial term.", solution: "$\\Delta s^2=c^2\\Delta t^2-\\Delta x^2-\\Delta y^2-\\Delta z^2$ is invariant under the Lorentz transformation, even though $\\Delta x,\\Delta t$ individually are not.", difficulty: 1, tags: ["relativity", "invariant-interval"] },
    { id: "relativity-velocity-interval-d4", lesson: "relativity-velocity-interval", type: "mc", prompt: "For $u',v\\ll c$, the relativistic velocity-addition formula $u=(u'+v)/(1+u'v/c^2)$ reduces to:", options: ["$u=u'-v$", "$u\\approx u'+v$ (ordinary Galilean addition)", "$u=c$ always", "$u=0$"], answer: 1, hint: "The denominator's correction term becomes negligible.", solution: "As $u'v/c^2\\to0$, the denominator $\\to1$, recovering ordinary Galilean addition — consistent with everyday-speed physics being unaffected.", difficulty: 1, tags: ["relativity", "velocity-addition"] },
    { id: "relativity-velocity-interval-d5", lesson: "relativity-velocity-interval", type: "mc", prompt: "Two rockets each move at $0.9c$ in opposite directions relative to a space station. The speed of one rocket as measured *from the other rocket's own frame* is:", options: ["$1.8c$", "$0.994c$", "$0.9c$", "$c$"], answer: 1, hint: "Use $u=(0.9c+0.9c)/(1+0.9\\times0.9)$.", solution: "$u=(0.9+0.9)/(1+0.81)c=1.8/1.81\\,c\\approx0.994c$ — close to but never reaching $c$.", difficulty: 2, tags: ["relativity", "velocity-addition"] },
    // relativity-momentum-energy
    { id: "relativity-momentum-energy-d1", lesson: "relativity-momentum-energy", type: "mc", prompt: "Relativistic momentum is defined as:", options: ["$p=mv$", "$p=\\gamma mv$", "$p=mc$", "$p=mv^2$"], answer: 1, hint: "Recall the factor needed to keep momentum conserved across frames.", solution: "$p=\\gamma m v$, reducing to $mv$ for $v\\ll c$.", difficulty: 1, tags: ["relativity", "momentum-energy"] },
    { id: "relativity-momentum-energy-d2", lesson: "relativity-momentum-energy", type: "numeric", prompt: "A proton ($mc^2=938\\text{ MeV}$) has total energy $E=1500\\text{ MeV}$. Find its momentum $pc$ in MeV.", answer: 1170.5, tolerance: 0.03, unit: "MeV", hint: "$pc=\\sqrt{E^2-(mc^2)^2}$.", solution: "$pc=\\sqrt{1500^2-938^2}=\\sqrt{2{,}250{,}000-879{,}844}=\\sqrt{1{,}370{,}156}\\approx1170\\text{ MeV}$.", difficulty: 2, tags: ["relativity", "momentum-energy"] },
    { id: "relativity-momentum-energy-d3", lesson: "relativity-momentum-energy", type: "mc", prompt: "The relation $E^2=(pc)^2+(mc^2)^2$, applied to a massless particle ($m=0$), gives:", options: ["$E=0$", "$E=pc$", "$E=mc^2$ still", "$p=0$"], answer: 1, hint: "Set $m=0$ directly.", solution: "With $m=0$, $E^2=(pc)^2\\Rightarrow E=pc$ — exactly the photon's energy-momentum relation.", difficulty: 1, tags: ["relativity", "momentum-energy"] },
    { id: "relativity-momentum-energy-d4", lesson: "relativity-momentum-energy", type: "mc", prompt: "As $v\\to0$, relativistic kinetic energy $KE=(\\gamma-1)mc^2$ approaches:", options: ["$mc^2$", "$0$", "$\\tfrac12mv^2$ (the classical result)", "Infinity"], answer: 2, hint: "Taylor-expand $\\gamma$ for small $v/c$.", solution: "$\\gamma\\approx1+\\tfrac12v^2/c^2$, so $KE\\approx\\tfrac12mv^2$ — the classical formula is the low-speed limit.", difficulty: 2, tags: ["relativity", "momentum-energy"] },
    { id: "relativity-momentum-energy-d5", lesson: "relativity-momentum-energy", type: "numeric", prompt: "A particle with rest mass $mc^2=100\\text{ MeV}$ has kinetic energy $KE=300\\text{ MeV}$. Find $\\gamma$.", answer: 4.0, tolerance: 0.02, unit: "(dimensionless)", hint: "$E=mc^2+KE$; $\\gamma=E/mc^2$.", solution: "$E=100+300=400\\text{ MeV}$; $\\gamma=400/100=4.0$.", difficulty: 2, tags: ["relativity", "momentum-energy"] },
    // relativity-doppler-fourvector
    { id: "relativity-doppler-fourvector-d1", lesson: "relativity-doppler-fourvector", type: "mc", prompt: "The classical Doppler formula for sound cannot be directly reused for light because:", options: ["Light has no frequency", "It distinguishes 'source moving' from 'observer moving' relative to a medium, and light has no medium to define such a distinction", "Sound travels faster than light", "The classical formula predicts no shift at all"], answer: 1, hint: "Recall the medium-based asymmetry.", solution: "The classical formula's dependence on motion relative to a medium has no counterpart for light, which requires a formula depending only on relative velocity.", difficulty: 1, tags: ["relativity", "doppler"] },
    { id: "relativity-doppler-fourvector-d2", lesson: "relativity-doppler-fourvector", type: "numeric", prompt: "A source recedes directly along the line of sight at $\\beta=0.6$. Find the ratio $f_{obs}/f_{source}$.", answer: 0.5, tolerance: 0.02, unit: "(dimensionless)", hint: "$f_{obs}/f_{source}=\\sqrt{(1-\\beta)/(1+\\beta)}$.", solution: "$\\sqrt{(1-0.6)/(1+0.6)}=\\sqrt{0.4/1.6}=\\sqrt{0.25}=0.5$.", difficulty: 2, tags: ["relativity", "doppler"] },
    { id: "relativity-doppler-fourvector-d3", lesson: "relativity-doppler-fourvector", type: "mc", prompt: "The transverse Doppler effect (motion exactly perpendicular to the line of sight at closest approach) is caused entirely by:", options: ["Ordinary light-travel-time changes", "Time dilation of the moving source's clock", "The observer's own motion", "The medium's refractive index"], answer: 1, hint: "There's no classical light-travel-time effect at that exact instant.", solution: "At closest approach there's no changing light-travel-time contribution, so any observed shift must come purely from the moving source's time-dilated internal clock (its oscillation frequency).", difficulty: 2, tags: ["relativity", "doppler"] },
    { id: "relativity-doppler-fourvector-d4", lesson: "relativity-doppler-fourvector", type: "mc", prompt: "A four-vector's Minkowski 'dot product' with itself, computed by any inertial observer, is:", options: ["Different for every observer", "Frame-invariant, the same value for every inertial observer", "Always zero", "Only defined for massless particles"], answer: 1, hint: "This generalizes the invariant interval.", solution: "Just as $\\Delta s^2$ is invariant for the position four-vector, $E^2-(pc)^2=(mc^2)^2$ is invariant for the energy-momentum four-vector — a general property of four-vector dot products.", difficulty: 2, tags: ["relativity", "four-vectors"] },
    { id: "relativity-doppler-fourvector-d5", lesson: "relativity-doppler-fourvector", type: "mc", prompt: "Relativistic Doppler shift (motion through space) and cosmological redshift (expansion of space) are:", options: ["Exactly the same physical mechanism", "Different physical mechanisms that can produce formally similar-looking redshift formulas", "Both caused by an ether medium", "Only relevant to sound waves"], answer: 1, hint: "One involves relative velocity through space; the other involves the metric itself expanding.", solution: "Doppler shift arises from relative motion between source and observer through space; cosmological redshift arises from the expansion of space itself (covered later in this curriculum) — physically distinct even though both stretch wavelengths.", difficulty: 2, tags: ["relativity", "doppler"] }
  ],

  test: [
    { id: "relativity-t1", prompt: "Which experimental result was most directly responsible for ruling out a luminiferous ether at rest relative to which light travels at fixed speed?", options: ["The photoelectric effect", "The Michelson–Morley null result", "Compton scattering", "The Zeeman effect", "Rutherford scattering"], answer: 1, solution: "The Michelson–Morley experiment found no directional variation in light's speed, ruling out a detectable ether wind.", difficulty: 1, tags: ["relativity", "postulates"], lesson: "relativity-invariant-c" },
    { id: "relativity-t2", prompt: "A spaceship of proper length 60 m moves at $v=0.8c$ ($\\gamma=5/3$). Its length as measured by a stationary observer is:", options: ["36 m", "45 m", "60 m", "75 m", "100 m"], answer: 0, solution: "$L=L_0/\\gamma=60/(5/3)=60\\times3/5=36\\text{ m}$.", difficulty: 1, tags: ["relativity", "length-contraction"], lesson: "relativity-time-length" },
    { id: "relativity-t3", prompt: "A particle has proper lifetime $\\tau_0$ and moves at $v=0.6c$ ($\\gamma=1.25$). If it travels a lab-frame distance $d$ before decaying, the lab-frame lifetime used to estimate $d$ should be:", options: ["$\\tau_0$", "$\\tau_0/\\gamma$", "$\\gamma\\tau_0$", "$\\gamma^2\\tau_0$", "$\\tau_0/\\gamma^2$"], answer: 2, solution: "Lab-frame elapsed time is the dilated time $\\gamma\\tau_0$, always larger than the proper lifetime.", difficulty: 1, tags: ["relativity", "time-dilation"], lesson: "relativity-time-length" },
    { id: "relativity-t4", prompt: "Two events occur simultaneously in frame $S$ but at different positions along the direction of relative motion. An observer in frame $S'$, moving relative to $S$, will in general observe:", options: ["The same simultaneity as $S$", "A different time ordering than $S$, since $t'$ depends on both $t$ and $x$ in the Lorentz transformation", "No events at all", "Only one of the two events", "Both events shift to the same later time"], answer: 1, solution: "Because $t'=\\gamma(t-vx/c^2)$ depends on $x$, equal-$t$ events at different $x$ generally have different $t'$ — the relativity of simultaneity.", difficulty: 2, tags: ["relativity", "simultaneity"], lesson: "relativity-lorentz" },
    { id: "relativity-t5", prompt: "Which of the following correctly distinguishes the Lorentz transformation from the Galilean transformation?", options: ["The Lorentz transformation has no low-speed limit", "The Lorentz transformation mixes space and time coordinates together, while the Galilean transformation keeps time universal", "The Galilean transformation is used only for light", "The Lorentz transformation predicts infinite speed of light", "The Galilean transformation includes a $\\gamma$ factor"], answer: 1, solution: "The defining structural change is that $t'$ depends on $x$ (not just $t$) in the Lorentz transformation, unlike the Galilean case where time is universal.", difficulty: 1, tags: ["relativity", "lorentz-transformation"], lesson: "relativity-lorentz" },
    { id: "relativity-t6", prompt: "A rocket moves at $0.6c$ relative to a space station and launches a probe forward at $0.6c$ relative to the rocket. The probe's speed relative to the station is:", options: ["$1.2c$", "$0.6c$", "$0.882c$", "$0.960c$", "$c$"], answer: 2, solution: "$u=(0.6+0.6)/(1+0.36)c=1.2/1.36\\,c\\approx0.882c$.", difficulty: 2, tags: ["relativity", "velocity-addition"], lesson: "relativity-velocity-interval" },
    { id: "relativity-t7", prompt: "The invariant spacetime interval $\\Delta s^2=c^2\\Delta t^2-\\Delta x^2$ is useful because:", options: ["It is always zero", "It has the same value for every inertial observer, unlike $\\Delta t$ or $\\Delta x$ separately", "It only applies to light", "It equals the Galilean distance", "It depends on the observer's velocity"], answer: 1, solution: "Every inertial observer computes the same $\\Delta s^2$, even though they disagree on $\\Delta t$ and $\\Delta x$ individually — the relativistic analog of an invariant distance.", difficulty: 2, tags: ["relativity", "invariant-interval"], lesson: "relativity-velocity-interval" },
    { id: "relativity-t8", prompt: "A muon ($mc^2=106\\text{ MeV}$) has total energy $E=530\\text{ MeV}$. Its momentum $pc$, in MeV, is closest to:", options: ["106 MeV", "212 MeV", "424 MeV", "519 MeV", "530 MeV"], answer: 3, solution: "$pc=\\sqrt{E^2-(mc^2)^2}=\\sqrt{530^2-106^2}=\\sqrt{280{,}900-11{,}236}=\\sqrt{269{,}664}\\approx519\\text{ MeV}$.", difficulty: 2, tags: ["relativity", "momentum-energy"], lesson: "relativity-momentum-energy" },
    { id: "relativity-t9", prompt: "Which statement correctly describes $E=mc^2$?", options: ["It is an independent law unrelated to momentum", "It is the $p=0$ special case of the general relation $E^2=(pc)^2+(mc^2)^2$", "It only holds for photons", "It contradicts the conservation of energy", "It applies only in the Galilean limit"], answer: 1, solution: "Setting momentum to zero in the general energy-momentum relation gives exactly $E=mc^2$ — the object's rest energy.", difficulty: 1, tags: ["relativity", "momentum-energy"], lesson: "relativity-momentum-energy" },
    { id: "relativity-t10", prompt: "For a particle with $\\gamma=1$, the kinetic energy is:", options: ["$mc^2$", "$0$", "Infinite", "$mc^2/2$", "$2mc^2$"], answer: 1, solution: "$\\gamma=1$ corresponds to $v=0$, so $KE=(\\gamma-1)mc^2=0$.", difficulty: 1, tags: ["relativity", "momentum-energy"], lesson: "relativity-momentum-energy" },
    { id: "relativity-t11", prompt: "A star recedes directly along the line of sight at $\\beta=0.8$. The observed wavelength is shifted relative to the emitted wavelength by a factor $\\lambda_{obs}/\\lambda_{source}$ closest to:", options: ["0.11", "0.33", "1.0", "3.0", "9.0"], answer: 3, solution: "$\\lambda_{obs}/\\lambda_{source}=\\sqrt{(1+\\beta)/(1-\\beta)}=\\sqrt{1.8/0.2}=\\sqrt{9}=3.0$.", difficulty: 2, tags: ["relativity", "doppler"], lesson: "relativity-doppler-fourvector" },
    { id: "relativity-t12", prompt: "Which of the following is a genuinely relativistic effect with no classical (sound-wave) Doppler analog?", options: ["Redshift from a directly receding source", "Blueshift from a directly approaching source", "Transverse Doppler shift at closest approach, arising purely from time dilation", "Any Doppler shift at all", "Redshift from an object falling into a gravitational well"], answer: 2, solution: "Transverse Doppler shift has no classical counterpart, since it arises purely from time dilation of the source's clock rather than a changing light-travel-time path.", difficulty: 2, tags: ["relativity", "doppler"], lesson: "relativity-doppler-fourvector" }
  ]
});
