window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "thermo",
  title: "Thermodynamics and Statistical Mechanics",
  order: 4,
  greWeight: 0.10,
  prereqs: ["mechanics"],
  blurb: "Connects the macroscopic laws of heat and engines to the microscopic statistics of huge numbers of particles.",

  lessons: [
    // ---------------------------------------------------------------
    {
      id: "thermo-temperature",
      title: "Temperature and the Zeroth Law",
      minutes: 10,
      discovery: "Temperature is only a well-defined single number because thermal equilibrium is transitive.",
      sections: [
        { kind: "problem", md: `You have an engine block and a coolant sensor sealed in separate housings. You need to know whether they are at the same temperature *without* opening either one up or forcing them into contact (that would ruin the measurement, or just be impossible for a running engine). More generally: what does it even mean to say two separated objects "have the same temperature," and how would you check it?` },
        { kind: "candidates", md: `**A. Touch each object and compare.** Your hand is a built-in thermometer — hot feels hot, cold feels cold.

**B. Put a third object in contact with each one in turn, and compare some measurable property of that third object (like the volume of gas in a sealed tube) after each contact.**` },
        { kind: "failures", md: `**A fails immediately.** Touch a metal doorknob and a wooden door on the same cold morning: the metal feels colder, even though both have been sitting in the same room at the same temperature for hours. Your hand isn't measuring temperature — it's measuring *heat flow rate*, which depends on thermal conductivity as much as on temperature. Two objects at identical temperature can feel completely different.

So B looks more promising — but only if we can trust the following chain of logic: if the third object (call it C) reaches the same equilibrium reading in contact with A as it does in contact with B, can we conclude A and B would be in equilibrium with each other, *without ever actually touching A to B*? Nothing forces that to be true a priori. It's an empirical claim about how the world works, not a logical necessity — equilibrium doesn't have to be transitive.` },
        { kind: "discovery", md: `Experimentally, it always turns out to be transitive: if C equilibrates with A, and C separately equilibrates with B, then A and B — when finally put in contact — show no further heat flow between them. This transitivity is what makes "temperature" possible as a *single number* you can assign to an object independent of what you're comparing it to. Without it, you'd need a separate comparison for every pair of objects in the universe; with it, one number per object suffices, and object C (the thermometer) can be calibrated once and reused everywhere.` },
        { kind: "formal", md: `**Zeroth law of thermodynamics:** if system A is in thermal equilibrium with system C, and system B is separately in thermal equilibrium with C, then A and B are in thermal equilibrium with each other. This law is what licenses defining a state function, temperature $T$, such that thermal equilibrium $\\iff$ equal $T$.

A practical realization is the **ideal-gas thermometer**: a fixed amount of dilute gas held at constant volume, brought to equilibrium with whatever you want to measure. Its pressure $P$ serves as the thermometric property, and temperature is *defined* (on the Kelvin scale) by $T \\propto P$ in this limit, with the constant fixed by declaring the triple point of water to be $273.16\\text{ K}$.` },
        { kind: "apply", md: `A constant-volume gas thermometer reads $P_1 = 0.900\\text{ atm}$ at the triple point of water ($T_1 = 273.16\\text{ K}$). Placed in contact with a sample, it reads $P_2 = 1.200\\text{ atm}$. Since $T \\propto P$ at fixed volume: $T_2 = 273.16\\text{ K} \\times \\dfrac{1.200}{0.900} = 364.2\\text{ K}$.` },
        { kind: "transfer", md: `The zeroth law is an *equivalence relation* (reflexive, symmetric, transitive) — the same structure that lets you partition any set into equivalence classes. Here the classes are "isotherms," and temperature is just a label for which class you're in. This is the quiet, unglamorous law that has to come before any of the other three — you can't even write "$T$" in the first law until you know it names something well-defined.` }
      ],
      checkpoints: [
        { q: "Why does a metal railing feel colder than a wooden fence at the same ambient temperature?", options: ["Metal is always at a lower equilibrium temperature outdoors", "Touch senses heat-flow rate, which depends on conductivity, not temperature alone", "Wood has a higher specific heat so it warms your hand", "Metal has negative thermal expansion"], answer: 1, explain: "Both are in equilibrium with the same air, so both are at the same temperature. Metal conducts heat away from your hand faster, which is what you actually perceive." },
        { q: "The zeroth law is essential because it guarantees that thermal equilibrium is:", options: ["Reversible", "Adiabatic", "Transitive", "Isentropic"], answer: 2, explain: "Transitivity (A~C and B~C imply A~B) is exactly what allows one number, temperature, to characterize equilibrium for every pair of objects." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-kinetic-theory",
      title: "The Ideal Gas From Kinetic Theory",
      minutes: 14,
      discovery: "Pressure is momentum transfer from molecular collisions, and temperature turns out to just be average molecular kinetic energy.",
      sections: [
        { kind: "problem", md: `A gas pushes outward on the walls of its container with some pressure $P$. Experimentally, $P$ rises when you heat the gas and rises when you compress it into a smaller volume ($PV = nRT$, found empirically well before anyone knew what a molecule was). *Why* should squeezing gas into less space, or heating it, increase the outward push? What is pressure, physically?` },
        { kind: "candidates", md: `**A. Pressure is just a direct measure of "how hot" the gas is** — a property of the substance as a whole, no mechanism needed.

**B. Model the gas as a swarm of point particles bouncing elastically off the walls; pressure is the rate at which they deliver momentum to the walls.**` },
        { kind: "failures", md: `**A fails to explain the $V$-dependence.** Compress a gas at fixed temperature (isothermal compression) and pressure still rises, even though "how hot" hasn't changed. Treating $P$ and $T$ as the same thing with no mechanism can't produce the correct $PV=nRT$ relation — it can only be fit to it after the fact, not derived.

**B looks more promising, but needs to actually produce a number.** Try it for one particle first: does a single fast molecule bouncing back and forth even resemble a steady pressure? It delivers momentum in discrete impulsive kicks, not a smooth push — so B needs $N$ to be enormous (it is, $\\sim 10^{23}$) before the kicks blur into something that looks like continuous pressure. That's a real requirement, not a fatal flaw, so B survives — but only after checking it.` },
        { kind: "discovery", md: `Push B through: consider $N$ molecules of mass $m$ in a cube of side $L$ (volume $V=L^3$). A molecule with velocity component $v_x$ hits the wall perpendicular to $x$, bounces back elastically (reversing $v_x$), transferring momentum $2mv_x$ per collision. It returns to hit that same wall again after traveling $2L$, so it collides every $\\Delta t = 2L/v_x$. Averaging over all $N$ molecules and summing over the two other directions by symmetry gives the force per unit area:
$$P = \\frac{1}{3}\\frac{Nm\\langle v^2\\rangle}{V} \\quad\\Longrightarrow\\quad PV = \\frac{1}{3}Nm\\langle v^2\\rangle$$
where $\\langle v^2\\rangle$ is the mean-square speed. This is a real derivation from a mechanical model — not a fit — and it reproduces the empirical gas law when compared against $PV=NkT$.` },
        { kind: "formal", md: `Comparing $PV=\\tfrac13 Nm\\langle v^2\\rangle$ with the empirical ideal gas law $PV=NkT$ (Boltzmann constant $k=1.38\\times10^{-23}\\text{ J/K}$) gives
$$\\frac{1}{2}m\\langle v^2\\rangle = \\frac{3}{2}kT$$
Temperature *is*, up to a constant, the average translational kinetic energy per molecule. This is the payoff of kinetic theory: a macroscopic, easily-measured quantity ($T$) is identified with a microscopic average that no one can measure molecule-by-molecule.` },
        { kind: "apply", md: `Root-mean-square speed of $\\text{N}_2$ ($m = 4.65\\times10^{-26}\\text{ kg}$) at room temperature ($T=300\\text{ K}$):
$$v_{rms} = \\sqrt{\\langle v^2\\rangle} = \\sqrt{\\frac{3kT}{m}} = \\sqrt{\\frac{3(1.38\\times10^{-23})(300)}{4.65\\times10^{-26}}} \\approx 517\\text{ m/s}$$
Faster than the speed of sound in air ($\\sim 340\\text{ m/s}$) — consistent, since sound propagates by molecular collisions and can't outrun the molecules carrying it.` },
        { kind: "transfer", md: `This is the founding move of statistical mechanics: a macroscopic observable ($P$, or $T$) is recovered as the *average* of a microscopic quantity over an enormous number of degrees of freedom. Every later lesson in this module — equipartition, the Boltzmann factor, blackbody radiation — is a variation on exactly this trick.` }
      ],
      checkpoints: [
        { q: "In the kinetic-theory derivation of pressure, the factor of $\\tfrac13$ comes from:", options: ["Averaging over the three spatial directions by symmetry", "The three degrees of freedom in the Boltzmann factor", "A relativistic correction", "The ratio $C_p/C_v$ for a monatomic gas"], answer: 0, explain: "Only the velocity component perpendicular to a given wall contributes to the momentum transfer there; by symmetry $\\langle v_x^2\\rangle=\\langle v_y^2\\rangle=\\langle v_z^2\\rangle=\\tfrac13\\langle v^2\\rangle$." },
        { q: "Doubling the absolute temperature of an ideal gas at fixed volume multiplies $v_{rms}$ by:", options: ["2", "4", "$\\sqrt2$", "$1/\\sqrt2$"], answer: 2, explain: "$v_{rms}\\propto\\sqrt{T}$, so doubling $T$ multiplies $v_{rms}$ by $\\sqrt2$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-first-law",
      title: "The First Law and Specific Heats",
      minutes: 13,
      discovery: "Heat capacity isn't one number per substance — it depends on the constraint (constant V vs constant P), because work steals some of the heat.",
      sections: [
        { kind: "problem", md: `You want to raise the temperature of one mole of gas by $1\\text{ K}$. How much heat does that take? You measure it two ways: once with the gas sealed in a rigid, fixed-volume container, and once with the gas in a cylinder with a free piston held at constant pressure by a weight. The two experiments give *different* answers — the constant-pressure case always needs more heat. Why would the same $1\\text{ K}$ rise cost different amounts of heat?` },
        { kind: "candidates", md: `**A. Heat capacity is an intrinsic material property — one number per substance — and any experimental mismatch is measurement error.**

**B. All the heat you add goes directly into raising the temperature; work done by the gas is irrelevant to how much heat is needed.**` },
        { kind: "failures", md: `**A fails against repeatable, non-error-sized discrepancies.** For an ideal gas the constant-pressure heat capacity is measurably $R\\approx 8.31\\text{ J/(mol K)}$ larger than the constant-volume one, every time, for every ideal gas — that's a pattern, not noise.

**B fails in the free-piston case specifically.** When the gas is held at constant pressure and heated, it also expands, lifting the piston against the weight — it does mechanical work on its surroundings. That work has to come from somewhere. If "all heat goes into temperature" were true, the constant-$P$ and constant-$V$ experiments would need identical heat input for the same $\\Delta T$, contradicting what's measured.` },
        { kind: "discovery", md: `The resolution is energy conservation with *two* competing destinations for the heat: it can raise internal energy $U$ (which is what temperature actually tracks for an ideal gas) or it can do mechanical work $W=\\int P\\,dV$ (the area under the curve on a $P$–$V$ diagram) as the gas expands. At constant volume, $dV=0$, so no work is done and *every joule of heat goes into $dU$*. At constant pressure, some heat is siphoned off into pushing the piston, so more total heat is required for the same $\\Delta U$ (same $\\Delta T$).` },
        { kind: "formal", md: `**First law:** $dU = dQ - dW$, with $dW = P\\,dV$ for quasistatic processes. Define the heat capacities directly in terms of state functions:
$$C_V \\equiv \\left(\\frac{\\partial U}{\\partial T}\\right)_V, \\qquad C_P \\equiv \\left(\\frac{\\partial H}{\\partial T}\\right)_P$$
using the enthalpy $H\\equiv U+PV$ (chosen precisely so that, at constant $P$, $dH=dQ$ — just as $dU=dQ$ at constant $V$). For an ideal gas $U$ depends on $T$ alone (a consequence of kinetic theory — $U=\\tfrac32 NkT$ for a monatomic gas), so $H=U+nRT$ gives:
$$C_P = \\left(\\frac{\\partial H}{\\partial T}\\right)_P = C_V + nR \\quad\\Longrightarrow\\quad C_P - C_V = nR$$` },
        { kind: "apply", md: `For one mole of a monatomic ideal gas, kinetic theory gives $U=\\tfrac32 RT$, so $C_V=\\tfrac32 R \\approx 12.5\\text{ J/(mol K)}$ and $C_P = C_V+R = \\tfrac52 R\\approx 20.8\\text{ J/(mol K)}$ — matching the measured constant-pressure excess of exactly $R$.` },
        { kind: "transfer", md: `The general lesson: any time a system can respond to the same input along *different constrained paths*, you get different effective "capacities," and the difference is exactly whatever work leaks out along the less-constrained path. The same logic reappears with magnetic vs. non-magnetic heat capacities, and with the difference between isothermal and adiabatic compressibility.` }
      ],
      checkpoints: [
        { q: "At constant volume, all heat added to an ideal gas goes into:", options: ["Work done on the surroundings", "Internal energy (raising $T$)", "Entropy production only", "Kinetic energy of the container walls"], answer: 1, explain: "$dV=0 \\Rightarrow dW=0 \\Rightarrow dQ=dU$ exactly." },
        { q: "$C_P - C_V = nR$ for an ideal gas because, at constant pressure, part of the added heat:", options: ["Is lost as friction", "Does expansion work against the surroundings", "Converts to potential energy of the molecules", "Radiates away as heat"], answer: 1, explain: "At constant $P$ the gas expands as it's heated and does work $P\\Delta V = nR\\Delta T$ on its surroundings, so more heat is needed for the same $\\Delta T$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-heat-transfer",
      title: "Conduction, Convection, and Radiation: Three Ways to Move Heat",
      minutes: 16,
      discovery: "Heat can only be carried three physically distinct ways — molecule-to-molecule handoff, buoyancy-driven bulk fluid motion, or electromagnetic radiation needing no medium at all — and each has a different scaling law, which is the fast way to identify which mechanism dominates a given scenario.",
      sections: [
        { kind: "problem", md: `A mug of hot coffee cools in a quiet room. Touch the mug's outer wall and it's warm — heat clearly traveled through the solid ceramic to reach your hand. Look just above the coffee's surface and you can see faint shimmering currents of rising warm air. And even coffee sealed inside a vacuum-walled thermos (no air gap at all between the inner and outer walls) still slowly loses heat to the room. Is "heat leaving the coffee" the same physical process in all three cases, just happening in different substances, or are these genuinely different mechanisms — and if they're different, does that change how fast each one happens?` },
        { kind: "candidates", md: `1. It's all one process: heat flows from hot to cold according to a single universal law, regardless of what's in between.
2. It's molecule-to-molecule collision everywhere — a vibrating molecule bumps its neighbor, which bumps the next, whether that's in the solid mug wall, the moving air, or the thermos gap.
3. Each situation genuinely needs a different physical carrier, because a vacuum gap has no molecules available to do any bumping at all.` },
        { kind: "failures", md: `Candidate 1 predicts one rate law everywhere, but measured heat-loss rates don't behave that way: heat lost across an evacuated gap doesn't scale simply with the temperature difference the way conduction does. For an object starting $10\\,\\text{K}$ above $290\\,\\text{K}$ surroundings, quadrupling that excess to $40\\,\\text{K}$ multiplies the radiated power by only about $4.6\\times$, not the $4\\times$ a linear (conduction-like) law would give — a small but telling mismatch, because the true dependence turns out to be on $T^4-T_s^4$ (absolute temperatures), not on $\\Delta T$ alone. Meanwhile heat lost through a solid wall scales simply and linearly with the temperature difference. Two different scaling behaviors can't come from one universal law.
Candidate 2 fails outright at the vacuum gap: with no molecules present to collide, there is nothing to "bump" the energy along neighbor to neighbor — and yet the thermos indisputably still loses heat, just slowly. Something is carrying energy across empty space with zero matter in transit.` },
        { kind: "discovery", md: `Three distinct carriers are actually at work. In the solid mug wall, energy hops from vibrating molecule to vibrating molecule (and, in metals, via free electrons) with no bulk material actually moving — this is **conduction**. Above the coffee, a parcel of air heated by the surface expands (heating anything makes it expand slightly, lowering its density) and becomes buoyant, so it physically rises and carries its extra energy away with it as it moves — this is **convection**, and it's only possible because thermal expansion makes hot fluid less dense than cold fluid nearby. Across the thermos's vacuum gap, no medium is needed at all: any object above absolute zero continuously emits electromagnetic (infrared) radiation, which carries energy at the speed of light through empty space — this is **radiation**. All three mechanisms drive the net flow to zero once both objects reach the same temperature, but each has its own distinct rate law, which is exactly what explained the different scaling behaviors that killed candidate 1.` },
        { kind: "formal", md: `**Thermal expansion** (the density change that powers *natural* convection): for an isotropic solid — one that expands by the same fractional amount in every direction — a linear dimension grows as $\\Delta L/L \\approx \\alpha\\,\\Delta T$ (linear expansion coefficient $\\alpha$). Since volume $V=L^3$, a small fractional length change of $\\alpha\\,\\Delta T$ in each of the three (identical, by isotropy) dimensions combines (to first order, ignoring the tiny cross terms) to $$\\frac{\\Delta V}{V} \\approx 3\\alpha\\,\\Delta T.$$

**Conduction** (Fourier's law): rate of heat flow through a slab of area $A$, thickness $d$, thermal conductivity $k$, across temperature difference $\\Delta T$: $$\\frac{dQ}{dt} = \\frac{kA\\,\\Delta T}{d}.$$ Defining a **thermal resistance** $R \\equiv d/(kA)$ turns this into $dQ/dt = \\Delta T/R$ — exactly Ohm's-law form, so multiple layers stacked in series (heat must pass through each in turn) combine the same way series resistors do: $R_{\\text{total}} = \\sum_i R_i$. Insulation is often instead rated by an area-specific resistance $R'' \\equiv d/k$ (units $\\text{m}^2\\text{K/W}$, independent of the slab's area), related to the full resistance by $R = R''/A$; these area-specific values add in series the same way.

**Convection**: heat carried away by moving fluid, either *natural* (buoyancy-driven, powered by the density drop from thermal expansion, as in the rising air above the coffee) or *forced* (fan- or pump-driven flow). Both are modeled, qualitatively, by Newton's law of cooling: $$\\frac{dQ}{dt} = hA\\,\\Delta T$$ — same linear-in-$\\Delta T$ form as conduction. The coefficient $h$ is roughly constant for forced convection (fixed flow speed sets a stable $h$), but only approximately constant for natural convection, where $h$ itself depends weakly on $\\Delta T$ since a larger temperature excess drives stronger buoyant flow.

**Radiation** (Stefan-Boltzmann, net exchange between an object at $T$ and surroundings at $T_s$): $$\\frac{dQ}{dt} = \\epsilon\\sigma A\\,(T^4 - T_s^4),$$ with emissivity $\\epsilon$ (1 for an ideal blackbody) and the Stefan-Boltzmann constant $\\sigma \\approx 5.67\\times10^{-8}\\,\\text{W/(m}^2\\text{K}^4\\text{)}$. Note that only **radiation** uses *absolute* temperature raised to the fourth power — conduction and convection depend on the temperature *difference* $\\Delta T$ linearly.` },
        { kind: "apply", md: `Back to the coffee mug: heat crosses the thin ceramic wall by conduction (short distance, moderate $k$, so a sizeable rate for a modest $\\Delta T$); heat leaves the liquid surface into the room mainly by natural convection, as warmed, thermally-expanded air continuously rises away and is replaced by cooler air; radiation is present too but, near room temperature, is small compared to the other two — until the object gets hot. A hot stove element near $900\\,\\text{K}$ radiates enormously more than the same object would at $300\\,\\text{K}$, *with surroundings negligible by comparison in both cases*: since $(900/300)^4 = 3^4 = 81$, tripling absolute temperature multiplies emitted power by $81\\times$, which is why radiation dominates for furnaces and stars but is a minor correction for a coffee mug near room temperature.` },
        { kind: "transfer", md: `The GRE-relevant reflex: check whether a problem's temperature scaling is linear in $\\Delta T$ (conduction, convection — a doubled temperature *difference* doubles the rate) or quartic in *absolute* $T$ (radiation, with surroundings negligible — a doubled absolute temperature multiplies emitted power by $16$). Confusing "twice as hot" (absolute $T$) with "twice the temperature difference" ($\\Delta T$) is a classic trap on radiation problems. Series thermal resistance reusing the electrical-resistance addition rule is the same "add up the equivalent local resistances" structure as circuits (see the EM module) — recognizing a shared mathematical skeleton across different physics is worth more than memorizing each formula separately.` }
      ],
      checkpoints: [
        { q: "A metal rod's length increases by $0.1\\%$ when heated by some $\\Delta T$. Its volume increases by approximately:", options: ["$0.1\\%$", "$0.3\\%$", "$0.033\\%$", "$0.01\\%$"], answer: 1, explain: "$\\Delta V/V \\approx 3\\,\\Delta L/L$, so a $0.1\\%$ linear change gives approximately a $0.3\\%$ volume change." },
        { q: "Doubling the absolute temperature of a blackbody radiator (surroundings held near $0\\,\\text{K}$) multiplies its radiated power by:", options: ["$2$", "$4$", "$8$", "$16$"], answer: 3, explain: "Radiated power scales as $T^4$; doubling $T$ multiplies power by $2^4=16$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-adiabatic",
      title: "Adiabatic vs. Isothermal Processes",
      minutes: 12,
      discovery: "A fast compression heats the gas because there's no time for heat to escape — the process obeys $PV^\\gamma=\\text{const}$, not $PV=\\text{const}$.",
      sections: [
        { kind: "problem", md: `Push down hard and fast on a bicycle pump with the outlet blocked: the barrel gets noticeably hot, even though you added no heat — you only did mechanical work. But the ideal gas law $PV=nRT$ says nothing about *how fast* you compress; it's a relation between equilibrium states. If you compress the same gas by the same volume ratio very slowly instead, submerged in a water bath, it barely warms at all. Same $\\Delta V$, same $P$'s and $V$'s satisfying the same $PV=nRT$ at each end — so why is the temperature outcome different?` },
        { kind: "candidates", md: `**A. Assume the process is isothermal — $PV=\\text{const}$ — since the ideal gas law is always true.**

**B. The ideal gas law only relates $P$, $V$, $T$ *at each instant*; it doesn't by itself tell you the *path* between two states, so something else must fix that path.**` },
        { kind: "failures", md: `**A fails for the fast pump.** $PV=nRT=\\text{const}$ at fixed $T$ predicts zero temperature change for any compression — flatly contradicted by the hot barrel. The gas law alone under-determines the process: $P$, $V$, $T$ are related, but the *relationship between $\\Delta P$ and $\\Delta V$ along a specific process* depends on what's happening to the heat, which the gas law says nothing about.

So B is right that something extra is needed — the missing ingredient is the first law plus a statement about heat exchange with the surroundings.` },
        { kind: "discovery", md: `The fast pump compression happens on a timescale much shorter than heat can conduct out through the barrel walls — essentially no heat is exchanged, $dQ\\approx 0$ (**adiabatic**). The slow, water-bath compression happens on a timescale long enough that heat continuously leaks out to keep $T$ fixed (**isothermal**). These are two different constraints on the *same* first law, $dU=dQ-P\\,dV$, and they produce two different $P$–$V$ relations. Speed of the process relative to the thermal relaxation time is what selects which one applies.` },
        { kind: "formal", md: `For an adiabatic process on an ideal gas, $dQ=0$ so $dU=-P\\,dV$. Using $dU = nC_V\\,dT$ and $PV=nRT$ (so $dT = d(PV)/(nR)$), substitution and integration give
$$PV^\\gamma = \\text{const}, \\qquad \\gamma \\equiv \\frac{C_P}{C_V} > 1$$
compared with the isothermal relation $PV=\\text{const}$ (i.e., $\\gamma\\to1$ formally). Since $\\gamma>1$, the adiabatic curve is *steeper* than the isothermal one on a $P$–$V$ diagram at the same point: adiabatic compression raises $P$ (and $T$) faster than isothermal compression for the same $\\Delta V$.` },
        { kind: "apply", md: `Monatomic ideal gas ($\\gamma=5/3$) adiabatically compressed to half its volume: $P_2 = P_1(V_1/V_2)^\\gamma = P_1\\cdot 2^{5/3}\\approx 3.17\\,P_1$. Isothermal compression to the same volume would only give $P_2=2P_1$ — the adiabatic case ends at higher pressure because the same compression work isn't shared out to an escaping heat flow, so it also raises $T$.` },
        { kind: "transfer", md: `"Fast" and "slow" are always relative to a relaxation timescale — this exact adiabatic/isothermal split reappears for sound waves (adiabatic, since compressions/rarefactions are too fast for heat to equilibrate — this is why the speed of sound uses $\\gamma$, not $1$) and for any system driven faster or slower than it can relax.` }
      ],
      checkpoints: [
        { q: "Why does rapid compression heat a gas while slow compression at the same volume ratio does not?", options: ["Rapid compression does more total work", "Rapid compression is adiabatic (no time for heat to escape); slow compression is isothermal", "Fast molecules collide more elastically", "Pressure has no effect on temperature"], answer: 1, explain: "Both do compression work, but the isothermal process lets that energy leak out as heat to keep $T$ fixed, while the adiabatic process keeps all of it as $\\Delta U$." },
        { q: "For an ideal gas, $\\gamma = C_P/C_V$ is always:", options: ["Less than 1", "Exactly 1", "Greater than 1", "Negative"], answer: 2, explain: "$C_P = C_V + nR > C_V$ for any ideal gas, so $\\gamma>1$ always." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-carnot",
      title: "Heat Engines and the Carnot Bound",
      minutes: 13,
      discovery: "No heat engine operating between two temperatures can beat the Carnot efficiency $1-T_c/T_h$ — and that bound depends on nothing but the two temperatures.",
      sections: [
        { kind: "problem", md: `You want to build an engine that takes in heat from a hot reservoir (burning fuel) and outputs mechanical work, running in a repeating cycle. What's the best possible efficiency $\\eta = W/Q_h$ you could ever achieve, and does it depend on how cleverly you engineer the pistons, the working fluid, the gear ratios?` },
        { kind: "candidates", md: `**A. With good enough engineering, efficiency can approach 100% ($\\eta\\to1$) — convert essentially all the input heat into work.**

**B. Efficiency is capped by something in the design of the engine — the choice of working fluid, cycle shape, materials — so a sufficiently exotic engine could beat any efficiency another engine achieves.**` },
        { kind: "failures", md: `**A fails on cyclic operation.** A cyclic engine returns to its starting state every cycle, so it can't simply keep accumulating internal energy — it must also dump some waste heat $Q_c$ to a cold reservoir. If a $\\eta=1$ engine existed, its work output could drive an ordinary refrigerator pumping heat from a cold reservoir to a hot one; since the $\\eta=1$ engine itself needed no waste heat rejected anywhere, the *net* combined effect is heat flowing from cold to hot with zero external work input overall — exactly what the Clausius statement of the second law forbids. Empirically, no engine has ever achieved $\\eta=1$ either.

**B fails once you compare two reversible engines.** Suppose engine X (reversible) runs between $T_h$ and $T_c$ with efficiency $\\eta_X$, and engine Y (also reversible, different design) runs between the *same* two reservoirs with $\\eta_Y>\\eta_X$. Run Y forward to drive X backward (as a refrigerator, using Y's output work). Net effect: heat is pumped from cold to hot reservoir with *zero net work input* — again forbidden by the second law. So no design trick can make one reversible engine beat another between the same two reservoirs: efficiency for a reversible engine can only depend on $T_h,T_c$, not on the engine's internal design.` },
        { kind: "discovery", md: `Since design doesn't matter for a reversible engine, compute the efficiency for *any* convenient reversible cycle and the answer applies to all of them. The **Carnot cycle** — two isotherms (heat exchange at constant $T$) connected by two adiabats (no heat exchange, just work) — is the simplest to compute exactly, and gives the universal bound.` },
        { kind: "formal", md: `For the Carnot cycle, heat absorbed at $T_h$ is $Q_h$, heat rejected at $T_c$ is $Q_c$, and the reversible isotherms give $Q_c/Q_h = T_c/T_h$. Efficiency:
$$\\eta_{Carnot} = 1 - \\frac{Q_c}{Q_h} = 1 - \\frac{T_c}{T_h}$$
Any real (irreversible) engine operating between the same two reservoirs must satisfy $\\eta \\le \\eta_{Carnot}$ — the equality holds only in the reversible limit. This is a hard ceiling, not an engineering target that ambitious enough design could exceed.` },
        { kind: "apply", md: `A power plant's steam runs between $T_h=800\\text{ K}$ and $T_c=300\\text{ K}$: $\\eta_{max} = 1-300/800 = 0.625$, i.e. at most $62.5\\%$ of the input heat can become work, no matter the turbine design — the rest is fundamentally unavailable, not merely "lost to friction."` },
        { kind: "transfer", md: `This is a proof-by-contradiction bound: instead of computing a limit by exhausting all possible designs, you show that *any* violation lets you build a perpetual-motion-adjacent contraption, which is forbidden on other grounds. The same proof technique (assume a violation, combine two instances to break a known law) reappears whenever physics states a fundamental "you cannot beat this bound" result.` }
      ],
      checkpoints: [
        { q: "Two different reversible engines operate between the same $T_h$ and $T_c$. Their efficiencies must be:", options: ["Equal, regardless of design", "Different, favoring the more complex design", "Unrelated to each other", "Both exactly 1"], answer: 0, explain: "If they differed, running the more efficient one forward and the less efficient one in reverse would pump heat from cold to hot with no net work input, violating the second law." },
        { q: "A reversible engine operates between $500\\text{ K}$ and $250\\text{ K}$. Its maximum possible efficiency is:", options: ["25%", "50%", "75%", "100%"], answer: 1, explain: "$\\eta = 1 - T_c/T_h = 1 - 250/500 = 0.50$." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-entropy",
      title: "Entropy: From Clausius to Counting Microstates",
      minutes: 15,
      discovery: "Entropy measures the number of microscopic arrangements consistent with a macroscopic state, and irreversibility is just the overwhelming statistical pull toward more of them.",
      sections: [
        { kind: "problem", md: `Open a valve connecting a gas-filled chamber to an evacuated one: the gas rushes in and fills both. Energy is exactly conserved in this process — and it would *also* be exactly conserved if you ran the movie backward and watched all the gas spontaneously crowd back into the first chamber. Yet you never see that happen. What distinguishes the forward direction from the backward one, if energy conservation permits both equally?` },
        { kind: "candidates", md: `**A. Processes that decrease the total energy of the system are forbidden; the ones we see are the energy-decreasing ones.**

**B. The forward direction is simply the one where the gas ends up more "spread out" or "disordered" — vague, but suggestive.**` },
        { kind: "failures", md: `**A fails immediately** — free expansion doesn't change the gas's internal energy at all ($\\Delta U=0$, since no work is done and no heat is exchanged with anything). Both the forward (spread out) and hypothetical backward (crowd back in) versions conserve energy exactly equally, so energy alone cannot be what selects the arrow of time here.

**B is on the right track but needs to be made precise.** "Disordered" isn't a number you can compute — you need a way to *count* just how many microscopic arrangements correspond to "gas spread through both chambers" versus "gas crowded in one chamber," and show the first number dwarfs the second.` },
        { kind: "discovery", md: `Historically, Clausius first defined a new state function purely thermodynamically — via $dS = dQ_{rev}/T$ along any *reversible* path connecting two states — and showed spontaneous (irreversible) processes in an isolated system always have $\\Delta S \\ge 0$. This works, but doesn't yet explain *why*. The statistical answer, due to Boltzmann: count $\\Omega$, the number of distinct microscopic arrangements (microstates) compatible with a given macroscopic description (macrostate). For $N$ gas molecules free to be in either of two equal chambers, the "spread through both" macrostate has enormously more compatible microstates than "all crowded in one chamber" — spontaneous evolution toward the free-expansion macrostate isn't a violation of any law, it's just overwhelmingly more likely, the same way shuffling a sorted deck is overwhelmingly likely to land on a "disordered-looking" arrangement (there are vastly more of those).` },
        { kind: "formal", md: `**Boltzmann's formula:** $S = k\\ln\\Omega$, connecting the thermodynamic entropy directly to the microstate count. The two definitions agree: computing $\\Delta S$ via Clausius (using a convenient reversible path between the same two endpoints, since $S$ is a state function and path-independent) gives the same answer as computing $k\\ln(\\Omega_f/\\Omega_i)$ directly.

**Second law:** the entropy of an isolated system never decreases, $\\Delta S \\ge 0$, with equality only for reversible processes.` },
        { kind: "apply", md: `Ideal gas of $N$ molecules doubles its volume in free expansion ($\\Delta U=0$, so $T$ unchanged).

*Clausius route:* substitute a reversible isothermal expansion between the same endpoints. For that path, $\\Delta U=0 \\Rightarrow Q=W=\\int_V^{2V}\\frac{NkT}{V'}dV' = NkT\\ln 2$, so $\\Delta S = Q/T = Nk\\ln 2$.

*Counting route:* each molecule independently has twice as many positions available, so $\\Omega_f/\\Omega_i = 2^N$, giving $\\Delta S = k\\ln(2^N) = Nk\\ln2$. Same answer, two routes — the microscopic count and the macroscopic heat bookkeeping agree exactly.` },
        { kind: "transfer", md: `"Nature evolves toward the more probable state, not the lower-energy one" is the deepest idea in this module — it's why heat flows hot-to-cold (more microstates available to the combined system that way), why mixing is irreversible, and it's the direct ancestor of Shannon's information entropy, which is $-\\sum p_i \\ln p_i$ for exactly the same counting reason.` }
      ],
      checkpoints: [
        { q: "Free expansion of an ideal gas into a vacuum conserves energy exactly. It's irreversible because:", options: ["Energy is secretly lost as heat", "The spread-out macrostate has far more compatible microstates than the crowded one", "Entropy is undefined for irreversible processes", "The second law only applies to engines"], answer: 1, explain: "$\\Omega_{spread} \\gg \\Omega_{crowded}$, so $S=k\\ln\\Omega$ is enormously larger after expansion; the reverse process is not forbidden, just statistically negligible." },
        { q: "Doubling the volume of $N$ molecules of ideal gas isothermally changes the entropy by:", options: ["$Nk$", "$Nk\\ln2$", "$\\tfrac32 Nk$", "0"], answer: 1, explain: "$\\Delta S = Nk\\ln(V_f/V_i) = Nk\\ln2$ for isothermal doubling of volume." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-boltzmann",
      title: "The Boltzmann Factor and Partition Function",
      minutes: 14,
      discovery: "In contact with a heat bath, the probability of any microstate falls off as $e^{-E/kT}$ — one formula that generates essentially all of statistical mechanics.",
      sections: [
        { kind: "problem", md: `A single atom sits in a huge gas at temperature $T$, exchanging energy constantly with its neighbors through collisions. At any instant, what's the probability that *this particular atom* happens to be found in a microstate of energy $E$? You need this to predict almost anything: the distribution of molecular speeds, the fraction of spins pointing up in a magnetic field, the rate of a chemical reaction that requires a minimum activation energy.` },
        { kind: "candidates", md: `**A. All accessible microstates are equally probable, regardless of energy.**

**B. Probability falls off with energy somehow — try $P(E)\\propto 1/E$ as a simple guess.**` },
        { kind: "failures", md: `**A fails observationally.** Stand near a candle flame: the "high-energy" microstates (fast-moving air molecules) are clearly *not* as common as low-energy ones far from the flame — hot spots are the exception, not the norm, and this asymmetry has to come from somewhere. Equal-probability also gives no role at all to temperature, which is absurd — raising $T$ obviously changes which energies are common.

**B fails multiple ways at once.** $1/E$ blows up at $E=0$ (nonsensical), has no temperature dependence anywhere in it (so it can't distinguish a hot bath from a cold one), and doesn't reduce to anything sensible in any limit. It's a guess with no derivation behind it and no natural place for $T$ to enter.` },
        { kind: "discovery", md: `Treat the atom-plus-bath as one big isolated system with total energy fixed. By the *same* microstate-counting logic from the entropy lesson, the combined system overwhelmingly favors whichever split of energy between atom and bath maximizes the *total* number of microstates. Since the bath is enormous, giving the small atom slightly more energy $E$ costs the bath a specific, calculable amount of its own entropy (because it has slightly less energy left to distribute). Working through that trade-off (a short calculation using $S_{bath}=k\\ln\\Omega_{bath}(E_{total}-E)$ and a first-order expansion in $E$) shows the atom's probability of being in a state of energy $E$ falls off *exponentially*: $P(E)\\propto e^{-E/kT}$.` },
        { kind: "formal", md: `**Boltzmann factor:** $P(E_i) \\propto e^{-E_i/kT}$, often written with $\\beta\\equiv 1/kT$. Normalizing over all accessible microstates $i$ defines the **partition function**
$$Z = \\sum_i e^{-\\beta E_i}, \\qquad P(E_i) = \\frac{e^{-\\beta E_i}}{Z}$$
$Z$ packages essentially all thermodynamics of the system: average energy $\\langle E\\rangle = -\\dfrac{\\partial \\ln Z}{\\partial \\beta}$, and free energy, entropy, and heat capacity all follow from derivatives of $\\ln Z$.` },
        { kind: "apply", md: `Two-level system: spin down at energy $0$, spin up at energy $\\Delta E$ in a field. $Z = 1+e^{-\\Delta E/kT}$, and the population ratio is
$$\\frac{n_\\uparrow}{n_\\downarrow} = \\frac{e^{-\\Delta E/kT}}{e^{0}} = e^{-\\Delta E/kT}$$
As $T\\to0$, this ratio $\\to0$ (everything in the ground state); as $T\\to\\infty$, it $\\to1$ (equal populations) — both limits match intuition, a good sanity check on the formula.` },
        { kind: "transfer", md: `This is "the one tool" of thermal physics: Maxwell–Boltzmann speed distributions, the exponential suppression behind Arrhenius reaction rates, the Boltzmann factor governing chemical and nuclear equilibria, and (with a twist for indistinguishable particles) blackbody radiation and quantum statistics — all of them are this same $e^{-E/kT}$ applied to a different energy ladder.` }
      ],
      checkpoints: [
        { q: "The Boltzmann factor $P(E)\\propto e^{-E/kT}$ arises because:", options: ["High-energy states are intrinsically forbidden", "Giving a small system more energy costs the much larger bath entropy, and the bath's entropy loss dominates the combined count", "Energy must always be minimized", "It is an empirical fit with no derivation"], answer: 1, explain: "Maximizing total microstates of system+bath under fixed total energy, with the bath enormous, produces the exponential falloff." },
        { q: "As $T\\to\\infty$ in a two-level system, the ratio of upper- to lower-level populations approaches:", options: ["0", "1", "$\\infty$", "$e$"], answer: 1, explain: "$e^{-\\Delta E/kT}\\to e^0=1$ as $T\\to\\infty$: the two levels become equally populated." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-equipartition",
      title: "Equipartition and Its Failure",
      minutes: 13,
      discovery: "Equipartition gives $\\tfrac12 kT$ per quadratic degree of freedom, but it silently assumes energy is continuous — and when a mode's spacing exceeds $kT$, that mode freezes out.",
      sections: [
        { kind: "problem", md: `Kinetic theory predicted $\\langle KE\\rangle = \\tfrac32 kT$ per monatomic molecule (three translational directions, $\\tfrac12 kT$ each) and it matches measured $C_V=\\tfrac32 R$ for monatomic gases beautifully. Diatomic molecules (like $\\text{N}_2$) should have *more* ways to store energy — translation (3), rotation (2, since spinning about the bond axis stores negligible energy), and vibration (2, one for kinetic and one for potential energy of the bond stretch) — for a predicted $C_V = \\tfrac72 R$. Measured room-temperature $C_V$ for $\\text{N}_2$ is $\\tfrac52 R$, not $\\tfrac72 R$. Where did two whole degrees of freedom's worth of heat capacity go?` },
        { kind: "candidates", md: `**A. The prediction is basically right; vibration must just be there, contributing weakly, and better measurement would reveal it.**

**B. Vibration takes a very long time to equilibrate with translation/rotation, so at room temperature it just hasn't "caught up" yet — given enough time, $C_V$ should still reach $\\tfrac72 R$.**` },
        { kind: "failures", md: `**A fails against precision measurement.** The discrepancy is not a small correction — vibrational modes contribute essentially *zero* to $C_V$ at room temperature, then turn on sharply as $T$ rises into the thousands of kelvin (measured directly). That's not a weak-but-present effect; it's an on/off switch, which a "just slightly under-measured" story can't produce.

**B fails against a controlled time test.** Leave the gas at room temperature in perfect thermal equilibrium for arbitrarily long — days, weeks — and $C_V$ still doesn't budge from $\\tfrac52 R$. This isn't a kinetic bottleneck (slow equilibration); it's a genuine, permanent energy independence: vibration is *not* contributing, at *equilibrium*, indefinitely.` },
        { kind: "discovery", md: `The equipartition derivation (via the Boltzmann factor, integrating $E\\,e^{-\\beta E}$ over a *continuous* range of $E$ for each quadratic term) silently assumes each mode can absorb energy in arbitrarily small increments. If a mode's actual allowed energies are instead separated by discrete steps of size $\\varepsilon$, and $\\varepsilon \\gg kT$, the Boltzmann factor $e^{-\\varepsilon/kT}$ for reaching even the *first* excited level is astronomically small — the mode is overwhelmingly stuck in its ground state and contributes essentially nothing to the heat capacity, no matter how long you wait. Vibrational level spacing in $\\text{N}_2$ happens to be large compared to $kT$ at room temperature ($\\varepsilon/k \\sim 3000\\text{ K}$ for $\\text{N}_2$), which is exactly why it's "frozen out" until $T$ climbs into that range.` },
        { kind: "formal", md: `**Equipartition theorem (classical, continuous-energy assumption):** each degree of freedom whose energy appears quadratically (e.g. $\\tfrac12 mv_x^2$, $\\tfrac12 I\\omega^2$, $\\tfrac12 kx^2$) contributes $\\tfrac12 kT$ to the average energy, hence $\\tfrac12 k$ to $C_V$ per mole-degree-of-freedom (times $R$ per mole). This holds *only* when the mode's discrete level spacing $\\varepsilon \\ll kT$; when $\\varepsilon \\gg kT$ that mode is frozen out, and a full quantum treatment (harmonic-oscillator energy levels, later lesson) replaces the classical prediction with one that correctly interpolates between "frozen" and "fully classical."` },
        { kind: "apply", md: `Sketch: $C_V(T)$ for $\\text{H}_2$ rises in steps as $T$ increases — $\\tfrac32R$ (translation only, very cold), then a rise toward $\\tfrac52R$ once rotational spacing ($\\varepsilon/k\\sim 85\\text{ K}$ for $\\text{H}_2$) becomes $\\ll kT$, then a further rise toward $\\tfrac72R$ only once $T$ approaches vibrational spacing ($\\varepsilon/k \\sim 6000\\text{ K}$ for $\\text{H}_2$). Each plateau is a mode "waiting" for $kT$ to catch up to its spacing.` },
        { kind: "transfer", md: `Any time a classical continuum prediction (equipartition, or the blackbody spectrum in the next lesson) fails specifically at *low temperature or high frequency* while working fine elsewhere, that's the historical fingerprint of quantization — discreteness matters only when the level spacing is comparable to or larger than the thermal energy scale $kT$ available to probe it.` }
      ],
      checkpoints: [
        { q: "A mode with discrete energy-level spacing $\\varepsilon \\gg kT$ will:", options: ["Contribute the full classical $\\tfrac12 kT$ regardless", "Contribute essentially zero to the heat capacity — it's frozen out", "Contribute negative heat capacity", "Equilibrate slowly but eventually reach $\\tfrac12kT$"], answer: 1, explain: "The Boltzmann factor for reaching the first excited level, $e^{-\\varepsilon/kT}$, is vanishingly small, so the mode stays in its ground state at equilibrium — not a kinetic delay, a genuine equilibrium effect." },
        { q: "Room-temperature $\\text{N}_2$ has measured $C_V \\approx \\tfrac52R$ rather than the fully classical $\\tfrac72R$ because:", options: ["Rotation is frozen out at room temperature", "Vibration is frozen out at room temperature", "Translation is frozen out at room temperature", "$\\text{N}_2$ is not an ideal gas"], answer: 1, explain: "Vibrational spacing ($\\sim3000\\text{ K}$ in temperature units) is far above room temperature, so it doesn't contribute; rotation ($\\sim3\\text{ K}$) is fully active." }
      ]
    },
    // ---------------------------------------------------------------
    {
      id: "thermo-blackbody",
      title: "Blackbody Radiation and the Quantum Statistics",
      minutes: 15,
      discovery: "Quantizing the energy of each electromagnetic mode kills the ultraviolet catastrophe and reproduces the observed blackbody spectrum — the same fix that saved equipartition.",
      sections: [
        { kind: "problem", md: `A hot cavity (like a kiln, or a star) radiates electromagnetic energy across a spectrum that peaks at some frequency and falls off on both sides — total power scales roughly as $T^4$. Classical E&M says the cavity supports standing electromagnetic wave modes at every frequency, with the number of modes in a frequency range $d\\nu$ growing as $\\nu^2\\,d\\nu$ (more ways to fit more wiggles in the same box at higher frequency). Equipartition says each mode should carry average energy $kT$. Multiply those together and the predicted total radiated power *diverges* — infinite energy in the ultraviolet. Real ovens do not incinerate the universe when you turn them on. Where does the classical argument break?` },
        { kind: "candidates", md: `**A. The cavity must have some maximum frequency cutoff from its finite size, which stops the divergence.**

**B. Equipartition itself must be simply wrong, even at everyday temperatures.**` },
        { kind: "failures", md: `**A fails:** a cavity of any size supports arbitrarily high-frequency standing waves (just more nodes packed into the same length) — there's no finite-size cutoff in classical electromagnetism, and the catastrophe persists for a cavity of any size.

**B fails:** equipartition matches measured gas heat capacities extremely well at ordinary temperatures (previous lesson) — it can't be *simply* wrong; it must be a good approximation *in some regime* and break down in another, which points back to the frozen-out-mode idea rather than outright rejection.` },
        { kind: "discovery", md: `Apply exactly the equipartition fix from the previous lesson to electromagnetic modes: quantize the energy of a mode at frequency $\\nu$ in units of $h\\nu$ (so its allowed energies are $0,h\\nu,2h\\nu,\\dots$), and redo the Boltzmann-factor average instead of assuming a continuum. Low-frequency modes have $h\\nu \\ll kT$ and behave classically (contributing $\\approx kT$, matching the old result); high-frequency modes have $h\\nu \\gg kT$ and are exponentially suppressed, exactly as vibrational modes were frozen out — this kills the $\\nu^2$ growth before it can diverge.` },
        { kind: "formal", md: `**Planck's law:** average energy per mode at frequency $\\nu$ is
$$\\langle E(\\nu)\\rangle = \\frac{h\\nu}{e^{h\\nu/kT}-1}$$
which $\\to kT$ for $h\\nu\\ll kT$ (recovering the classical result at low frequency) and $\\to h\\nu\\,e^{-h\\nu/kT}\\to0$ for $h\\nu\\gg kT$ (killing the ultraviolet catastrophe). Integrating over all modes gives the **Stefan–Boltzmann law** $P = \\sigma A T^4$ and **Wien's displacement law** $\\lambda_{max}T = \\text{const} \\approx 2.90\\times10^{-3}\\text{ m K}$.

*Recognition level, GRE-relevant:* photons obey **Bose–Einstein statistics** (any number of photons can occupy one mode, giving the $e^{h\\nu/kT}-1$ denominator above); electrons and other spin-$\\tfrac12$ particles obey **Fermi–Dirac statistics** (Pauli exclusion allows at most one particle per state, giving a $e^{E/kT}+1$ denominator instead). For photons (zero chemical potential), both statistics reduce to the classical Boltzmann factor whenever the mode energy is large, $e^{h\\nu/kT}\\gg1$ — the same high-frequency regime where Planck's law already matches the classical result. Separately, the **thermodynamic potentials** $U$, $H=U+PV$, $F=U-TS$ (Helmholtz), $G=H-TS$ (Gibbs) are Legendre transforms of one another suited to different fixed variables, and **Maxwell relations** (e.g. $\\left(\\frac{\\partial S}{\\partial V}\\right)_T = \\left(\\frac{\\partial P}{\\partial T}\\right)_V$) follow from the equality of mixed partial derivatives of these potentials — the GRE tests recognizing and applying these, not re-deriving them.` },
        { kind: "apply", md: `Estimate the Sun's peak emission wavelength from its surface temperature $T\\approx5800\\text{ K}$:
$$\\lambda_{max} = \\frac{2.90\\times10^{-3}\\text{ m K}}{5800\\text{ K}} \\approx 5.0\\times10^{-7}\\text{ m} = 500\\text{ nm}$$
— squarely in the visible (green) part of the spectrum, consistent with sunlight looking roughly white/yellow to eyes evolved under it.` },
        { kind: "transfer", md: `The ultraviolet catastrophe and the diatomic-gas heat-capacity anomaly are the *same* mathematical resolution applied to two different physical modes — this repeated pattern (classical continuum theory diverges or over-predicts $\\Rightarrow$ quantize $\\Rightarrow$ agreement restored) is the historical throughline into all of quantum mechanics, picked up again from the start in the next module.` }
      ],
      checkpoints: [
        { q: "The ultraviolet catastrophe in blackbody radiation is resolved by:", options: ["A finite cavity size cutting off high frequencies", "Quantizing each mode's energy in units of $h\\nu$, suppressing high-frequency modes via the Boltzmann factor", "Rejecting equipartition entirely", "Assuming light has no wave modes above the visible range"], answer: 1, explain: "High-frequency modes require $h\\nu \\gg kT$ to reach even their first excited state, making them exponentially rare — the same frozen-out-mode mechanism as vibrational heat capacity." },
        { q: "Photons obey Bose–Einstein statistics, meaning:", options: ["At most one photon can occupy a given mode", "Any number of photons can occupy the same mode", "Photons cannot be created or destroyed", "Photon energy is never quantized"], answer: 1, explain: "Unlike fermions (Pauli exclusion), bosons like photons can pile up arbitrarily many to a mode — this is what gives Planck's formula its $e^{h\\nu/kT}-1$ denominator rather than $+1$." }
      ]
    }
  ],

  drills: [
    // thermo-temperature
    { id: "thermo-temperature-d1", lesson: "thermo-temperature", type: "mc", prompt: "The zeroth law of thermodynamics is the logical basis for defining:", options: ["Entropy", "Temperature as a well-defined state variable", "The first law", "Absolute zero"], answer: 1, hint: "It's about equilibrium being transitive.", solution: "Transitivity of thermal equilibrium (A~C, B~C imply A~B) is precisely what allows one number, temperature, to characterize equilibrium state for any object.", difficulty: 1, tags: ["thermo", "zeroth-law"] },
    { id: "thermo-temperature-d2", lesson: "thermo-temperature", type: "numeric", prompt: "A constant-volume gas thermometer reads $P=0.750\\text{ atm}$ at the triple point of water ($T=273.16\\text{ K}$). It reads $P=0.500\\text{ atm}$ in contact with a cold sample. Find the sample's temperature in kelvin.", answer: 182.1, tolerance: 0.02, unit: "K", hint: "$T \\propto P$ at fixed volume for an ideal-gas thermometer.", solution: "$T = 273.16 \\times \\dfrac{0.500}{0.750} = 182.1\\text{ K}$.", difficulty: 1, tags: ["thermo", "zeroth-law"] },
    { id: "thermo-temperature-d3", lesson: "thermo-temperature", type: "mc", prompt: "Two blocks feel like they're at different temperatures when touched, but a thermometer shows they're identical. This is because:", options: ["The thermometer is wrong", "Touch senses heat flow rate (conductivity-dependent), not temperature directly", "The blocks are not really in equilibrium", "Temperature is not a real physical quantity"], answer: 1, hint: "Think about the metal-vs-wood scenario.", solution: "Perceived 'hot' or 'cold' by touch depends on thermal conductivity as much as on temperature; the thermometer, calibrated via the zeroth law, reports the actual state variable.", difficulty: 1, tags: ["thermo", "zeroth-law"] },
    { id: "thermo-temperature-d4", lesson: "thermo-temperature", type: "mc", prompt: "Which statement is the zeroth law of thermodynamics?", options: ["Energy is conserved in any process", "If A is in equilibrium with C, and B is in equilibrium with C, then A is in equilibrium with B", "Entropy of an isolated system never decreases", "No engine can be 100% efficient"], answer: 1, hint: "It's the one that comes 'before' the first law logically.", solution: "This transitivity statement is the zeroth law; the other three options are the first, second, and a corollary of the second law respectively.", difficulty: 1, tags: ["thermo", "zeroth-law"] },

    // thermo-kinetic-theory
    { id: "thermo-kinetic-theory-d1", lesson: "thermo-kinetic-theory", type: "mc", prompt: "In the kinetic-theory derivation, pressure arises physically from:", options: ["The average potential energy of the molecules", "Momentum transferred to the walls by colliding molecules", "Electrostatic repulsion between molecules", "The rotational energy of molecules"], answer: 1, hint: "Think about what a single molecule does at the wall.", solution: "Each elastic collision transfers momentum $2mv_x$ to the wall; summing over rate and molecules gives pressure as a force-per-area from these impacts.", difficulty: 1, tags: ["thermo", "kinetic-theory"] },
    { id: "thermo-kinetic-theory-d2", lesson: "thermo-kinetic-theory", type: "numeric", prompt: "Find $v_{rms}$ for helium atoms ($m=6.65\\times10^{-27}\\text{ kg}$) at $T=400\\text{ K}$.", answer: 1580, tolerance: 0.03, unit: "m/s", hint: "$v_{rms}=\\sqrt{3kT/m}$.", solution: "$v_{rms}=\\sqrt{3(1.38\\times10^{-23})(400)/6.65\\times10^{-27}} \\approx 1580\\text{ m/s}$.", difficulty: 2, tags: ["thermo", "kinetic-theory"] },
    { id: "thermo-kinetic-theory-d3", lesson: "thermo-kinetic-theory", type: "mc", prompt: "According to kinetic theory, average translational KE per molecule equals:", options: ["$kT$", "$\\tfrac32 kT$", "$\\tfrac12 kT$", "$3kT$"], answer: 1, hint: "Three translational degrees of freedom, $\\tfrac12kT$ each.", solution: "$\\tfrac12m\\langle v^2\\rangle = \\tfrac32 kT$, from combining $PV=\\tfrac13Nm\\langle v^2\\rangle$ with $PV=NkT$.", difficulty: 1, tags: ["thermo", "kinetic-theory"] },
    { id: "thermo-kinetic-theory-d4", lesson: "thermo-kinetic-theory", type: "mc", prompt: "At fixed volume, if the absolute temperature of an ideal gas is quadrupled, $v_{rms}$ is multiplied by:", options: ["2", "4", "8", "16"], answer: 0, hint: "$v_{rms}\\propto\\sqrt T$.", solution: "$v_{rms}\\propto\\sqrt T$, so quadrupling $T$ doubles $v_{rms}$.", difficulty: 1, tags: ["thermo", "kinetic-theory"] },
    { id: "thermo-kinetic-theory-d5", lesson: "thermo-kinetic-theory", type: "mc", prompt: "A heavier gas molecule at the same temperature as a lighter one has:", options: ["Higher average KE", "Lower average KE", "The same average KE but lower $v_{rms}$", "The same average KE and the same $v_{rms}$"], answer: 2, hint: "$\\tfrac12m\\langle v^2\\rangle = \\tfrac32kT$ depends on $T$ only, not $m$.", solution: "Average KE $=\\tfrac32kT$ depends only on $T$; since KE is fixed and $m$ is larger, $v_{rms}=\\sqrt{3kT/m}$ must be smaller.", difficulty: 2, tags: ["thermo", "kinetic-theory"] },

    // thermo-first-law
    { id: "thermo-first-law-d1", lesson: "thermo-first-law", type: "mc", prompt: "For an ideal gas, $C_P - C_V$ equals:", options: ["$0$", "$R$", "$\\tfrac32R$", "$\\gamma R$"], answer: 1, hint: "Follows from $H=U+PV=U+nRT$.", solution: "$C_P = (\\partial H/\\partial T)_P = C_V + nR$ per mole gives $C_P-C_V=R$ (molar).", difficulty: 1, tags: ["thermo", "first-law"] },
    { id: "thermo-first-law-d2", lesson: "thermo-first-law", type: "numeric", prompt: "1.5 mol of monatomic ideal gas is heated at constant volume, raising $T$ by $40\\text{ K}$. Find the heat added, in joules. ($R=8.31\\text{ J/(mol K)}$)", answer: 748, tolerance: 0.03, unit: "J", hint: "$Q=nC_V\\Delta T$, $C_V=\\tfrac32R$ for monatomic.", solution: "$Q = n C_V \\Delta T = 1.5 \\times \\tfrac32(8.31) \\times 40 \\approx 748\\text{ J}$.", difficulty: 2, tags: ["thermo", "first-law"] },
    { id: "thermo-first-law-d3", lesson: "thermo-first-law", type: "mc", prompt: "On a $P$–$V$ diagram, the work done by a gas during a process equals:", options: ["The slope of the curve", "The area under the curve", "The change in internal energy", "The heat capacity"], answer: 1, hint: "$W=\\int P\\,dV$.", solution: "$W=\\int P\\,dV$ is exactly the area under the $P$–$V$ curve between the initial and final volumes.", difficulty: 1, tags: ["thermo", "first-law"] },
    { id: "thermo-first-law-d4", lesson: "thermo-first-law", type: "mc", prompt: "A gas is compressed at constant volume, and its internal energy increases by 300 J with no work done. According to the first law, the heat added is:", options: ["0 J", "150 J", "300 J", "600 J"], answer: 2, hint: "$dU=dQ-dW$, $dW=0$.", solution: "$dV=0\\Rightarrow dW=0\\Rightarrow Q=\\Delta U = 300\\text{ J}$.", difficulty: 1, tags: ["thermo", "first-law"] },
    { id: "thermo-first-law-d5", lesson: "thermo-first-law", type: "mc", prompt: "For a diatomic ideal gas with vibration frozen out, $C_V=\\tfrac52R$. Its $C_P$ is:", options: ["$\\tfrac52R$", "$\\tfrac72R$", "$\\tfrac32R$", "$3R$"], answer: 1, hint: "$C_P=C_V+R$.", solution: "$C_P = \\tfrac52R + R = \\tfrac72R$.", difficulty: 1, tags: ["thermo", "first-law"] },

    // thermo-adiabatic
    { id: "thermo-heat-transfer-d1", lesson: "thermo-heat-transfer", type: "mc", prompt: "By Fourier's law $dQ/dt = kA\\Delta T/d$, doubling the thickness $d$ of a conducting slab (all else fixed) has what effect on the conduction rate?", options: ["Doubles it", "Halves it", "Quadruples it", "No effect"], answer: 1, hint: "Rate is inversely proportional to $d$.", solution: "$dQ/dt \\propto 1/d$, so doubling $d$ halves the rate — a thicker wall is a better insulator.", difficulty: 1, tags: ["thermo", "heat-transfer"] },
    { id: "thermo-heat-transfer-d2", lesson: "thermo-heat-transfer", type: "numeric", prompt: "A window pane has area $2\\,\\text{m}^2$, thickness $0.05\\,\\text{m}$, thermal conductivity $k=0.8\\,\\text{W/(m K)}$, and a temperature difference of $20\\,\\text{K}$ across it. Find the conduction rate, in watts.", answer: 640, tolerance: 0.03, unit: "W", hint: "$dQ/dt=kA\\Delta T/d$.", solution: "$dQ/dt = (0.8)(2)(20)/0.05 = 32/0.05 = 640\\,\\text{W}$.", difficulty: 2, tags: ["thermo", "heat-transfer"] },
    { id: "thermo-heat-transfer-d3", lesson: "thermo-heat-transfer", type: "numeric", prompt: "A steel rod of length $10\\,\\text{m}$ ($\\alpha=12\\times10^{-6}\\,\\text{K}^{-1}$) is heated by $30\\,\\text{K}$. Find its change in length, in mm.", answer: 3.6, tolerance: 0.03, unit: "mm", hint: "$\\Delta L = \\alpha L\\,\\Delta T$.", solution: "$\\Delta L = (12\\times10^{-6})(10)(30) = 3.6\\times10^{-3}\\,\\text{m} = 3.6\\,\\text{mm}$.", difficulty: 1, tags: ["thermo", "heat-transfer", "thermal-expansion"] },
    { id: "thermo-heat-transfer-d4", lesson: "thermo-heat-transfer", type: "mc", prompt: "For an isotropic solid, the volumetric expansion coefficient $\\beta$ relates to the linear expansion coefficient $\\alpha$ by:", options: ["$\\beta = \\alpha$", "$\\beta = 3\\alpha$", "$\\beta = \\alpha^3$", "$\\beta = \\alpha/3$"], answer: 1, hint: "Differentiate $V=L^3$ to first order.", solution: "$dV/V = 3\\,dL/L$ to first order, since each of the three dimensions contributes an equal fractional change, so $\\beta=3\\alpha$.", difficulty: 1, tags: ["thermo", "heat-transfer", "thermal-expansion"] },
    { id: "thermo-heat-transfer-d5", lesson: "thermo-heat-transfer", type: "numeric", prompt: "An object at $T=400\\,\\text{K}$ with emissivity $\\epsilon=1$, area $0.5\\,\\text{m}^2$, radiates to surroundings at $T_s=300\\,\\text{K}$. Find the net radiative power, in watts. ($\\sigma=5.67\\times10^{-8}\\,\\text{W/(m}^2\\text{K}^4\\text{)}$)", answer: 496, tolerance: 0.03, unit: "W", hint: "$dQ/dt=\\epsilon\\sigma A(T^4-T_s^4)$.", solution: "$T^4=2.56\\times10^{10}$, $T_s^4=8.1\\times10^9$; difference $=1.75\\times10^{10}$; $dQ/dt = (5.67\\times10^{-8})(0.5)(1.75\\times10^{10}) \\approx 496\\,\\text{W}$.", difficulty: 2, tags: ["thermo", "heat-transfer", "radiation"] },
    { id: "thermo-heat-transfer-d6", lesson: "thermo-heat-transfer", type: "mc", prompt: "Two insulating layers, each with thermal resistance $R$, are stacked in series (heat must cross one, then the other). The combined resistance to heat flow is:", options: ["$R/2$", "$R$", "$2R$", "$R^2$"], answer: 2, hint: "Thermal resistances in series add, just like electrical resistors in series.", solution: "$R_{\\text{total}}=R_1+R_2=R+R=2R$, mirroring series electrical resistance.", difficulty: 2, tags: ["thermo", "heat-transfer"] },
    { id: "thermo-adiabatic-d1", lesson: "thermo-adiabatic", type: "mc", prompt: "An adiabatic process is one in which:", options: ["Temperature is constant", "Pressure is constant", "No heat is exchanged with the surroundings", "Entropy always decreases"], answer: 2, hint: "$Q=0$ by definition.", solution: "Adiabatic means $dQ=0$ throughout the process; it need not be isothermal or reversible in general (though a reversible adiabat is also isentropic).", difficulty: 1, tags: ["thermo", "adiabatic"] },
    { id: "thermo-adiabatic-d2", lesson: "thermo-adiabatic", type: "numeric", prompt: "A monatomic ideal gas ($\\gamma=5/3$) at $P_1=1.0\\times10^5\\text{ Pa}$ is adiabatically compressed to one-third its original volume. Find the final pressure in units of $10^5\\text{ Pa}$.", answer: 6.24, tolerance: 0.03, unit: "$\\times10^5$ Pa", hint: "$P_2=P_1(V_1/V_2)^\\gamma$.", solution: "$P_2 = P_1\\cdot3^{5/3} \\approx 1.0\\times10^5\\times6.24 = 6.24\\times10^5\\text{ Pa}$.", difficulty: 2, tags: ["thermo", "adiabatic"] },
    { id: "thermo-adiabatic-d3", lesson: "thermo-adiabatic", type: "mc", prompt: "On a $P$–$V$ diagram at the same starting point, the adiabatic curve compared to the isothermal curve is:", options: ["Less steep", "Equally steep", "More steep", "Horizontal"], answer: 2, hint: "$\\gamma>1$ for any ideal gas.", solution: "Since $PV^\\gamma=\\text{const}$ with $\\gamma>1$ (vs. $PV^1=\\text{const}$ isothermal), the adiabat is steeper at any given point.", difficulty: 2, tags: ["thermo", "adiabatic"] },
    { id: "thermo-adiabatic-d4", lesson: "thermo-adiabatic", type: "mc", prompt: "Sound waves in air are best modeled as:", options: ["Isothermal compressions", "Adiabatic compressions, because they oscillate too fast for heat to equilibrate", "Isobaric processes", "Free expansions"], answer: 1, hint: "Sound is fast relative to thermal conduction.", solution: "The compressions/rarefactions of a sound wave happen too fast for heat to flow between them, so they're adiabatic — this is why the speed of sound formula involves $\\gamma$.", difficulty: 2, tags: ["thermo", "adiabatic"] },
    { id: "thermo-adiabatic-d5", lesson: "thermo-adiabatic", type: "mc", prompt: "Why does a bicycle pump barrel get hot when you compress it quickly with the outlet blocked?", options: ["Friction between piston and walls only", "The compression is adiabatic, so all the work done goes into raising internal energy", "The gas absorbs heat from the surroundings", "Pressure has no relation to temperature"], answer: 1, hint: "No time for heat to escape.", solution: "Fast compression is approximately adiabatic ($Q\\approx0$), so $dU=-dW$: all the compression work raises internal energy, heating the gas.", difficulty: 1, tags: ["thermo", "adiabatic"] },

    // thermo-carnot
    { id: "thermo-carnot-d1", lesson: "thermo-carnot", type: "numeric", prompt: "A Carnot engine operates between $T_h=650\\text{ K}$ and $T_c=310\\text{ K}$. Find its efficiency.", answer: 0.523, tolerance: 0.02, unit: "(fraction)", hint: "$\\eta=1-T_c/T_h$.", solution: "$\\eta = 1 - 310/650 \\approx 0.523$.", difficulty: 1, tags: ["thermo", "carnot"] },
    { id: "thermo-carnot-d2", lesson: "thermo-carnot", type: "mc", prompt: "No real engine between $T_h$ and $T_c$ can exceed Carnot efficiency because:", options: ["Friction is unavoidable", "Doing so would let you combine two engines to pump heat from cold to hot with zero net work input, violating the second law", "Materials cannot withstand the required temperatures", "Carnot efficiency is only a theoretical upper bound with no physical justification"], answer: 1, hint: "Contradiction argument from the lesson.", solution: "The bound follows from a contradiction: exceeding it lets you build a device that violates the second law by moving heat from cold to hot with no external work.", difficulty: 2, tags: ["thermo", "carnot"] },
    { id: "thermo-carnot-d3", lesson: "thermo-carnot", type: "mc", prompt: "Carnot efficiency depends on:", options: ["The working fluid only", "The engine's mechanical design only", "Only the two reservoir temperatures", "The rate at which the cycle is run"], answer: 2, hint: "Design-independence is the key result.", solution: "$\\eta_{Carnot}=1-T_c/T_h$ depends on temperatures alone — a consequence of all reversible engines between the same reservoirs sharing one efficiency.", difficulty: 1, tags: ["thermo", "carnot"] },
    { id: "thermo-carnot-d4", lesson: "thermo-carnot", type: "numeric", prompt: "A Carnot engine absorbs $Q_h=800\\text{ J}$ from a hot reservoir at $T_h=500\\text{ K}$ and exhausts heat to a cold reservoir at $T_c=250\\text{ K}$. Find the work output in joules.", answer: 400, tolerance: 0.02, unit: "J", hint: "$W=\\eta Q_h$.", solution: "$\\eta=1-250/500=0.5$, so $W=0.5\\times800=400\\text{ J}$.", difficulty: 2, tags: ["thermo", "carnot"] },
    { id: "thermo-carnot-d5", lesson: "thermo-carnot", type: "mc", prompt: "As $T_c\\to0\\text{ K}$ (with $T_h$ fixed), Carnot efficiency approaches:", options: ["0", "0.5", "1", "$\\infty$"], answer: 2, hint: "$\\eta=1-T_c/T_h$.", solution: "$\\eta\\to1-0=1$; note this limit is unreachable since $T_c=0$ is unattainable (third law), so $\\eta=1$ is never actually achieved.", difficulty: 2, tags: ["thermo", "carnot"] },

    // thermo-entropy
    { id: "thermo-entropy-d1", lesson: "thermo-entropy", type: "mc", prompt: "Boltzmann's formula for entropy is:", options: ["$S=kT$", "$S=k\\ln\\Omega$", "$S=Q/T$ always", "$S=\\ln k\\Omega$"], answer: 1, hint: "Connects entropy to microstate counting.", solution: "$S=k\\ln\\Omega$, where $\\Omega$ is the number of microstates consistent with the macrostate.", difficulty: 1, tags: ["thermo", "entropy"] },
    { id: "thermo-entropy-d2", lesson: "thermo-entropy", type: "numeric", prompt: "3 mol of ideal gas expand isothermally and reversibly to 4 times their initial volume. Find $\\Delta S$ in J/K. ($R=8.31\\text{ J/(mol K)}$)", answer: 34.6, tolerance: 0.03, unit: "J/K", hint: "$\\Delta S = nR\\ln(V_f/V_i)$.", solution: "$\\Delta S = nR\\ln4 = 3\\times8.31\\times1.386 \\approx 34.6\\text{ J/K}$.", difficulty: 2, tags: ["thermo", "entropy"] },
    { id: "thermo-entropy-d3", lesson: "thermo-entropy", type: "mc", prompt: "Free expansion of an ideal gas into vacuum is irreversible even though energy is conserved, because:", options: ["Momentum is not conserved", "The reverse process would require an astronomically improbable decrease in the number of accessible microstates", "The first law is violated in reverse", "Free expansion actually conserves entropy"], answer: 1, hint: "Think about $\\Omega_{final}$ vs $\\Omega_{initial}$ for the reverse process.", solution: "Reversing free expansion would require the gas to spontaneously crowd into a far smaller-$\\Omega$ macrostate — not forbidden by energy conservation, but statistically negligible.", difficulty: 2, tags: ["thermo", "entropy"] },
    { id: "thermo-entropy-d4", lesson: "thermo-entropy", type: "mc", prompt: "For an isolated system undergoing a spontaneous process, entropy:", options: ["Always decreases", "Always stays constant", "Never decreases", "Oscillates unpredictably"], answer: 2, hint: "Second law statement.", solution: "$\\Delta S\\ge0$ for an isolated system, with equality only in the reversible (idealized) limit.", difficulty: 1, tags: ["thermo", "entropy"] },
    { id: "thermo-entropy-d5", lesson: "thermo-entropy", type: "mc", prompt: "To compute $\\Delta S$ between two equilibrium states connected by an irreversible process, the standard technique is to:", options: ["Use $Q_{irrev}/T$ directly", "Substitute any convenient reversible path between the same two endpoints, since $S$ is a state function", "Assume $\\Delta S=0$", "Measure the process's duration"], answer: 1, hint: "Path-independence of state functions.", solution: "Since entropy is a state function, $\\Delta S$ only depends on endpoints; compute it along a reversible path with the same endpoints using $\\Delta S=\\int dQ_{rev}/T$.", difficulty: 2, tags: ["thermo", "entropy"] },

    // thermo-boltzmann
    { id: "thermo-boltzmann-d1", lesson: "thermo-boltzmann", type: "mc", prompt: "The Boltzmann factor $e^{-E/kT}$ gives the relative probability of a microstate because:", options: ["High-energy states are forbidden by conservation of energy", "Giving energy $E$ to a small system costs the much larger heat bath entropy proportional to $E/T$", "It is an empirical curve fit", "Energy must always decrease over time"], answer: 1, hint: "Derived from maximizing combined system+bath entropy.", solution: "Maximizing total (system+bath) entropy at fixed total energy, with the bath enormous, gives an exponential suppression $e^{-E/kT}$ for the small system's energy.", difficulty: 2, tags: ["thermo", "boltzmann-factor"] },
    { id: "thermo-boltzmann-d2", lesson: "thermo-boltzmann", type: "numeric", prompt: "A two-level system has level spacing $\\Delta E = 0.050\\text{ eV}$. At $T=300\\text{ K}$ ($kT\\approx0.0259\\text{ eV}$), find the ratio $n_\\uparrow/n_\\downarrow$.", answer: 0.145, tolerance: 0.05, unit: "(ratio)", hint: "$n_\\uparrow/n_\\downarrow = e^{-\\Delta E/kT}$.", solution: "$e^{-0.050/0.0259} = e^{-1.93} \\approx 0.145$.", difficulty: 2, tags: ["thermo", "boltzmann-factor"] },
    { id: "thermo-boltzmann-d3", lesson: "thermo-boltzmann", type: "mc", prompt: "The partition function $Z=\\sum_i e^{-\\beta E_i}$ is useful because:", options: ["It equals the total number of particles", "Derivatives of $\\ln Z$ give thermodynamic quantities like average energy directly", "It is always equal to 1", "It only applies to gases"], answer: 1, hint: "$\\langle E\\rangle = -\\partial\\ln Z/\\partial\\beta$.", solution: "$Z$ packages the full statistical description of a system in contact with a heat bath; its log-derivatives yield average energy, entropy, free energy, etc.", difficulty: 2, tags: ["thermo", "boltzmann-factor"] },
    { id: "thermo-boltzmann-d4", lesson: "thermo-boltzmann", type: "mc", prompt: "As $T\\to0$ for a two-level system, the population ratio $n_\\uparrow/n_\\downarrow$ approaches:", options: ["1", "0", "$\\infty$", "$e^{-1}$"], answer: 1, hint: "$e^{-\\Delta E/kT}$ as $T\\to0$.", solution: "$e^{-\\Delta E/kT}\\to0$ as $T\\to0^+$: essentially all population collapses to the ground state.", difficulty: 1, tags: ["thermo", "boltzmann-factor"] },
    { id: "thermo-boltzmann-d5", lesson: "thermo-boltzmann", type: "mc", prompt: "The Boltzmann factor underlies which of the following?", options: ["Maxwell–Boltzmann speed distribution only", "Arrhenius reaction rate law only", "Both the Maxwell–Boltzmann speed distribution and the Arrhenius rate law", "Neither; they are unrelated formulas"], answer: 2, hint: "Same exponential, different energy ladder.", solution: "Both are applications of $P(E)\\propto e^{-E/kT}$ to different physical energies (kinetic energy of molecules; activation energy of a reaction).", difficulty: 2, tags: ["thermo", "boltzmann-factor"] },

    // thermo-equipartition
    { id: "thermo-equipartition-d1", lesson: "thermo-equipartition", type: "mc", prompt: "Classical equipartition assigns to each quadratic degree of freedom an average energy of:", options: ["$kT$", "$\\tfrac12kT$", "$\\tfrac32kT$", "$2kT$"], answer: 1, hint: "One $\\tfrac12kT$ per quadratic term.", solution: "Each term like $\\tfrac12mv_x^2$ contributes $\\tfrac12kT$ on average, under the classical continuous-energy assumption.", difficulty: 1, tags: ["thermo", "equipartition"] },
    { id: "thermo-equipartition-d2", lesson: "thermo-equipartition", type: "mc", prompt: "Vibrational modes of $\\text{N}_2$ are 'frozen out' at room temperature because:", options: ["Vibration doesn't exist in diatomic molecules", "The vibrational level spacing is much larger than $kT$ at room temperature", "$\\text{N}_2$ molecules never vibrate", "Equipartition doesn't apply to molecules"], answer: 1, hint: "$\\varepsilon/k \\sim 3000\\text{ K}$ for $\\text{N}_2$ vibration.", solution: "With $\\varepsilon \\gg kT$ at $300\\text{ K}$, the Boltzmann factor for exciting even the first vibrational level is negligible, so the mode contributes essentially nothing to $C_V$.", difficulty: 2, tags: ["thermo", "equipartition"] },
    { id: "thermo-equipartition-d3", lesson: "thermo-equipartition", type: "mc", prompt: "As temperature rises well above a mode's characteristic spacing $\\varepsilon/k$, that mode's contribution to $C_V$:", options: ["Stays at zero", "Approaches the full classical equipartition value", "Becomes negative", "Diverges to infinity"], answer: 1, hint: "$kT \\gg \\varepsilon$ recovers the classical continuum limit.", solution: "Once $kT\\gg\\varepsilon$, the discreteness becomes irrelevant and the mode behaves as a classical continuous degree of freedom, contributing its full equipartition share.", difficulty: 2, tags: ["thermo", "equipartition"] },
    { id: "thermo-equipartition-d4", lesson: "thermo-equipartition", type: "mc", prompt: "A fully classical (unfrozen) diatomic ideal gas, including vibration, would have $C_V$ equal to:", options: ["$\\tfrac32R$", "$\\tfrac52R$", "$\\tfrac72R$", "$4R$"], answer: 2, hint: "3 translational + 2 rotational + 2 vibrational (KE+PE) = 7 quadratic terms.", solution: "7 quadratic degrees of freedom $\\times\\tfrac12R$ each $= \\tfrac72R$.", difficulty: 2, tags: ["thermo", "equipartition"] },
    { id: "thermo-equipartition-d5", lesson: "thermo-equipartition", type: "mc", prompt: "The failure of classical equipartition at low temperature was historically significant because it:", options: ["Disproved the first law of thermodynamics", "Was the first clear experimental evidence that energy is quantized", "Proved that heat capacities are always constant", "Showed that gases don't obey the ideal gas law"], answer: 1, hint: "Same theme continued in blackbody radiation.", solution: "The sharp, temperature-dependent freezing-out of modes could only be explained by discrete (quantized) energy levels, foreshadowing quantum mechanics.", difficulty: 2, tags: ["thermo", "equipartition"] },

    // thermo-blackbody
    { id: "thermo-blackbody-d1", lesson: "thermo-blackbody", type: "mc", prompt: "The ultraviolet catastrophe refers to the classical prediction that:", options: ["Blackbody radiation is always red", "A hot cavity's total radiated power diverges due to equal $kT$ energy assigned to arbitrarily many high-frequency modes", "UV light cannot be absorbed by any material", "Stars cannot radiate energy"], answer: 1, hint: "Equipartition applied to EM modes without quantization.", solution: "Classically, mode density grows as $\\nu^2$ while each mode carries $kT$ on average (equipartition), giving a divergent total power — resolved by quantizing mode energy.", difficulty: 2, tags: ["thermo", "blackbody"] },
    { id: "thermo-blackbody-d2", lesson: "thermo-blackbody", type: "numeric", prompt: "Estimate the peak wavelength of blackbody radiation from a body at $T=2900\\text{ K}$ (Wien's law, $\\lambda_{max}T\\approx2.90\\times10^{-3}\\text{ m K}$).", answer: 1000, tolerance: 0.03, unit: "nm", hint: "$\\lambda_{max}=2.90\\times10^{-3}/T$.", solution: "$\\lambda_{max} = 2.90\\times10^{-3}/2900 = 1.00\\times10^{-6}\\text{ m} = 1000\\text{ nm}$ (infrared).", difficulty: 2, tags: ["thermo", "blackbody"] },
    { id: "thermo-blackbody-d3", lesson: "thermo-blackbody", type: "mc", prompt: "Planck's average mode energy $\\langle E(\\nu)\\rangle = \\dfrac{h\\nu}{e^{h\\nu/kT}-1}$ reduces to the classical equipartition result $kT$ in the limit:", options: ["$h\\nu \\gg kT$", "$h\\nu \\ll kT$", "$T\\to0$", "$\\nu\\to\\infty$"], answer: 1, hint: "Taylor expand the denominator for small $h\\nu/kT$.", solution: "For $h\\nu\\ll kT$, $e^{h\\nu/kT}-1\\approx h\\nu/kT$, so $\\langle E\\rangle \\approx h\\nu/(h\\nu/kT)=kT$.", difficulty: 2, tags: ["thermo", "blackbody"] },
    { id: "thermo-blackbody-d4", lesson: "thermo-blackbody", type: "mc", prompt: "If a star's absolute temperature doubles, the Stefan–Boltzmann law predicts its radiated power (per unit area) increases by a factor of:", options: ["2", "4", "8", "16"], answer: 3, hint: "$P\\propto T^4$.", solution: "$P\\propto T^4$, so doubling $T$ multiplies power by $2^4=16$.", difficulty: 1, tags: ["thermo", "blackbody"] },
    { id: "thermo-blackbody-d5", lesson: "thermo-blackbody", type: "mc", prompt: "Fermi–Dirac statistics differ from Bose–Einstein statistics in that:", options: ["Fermions can occupy the same state in unlimited numbers", "Fermions obey the Pauli exclusion principle, limiting occupation of a state to one particle", "Bosons cannot exist at low temperature", "Fermi–Dirac statistics apply only to photons"], answer: 1, hint: "Pauli exclusion is the fermion-specific rule.", solution: "Fermions (spin-$\\tfrac12$, e.g. electrons) obey Pauli exclusion, at most one per state; bosons (e.g. photons) can occupy a state in any number.", difficulty: 2, tags: ["thermo", "blackbody"] },
    { id: "thermo-blackbody-d6", lesson: "thermo-blackbody", type: "mc", prompt: "Which thermodynamic potential is the appropriate one to minimize at equilibrium for a system held at constant temperature and pressure?", options: ["Internal energy $U$", "Enthalpy $H$", "Helmholtz free energy $F$", "Gibbs free energy $G$"], answer: 3, hint: "$G=H-TS$ is suited to constant $T,P$.", solution: "$G=H-TS$ is the natural potential for constant $T$ and $P$ (most laboratory chemistry conditions), just as $F=U-TS$ is natural for constant $T,V$.", difficulty: 3, tags: ["thermo", "thermodynamic-potentials"] }
  ],

  test: [
    { id: "thermo-t1", prompt: "An ideal-gas thermometer at constant volume reads pressure $P_0$ at the triple point of water ($273.16\\text{ K}$) and pressure $2P_0$ in contact with a sample. The sample's temperature is closest to:", options: ["136.6 K", "273.2 K", "410 K", "546.3 K", "819 K"], answer: 3, solution: "$T\\propto P$ at fixed volume, so $T = 273.16\\times2 \\approx 546.3\\text{ K}$.", difficulty: 1, tags: ["thermo", "zeroth-law"], lesson: "thermo-temperature" },
    { id: "thermo-t2", prompt: "Estimate $v_{rms}$ for oxygen molecules ($M=32\\text{ g/mol}$) at $T=300\\text{ K}$. ($R=8.31\\text{ J/(mol K)}$)", options: ["48 m/s", "150 m/s", "310 m/s", "480 m/s", "960 m/s"], answer: 3, solution: "$v_{rms}=\\sqrt{3RT/M} = \\sqrt{3(8.31)(300)/0.032} \\approx 482\\text{ m/s}$.", difficulty: 1, tags: ["thermo", "kinetic-theory"], lesson: "thermo-kinetic-theory" },
    { id: "thermo-t3", prompt: "Two ideal gases, helium and argon, are at the same temperature. Which statement is correct?", options: ["Both have the same average speed", "Both have the same average kinetic energy per molecule", "Helium molecules have lower average kinetic energy", "Argon molecules move faster on average", "Both have the same pressure regardless of container size"], answer: 1, solution: "$\\langle KE\\rangle=\\tfrac32kT$ depends only on $T$, not on molecular mass — so both gases have equal average KE, though helium (lighter) has higher $v_{rms}$.", difficulty: 1, tags: ["thermo", "kinetic-theory"], lesson: "thermo-kinetic-theory" },
    { id: "thermo-t4", prompt: "2 mol of a monatomic ideal gas absorb 600 J of heat at constant volume. The temperature change is approximately: ($R=8.31\\text{ J/(mol K)}$)", options: ["4.8 K", "12 K", "24 K", "36 K", "48 K"], answer: 2, solution: "$Q=nC_V\\Delta T$, $C_V=\\tfrac32R$: $\\Delta T = 600/(2\\times1.5\\times8.31) \\approx 24.1\\text{ K}$.", difficulty: 1, tags: ["thermo", "first-law"], lesson: "thermo-first-law" },
    { id: "thermo-t5", prompt: "A diatomic ideal gas (vibration frozen, rotation active) undergoes an isobaric process where its volume doubles. The ratio of heat added to work done, $Q/W$, is:", options: ["1", "5/2", "7/2", "5/3", "3/2"], answer: 2, solution: "At constant $P$: $Q=nC_P\\Delta T$ and $W=nR\\Delta T$. With rotation active and vibration frozen, $C_V=\\tfrac52R$, so $C_P=C_V+R=\\tfrac72R$, giving $Q/W=C_P/R=7/2$.", difficulty: 2, tags: ["thermo", "first-law"], lesson: "thermo-first-law" },
    { id: "thermo-t6", prompt: "A monatomic ideal gas is compressed adiabatically to one-eighth its original volume. By what factor does its temperature increase? ($\\gamma=5/3$)", options: ["2", "4", "8", "16", "32"], answer: 1, solution: "For adiabatic ideal gas, $TV^{\\gamma-1}=\\text{const}$, so $T_2/T_1=(V_1/V_2)^{\\gamma-1}=8^{2/3}=4$.", difficulty: 2, tags: ["thermo", "adiabatic"], lesson: "thermo-adiabatic" },
    { id: "thermo-t7", prompt: "Which best explains why the speed of sound in a gas is computed using an adiabatic relation ($v=\\sqrt{\\gamma P/\\rho}$) rather than an isothermal one?", options: ["Sound waves involve no pressure variation", "Compressions and rarefactions oscillate too quickly for heat to flow between them", "Gases cannot support isothermal processes", "Sound only travels through solids adiabatically", "The isothermal formula gives a faster, unphysical speed"], answer: 1, solution: "Sound oscillations are fast compared to thermal conduction timescales, so each compression/rarefaction is effectively adiabatic, not isothermal.", difficulty: 1, tags: ["thermo", "adiabatic"], lesson: "thermo-adiabatic" },
    { id: "thermo-t8", prompt: "A reversible engine operates between reservoirs at 400 K and 250 K, delivering 900 J of work per cycle. The heat rejected to the cold reservoir per cycle is closest to:", options: ["600 J", "1000 J", "1500 J", "2400 J", "3600 J"], answer: 2, solution: "$\\eta=1-250/400=0.375$; $Q_h=W/\\eta=900/0.375=2400\\text{ J}$; $Q_c=Q_h-W=2400-900=1500\\text{ J}$.", difficulty: 2, tags: ["thermo", "carnot"], lesson: "thermo-carnot" },
    { id: "thermo-t9", prompt: "Which statement about heat engines is correct?", options: ["Any engine design can, with sufficient engineering, reach 100% efficiency", "Two reversible engines operating between the same two reservoirs must have equal efficiency", "Carnot efficiency depends on the working substance used", "A refrigerator is just a heat engine run forward with no other changes", "Irreversible engines can exceed the Carnot efficiency for the same reservoirs"], answer: 1, solution: "This is the design-independence result: unequal efficiencies between two reversible engines on the same reservoirs would allow construction of a device violating the second law.", difficulty: 3, tags: ["thermo", "carnot"], lesson: "thermo-carnot" },
    { id: "thermo-t10", prompt: "An ideal monatomic gas expands reversibly and isothermally to triple its volume at $T=350\\text{ K}$. If the gas has $n=2\\text{ mol}$, the entropy change is closest to: ($R=8.31\\text{ J/(mol K)}$)", options: ["9.1 J/K", "18.3 J/K", "36.5 J/K", "58.0 J/K", "116 J/K"], answer: 1, solution: "$\\Delta S = nR\\ln3 = 2\\times8.31\\times1.0986\\approx18.3\\text{ J/K}$ (temperature is irrelevant here since the gas is ideal and the process is isothermal — $\\Delta S$ depends only on the volume ratio).", difficulty: 2, tags: ["thermo", "entropy"], lesson: "thermo-entropy" },
    { id: "thermo-t11", prompt: "A gas undergoes free expansion into a vacuum, doubling its volume. Which statement is correct?", options: ["$\\Delta U>0$ and $\\Delta S=0$", "$\\Delta U=0$ and $\\Delta S>0$", "$\\Delta U<0$ and $\\Delta S<0$", "$\\Delta U=0$ and $\\Delta S=0$", "$\\Delta U>0$ and $\\Delta S<0$"], answer: 1, solution: "Free expansion does no work and exchanges no heat, so $\\Delta U=0$; but $\\Omega$ increases (more available positions), so $\\Delta S=Nk\\ln2>0$.", difficulty: 1, tags: ["thermo", "entropy"], lesson: "thermo-entropy" },
    { id: "thermo-t12", prompt: "Why is entropy production in free expansion consistent with the second law even though the process happens spontaneously with no external driving?", options: ["The second law only applies to engines", "The final macrostate has overwhelmingly more accessible microstates than the initial one", "Free expansion actually violates the second law", "Entropy is conserved, not produced, in free expansion", "The gas loses energy to its surroundings"], answer: 1, solution: "$S=k\\ln\\Omega$; spontaneous evolution toward the vastly larger-$\\Omega$ macrostate is exactly what the second law (statistically) requires, with no external driving needed.", difficulty: 2, tags: ["thermo", "entropy"], lesson: "thermo-entropy" },
    { id: "thermo-t13", prompt: "A system in contact with a large heat bath at temperature $T$ has two accessible energy levels separated by $\\Delta E$. If $\\Delta E = kT\\ln4$, the ratio of upper- to lower-level populations is:", options: ["4", "2", "1", "1/2", "1/4"], answer: 4, solution: "$n_\\uparrow/n_\\downarrow = e^{-\\Delta E/kT} = e^{-\\ln4} = 1/4$.", difficulty: 2, tags: ["thermo", "boltzmann-factor"], lesson: "thermo-boltzmann" },
    { id: "thermo-t14", prompt: "The exponential form of the Boltzmann factor, $P(E)\\propto e^{-E/kT}$, follows most directly from:", options: ["Conservation of momentum for the system", "Maximizing the combined entropy of a small system plus a much larger heat bath at fixed total energy", "The ideal gas law", "Planck's constant being nonzero", "The first law of thermodynamics alone"], answer: 1, solution: "It's derived by maximizing $S_{total}=S_{system}+S_{bath}$ subject to fixed total energy, expanding $S_{bath}$ to first order in the energy given to the system.", difficulty: 2, tags: ["thermo", "boltzmann-factor"], lesson: "thermo-boltzmann" },
    { id: "thermo-t15", prompt: "Room-temperature $\\text{N}_2$ gas has measured molar $C_V \\approx \\tfrac52R$ rather than the fully classical $\\tfrac72R$. The most direct explanation is:", options: ["$\\text{N}_2$ does not have rotational degrees of freedom", "Translational motion is frozen out at room temperature", "Vibrational level spacing greatly exceeds $kT$ at room temperature, so vibration doesn't contribute", "The ideal gas law fails for diatomic molecules", "Equipartition is entirely incorrect for real gases"], answer: 2, solution: "Vibrational spacing corresponds to $\\varepsilon/k\\sim3000\\text{ K}\\gg300\\text{ K}$, so that mode is frozen out at room T, leaving only translation + rotation contributing ($\\tfrac52R$).", difficulty: 2, tags: ["thermo", "equipartition"], lesson: "thermo-equipartition" },
    { id: "thermo-t16", prompt: "The historical significance of the equipartition failure (and the related ultraviolet catastrophe) is that both were resolved by:", options: ["Rejecting the first law of thermodynamics", "Postulating that energy levels of certain modes are quantized in discrete units", "Assuming gases are never in true thermal equilibrium", "Introducing relativistic corrections to kinetic theory", "Redefining temperature as a purely statistical quantity with no thermodynamic meaning"], answer: 1, solution: "Both anomalies are resolved by quantizing the energy of the relevant modes (vibrational, or electromagnetic cavity modes), suppressing high-energy modes exponentially via the Boltzmann factor.", difficulty: 3, tags: ["thermo", "blackbody", "equipartition"], lesson: "thermo-blackbody" },
    { id: "thermo-t17", prompt: "A blackbody's peak emission wavelength shifts from 725 nm to 483 nm as it's heated. By approximately what factor did its absolute temperature increase?", options: ["0.67", "1.0", "1.2", "1.5", "2.25"], answer: 3, solution: "Wien's law: $\\lambda T=\\text{const}$, so $T_2/T_1=\\lambda_1/\\lambda_2=725/483\\approx1.50$.", difficulty: 2, tags: ["thermo", "blackbody"], lesson: "thermo-blackbody" },
    { id: "thermo-t18", prompt: "Which pairing of a thermodynamic potential with its natural (fixed) variables is correct?", options: ["Internal energy $U$: fixed $T,P$", "Enthalpy $H$: fixed $S,V$", "Helmholtz free energy $F$: fixed $T,V$", "Gibbs free energy $G$: fixed $S,P$", "Internal energy $U$: fixed $T,V$"], answer: 2, solution: "$F=U-TS$ has natural variables $T,V$ (i.e. $dF=-S\\,dT-P\\,dV$); $U$ pairs with $S,V$; $H$ with $S,P$; $G$ with $T,P$.", difficulty: 3, tags: ["thermo", "thermodynamic-potentials"], lesson: "thermo-blackbody" },
    { id: "thermo-t19", prompt: "A composite wall has two layers in series, with area-specific thermal resistances $R_1''=0.2\\,\\text{m}^2\\text{K/W}$ and $R_2''=0.5\\,\\text{m}^2\\text{K/W}$, total area $2\\,\\text{m}^2$, and a temperature difference of $30\\,\\text{K}$ across the whole wall. The heat flow rate is closest to:", options: ["$21\\,\\text{W}$", "$43\\,\\text{W}$", "$86\\,\\text{W}$", "$120\\,\\text{W}$", "$210\\,\\text{W}$"], answer: 2, solution: "Series resistances add: $R''_{\\text{total}}=0.7\\,\\text{m}^2\\text{K/W}$; rate $= A\\,\\Delta T/R''_{\\text{total}} = 2(30)/0.7 \\approx 86\\,\\text{W}$.", difficulty: 2, tags: ["thermo", "heat-transfer"], lesson: "thermo-heat-transfer" },
    { id: "thermo-t20", prompt: "A blackbody's absolute temperature increases from $300\\,\\text{K}$ to $600\\,\\text{K}$ (surroundings negligible). Its radiated power increases by a factor of:", options: ["$2$", "$4$", "$8$", "$16$", "$32$"], answer: 3, solution: "Stefan-Boltzmann power scales as $T^4$; $(600/300)^4=2^4=16$.", difficulty: 1, tags: ["thermo", "heat-transfer", "radiation"], lesson: "thermo-heat-transfer" },
    { id: "thermo-t21", prompt: "A steel bridge girder of length $50\\,\\text{m}$ ($\\alpha=12\\times10^{-6}\\,\\text{K}^{-1}$) experiences a temperature swing of $40°\\text{C}$ between winter and summer. The length change is closest to:", options: ["$2.4\\,\\text{mm}$", "$24\\,\\text{mm}$", "$0.24\\,\\text{mm}$", "$240\\,\\text{mm}$", "$2.4\\,\\text{m}$"], answer: 1, solution: "$\\Delta L = \\alpha L\\,\\Delta T = (12\\times10^{-6})(50)(40) = 0.024\\,\\text{m} = 24\\,\\text{mm}$.", difficulty: 1, tags: ["thermo", "heat-transfer", "thermal-expansion"], lesson: "thermo-heat-transfer" }
  ]
});
