window.PGRE = window.PGRE || {}; window.PGRE.modules = window.PGRE.modules || [];
window.PGRE.modules.push({
  id: "waves-optics",
  title: "Waves and Optics",
  order: 3,
  greWeight: 0.09,
  prereqs: ["mechanics", "em"],
  blurb: "Unlocks interference, diffraction, and the optics questions that reuse EM-wave ideas from electromagnetism.",
  lessons: [
    {
      id: "waves-optics-wave-equation",
      title: "The wave equation and why $v=\\sqrt{T/\\mu}$",
      minutes: 12,
      discovery: "Applying Newton's second law to a small element of a taut string, with tension as the restoring force and mass density as the inertia, forces wave speed to depend only on $T$ and $\\mu$ — not on the shape, amplitude, or frequency of the disturbance.",
      sections: [
        { kind: "problem", md: "Pluck a taut string (or snap a rope) and a pulse travels along it. What determines how fast the pulse moves — does a bigger pluck (larger amplitude) send the pulse faster? Does a sharper, narrower pulse move faster than a broad one? You need a rule for wave speed that a no-calculator exam can apply instantly, not a case-by-case simulation." },
        { kind: "candidates", md: "**A. Guess by dimensional analysis alone**: list the quantities that seem relevant (tension $T$, mass per length $\\mu$, amplitude $A$, pulse width $\\ell$) and try to combine them into something with units of speed, without knowing which actually belong.\n\n**B. Assume a larger-amplitude pulse moves faster**, since a bigger disturbance means a bigger restoring force pulling it back, which sounds like it should mean bigger acceleration and higher speed.\n\n**C. Apply Newton's second law directly to a small element of the string**, using tension as the force and mass density as the inertia, and see what governs the resulting motion." },
        { kind: "failures", md: "**A can't tell you which variables actually matter** — $\\sqrt{T\\ell/\\text{(mass)}}$ and $\\sqrt{T/\\mu}$ both have units of speed, but only one is correct, and dimensional analysis alone can't distinguish them without physics input.\n\n**B is falsified experimentally**: a gentle pluck and a hard pluck on the *same* string send pulses that travel at the *same* speed (you can verify this by timing two pulses of different sizes reach the far end together) — amplitude turns out not to matter at all, for small-enough disturbances, which kills the 'bigger force means faster' intuition." },
        { kind: "discovery", md: "C is the productive route. Take a small element of string, length $dx$, mass $\\mu\\,dx$. The two tension forces at its ends are equal in magnitude $T$ but point along the string's local slope, which differs slightly at the two ends if the string is curved; that mismatch is the net transverse restoring force, proportional to the *curvature* $\\partial^2y/\\partial x^2$ (for small slopes). Newton's second law, force $=$ mass $\\times$ acceleration, becomes $\\mu\\,dx\\,\\dfrac{\\partial^2y}{\\partial t^2} = T\\,dx\\,\\dfrac{\\partial^2y}{\\partial x^2}$ — critically, this equation has no reference at all to amplitude, pulse shape, or width; $T$ and $\\mu$ are the *only* physical parameters that appear, which is exactly why the wave speed depends on nothing else." },
        { kind: "formal", md: "**Wave equation**: $\\dfrac{\\partial^2 y}{\\partial t^2} = v^2\\dfrac{\\partial^2 y}{\\partial x^2}$, where $v^2 = T/\\mu$, so $v = \\sqrt{T/\\mu}$ for a string (tension $T$, mass per unit length $\\mu$). Any function of the form $y(x,t) = f(x-vt)$ or $f(x+vt)$ satisfies this equation (shape-preserving travel at speed $v$, either direction) — you can check this by direct substitution, which is a useful habit for verifying any claimed wave solution on the exam." },
        { kind: "apply", md: "A string with $\\mu = 0.010\\,\\text{kg/m}$ is under tension $T=40\\,\\text{N}$: $v = \\sqrt{40/0.010} = \\sqrt{4000} \\approx 63\\,\\text{m/s}$. **Limiting-case sanity check**: tightening the string (increasing $T$) should make it 'stiffer' and faster to respond — $v\\propto\\sqrt{T}$ agrees. A heavier string (larger $\\mu$) should respond more sluggishly (more inertia per length) — $v\\propto1/\\sqrt{\\mu}$ agrees." },
        { kind: "transfer", md: "This is the template for every wave speed formula you'll meet: a **restoring stiffness** over an **inertia density**, square-rooted. Sound in a gas: $v=\\sqrt{B/\\rho}$ (bulk modulus over mass density — stiffness of compression over inertia). The EM wave speed you already derived, $c=1/\\sqrt{\\mu_0\\epsilon_0}=\\sqrt{(1/\\epsilon_0)/\\mu_0}$, fits the same mold once you recognize $\\mu_0$ as playing the role of an effective inertia and $1/\\epsilon_0$ as the effective stiffness of the field itself. Whenever you see a new wave speed formula on the exam, checking that it reduces to (something stiffness-like)/(something inertia-like), square-rooted, is a fast sanity check against a misremembered formula." }
      ],
      checkpoints: [
        { q: "Two pulses of very different amplitude are sent down the same string, under the same tension. Their speeds are:", options: ["The same, since $v=\\sqrt{T/\\mu}$ doesn't depend on amplitude", "Different, with the larger pulse moving faster", "Different, with the larger pulse moving slower", "Impossible to determine without knowing the pulse shape"], answer: 0, explain: "$v=\\sqrt{T/\\mu}$ contains no amplitude dependence — this matches the experimental fact that (small-amplitude) pulse speed is amplitude-independent." },
        { q: "If a string's tension is quadrupled while its mass per unit length stays the same, the wave speed:", options: ["Doubles", "Quadruples", "Halves", "Stays the same"], answer: 0, explain: "$v\\propto\\sqrt{T}$, so quadrupling $T$ doubles $v$." }
      ]
    },
    {
      id: "waves-optics-superposition",
      title: "Superposition: standing waves and beats from the same principle",
      minutes: 13,
      discovery: "In a linear medium, two overlapping waves simply add their displacements point by point with no interaction — that single fact, applied to two waves traveling in opposite directions, produces a standing wave, and applied to two waves of slightly different frequency, produces beats.",
      sections: [
        { kind: "problem", md: "Send two pulses toward each other on the same string from opposite ends. What happens when they overlap — does one pulse destroy the other, does the string just show whichever pulse is 'stronger,' or something else? Separately: play two tuning forks of very close but not identical frequency together, and you hear a slow, throbbing rise and fall in loudness rather than a steady tone — what's producing that rhythm?" },
        { kind: "candidates", md: "**A. One wave wins.** The pulse with more energy or amplitude 'overrides' the other at the point of overlap, the way one voice might drown out another.\n\n**B. The medium averages the two disturbances**, displaying some blended compromise shape.\n\n**C. The medium's displacement is simply the sum of what each wave would produce alone**, with each wave completely unaware of the other's presence." },
        { kind: "failures", md: "**A fails observationally**: if you send a pulse leaning up and an equal-and-opposite pulse leaning down toward each other, at the instant they exactly overlap the string is *flat* — neither pulse 'wins,' they momentarily cancel completely, and then each pulse **continues onward unchanged**, as if the other had never been there. A 'winner' model can't explain either the cancellation or the pulses' un-mangled continuation afterward.\n\n**B is closer but wrong in general**: 'averaging' would mean the combined displacement is always between the two individual displacements, but two same-sign pulses overlapping produce a peak *taller* than either alone — outside the range 'averaging' would allow." },
        { kind: "discovery", md: "C survives both tests: pointwise addition explains total cancellation (opposite-sign pulses summing to zero at the crossing instant), taller-than-either peaks (same-sign pulses adding), and the pulses' unchanged continuation afterward (each wave's own governing equation — the wave equation from the last lesson — is linear, so one solution doesn't perturb another; they literally pass through each other). This is the **superposition principle**, and it's exactly why the wave equation being *linear* in $y$ matters: sums of solutions are themselves solutions." },
        { kind: "formal", md: "**Superposition**: total displacement $y_{\\text{total}}(x,t) = y_1(x,t)+y_2(x,t)$, always, for any waves obeying a linear wave equation. **Standing wave** (apply to two identical waves traveling in opposite directions, e.g. a wave and its reflection): $y = A\\sin(kx-\\omega t) + A\\sin(kx+\\omega t) = 2A\\sin(kx)\\cos(\\omega t)$ — a product of a fixed spatial shape $\\sin(kx)$ and a time oscillation $\\cos(\\omega t)$, not a traveling wave at all: **nodes** (always zero) where $\\sin(kx)=0$, **antinodes** (maximum amplitude) where $|\\sin(kx)|=1$. A string fixed at both ends (length $L$) only supports standing waves with nodes at both ends: $L = n\\lambda/2$, giving allowed frequencies $f_n = nv/2L$ ($n=1,2,3,\\dots$). **Beats** (apply to two waves of close but different frequency, $f_1$ and $f_2$, same point in space): summing $\\cos(2\\pi f_1t)+\\cos(2\\pi f_2t)$ gives a fast oscillation at the average frequency $(f_1+f_2)/2$, with its amplitude itself slowly oscillating (an 'envelope') at frequency $|f_1-f_2|/2$ — but since loudness depends on the *square* of amplitude, you hear a beat (loud) twice per envelope cycle, so the perceived beat frequency is $f_{\\text{beat}}=|f_1-f_2|$." },
        { kind: "apply", md: "A string of length $1.2\\,\\text{m}$ fixed at both ends, wave speed $v=40\\,\\text{m/s}$: fundamental frequency $f_1 = v/2L = 40/2.4 \\approx 16.7\\,\\text{Hz}$; the next allowed mode is $f_2=2f_1\\approx33.3\\,\\text{Hz}$ — only integer multiples of the fundamental are allowed, a direct consequence of needing nodes at both fixed ends. **Beats**: two tuning forks at $440\\,\\text{Hz}$ and $444\\,\\text{Hz}$ produce a beat frequency of $|444-440|=4\\,\\text{Hz}$ — four loud/soft cycles per second, easily audible as a throb even though the two tones themselves are indistinguishable by ear alone." },
        { kind: "transfer", md: "Superposition is the single most-reused principle in this module: interference (next-but-one lesson) is standing-wave-style superposition applied in two or three spatial dimensions instead of one, and the 'sum of two close frequencies produces a slow envelope' beat pattern reappears as the mathematical seed of wave packets and (later, outside this exam's scope) the uncertainty principle. Recognizing 'this is just superposition, applied to a new geometry or frequency relationship' is the fastest way to avoid re-deriving interference and diffraction results from scratch." }
      ],
      checkpoints: [
        { q: "A string fixed at both ends has fundamental frequency $f_1$. What is the frequency of its third harmonic?", options: ["$f_1$", "$1.5f_1$", "$3f_1$", "$9f_1$"], answer: 2, explain: "Allowed frequencies on a string fixed at both ends are integer multiples of the fundamental: $f_n=nf_1$, so the third harmonic is $3f_1$." },
        { q: "Two tones of $500\\,\\text{Hz}$ and $503\\,\\text{Hz}$ are played together. The beat frequency heard is:", options: ["$0.5\\,\\text{Hz}$", "$3\\,\\text{Hz}$", "$500\\,\\text{Hz}$", "$1003\\,\\text{Hz}$"], answer: 1, explain: "Beat frequency is the difference of the two frequencies: $|503-500|=3\\,\\text{Hz}$." }
      ]
    },
    {
      id: "waves-optics-doppler",
      title: "The Doppler effect: sound needs a medium, light doesn't",
      minutes: 12,
      discovery: "For sound, the medium provides an absolute rest frame, so a moving source and a moving observer at the same relative speed produce genuinely different frequency shifts — but light has no medium (you already established this deriving the EM wave speed), so its Doppler shift can only depend on relative velocity, forcing a different, symmetric formula.",
      sections: [
        { kind: "problem", md: "An ambulance siren rises in pitch as it approaches and drops as it passes — the classic Doppler effect. Quick question to test your intuition: does it matter, for the size of the frequency shift, whether the *source* is moving toward a stationary listener, or the *listener* is moving toward a stationary source, at the same relative speed? Naively you might expect these to be identical, since 'relative speed' sounds like the only thing that should matter." },
        { kind: "candidates", md: "**A. A single formula depending only on relative speed** $u_{\\text{rel}}$, e.g. $f' = f(v+u_{\\text{rel}})/v$, applies regardless of whether the source or the observer is the one actually moving.\n\n**B. Only source motion matters**; a moving observer with a stationary source produces no shift at all, since the source's emitted frequency hasn't changed.\n\n**C. Work out both cases separately from first principles** — how wavefronts are emitted and how they're received — since sound waves travel through a physical medium (air) that has its own rest frame." },
        { kind: "failures", md: "**B fails immediately by experience**: run toward a stationary speaker playing a steady tone and the pitch you hear *does* rise, even though the speaker's frequency never changed — so observer motion clearly matters too.\n\n**A fails on closer inspection**: compute the source-moving case (source speed $u$ toward a stationary listener, sound speed $v$) versus the observer-moving case (listener speed $u$ toward a stationary source) at the *same* $u$, say $u=v/2$. Source-moving analysis (wavefronts bunch up ahead of the source, each successive crest emitted from a closer point) gives $f' = fv/(v-u) = f\\cdot v/(v/2) = 2f$. Observer-moving analysis (the listener sweeps up extra wavefronts per second simply by moving into them) gives $f' = f(v+u)/v = f(v+v/2)/v = 1.5f$. These disagree — $2f \\ne 1.5f$ — so a single relative-speed-only formula cannot be right for sound." },
        { kind: "discovery", md: "The asymmetry makes sense once you notice sound waves propagate through a physical medium (air), which defines an absolute rest frame independent of either the source or the observer. 'Source moving' and 'observer moving' are physically different situations *relative to the medium*, even though they look the same 'relative to each other' — so it's not surprising they give different shifts. This immediately raises the question you already have the tools to answer: light has no medium (you derived $c=1/\\sqrt{\\mu_0\\epsilon_0}$ with no reference to any material substrate, and Maxwell's equations propagate a self-sustaining disturbance through pure vacuum). With no medium to provide an absolute rest frame, light's Doppler shift *cannot* distinguish 'source moving' from 'observer moving' — only their relative velocity can appear in the formula, unlike sound." },
        { kind: "formal", md: "**Sound Doppler** (medium at rest, speed $v$): source moving toward stationary observer at speed $u_s$: $f' = f\\dfrac{v}{v-u_s}$ (shift up); source moving away: $f'=f\\dfrac{v}{v+u_s}$. Observer moving toward stationary source at speed $u_o$: $f'=f\\dfrac{v+u_o}{v}$; observer moving away: $f'=f\\dfrac{v-u_o}{v}$. General case (both moving): $f' = f\\dfrac{v\\pm u_o}{v\\mp u_s}$ (signs chosen by physical direction — moving toward each other increases $f'$). **Light Doppler** (relative velocity $u$ only, $u\\ll c$ approximation sufficient for this exam): $f' \\approx f\\left(1 \\pm \\dfrac{u}{c}\\right)$, symmetric in which object 'moves' since only relative velocity enters — this is the redshift/blueshift you'll hear referenced in astrophysics contexts." },
        { kind: "apply", md: "A train horn at $500\\,\\text{Hz}$ approaches a stationary platform observer at $34\\,\\text{m/s}$, sound speed $v=340\\,\\text{m/s}$: $f' = 500\\cdot\\dfrac{340}{340-34} = 500\\cdot\\dfrac{340}{306} \\approx 556\\,\\text{Hz}$. **Limiting case check**: as $u_s\\to v$ (source approaching at the speed of sound), $f'\\to\\infty$ — wavefronts pile up entirely at the source's location with no time to spread out ahead of it, the sound analogue of a sonic boom forming, a useful sanity check that the formula blows up exactly where you'd physically expect something dramatic to happen." },
        { kind: "transfer", md: "This lesson's real payoff is a general exam heuristic: whenever a wave phenomenon seems to depend on 'who is moving,' ask whether the wave has a physical medium. If yes (sound, water waves), source and observer motion can differ. If no (light, or any EM wave), only relative motion can matter, and you should expect — and can predict without memorizing a new formula — a symmetric result. This same medium/no-medium distinction is what made the disproof of the 'ether' (a hypothesized medium for light) historically significant, and it's the conceptual seed of special relativity, though that's beyond this exam's scope." }
      ],
      checkpoints: [
        { q: "A source and an observer approach each other, each at speed $u=v/2$ relative to the air (so the closing speed is $v$), where $v$ is the speed of sound. Is the frequency shift the same as if only the source moved at speed $v$ toward a stationary observer?", options: ["Yes, since only relative speed matters for sound", "No — source motion and observer motion contribute differently, so splitting the same closing speed between them gives a different shift than putting it all on the source", "No, because sound Doppler shifts only depend on the observer's motion", "Yes, but only because $u=v/2$ is a special case"], answer: 1, explain: "Sound's medium breaks source/observer symmetry; the combined formula $f'=f\\dfrac{v+u_o}{v-u_s}$ with $u_s=u_o=v/2$ gives a different result than $u_s=v, u_o=0$ alone, even though the closing speed is the same in both scenarios." },
        { q: "Why can't light's Doppler formula distinguish 'source moving' from 'observer moving,' unlike sound's?", options: ["Light travels too fast for the distinction to matter", "Light has no medium providing an absolute rest frame, so only the relative velocity between source and observer is physically meaningful", "Light's frequency is fixed and cannot shift at all", "The distinction does exist for light too; it was overlooked historically"], answer: 1, explain: "With no medium (established directly from Maxwell's equations propagating through vacuum), there's no absolute frame to measure 'source motion' or 'observer motion' against separately — only their relative velocity is physically defined." }
      ]
    },
    {
      id: "waves-optics-geometric-optics",
      title: "Thin lenses and mirrors: the paraxial shortcut",
      minutes: 14,
      discovery: "Restricting attention to rays close to the optical axis (small angles) linearizes Snell's law and mirror reflection, collapsing the exact geometry into one simple algebraic equation and three easy-to-draw principal rays — at the cost of being only approximately right for rays far from the axis.",
      sections: [
        { kind: "problem", md: "Light from an object passes through a lens (or reflects off a curved mirror); you need to know where the image forms, whether it's upright or inverted, real or virtual, magnified or shrunk — fast, with no calculator, and without ambiguity from sign conventions that trip people up under time pressure." },
        { kind: "candidates", md: "**A. Trace every ray exactly**, applying Snell's law at each curved surface the light crosses, for as many rays as needed to locate the image precisely.\n\n**B. Restrict attention to rays that stay close to the optical axis (small angles from it)**, and see whether the exact laws simplify.\n\n**C. Memorize image-location rules for specific object distances** (e.g. 'object beyond $2f$', 'object between $f$ and $2f$') as separate cases with no unifying formula." },
        { kind: "failures", md: "**A is exact but far too slow** for a 1–2 minute exam question — full Snell's-law ray tracing through curved surfaces is a job for careful geometric construction or a computer, not mental math under time pressure.\n\n**C works only for the specific cases memorized**, breaks down the moment a question asks about an unfamiliar object distance or a mirror instead of a lens, and gives no way to check your answer symbolically." },
        { kind: "discovery", md: "B is exactly the small-angle approximation you already used for pendulums and SHM (foundations module): for rays making a small angle $\\theta$ with the optical axis, $\\sin\\theta\\approx\\theta$ turns Snell's law (and the geometry of reflection off a curved mirror) into *linear* relationships between object distance, image distance, and the surface's curvature. Linear equations, unlike the exact trigonometric ones, combine into one clean formula that works for *any* object distance at once — you don't need separate memorized cases, just one equation plus a sign convention, and you don't even need calculus, since only the small-angle Taylor truncation (sin θ ≈ θ) is used." },
        { kind: "formal", md: "**Thin lens / mirror equation**: $\\dfrac{1}{d_o} + \\dfrac{1}{d_i} = \\dfrac{1}{f}$, with **magnification** $m = -d_i/d_o$ (negative means inverted). **Sign convention** (one consistent choice, memorize once): $d_o>0$ for a real object (light diverges from it toward the lens/mirror); $d_i>0$ for a real image (light actually converges there, on the far side for a lens, same side as the object for a mirror) and $d_i<0$ for a virtual image; $f>0$ for a converging lens or concave mirror, $f<0$ for a diverging lens or convex mirror; $|m|>1$ magnified, $|m|<1$ shrunk, $m<0$ inverted, $m>0$ upright. **Three principal rays** for a quick ray-diagram: (1) parallel to axis $\\to$ bends through the focal point; (2) through the center of a thin lens (undeviated) or through the mirror's center of curvature (retraces itself); (3) through the near focal point $\\to$ emerges parallel to the axis. Any two of these locate the image; the third is a consistency check." },
        { kind: "apply", md: "Object at $d_o=30\\,\\text{cm}$ in front of a converging lens with $f=10\\,\\text{cm}$: $\\dfrac{1}{d_i} = \\dfrac1{10}-\\dfrac1{30} = \\dfrac{3-1}{30}=\\dfrac{2}{30} \\Rightarrow d_i=15\\,\\text{cm}$ (positive: real image, opposite side from the object). Magnification $m=-15/30=-0.5$ (inverted, shrunk to half size) — matches the ray-diagram intuition that an object well outside $2f$ from a converging lens produces a small, inverted, real image. **Limiting case**: as $d_o\\to f^+$ (object approaches the focal point), $1/d_i \\to 0^+$, so $d_i\\to+\\infty$ — rays emerge nearly parallel, consistent with $f$ being defined as exactly the distance where an object produces an image 'at infinity.'" },
        { kind: "transfer", md: "The linearize-by-small-angle move is the same trick used for the pendulum's SHM approximation and for paraxial optics generally — it's a specific instance of 'Taylor-expand and keep the leading term' from the foundations module, applied to angles instead of displacements. The one-equation-plus-sign-convention structure also transfers directly to the interference and diffraction lessons ahead, where path-length differences (not focal lengths) become the quantity you track with a single consistent sign/geometry convention rather than memorized special cases." }
      ],
      checkpoints: [
        { q: "An object sits at $d_o = f$ exactly (at the focal point) in front of a converging lens. Using $1/d_o + 1/d_i = 1/f$, the image distance $d_i$ is:", options: ["Zero", "Equal to $f$", "Infinite — rays emerge parallel", "Negative, indicating a virtual image at the object's location"], answer: 2, explain: "$1/d_i = 1/f - 1/f = 0$, so $d_i \\to \\infty$: an object at the focal point produces rays that emerge parallel, never converging to a finite image point." },
        { q: "A lens produces a magnification of $m=-2$. This means the image is:", options: ["Upright and twice the object's size", "Inverted and twice the object's size", "Upright and half the object's size", "Inverted and half the object's size"], answer: 1, explain: "The sign of $m$ gives orientation ($m<0$ means inverted); the magnitude gives size ratio ($|m|=2$ means twice as large)." }
      ]
    },
    {
      id: "waves-optics-interference",
      title: "Interference: double slit, thin films, and the Michelson interferometer",
      minutes: 15,
      discovery: "Because light amplitudes (not intensities) superpose, the intensity at a point depends on the phase difference between arriving waves — which is set purely by path-length difference — so the same 'count the path difference in wavelengths' logic explains double-slit fringes, thin-film colors, and interferometer output alike.",
      sections: [
        { kind: "problem", md: "Shine light through two narrow, closely spaced slits onto a distant screen. Naively you'd expect two bright lines (one behind each slit). Instead you see an extended pattern of many alternating bright and dark fringes — including points that are *darker* than if only one slit were open at all, which seems to say 'more light in, less light out.' You need a model that explains both the extra brightness at some points and the genuine darkness at others." },
        { kind: "candidates", md: "**A. Light behaves like a stream of particles** passing straight through each slit; expect exactly two bright bands, one per slit, with no structure in between.\n\n**B. The two slits' contributions add as intensities**: $I_{\\text{total}} = I_1 + I_2$ everywhere, giving a roughly uniform bright region (the sum of two positive quantities).\n\n**C. The two slits' contributions add as amplitudes (signed field values, from the superposition principle you already established for mechanical waves)**, and intensity is measured only afterward, from the *square* of that sum." },
        { kind: "failures", md: "**A fails outright**: the observed pattern has many fringes, not two isolated bright spots — something is spreading and structuring the light between the slits' geometric shadow positions.\n\n**B fails on a sharp point**: intensities are always $\\ge0$, so summing two positive intensities can never produce a result *smaller* than either one alone — yet dark fringes are observed where the combined light is dimmer than *either* slit's individual contribution. Something must be able to cancel, which a sum of non-negative intensities structurally cannot do." },
        { kind: "discovery", md: "C is forced by the cancellation observation: field amplitudes can be positive or negative (they oscillate), so $E_{\\text{total}} = E_1+E_2$ really can be smaller in magnitude than either alone, if the two are out of phase when they arrive — exactly like the beats lesson's superposition, but now the two waves overlap continuously at one point rather than differing slightly in frequency over time. The relative phase at a given screen point is set entirely by how much farther one slit's light had to travel than the other's — the **path difference** $\\delta$. When $\\delta$ is a whole number of wavelengths, the waves arrive in phase and add constructively (bright); when $\\delta$ is a half-integer number of wavelengths, they arrive exactly out of phase and cancel (dark)." },
        { kind: "formal", md: "**Double slit** (slit separation $d$, small angle $\\theta$ from center, screen far away): path difference $\\delta = d\\sin\\theta$. Bright fringes (constructive): $d\\sin\\theta = m\\lambda$, $m=0,\\pm1,\\pm2,\\dots$. Dark fringes (destructive): $d\\sin\\theta = (m+\\tfrac12)\\lambda$. **Thin films** (light reflecting off the top and bottom of a thin film, index $n$, thickness $t$): path difference inside the film is $2nt$ (down and back), but there's an extra subtlety — a reflection off a *higher*-index medium adds a half-wavelength phase shift (a $\\pi$ phase flip), while reflection off a *lower*-index medium does not; whether zero or one of the two reflections picks up this extra shift determines whether the *effective* constructive condition is $2nt=m\\lambda$ or $2nt=(m+\\tfrac12)\\lambda$. **Michelson interferometer**: splits a beam, sends it down two perpendicular arms of length $L_1,L_2$, recombines it; moving one mirror by $\\Delta L$ changes the round-trip path difference by $2\\Delta L$, cycling through bright/dark fringes every time $2\\Delta L$ changes by $\\lambda$ — an extremely sensitive length-measuring tool for exactly this reason." },
        { kind: "apply", md: "Double slit, $d=0.20\\,\\text{mm}$, $\\lambda=600\\,\\text{nm}$: first bright fringe off-axis at $\\sin\\theta = \\lambda/d = (600\\times10^{-9})/(0.20\\times10^{-3}) = 3\\times10^{-3}$, a tiny angle, consistent with the small-angle approximation used throughout. **Thin-film limiting case**: a soap film ($n\\approx1.33$) in air, so light reflects off a higher-index surface on top ($\\pi$ shift) and a lower-index surface on the bottom, going from film back to air (no shift) — net one shift, so the constructive condition becomes $2nt=(m+\\tfrac12)\\lambda$, which is why soap films look dark (destructive for all visible wavelengths) at their thinnest point just before popping, rather than bright — a classic 'notice which surfaces flip phase' trap." },
        { kind: "transfer", md: "'Amplitude superposition, judged by path difference measured in wavelengths' is the single idea underlying every interference phenomenon in optics, exactly paralleling the standing-wave lesson's superposition of counter-propagating waves — the difference is purely geometric (two spatially separated sources instead of one wave reflecting back on itself). The next lesson (diffraction) extends this from two sources to a continuum of sources across a slit or many discrete sources in a grating, using the identical path-difference logic." }
      ],
      checkpoints: [
        { q: "In a double-slit experiment, why must waves be treated as amplitudes that can cancel, rather than as intensities that simply add?", options: ["Because intensities can be negative", "Because observed dark fringes are dimmer than either slit's individual contribution, which a sum of non-negative intensities could never produce", "Because light travels faster through one slit than the other", "Because the slits are too close together for intensities to add properly"], answer: 1, explain: "Summing two non-negative intensities can only ever give a result at least as large as the larger one; true cancellation (dark fringes below either individual intensity) requires signed amplitudes that can destructively interfere." },
        { q: "A thin film experiences a net phase shift of $\\pi$ from its two reflecting surfaces combined (one surface flips, one doesn't). Its constructive-interference condition is:", options: ["$2nt = m\\lambda$", "$2nt = (m+\\tfrac12)\\lambda$", "$nt = m\\lambda$", "$t = m\\lambda$"], answer: 1, explain: "An extra half-wavelength shift from reflection flips which path-difference condition corresponds to constructive vs. destructive interference, giving $2nt=(m+\\tfrac12)\\lambda$ for constructive." }
      ]
    },
    {
      id: "waves-optics-diffraction",
      title: "Diffraction: single slit, gratings, and the resolution limit",
      minutes: 14,
      discovery: "Treating every point across an open slit as its own point source (Huygens' principle) and summing their interference explains why even a single slit produces a fringe pattern — and the same reasoning, applied to a circular aperture, sets a hard limit on how finely any optical instrument can resolve detail.",
      sections: [
        { kind: "problem", md: "Shine light through a *single* narrow slit (not two). There's no second source to interfere with — so why does the resulting pattern on a screen still show multiple dark fringes, not just one broad bright smear directly behind the slit? And separately: why can't a telescope, no matter how well-built, resolve two stars that are angularly too close together — what fundamentally limits resolution, beyond just 'better lenses'?" },
        { kind: "candidates", md: "**A. A single slit should produce one bright region directly behind it**, tapering off smoothly, since there's no second source to interfere against.\n\n**B. Treat the slit's finite width as irrelevant** — for a narrow enough slit, light should behave as if it came from a single point, producing a simple point-source pattern.\n\n**C. Treat every point across the slit's open width as its own independent point source (Huygens' principle), and sum the interference of *all* of them at each screen angle.**" },
        { kind: "failures", md: "**A fails observationally**: real single-slit patterns show a bright central maximum flanked by multiple dimmer fringes with genuine dark minima in between — structure that a single, structureless source could never produce.\n\n**B fails for the same reason it did with resolution**: if slit width truly didn't matter, no diffraction pattern would exist at all, and any two point sources — however close — would produce perfectly sharp, separable images no matter how small the lens. Real telescopes clearly don't resolve arbitrarily close stars, so *something* about the aperture's finite size is doing physical work here." },
        { kind: "discovery", md: "C, applied carefully, resolves both puzzles. Pair up points across the slit width $w$ that are exactly $w/2$ apart: at certain screen angles, every such pair is exactly out of phase (path difference $\\lambda/2$), and since this pairing covers the *entire* slit, the whole thing cancels — a genuine dark fringe from a *single* slit, no second slit required. The same 'finite aperture $\\Rightarrow$ some inherent angular spread in the output' logic applies to any lens or telescope aperture (effectively a circular slit): light passing through a finite opening *must* spread by some minimum angle, which is why two point sources close enough together produce overlapping diffraction patterns that can no longer be told apart — the resolution limit isn't an engineering flaw, it's the diffraction pattern's own dark-fringe structure setting a floor." },
        { kind: "formal", md: "**Single-slit minima** (slit width $w$): $w\\sin\\theta = m\\lambda$, $m=1,2,3,\\dots$ (note: $m=0$ is *not* a minimum here — it's the central bright maximum, unlike the double-slit case where $m=0$ gives a bright fringe at the center for the *same* reason but a different formula; don't confuse the two conditions). **Diffraction grating** ($N$ slits, spacing $d$): bright maxima still occur where $d\\sin\\theta=m\\lambda$ (same condition as double slit, since it's still 'path difference between adjacent sources'), but with $N$ sources instead of $2$, the maxima become much narrower and brighter — more sources to destructively interfere away from the peak means less light leaking into a broad smear. **Rayleigh criterion** (angular resolution limit of a circular aperture, diameter $D$): $\\theta_{\\min} \\approx 1.22\\dfrac{\\lambda}{D}$ — two point sources closer than this angle are considered unresolved." },
        { kind: "apply", md: "A single slit of width $w=0.10\\,\\text{mm}$ illuminated by $\\lambda=500\\,\\text{nm}$: first minimum at $\\sin\\theta = \\lambda/w = (500\\times10^{-9})/(10^{-4}) = 5\\times10^{-3}$ — small angle, matching the paraxial approximation used throughout this module. **Resolution estimate**: a telescope aperture $D=1.0\\,\\text{m}$ observing $\\lambda=550\\,\\text{nm}$ (visible light): $\\theta_{\\min} \\approx 1.22(550\\times10^{-9})/1.0 \\approx 6.7\\times10^{-7}\\,\\text{rad}$ — an extremely small angle, but not zero, which is exactly the point: even a 'perfect,' aberration-free telescope has this floor, set purely by the wave nature of light and the aperture size, not by manufacturing quality." },
        { kind: "transfer", md: "'Sum a continuum (or a large discrete number) of point sources across some aperture, and interference among them structures the output' is the same Huygens-style idea used for antenna arrays (radio engineering), X-ray diffraction off crystal lattices (identical math to a grating, just with a 2D/3D array of sources instead of a 1D line), and electron microscopy resolution limits (same Rayleigh-criterion logic, different wavelength regime). Recognizing 'this is a diffraction-limited resolution question' the moment you see 'smallest resolvable angle/detail' in a problem is a fast route straight to the Rayleigh formula, without re-deriving from Huygens' principle each time." }
      ],
      checkpoints: [
        { q: "A single slit of width $w$ produces a diffraction pattern with dark fringes even though there is only one slit. This happens because:", options: ["Light passing through a single slit cannot produce any pattern; this scenario is impossible", "Every point across the slit's width acts as its own source, and at certain angles these sources destructively interfere pairwise across the whole slit", "The slit itself absorbs some wavelengths selectively", "Diffraction only occurs with two or more slits, so this is actually a double-slit effect in disguise"], answer: 1, explain: "Huygens' principle treats the open slit as a continuum of point sources; at the single-slit minima, pairing points $w/2$ apart across the whole width gives complete pairwise cancellation." },
        { q: "Increasing a telescope's aperture diameter $D$ (keeping wavelength fixed) has what effect on its angular resolution limit $\\theta_{\\min}=1.22\\lambda/D$?", options: ["$\\theta_{\\min}$ decreases, meaning better (finer) resolution", "$\\theta_{\\min}$ increases, meaning worse resolution", "No effect; resolution depends only on wavelength", "$\\theta_{\\min}$ becomes exactly zero for any $D>0$"], answer: 0, explain: "$\\theta_{\\min}\\propto1/D$, so a larger aperture gives a smaller minimum resolvable angle — better resolution — which is the practical reason telescopes and microscopes are built with the largest feasible apertures." }
      ]
    },
    {
      id: "waves-optics-polarization",
      title: "Polarization: Malus's law, Brewster's angle, and birefringence",
      minutes: 13,
      discovery: "Because light's electric field oscillates transverse to its direction of travel (established when you derived the EM wave equation), it carries an orientation that a filter can selectively transmit — a property longitudinal waves like sound structurally cannot have, and the source of both Malus's law and Brewster's-angle reflection.",
      sections: [
        { kind: "problem", md: "Polarized sunglasses visibly dim glare off water or a road when worn normally, but rotate them $90°$ and the glare returns brighter — the *orientation* of the lens matters, not just its presence. Try the analogous experiment with sound: is there any filter you could rotate in front of a speaker that dims the sound differently depending on the filter's orientation, the way polarized lenses do for light? There isn't — so what does light have that sound doesn't, that makes this orientation-dependence possible?" },
        { kind: "candidates", md: "**A. Intensity through a filter depends only on the total intensity incident**, with no dependence on the filter's orientation — matching how sound filters (e.g. absorptive foam) work.\n\n**B. The filter selectively absorbs certain wavelengths depending on its rotation**, acting like a rotating color filter.\n\n**C. The filter selectively transmits only the component of the wave's oscillation aligned with some special axis of the filter** — which requires the wave to have an orientation (a direction of oscillation) that's independent of its direction of travel." },
        { kind: "failures", md: "**A directly contradicts the sunglasses experiment**: rotating the lens visibly changes transmitted brightness, so orientation demonstrably matters for light in a way it never does for a simple intensity-only filter.\n\n**B is falsified by color**: rotating polarized sunglasses changes *brightness*, not *color* — if the filter were wavelength-selective depending on angle, you'd see color shifts as you rotate them, which isn't observed. Whatever the filter is selecting, it isn't wavelength." },
        { kind: "discovery", md: "C is exactly what the EM-wave lesson set up: light's $\\mathbf{E}$ field oscillates *transverse* to the direction of travel, meaning it has a well-defined orientation within the plane perpendicular to propagation (e.g. vertical vs. horizontal) that's entirely separate from which direction the wave is heading. A polarizing filter has a transmission axis and passes only the component of $\\mathbf{E}$ along that axis, blocking the perpendicular component. Sound, being a *longitudinal* wave (compressions along the direction of travel, no side-to-side oscillation at all), has no such extra orientational degree of freedom to select — there's nothing analogous to 'rotate a sound-polarizing filter' because sound simply doesn't have a transverse orientation to filter." },
        { kind: "formal", md: "**Malus's law**: if light of intensity $I_0$, already polarized, passes through a second polarizer ('analyzer') whose transmission axis is at angle $\\theta$ to the light's polarization direction, the transmitted intensity is $I = I_0\\cos^2\\theta$ (the transmitted *field* amplitude is $E_0\\cos\\theta$, the projection onto the analyzer's axis; intensity $\\propto E^2$ gives the $\\cos^2\\theta$). **Brewster's angle**: unpolarized light reflecting off a dielectric surface (index $n_1\\to n_2$) becomes *fully* polarized (perpendicular to the plane of incidence) at one specific incidence angle $\\theta_B$ where $\\tan\\theta_B = n_2/n_1$ — physically, this is the angle at which the reflected and refracted rays are exactly perpendicular to each other, so the oscillating dipoles in the surface that would re-radiate the other polarization component can't radiate along the reflected direction at all (a dipole doesn't radiate along its own oscillation axis). **Birefringence** (recognition level): certain crystals (e.g. calcite) have a refractive index that depends on polarization direction, so unpolarized light splits into two separated rays with perpendicular polarizations traveling at different speeds through the crystal." },
        { kind: "apply", md: "Unpolarized light of intensity $I_0$ first passes through a polarizer (intensity halves, since it passes only one orientation's worth of the randomly-oriented incoming light: $I_0/2$), then through a second polarizer at $60°$ to the first: $I = (I_0/2)\\cos^2(60°) = (I_0/2)(1/4) = I_0/8$. **Brewster's angle for glass** ($n=1.5$, light from air): $\\theta_B = \\arctan(1.5) \\approx 56.3°$ — worth recognizing as 'somewhat steeper than $45°$' for a quick sanity check without a calculator, since $\\arctan(1)=45°$ and $n>1$ pushes the angle larger." },
        { kind: "transfer", md: "The 'transverse wave $\\Rightarrow$ has an orientation $\\Rightarrow$ can be polarized; longitudinal wave $\\Rightarrow$ cannot' distinction is a fast way to eliminate wrong answers on any question asking whether some wave (water waves, EM waves, sound, seismic waves) can be polarized — check transverse vs. longitudinal first. It also closes the loop on this module: the transverse nature of light traces directly back to Maxwell's equations forcing $\\mathbf{E}\\perp\\mathbf{B}\\perp(\\text{propagation direction})$, so polarization isn't a separate assumption bolted onto optics — it's a direct, inevitable consequence of the electromagnetic origin of light you established in the electromagnetism module." }
      ],
      checkpoints: [
        { q: "Why can sound waves in air (or in a fluid) not be polarized, while light waves can?", options: ["Sound waves travel too slowly for polarization to matter", "Sound in air or a fluid is a purely longitudinal wave with no oscillation transverse to its direction of travel, so it has no orientation for a filter to select", "Sound waves have too low a frequency", "Polarization is actually possible for sound in air too, using the right filter"], answer: 1, explain: "Polarization requires a transverse oscillation with a selectable orientation; sound in a fluid or gas compresses only along the direction of travel, leaving no transverse degree of freedom to filter (sound in a solid can support shear/transverse components and can be polarized, but that's a different case)." },
        { q: "Unpolarized light of intensity $I_0$ passes through a polarizer, then through a second polarizer whose axis is at $90°$ to the first. The transmitted intensity is:", options: ["$I_0/2$", "$I_0/4$", "Zero", "$I_0$"], answer: 2, explain: "The first polarizer gives $I_0/2$; Malus's law then gives $I=(I_0/2)\\cos^2(90°) = (I_0/2)(0) = 0$ — crossed polarizers block all light." }
      ]
    }
  ],
  drills: [
    { id: "waves-optics-wave-equation-d1", lesson: "waves-optics-wave-equation", type: "mc", prompt: "If a string's tension is quadrupled (mass per length unchanged), the wave speed:", options: ["Doubles", "Quadruples", "Halves", "Stays the same"], answer: 0, hint: "$v=\\sqrt{T/\\mu}$.", solution: "$v\\propto\\sqrt{T}$; quadrupling $T$ multiplies $v$ by $\\sqrt4=2$.", difficulty: 1, tags: ["wave-speed"] },
    { id: "waves-optics-wave-equation-d2", lesson: "waves-optics-wave-equation", type: "mc", prompt: "If a string's mass per unit length is quadrupled (tension unchanged), the wave speed:", options: ["Doubles", "Quadruples", "Halves", "Becomes one quarter"], answer: 2, hint: "$v=\\sqrt{T/\\mu}$.", solution: "$v\\propto1/\\sqrt{\\mu}$; quadrupling $\\mu$ divides $v$ by $\\sqrt4=2$.", difficulty: 1, tags: ["wave-speed"] },
    { id: "waves-optics-wave-equation-d3", lesson: "waves-optics-wave-equation", type: "numeric", prompt: "A string has $\\mu=0.0050\\,\\text{kg/m}$ under tension $90\\,\\text{N}$. Find the wave speed.", answer: 134.2, tolerance: 0.03, unit: "m/s", hint: "$v=\\sqrt{T/\\mu}$.", solution: "$v=\\sqrt{90/0.0050}=\\sqrt{18000}\\approx134.2\\,\\text{m/s}$.", difficulty: 2, tags: ["wave-speed", "computation"] },
    { id: "waves-optics-wave-equation-d4", lesson: "waves-optics-wave-equation", type: "mc", prompt: "Two pulses of very different amplitude are sent down the same string under the same tension. Their speeds are:", options: ["The same, since wave speed doesn't depend on amplitude", "Different, larger amplitude moves faster", "Different, larger amplitude moves slower", "Impossible to determine"], answer: 0, hint: "What variables appear in $v=\\sqrt{T/\\mu}$?", solution: "Amplitude doesn't appear in $v=\\sqrt{T/\\mu}$ at all, matching the experimental fact that small-amplitude pulse speed is amplitude-independent.", difficulty: 2, tags: ["wave-speed", "conceptual"] },
    { id: "waves-optics-wave-equation-d5", lesson: "waves-optics-wave-equation", type: "mc", prompt: "Which function is a valid solution of the wave equation $\\partial^2y/\\partial t^2 = v^2\\,\\partial^2y/\\partial x^2$?", options: ["$y=A\\sin(kx-\\omega t)$ with $\\omega/k=v$", "$y=Ax^2t$", "$y=A\\sin(kx)\\sin(\\omega t)$ with arbitrary $\\omega,k$", "$y=Ae^{-x^2}$ (time-independent)"], answer: 0, hint: "Substitute each candidate and check both sides match, requiring $\\omega/k=v$.", solution: "$y=A\\sin(kx-\\omega t)$ is a traveling wave of speed $\\omega/k$; substitution confirms it solves the equation only when $\\omega/k=v$, unlike the other options which fail for generic parameters.", difficulty: 3, tags: ["wave-equation", "verification"] },
    { id: "waves-optics-superposition-d1", lesson: "waves-optics-superposition", type: "mc", prompt: "On a string fixed at both ends, the fundamental standing wave has:", options: ["Nodes at both ends, one antinode in the middle", "Antinodes at both ends", "No nodes anywhere", "A node exactly at the string's center only"], answer: 0, hint: "Fixed ends can't move — think about what 'fixed' means for displacement.", solution: "Fixed ends have zero displacement always — nodes — and the fundamental mode has exactly one antinode between them.", difficulty: 1, tags: ["standing-waves"] },
    { id: "waves-optics-superposition-d2", lesson: "waves-optics-superposition", type: "numeric", prompt: "A string of length $0.80\\,\\text{m}$, fixed at both ends, has wave speed $60\\,\\text{m/s}$. Find its fundamental frequency.", answer: 37.5, tolerance: 0.03, unit: "Hz", hint: "$f_1=v/2L$.", solution: "$f_1 = 60/(2\\times0.80) = 60/1.6 = 37.5\\,\\text{Hz}$.", difficulty: 2, tags: ["standing-waves", "computation"] },
    { id: "waves-optics-superposition-d3", lesson: "waves-optics-superposition", type: "numeric", prompt: "Two tuning forks at $256\\,\\text{Hz}$ and $259\\,\\text{Hz}$ are struck together. Find the beat frequency.", answer: 3, tolerance: 0.03, unit: "Hz", hint: "$f_{\\text{beat}}=|f_1-f_2|$.", solution: "$|259-256|=3\\,\\text{Hz}$.", difficulty: 1, tags: ["beats", "computation"] },
    { id: "waves-optics-superposition-d4", lesson: "waves-optics-superposition", type: "mc", prompt: "Two identical pulses, one leaning up and one leaning down, travel toward each other on a string and momentarily overlap exactly. At that instant, the string's displacement at the overlap point is:", options: ["Zero, since the amplitudes cancel by superposition", "Twice either pulse's amplitude", "Equal to whichever pulse has more energy", "Undefined, since two waves cannot occupy the same point"], answer: 0, hint: "Superposition adds displacements directly, including sign.", solution: "Equal and opposite displacements sum to exactly zero at that instant, then each pulse continues on unchanged afterward.", difficulty: 2, tags: ["superposition", "conceptual"] },
    { id: "waves-optics-superposition-d5", lesson: "waves-optics-superposition", type: "mc", prompt: "A string fixed at both ends has length $L$. Which wavelengths are allowed for standing waves on it?", options: ["$\\lambda_n = 2L/n$ for positive integers $n$", "$\\lambda_n = L/n$ for positive integers $n$", "Any wavelength is allowed", "$\\lambda_n = 4L/n$ for odd integers $n$ only"], answer: 0, hint: "The condition is $L=n\\lambda/2$.", solution: "$L=n\\lambda/2 \\Rightarrow \\lambda_n = 2L/n$, requiring nodes at both fixed ends.", difficulty: 3, tags: ["standing-waves"] },
    { id: "waves-optics-doppler-d1", lesson: "waves-optics-doppler", type: "mc", prompt: "A sound source moves toward a stationary observer. The observed frequency $f'$ compared to the emitted frequency $f$ is:", options: ["Higher: $f'=fv/(v-u_s)$", "Lower: $f'=fv/(v+u_s)$", "Unchanged", "Higher: $f'=f(v+u_s)/v$"], answer: 0, hint: "Wavefronts bunch up ahead of an approaching source.", solution: "A source moving toward the observer emits successive wavefronts from closer positions, compressing the wavelength and raising $f'$: $f'=fv/(v-u_s)$.", difficulty: 1, tags: ["doppler"] },
    { id: "waves-optics-doppler-d2", lesson: "waves-optics-doppler", type: "mc", prompt: "An observer moves away from a stationary sound source at speed $u_o$. The observed frequency is:", options: ["$f' = f(v-u_o)/v$, lower than $f$", "$f' = f(v+u_o)/v$, higher than $f$", "Unchanged, since the source isn't moving", "$f' = fv/(v-u_o)$"], answer: 0, hint: "Moving away means sweeping up fewer wavefronts per second.", solution: "Moving away from the source, the observer intercepts fewer wavefronts per unit time: $f'=f(v-u_o)/v$, lower than $f$.", difficulty: 2, tags: ["doppler"] },
    { id: "waves-optics-doppler-d3", lesson: "waves-optics-doppler", type: "numeric", prompt: "A car horn at $400\\,\\text{Hz}$ approaches a stationary listener at $20\\,\\text{m/s}$ (sound speed $340\\,\\text{m/s}$). Find the observed frequency.", answer: 425, tolerance: 0.03, unit: "Hz", hint: "$f'=fv/(v-u_s)$.", solution: "$f' = 400\\times340/(340-20) = 400\\times340/320 = 425\\,\\text{Hz}$.", difficulty: 2, tags: ["doppler", "computation"] },
    { id: "waves-optics-doppler-d4", lesson: "waves-optics-doppler", type: "mc", prompt: "Unlike sound, light's Doppler shift depends only on the relative velocity between source and observer, not on which one is 'really' moving. This is because:", options: ["Light has no medium providing an absolute rest frame", "Light travels too fast for the distinction to be measurable", "Light's frequency cannot actually shift", "This is a common misconception; light's Doppler shift is also asymmetric"], answer: 0, hint: "Recall why sound's formula is asymmetric.", solution: "Sound's medium (air) breaks the symmetry between source and observer motion; light has no medium, so only relative velocity can appear in its Doppler formula.", difficulty: 1, tags: ["doppler", "em-waves"] },
    { id: "waves-optics-doppler-d5", lesson: "waves-optics-doppler", type: "mc", prompt: "As a sound source's speed toward a stationary observer approaches the speed of sound itself ($u_s\\to v$), the Doppler formula $f'=fv/(v-u_s)$ predicts:", options: ["$f'\\to\\infty$, consistent with wavefronts piling up at the source (a sonic boom forming)", "$f'\\to0$", "$f'\\to f$, unchanged", "The formula becomes undefined and gives no physical information"], answer: 0, hint: "What happens to the denominator as $u_s\\to v$?", solution: "As $u_s\\to v$, $(v-u_s)\\to0^+$, so $f'\\to\\infty$ — physically, wavefronts have no time to spread ahead of the source, matching the shock-wave (sonic boom) limit.", difficulty: 3, tags: ["doppler", "limiting-case"] },
    { id: "waves-optics-geometric-optics-d1", lesson: "waves-optics-geometric-optics", type: "mc", prompt: "In the standard thin-lens sign convention, a negative image distance $d_i$ indicates:", options: ["A virtual image", "A real image", "An inverted image", "A magnified image"], answer: 0, hint: "$d_i>0$ means light actually converges there.", solution: "$d_i<0$ means the image is virtual — light only appears to diverge from that point, it doesn't actually converge there.", difficulty: 1, tags: ["optics", "sign-convention"] },
    { id: "waves-optics-geometric-optics-d2", lesson: "waves-optics-geometric-optics", type: "numeric", prompt: "An object is placed $d_o=20\\,\\text{cm}$ from a converging lens with $f=5\\,\\text{cm}$. Find the image distance $d_i$.", answer: 6.67, tolerance: 0.03, unit: "cm", hint: "$1/d_o+1/d_i=1/f$.", solution: "$1/d_i = 1/5 - 1/20 = 4/20-1/20=3/20 \\Rightarrow d_i = 20/3 \\approx 6.67\\,\\text{cm}$.", difficulty: 2, tags: ["thin-lens", "computation"] },
    { id: "waves-optics-geometric-optics-d3", lesson: "waves-optics-geometric-optics", type: "mc", prompt: "A diverging lens, by the standard sign convention, has:", options: ["$f<0$", "$f>0$", "$f=0$", "$f$ that depends on the object distance"], answer: 0, hint: "Converging lenses have $f>0$; diverging is the opposite.", solution: "Diverging lenses (and convex mirrors) are assigned $f<0$ in the standard convention.", difficulty: 1, tags: ["optics", "sign-convention"] },
    { id: "waves-optics-geometric-optics-d4", lesson: "waves-optics-geometric-optics", type: "numeric", prompt: "A concave mirror with $f=15\\,\\text{cm}$ forms an image of an object at $d_o=45\\,\\text{cm}$. Find the magnification $m$.", answer: -0.5, tolerance: 0.05, hint: "First find $d_i$ from $1/d_o+1/d_i=1/f$, then $m=-d_i/d_o$.", solution: "$1/d_i = 1/15-1/45 = 3/45-1/45=2/45 \\Rightarrow d_i=22.5\\,\\text{cm}$. $m=-22.5/45=-0.5$.", difficulty: 2, tags: ["mirrors", "magnification", "computation"] },
    { id: "waves-optics-geometric-optics-d5", lesson: "waves-optics-geometric-optics", type: "mc", prompt: "An object is placed between a converging lens and its focal point ($0<d_o<f$). The resulting image is:", options: ["Virtual, upright, and magnified", "Real, inverted, and shrunk", "Real, upright, and magnified", "Virtual, inverted, and shrunk"], answer: 0, hint: "Solve $1/d_o+1/d_i=1/f$ symbolically for $d_o<f$ and check the sign of $d_i$.", solution: "For $d_o<f$, $1/d_i=1/f-1/d_o<0$, so $d_i<0$ (virtual); working through magnification gives $m>1$ and positive (upright, magnified) — this is the magnifying-glass configuration.", difficulty: 3, tags: ["thin-lens", "limiting-case"] },
    { id: "waves-optics-interference-d1", lesson: "waves-optics-interference", type: "mc", prompt: "In a double-slit experiment, bright fringes occur where the path difference $\\delta=d\\sin\\theta$ equals:", options: ["$m\\lambda$, integer $m$", "$(m+\\tfrac12)\\lambda$, integer $m$", "$m\\lambda/2$, any integer $m$", "$\\lambda/d$"], answer: 0, hint: "Constructive interference requires waves to arrive in phase.", solution: "In-phase arrival requires the path difference to be a whole number of wavelengths: $d\\sin\\theta=m\\lambda$.", difficulty: 1, tags: ["interference"] },
    { id: "waves-optics-interference-d2", lesson: "waves-optics-interference", type: "numeric", prompt: "A double slit with $d=0.15\\,\\text{mm}$ is illuminated by $\\lambda=650\\,\\text{nm}$. Find $\\sin\\theta$ for the first bright fringe off-center.", answer: 0.00433, tolerance: 0.03, hint: "$d\\sin\\theta=\\lambda$ for $m=1$.", solution: "$\\sin\\theta = \\lambda/d = (650\\times10^{-9})/(0.15\\times10^{-3}) \\approx 4.33\\times10^{-3}$.", difficulty: 2, tags: ["interference", "computation"] },
    { id: "waves-optics-interference-d3", lesson: "waves-optics-interference", type: "mc", prompt: "A thin coating (index $n_{\\text{coat}}$) sits on a glass substrate of higher index ($n_{\\text{substrate}} > n_{\\text{coat}} > n_{\\text{air}}$). Both reflections — air-to-coating and coating-to-substrate — pick up a $\\pi$ phase flip, for a net relative shift of zero. Its constructive-interference condition is:", options: ["$2nt = m\\lambda$", "$2nt = (m+\\tfrac12)\\lambda$", "$nt = (m+\\tfrac12)\\lambda$", "$t = m\\lambda/2$"], answer: 0, hint: "With no net extra shift (both reflections flip equally), the plain in-phase condition applies.", solution: "With both reflections flipping by $\\pi$, the flips cancel relative to each other, leaving the plain in-phase condition $2nt=m\\lambda$, the same form as double-slit but using the round-trip path $2nt$ inside the coating.", difficulty: 2, tags: ["thin-films"] },
    { id: "waves-optics-interference-d4", lesson: "waves-optics-interference", type: "numeric", prompt: "In a Michelson interferometer using $\\lambda=600\\,\\text{nm}$, one mirror is moved by $\\Delta L$ and 400 bright-dark fringe cycles are counted. Find $\\Delta L$.", answer: 0.00012, tolerance: 0.03, unit: "m", hint: "Each fringe cycle corresponds to $2\\Delta L = \\lambda$.", solution: "$2\\Delta L_{\\text{total}} = 400\\lambda \\Rightarrow \\Delta L = 200\\lambda = 200(600\\times10^{-9}) = 1.2\\times10^{-4}\\,\\text{m}$.", difficulty: 3, tags: ["michelson", "computation"] },
    { id: "waves-optics-interference-d5", lesson: "waves-optics-interference", type: "mc", prompt: "Interference patterns require light to be treated as adding via:", options: ["Amplitudes (signed field values), squared afterward for intensity", "Intensities directly, since intensity is what a detector measures", "Photon counts only, with no wave description needed", "Frequencies, which combine to form beats in space"], answer: 0, hint: "Recall why intensity summation alone can't explain dark fringes.", solution: "Amplitude (signed) superposition, with intensity computed as the square only at the end, is required to explain destructive interference (dark fringes dimmer than either source alone).", difficulty: 1, tags: ["interference", "conceptual"] },
    { id: "waves-optics-diffraction-d1", lesson: "waves-optics-diffraction", type: "mc", prompt: "For a single slit of width $w$, dark fringes (minima) occur where:", options: ["$w\\sin\\theta = m\\lambda$, integer $m\\ne0$", "$w\\sin\\theta = (m+\\tfrac12)\\lambda$", "$w\\sin\\theta = m\\lambda/2$, any integer $m$", "There are no minima for a single slit"], answer: 0, hint: "Pair points across the slit width for cancellation.", solution: "Single-slit minima occur at $w\\sin\\theta=m\\lambda$ ($m\\ne0$); note this is the double-slit *bright*-fringe formula but applied to minima here — don't mix up the two contexts.", difficulty: 1, tags: ["diffraction"] },
    { id: "waves-optics-diffraction-d2", lesson: "waves-optics-diffraction", type: "numeric", prompt: "A single slit of width $0.080\\,\\text{mm}$ is illuminated by $\\lambda=450\\,\\text{nm}$. Find $\\sin\\theta$ for the first minimum.", answer: 0.005625, tolerance: 0.03, hint: "$w\\sin\\theta=\\lambda$ for $m=1$.", solution: "$\\sin\\theta=\\lambda/w=(450\\times10^{-9})/(8\\times10^{-5})\\approx5.6\\times10^{-3}$.", difficulty: 2, tags: ["diffraction", "computation"] },
    { id: "waves-optics-diffraction-d3", lesson: "waves-optics-diffraction", type: "mc", prompt: "Compared to a simple double slit, a diffraction grating with many more slits ($N\\gg2$) at the same spacing $d$ produces bright maxima that are:", options: ["At the same angles, but much narrower and brighter", "At completely different angles", "Broader and dimmer", "Identical in every way to the double-slit pattern"], answer: 0, hint: "More sources means more destructive interference away from the exact maximum.", solution: "The maxima condition $d\\sin\\theta=m\\lambda$ is unchanged, but with more sources, cancellation away from the peak is much more complete, sharpening the maxima.", difficulty: 2, tags: ["diffraction", "grating"] },
    { id: "waves-optics-diffraction-d4", lesson: "waves-optics-diffraction", type: "numeric", prompt: "Estimate the minimum resolvable angle for a telescope with aperture $D=2.0\\,\\text{m}$ observing light of $\\lambda=550\\,\\text{nm}$.", answer: 3.36e-7, tolerance: 0.05, unit: "rad", hint: "$\\theta_{\\min}=1.22\\lambda/D$.", solution: "$\\theta_{\\min} = 1.22(550\\times10^{-9})/2.0 \\approx 3.36\\times10^{-7}\\,\\text{rad}$.", difficulty: 3, tags: ["diffraction", "resolution", "computation"] },
    { id: "waves-optics-diffraction-d5", lesson: "waves-optics-diffraction", type: "mc", prompt: "Doubling a telescope's aperture diameter $D$ (wavelength fixed) has what effect on its minimum resolvable angle?", options: ["It halves, meaning better resolution", "It doubles, meaning worse resolution", "No change", "It quadruples"], answer: 0, hint: "$\\theta_{\\min}\\propto1/D$.", solution: "$\\theta_{\\min}=1.22\\lambda/D\\propto1/D$; doubling $D$ halves $\\theta_{\\min}$.", difficulty: 1, tags: ["diffraction", "resolution"] },
    { id: "waves-optics-polarization-d1", lesson: "waves-optics-polarization", type: "numeric", prompt: "Polarized light of intensity $80\\,\\text{W/m}^2$ passes through an analyzer at $30°$ to its polarization direction. Find the transmitted intensity.", answer: 60, tolerance: 0.03, unit: "W/m^2", hint: "Malus's law: $I=I_0\\cos^2\\theta$.", solution: "$I = 80\\cos^2(30°) = 80(0.75) = 60\\,\\text{W/m}^2$.", difficulty: 2, tags: ["polarization", "malus", "computation"] },
    { id: "waves-optics-polarization-d2", lesson: "waves-optics-polarization", type: "mc", prompt: "Light passes through two polarizers with perpendicular (crossed) transmission axes. The transmitted intensity is:", options: ["Zero", "Half the incident intensity", "One quarter the incident intensity", "Equal to the incident intensity"], answer: 0, hint: "$\\cos^2(90°) = 0$.", solution: "Malus's law gives $I=I_1\\cos^2(90°)=0$: crossed polarizers block all light.", difficulty: 1, tags: ["polarization", "malus"] },
    { id: "waves-optics-polarization-d3", lesson: "waves-optics-polarization", type: "numeric", prompt: "Find Brewster's angle for light reflecting from a water surface ($n=1.33$) from air.", answer: 53.1, tolerance: 0.03, unit: "degrees", hint: "$\\tan\\theta_B = n_2/n_1$.", solution: "$\\theta_B = \\arctan(1.33) \\approx 53.1°$.", difficulty: 2, tags: ["polarization", "brewster", "computation"] },
    { id: "waves-optics-polarization-d4", lesson: "waves-optics-polarization", type: "mc", prompt: "Polarization is possible for light but not for ordinary sound waves because:", options: ["Light is transverse (oscillation perpendicular to travel direction); sound is longitudinal (oscillation along the travel direction)", "Light travels faster than sound", "Sound has too low a frequency to be polarized", "Polarization is actually possible for sound; this is a common misconception"], answer: 0, hint: "Polarization requires a transverse degree of freedom.", solution: "Only transverse waves have an orientation (perpendicular to travel) that a filter can select; sound's longitudinal compressions have no such freedom.", difficulty: 1, tags: ["polarization", "conceptual"] },
    { id: "waves-optics-polarization-d5", lesson: "waves-optics-polarization", type: "mc", prompt: "A birefringent crystal (like calcite) affects unpolarized light passing through it by:", options: ["Splitting it into two rays with perpendicular polarizations, traveling at different speeds", "Absorbing all light regardless of polarization", "Rotating the light's frequency", "Having no effect on light, since it's a normal transparent crystal"], answer: 0, hint: "The refractive index depends on polarization direction in such crystals.", solution: "Because $n$ differs for the two perpendicular polarization components, they refract differently, physically separating into two rays.", difficulty: 3, tags: ["polarization", "birefringence"] }
  ],
  test: [
    { id: "waves-optics-t1", prompt: "A string's tension is increased by a factor of 9 (mass per length unchanged). The new wave speed, compared to the original, is:", options: ["3 times as large", "9 times as large", "One third as large", "81 times as large", "One ninth as large"], answer: 0, solution: "$v=\\sqrt{T/\\mu}\\propto\\sqrt{T}$; a factor of 9 in $T$ gives a factor of $\\sqrt9=3$ in $v$.", difficulty: 1, tags: ["wave-speed"], lesson: "waves-optics-wave-equation" },
    { id: "waves-optics-t2", prompt: "A string of length $0.90\\,\\text{m}$, fixed at both ends, has a fundamental frequency of $50\\,\\text{Hz}$. The wave speed on the string is:", options: ["$45\\,\\text{m/s}$", "$90\\,\\text{m/s}$", "$180\\,\\text{m/s}$", "$22.5\\,\\text{m/s}$", "$100\\,\\text{m/s}$"], answer: 1, solution: "$f_1=v/2L \\Rightarrow v=2Lf_1=2(0.90)(50)=90\\,\\text{m/s}$.", difficulty: 2, tags: ["standing-waves", "computation"], lesson: "waves-optics-superposition" },
    { id: "waves-optics-t3", prompt: "Two tuning forks, $440\\,\\text{Hz}$ and $445\\,\\text{Hz}$, are struck together. The beat frequency heard is:", options: ["$5\\,\\text{Hz}$", "$2.5\\,\\text{Hz}$", "$445\\,\\text{Hz}$", "$440\\,\\text{Hz}$", "$885\\,\\text{Hz}$"], answer: 0, solution: "$f_{\\text{beat}}=|445-440|=5\\,\\text{Hz}$.", difficulty: 1, tags: ["beats"], lesson: "waves-optics-superposition" },
    { id: "waves-optics-t4", prompt: "A $600\\,\\text{Hz}$ source moves away from a stationary observer at $30\\,\\text{m/s}$ (sound speed $340\\,\\text{m/s}$). The observed frequency is closest to:", options: ["$551\\,\\text{Hz}$", "$654\\,\\text{Hz}$", "$600\\,\\text{Hz}$", "$500\\,\\text{Hz}$", "$340\\,\\text{Hz}$"], answer: 0, solution: "$f'=fv/(v+u_s) = 600(340)/(370) \\approx 551\\,\\text{Hz}$.", difficulty: 2, tags: ["doppler", "computation"], lesson: "waves-optics-doppler" },
    { id: "waves-optics-t5", prompt: "For light emitted by a slowly receding source ($u\\ll c$), doubling the recession speed $u$ doubles the fractional frequency shift $|\\Delta f|/f$. This follows directly from:", options: ["The light Doppler formula $f'\\approx f(1\\mp u/c)$ being linear in $u$", "Light having a medium that breaks source/observer symmetry", "The inverse-square law for intensity", "Brewster's angle depending on speed", "The Rayleigh resolution criterion"], answer: 0, solution: "$f'\\approx f(1-u/c)$ gives $\\Delta f/f \\approx -u/c$, directly proportional to $u$ — doubling $u$ doubles the fractional shift.", difficulty: 1, tags: ["doppler", "em-waves"], lesson: "waves-optics-doppler" },
    { id: "waves-optics-t6", prompt: "An object is placed $12\\,\\text{cm}$ from a converging lens with $f=8\\,\\text{cm}$. The image distance is:", options: ["$24\\,\\text{cm}$", "$12\\,\\text{cm}$", "$4.8\\,\\text{cm}$", "$-24\\,\\text{cm}$", "$6\\,\\text{cm}$"], answer: 0, solution: "$1/d_i = 1/8-1/12 = (3-2)/24 = 1/24 \\Rightarrow d_i=24\\,\\text{cm}$.", difficulty: 2, tags: ["thin-lens", "computation"], lesson: "waves-optics-geometric-optics" },
    { id: "waves-optics-t7", prompt: "A lens produces a magnification of $m=+0.5$. The image is:", options: ["Upright and half the object's size", "Inverted and half the object's size", "Upright and twice the object's size", "Inverted and twice the object's size", "Exactly the same size as the object"], answer: 0, solution: "The sign of $m$ gives orientation ($m>0$: upright); the magnitude gives size ratio ($|m|=0.5$: half size).", difficulty: 1, tags: ["optics", "magnification"], lesson: "waves-optics-geometric-optics" },
    { id: "waves-optics-t8", prompt: "A double slit with $d=0.50\\,\\text{mm}$ is illuminated by $\\lambda=633\\,\\text{nm}$ light, projected on a screen $2.0\\,\\text{m}$ away. The spacing between adjacent bright fringes is closest to:", options: ["$2.5\\,\\text{mm}$", "$0.25\\,\\text{mm}$", "$25\\,\\text{mm}$", "$1.25\\,\\text{mm}$", "$5.0\\,\\text{mm}$"], answer: 0, solution: "Fringe spacing $\\Delta y \\approx \\lambda L/d = (633\\times10^{-9})(2.0)/(0.50\\times10^{-3}) \\approx 2.5\\times10^{-3}\\,\\text{m} = 2.5\\,\\text{mm}$.", difficulty: 2, tags: ["interference", "computation"], lesson: "waves-optics-interference" },
    { id: "waves-optics-t9", prompt: "A thin oil film ($n=1.45$) floats on water ($n=1.33$), viewed from air above. Reflection off the top (air-to-oil) surface picks up a $\\pi$ phase shift; reflection off the bottom (oil-to-water) surface does not (oil's index exceeds water's). The condition for strong reflected intensity (constructive interference) at wavelength $\\lambda$ is:", options: ["$2nt = m\\lambda$", "$2nt = (m+\\tfrac12)\\lambda$", "$nt = m\\lambda$", "$t = m\\lambda/4n$", "$4nt = m\\lambda$"], answer: 1, solution: "With exactly one of the two reflections picking up a $\\pi$ shift, the effective condition flips relative to the no-shift case: constructive interference requires $2nt=(m+\\tfrac12)\\lambda$.", difficulty: 3, tags: ["thin-films"], lesson: "waves-optics-interference" },
    { id: "waves-optics-t10", prompt: "A single slit of width $0.050\\,\\text{mm}$ is illuminated by $500\\,\\text{nm}$ light. The angle of the first diffraction minimum is closest to:", options: ["$0.57°$", "$5.7°$", "$0.057°$", "$1.0°$", "$2.9°$"], answer: 0, solution: "$\\sin\\theta = \\lambda/w = (500\\times10^{-9})/(5\\times10^{-5}) = 0.01$, so $\\theta \\approx 0.01\\,\\text{rad} \\approx 0.57°$.", difficulty: 2, tags: ["diffraction", "computation"], lesson: "waves-optics-diffraction" },
    { id: "waves-optics-t11", prompt: "A diffraction grating with thousands of slits produces much sharper spectral lines than a simple double slit at the same slit spacing $d$. This is mainly because:", options: ["Many more interfering sources cause much more complete destructive interference away from each maximum", "The slits in a grating are closer together than in a double slit", "Gratings rely on different underlying physics than double-slit interference", "Gratings physically absorb stray light between the maxima", "Gratings use a shorter wavelength than double-slit setups"], answer: 0, solution: "The maxima condition $d\\sin\\theta=m\\lambda$ is unchanged, but more sources sharpen the peaks by causing near-total cancellation just off the exact maximum angle.", difficulty: 2, tags: ["diffraction", "grating"], lesson: "waves-optics-diffraction" },
    { id: "waves-optics-t12", prompt: "The human eye's pupil has diameter about $4.0\\,\\text{mm}$. Using $\\lambda=550\\,\\text{nm}$, its diffraction-limited angular resolution is closest to:", options: ["$1.7\\times10^{-4}\\,\\text{rad}$", "$1.7\\times10^{-6}\\,\\text{rad}$", "$1.7\\times10^{-2}\\,\\text{rad}$", "$5.5\\times10^{-7}\\,\\text{rad}$", "$4.0\\times10^{-3}\\,\\text{rad}$"], answer: 0, solution: "$\\theta_{\\min}=1.22\\lambda/D = 1.22(550\\times10^{-9})/(4.0\\times10^{-3}) \\approx 1.7\\times10^{-4}\\,\\text{rad}$.", difficulty: 3, tags: ["diffraction", "resolution", "computation"], lesson: "waves-optics-diffraction" },
    { id: "waves-optics-t13", prompt: "Unpolarized light passes through a polarizer, then through a second polarizer at $45°$ to the first. The transmitted intensity, as a fraction of the original unpolarized intensity, is:", options: ["25%", "50%", "12.5%", "75%", "0%"], answer: 0, solution: "First polarizer: $I_0/2$. Second, at $45°$: $(I_0/2)\\cos^2(45°) = (I_0/2)(0.5) = I_0/4 = 25\\%$ of the original.", difficulty: 2, tags: ["polarization", "malus", "computation"], lesson: "waves-optics-polarization" },
    { id: "waves-optics-t14", prompt: "At Brewster's angle, the reflected light is:", options: ["Completely polarized perpendicular to the plane of incidence", "Completely polarized parallel to the plane of incidence", "Completely unpolarized", "Completely absorbed, with no reflection at all", "Circularly polarized"], answer: 0, solution: "At Brewster's angle, the component of reflected light polarized in the plane of incidence vanishes entirely, leaving only the perpendicular component.", difficulty: 1, tags: ["polarization", "brewster"], lesson: "waves-optics-polarization" },
    { id: "waves-optics-t15", prompt: "Light of wavelength $600\\,\\text{nm}$ passes through a diffraction grating with $4000$ lines per centimeter. The angle of the first-order maximum is closest to:", options: ["$13.9°$", "$24°$", "$4.3°$", "$0.24°$", "$45°$"], answer: 0, solution: "Slit spacing $d = 1\\,\\text{cm}/4000 = 2.5\\times10^{-6}\\,\\text{m}$. $\\sin\\theta = m\\lambda/d = (600\\times10^{-9})/(2.5\\times10^{-6}) = 0.24 \\Rightarrow \\theta \\approx \\arcsin(0.24) \\approx 13.9°$.", difficulty: 3, tags: ["diffraction", "grating", "computation"], lesson: "waves-optics-diffraction" }
  ]
});
